src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MX_WB_ph_Telefono1__c</fullName>
        <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
        <label>Teléfono 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MX_WB_ph_Telefono2__c</fullName>
        <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
        <label>Telefono 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MX_WB_ph_Telefono3__c</fullName>
        <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
        <label>Telefono 3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC de cliente.</description>
        <label>RFC</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/iaso__GBL_Rest_Services_Url__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>iaso__Cache_Partition__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cache Partition</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iaso__Url__c</fullName>
        <description>Url of the Rest service</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <label>Rest Services Url</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>RFC__c</fullName>
    <label>RFC</label>
    <length>25</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono1__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 1</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono2__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 2</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono3__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 3</label>
    <type>Phone</type>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>ASD</fullName>
    <active>true</active>
    <businessProcess>ASD</businessProcess>
    <label>ASD</label>
</recordTypes>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Información para la cotización.</description>
        <label>Motivo de la Oportunidad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Venta Pre emisión</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC del asegurado.</description>
        <label>RFC del Asegurado</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TelefonoCliente__c</fullName>
        <label>Teléfono Asegurado</label>
        <type>Phone</type>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <label>ASD</label>
    </recordTypes>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Cuenta personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RFC__c</fullName>
        <label>RFC</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_SendLead_helper_tst.cls
/**-------------------------------------------------------------------------
* Nombre: MX_SB_VTS_SMARTCENTER_cargaBase_cls
* @author Vincent Juárez
* Proyecto: MW SB VTS - BBVA
* Descripción : Clase de ayuda para el componente de envio de leads

* --------------------------------------------------------------------------
*                         Fecha           Autor                   Desripción
* -------------------------------------------------------------------
* @version 1.0           02/05/2019      Vincent Juárez           Creación
* @version 1.0           27/08/2019      Arsenio Perez            Code smell
* --------------------------------------------------------------------------*/
@isTest
public class MX_SB_VTS_SendLead_helper_tst {
    /* Variables de apoyo*/
    static String txtPost = 'POST', txtDescription = 'DESCRIPCION', txtServicio='SERVICEID', txtMsj='NOT iS EMPTY',
        txtUrl='http://www.example.com', txttelf='5511223344', txtUsername='UserOwnerTest01';

    @TestSetup
    static void makeData() {
        final User usr = MX_WB_TestData_cls.crearUsuario('Auto Assigner', system.label.MX_SB_VTS_ProfileAdmin);
        usr.RFC__c = 'LEAS190719VTS';
        Insert usr;

        System.runAs(usr) {
            final Lead leadToAssign = MX_WB_TestData_cls.createLead('Lead Auto Assigner');
            leadToAssign.MX_WB_ph_Telefono1__c=txttelf;
            leadToAssign.MX_WB_ph_Telefono2__c='5511223345';
            leadToAssign.MX_WB_ph_Telefono3__c='5511223346';
            insert leadToAssign;
            final Lead leadToAssign2 = MX_WB_TestData_cls.createLead('Lead Auto Assigner2');
            leadToAssign2.MX_WB_ph_Telefono1__c=txttelf;
            leadToAssign2.MX_WB_ph_Telefono2__c='5511223345';
            leadToAssign2.MX_WB_ph_Telefono3__c='5511223346';
            insert leadToAssign2;
            final Lead leadToAssign3 = MX_WB_TestData_cls.createLead('Lead Auto Assigner3');
            leadToAssign3.MX_WB_ph_Telefono1__c=txttelf;
            leadToAssign3.MX_WB_ph_Telefono2__c='5511223345';
            leadToAssign3.MX_WB_ph_Telefono3__c='5511223346';
            insert leadToAssign3;
            final Account accToAssign = MX_WB_TestData_cls.crearCuenta('Doe', 'PersonAccount');
            accToAssign.PersonEmail = 'test@test.com.leas';
            insert accToAssign;
            final Opportunity oppToAssign = MX_WB_TestData_cls.crearOportunidad('Opp Auto Assigner', accToAssign.Id, usr.Id, 'ASD');
            oppToAssign.Producto__c = 'Hogar';
            oppToAssign.Reason__c = 'Venta';
            oppToAssign.TelefonoCliente__c= txttelf;
            insert oppToAssign;
        	insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenters_Crear_Carga', iaso__Url__c = txtUrl, iaso__Cache_Partition__c = 'local.MXSBVTSCache');
        	insert new iaso__GBL_Rest_Services_Url__c(Name = 'Authentication', iaso__Url__c = 'https://validation/ok', iaso__Cache_Partition__c = 'local.MXSBVTSCache');
        	insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenter', iaso__Url__c = 'https://bbvacifrado.smartcenterservicios.com/ws_salesforce_desarrollo/api/login/authenticate', iaso__Cache_Partition__c = 'local.MXSBVTSCache');
        }
    }
    /** */
        @isTest
    static void testmethodcero() {
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        final User userTest = MX_WB_TestData_cls.crearUsuario(txtUsername, system.label.MX_SB_VTS_ProfileAdmin);
        System.runAs(userTest) {
            Test.startTest();
            final System.HttpRequest req = new System.HttpRequest();
            req.setEndpoint(txtUrl);
            req.setHeader(txtServicio, '2');
            req.setMethod('GET');
            final Map<String,Object> temp = MX_SB_VTS_SendLead_helper_cls.Consulta_Carga_invoke('{"SERVICEID": "2"}');
        	System.assert(!temp.isEmpty(),txtMsj);
            Test.stopTest();
        }
    }
    /** */
    @isTest
    static void testmethodone() {
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        final User userTest = MX_WB_TestData_cls.crearUsuario(txtUsername, system.label.MX_SB_VTS_ProfileAdmin);
        System.runAs(userTest) {
            Test.startTest();
            final System.HttpRequest req = new System.HttpRequest();
            req.setEndpoint(txtUrl);
       		req.setHeader(txtDescription, txtDescription);
            req.setHeader(txtServicio, '2');
            req.setMethod(txtPost);
            final Map<String,Object> tem = MX_SB_VTS_SendLead_helper_cls.Crear_Carga_invoke('2','Prueba generacion 26');
        	System.assert(!tem.isEmpty(),txtMsj);
            Test.stopTest();
        }
    }
    /** */
    @isTest
    static void testmethodtwo() {
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        final User userTest = MX_WB_TestData_cls.crearUsuario(txtUsername, system.label.MX_SB_VTS_ProfileAdmin);
        System.runAs(userTest) {
            Test.startTest();
            final System.HttpRequest req = new System.HttpRequest();
            req.setMethod(txtPost);
            req.setEndpoint(txtUrl);
            req.setHeader(txtServicio, '2');
       		req.setHeader(txtDescription, txtDescription);
			final List<Lead> leadTemp = [select id, MX_WB_ph_Telefono1__c, MX_WB_ph_Telefono2__c, MX_WB_ph_Telefono3__c from Lead where MX_WB_ph_Telefono1__c not in ('') and MX_WB_ph_Telefono2__c not in ('') and MX_WB_ph_Telefono3__c not in ('') limit 3];
            final Map<Id, String> data = new Map<Id, String>();
            data.put(leadTemp[0].Id, '15/04/2019 05:20:00');
            final Map<String,Object> tem = MX_SB_VTS_SendLead_helper_cls.EntRegistroGestion_invoke('EntRegistroGestion', leadTemp,'','2','6', data);
        	System.assert(!tem.isEmpty(),txtMsj);
            Test.stopTest();
        }
    }
    /** */
    @isTest
    static void testmethodthree() {
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        final User userTest = MX_WB_TestData_cls.crearUsuario(txtUsername, system.label.MX_SB_VTS_ProfileAdmin);
        System.runAs(userTest) {
            Test.startTest();
            final System.HttpRequest req = new System.HttpRequest();
            req.setEndpoint(txtUrl);
            req.setHeader(txtDescription, txtDescription);
            req.setHeader(txtServicio, '2');
            req.setMethod(txtPost);
			final List<Lead> leadTemp = [select id, MX_WB_ph_Telefono1__c, MX_WB_ph_Telefono2__c, MX_WB_ph_Telefono3__c from Lead where MX_WB_ph_Telefono1__c not in ('') and MX_WB_ph_Telefono2__c not in ('') and MX_WB_ph_Telefono3__c not in ('') limit 3];
            final Map<Id, String> data = new Map<Id, String>();
            data.put(leadTemp[0].Id, '16/04/2019 05:20:00');
            final Map<String,Object> tem = MX_SB_VTS_SendLead_helper_cls.EntRegistroGestion_invoke('EntRegistroGestion', leadTemp,'','2','6', data);
        	System.assert(!tem.isEmpty(),txtMsj);
            Test.stopTest();
        }
    }
    /** */
    @isTest
    static void testmethodfour() {
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        final User userTest = MX_WB_TestData_cls.crearUsuario(txtUsername, system.label.MX_SB_VTS_ProfileAdmin);
        System.runAs(userTest) {
            Test.startTest();
            final System.HttpRequest req = new System.HttpRequest();
            req.setEndpoint(txtUrl);
            req.setHeader(txtServicio, '2');
            req.setMethod('GET');
            req.setHeader('DESCRIPCION', 'DESCRIPCION');
            final HttpResponse HttpRest= iaso.GBL_Integration_GenericService.invoke('ConsultaCarga', '{"SERVICEID": "2"}');
            final Map<String,Object> tem = (Map<String,Object>) JSON.deserializeUntyped(HttpRest.getBody());
        	System.assert(!tem.isEmpty(),txtMsj);
            Test.stopTest();
        }
    }
    /** */
    @isTest
    static void testmethodfive() {
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        final User userTest = MX_WB_TestData_cls.crearUsuario(txtUsername, system.label.MX_SB_VTS_ProfileAdmin);
        System.runAs(userTest) {
            Test.startTest();
            final System.HttpRequest req = new System.HttpRequest();
            req.setHeader(txtServicio, '2');
       		req.setHeader(txtDescription, txtDescription);
            req.setMethod(txtPost);
            req.setEndpoint(txtUrl);
			final List<Opportunity> leadTemp = [select id, TelefonoCliente__c from Opportunity where TelefonoCliente__c not in ('') limit 3];
            final Map<Id, String> data = new Map<Id, String>();
            data.put(leadTemp[0].Id, '17/04/2019 05:20:00');
			final Map<String,Object>   tem = MX_SB_VTS_SendLead_helper_cls.EntRegistroGestion_invoke('EntRegistroGestion', leadTemp,'','2','6', data);
        	System.assert(!tem.isEmpty(),txtMsj);
            Test.stopTest();
        }
    }
}