src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_de_cliente__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>No. de cliente</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Grupo</fullName>
        <active>true</active>        <!-- <compactLayoutAssignment>dwp_cglp__Group_Compact_Layout</compactLayoutAssignment> -->
        <description>Grupos de clientes</description>
        <label>Grupo</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_PYME_Productos__c</fullName>
        <description>Productos Seleccionados para la Oportunidad</description>
        <label>Productos</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agencia Houston Cheques</fullName>
                </value>
                <value>
                    <fullName>Ahorro</fullName>
                </value>
                <value>
                    <fullName>Ahorro Liquido</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aplinet</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Financiero</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Puro</fullName>
                </value>
                <value>
                    <fullName>Asset Management Gestión Terceros</fullName>
                </value>
                <value>
                    <fullName>Asset Management Previsión Social</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Auto Flotilla Única</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bancomer.com</fullName>
                </value>
                <value>
                    <fullName>Bancomer Net Cash</fullName>
                </value>
                <value>
                    <fullName>Bonds (Garantías)</fullName>
                </value>
                <value>
                    <fullName>Cadenas NAFIN</fullName>
                </value>
                <value>
                    <fullName>Cajeros Automáticos (ATMs)</fullName>
                </value>
                <value>
                    <fullName>Cambios</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito PyME</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Cheques</fullName>
                </value>
                <value>
                    <fullName>Cheques cuenta de grupo / GL</fullName>
                </value>
                <value>
                    <fullName>Ciclos de Vida/ Previsión Social</fullName>
                </value>
                <value>
                    <fullName>CIE Electrónico</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE Ventanilla</fullName>
                </value>
                <value>
                    <fullName>Cobertura/Renta Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cond__Account_Campaign__c.object
<CustomObject>
    <description>Junction object to relate Campaigns with Clients</description>
    <label>Account Campaign</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Divisi_n__c</fullName>
        <label>División</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>VP_ls_Banca__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BAJIO</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO CENTRO</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA</fullName>
                </value>
                <value>
                    <fullName>NORESTE</fullName>
                </value>
                <value>
                    <fullName>NOROESTE</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE</fullName>
                </value>
                <value>
                    <fullName>SUR</fullName>
                </value>
                <value>
                    <fullName>SURESTE</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVA</fullName>
                </value>
                <value>
                    <fullName>BAJIO PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA NORTE PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA SUR PYME</fullName>
                </value>
                <value>
                    <fullName>NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>NOROESTE PYME</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>SUR PYME</fullName>
                </value>
                <value>
                    <fullName>SURESTE PYME</fullName>
                </value>
                <value>
                    <fullName>METRO NORTE</fullName>
                </value>
                <value>
                    <fullName>METRO SUR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_PyME_Campaign_GenOpp_Test.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     MX_PyME_Campaign_GenOpp_Test
* @Author   Jhovanny De La Cruz Cruz jhovanny.delacruz.contractor@bbva.com
* @Date     Created: 2019-01-29
* @Group    Test Class for the functionality MX_PyME_Campaign_GenOpp_cls
* @Description Test class for the creation of opportunities functionality
* @Changes
*
*  |2019-01-29  jhovanny.delacruz.contractor@bbva.com
*				Test methods are added for MX_PyME_Campaign_GenOpp_cls
*/
@isTest
public class MX_PyME_Campaign_GenOpp_Test {

    /** Colocación */
	static final String STGAHORRO = 'Ahorro';
    /**
    * Crea un usuario ejecutivo PyME
     */
    public static User creaUserEjecPyme() {
        return UtilitysDataTest_tst.crearUsuario('USUARIO EJEC', 'Ejecutivo PyME Plus', 'EJEC PYME PLUS AGUASCALIENTES');
    }

    /**
    * Test de prueba con campaña con productos
     */
    static testMethod void getAccountCampaignFieldsTest() {
        final User usr = [SELECT Id,ProfileId,VP_ls_Banca__c,Divisi_n__c FROM User WHERE Id =: UserInfo.getUserId()];
        UtilitysDataTest_tst.crearProdForm('Colocación', STGAHORRO);
        final Account testAccount = UtilitysDataTest_tst.crearCuenta('Empresa 1 TEST', 'Grupo');
        testAccount.No_de_cliente__c = '1396008';
        insert testAccount;
        final List<Campaign> camps = new List<Campaign>();
        final List<cond__Account_Campaign__c> accCamp = new List<cond__Account_Campaign__c>();
        final Campaign cmp = new Campaign();
        cmp.Name = 'TEST CAMPAÑA';
        cmp.MX_PYME_Productos__c = STGAHORRO;
        cmp.RecordTypeId=  RecordTypeMemory_cls.getRecType('Campaign','AccountCampaign_Campaign');
        camps.add(cmp);
        insert camps;
        cond__Account_Campaign__c acccmp = new cond__Account_Campaign__c();
        acccmp =  UtilitysDataTest_tst.crearAccCampaign(String.valueOf(usr.id) , 'Pre_Validated_Account_Campaign', 'TEST', String.valueOf(testAccount.id));
        acccmp.cond__campaign_id__c = camps[0].id;
        acccmp.cond__campaign_name__c = 'Test Campaign';
        acccmp.cond__priority_campaign_type__c = 'High';
        accCamp.add(acccmp);
        insert accCamp;
        MX_PyME_Campaign_GenOpp_cls.getAccountCampaignFields(acccmp.id);
        MX_PyME_Campaign_GenOpp_cls.relatedRecordType();
        List<Product2> pdts = new List<Product2>();
        pdts = MX_PyME_Campaign_GenOpp_cls.getProductCampaign(acccmp.id);
        System.assert(pdts.isEmpty(),'There are no products associated with the campaign to generate an opportunity. Please contact your system administrator.');
    }

    /**
    * Test de prueba de campaña sin productos
     */
    static testMethod void getAccountCampaignFieldsTest2() {
        final User usr = [SELECT Id,ProfileId,VP_ls_Banca__c,Divisi_n__c FROM User WHERE Id =: UserInfo.getUserId()];
        UtilitysDataTest_tst.crearProdForm('Colocación', STGAHORRO);
        final Account testAccount = UtilitysDataTest_tst.crearCuenta('Empresa 1 TEST', 'Grupo');
        testAccount.No_de_cliente__c = '1396008';
        insert testAccount;
        final List<Campaign> camps = new List<Campaign>();
        final List<cond__Account_Campaign__c> accCamp = new List<cond__Account_Campaign__c>();
        final Campaign cmp = new Campaign();
        cmp.Name = 'TEST CAMPAÑA';
        cmp.cond__campaign_id__c = 'TEST';
        cmp.MX_PYME_Productos__c = STGAHORRO;
        cmp.RecordTypeId=  RecordTypeMemory_cls.getRecType('Campaign','AccountCampaign_Campaign');
        camps.add(cmp);
        insert camps;
        cond__Account_Campaign__c acccmp = new cond__Account_Campaign__c();
        acccmp =  UtilitysDataTest_tst.crearAccCampaign(String.valueOf(usr.id) , 'Pre_Validated_Account_Campaign', 'TEST', String.valueOf(testAccount.id));
        acccmp.cond__campaign_id__c = camps[0].id;
        acccmp.cond__campaign_name__c = 'Test Campaign';
        acccmp.cond__priority_campaign_type__c = 'High';
        accCamp.add(acccmp);
        insert accCamp;
        MX_PyME_Campaign_GenOpp_cls.getAccountCampaignFields(acccmp.id);
        MX_PyME_Campaign_GenOpp_cls.relatedRecordType();
        List<Product2> pdts = new List<Product2>();
        pdts = MX_PyME_Campaign_GenOpp_cls.getProductCampaign(acccmp.id);
        System.assert(pdts.isEmpty(),'There are no products associated with the campaign to generate an opportunity. Please contact your system administrator.');
    }
}