src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC de cliente.</description>
        <label>RFC</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/iaso__GBL_Rest_Services_Url__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>iaso__Cache_Partition__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cache Partition</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iaso__Url__c</fullName>
        <description>Url of the Rest service</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <label>Rest Services Url</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>RFC__c</fullName>
    <label>RFC</label>
    <length>25</length>
    <type>Text</type>
</fields>
	<fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Campo que permite identificar cual es la tarea actual que se esta trabajando durante el proceso de venta Telemarketing</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LLamada Activa</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
<sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_CatalogoObjeciones__c.object
<CustomObject>
    <description>En este objeto se cargaran todas las objeciones correspondientes  a un producto o flujo de venta</description>
    <fields>
        <fullName>MX_SB_VTS_DetOjecion__c</fullName>
        <description>Texto detallado de la Objeción</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Detalle Objeción</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_NombreObjecion__c</fullName>
        <description>Nombre de la objeción</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre objeción</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ObjecionActiva__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si una objeción se encuentra activa</description>
        <label>Activa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ProductoObjecion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación al producto que aplica la objeción</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Catalogos de objeciones</relationshipLabel>
        <relationshipName>Catalogos_de_objeciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Relevancia__c</fullName>
        <description>Importancia de la Objeción</description>
        <label>Relevancia</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_TipoObjecion__c</fullName>
        <description>Tipo de objeción indica si se utiliza en Lead u Oportunidad</description>
        <label>Tipo Objeción</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Catalogo objeciones</label>
    <nameField>
        <displayFormat>CatObje-{000}</displayFormat>
        <label>Nombre de Catalogo objectiones</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Catalogos de objeciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_Lead_tray__c.object
<CustomObject>
    <description>Objeto Creado para almacenar las bandejas generadas en los servicios. El objeto es Genérico para la creación de nuevos servicios.</description>
    <fields>
        <fullName>MX_SB_VTS_Description__c</fullName>
        <description>Descripción de las bandejas creadas.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Descripción</inlineHelpText>
        <label>Descripcion</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ID_Bandeja__c</fullName>
        <description>Id Generado en el servicio.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>ID de servicio generado.</inlineHelpText>
        <label>ID Bandeja</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Producto Relacionado con la bandeja.</description>
        <inlineHelpText>Inserta el producto relacionado con la bandeja,</inlineHelpText>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bandejas leads</relationshipLabel>
        <relationshipName>Bandejas_leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo relación a proveedor CTI</description>
        <label>ProveedorCTI</label>
        <referenceTo>MX_SB_VTS_ProveedoresCTI__c</referenceTo>
        <relationshipLabel>Bandejas leads</relationshipLabel>
        <relationshipName>Bandejas_leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipo_bandeja__c</fullName>
        <description>Tipo de bandeja</description>
        <label>Tipo bandeja HotLeads</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HotLeads</fullName>
                </value>
                <value>
                    <fullName>TrackingWeb</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>MX_SB_VTS_ServicioID__c</fullName>
        <description>ID del servicio relacionado con la bandeja</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>ID del servicio relacionado con la bandeja</inlineHelpText>
        <label>Servicio</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Bandejas lead</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de la bandeja</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bandejas leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_ProveedoresCTI__c.object
<CustomObject>
    <description>Objeto para registrar y dar de altas Proveedores de llamadas</description>
    <fields>
        <fullName>MX_SB_VTS_Identificador_Proveedor__c</fullName>
        <description>Identificador único de proveedores</description>
        <inlineHelpText>Seleccione un valor de la lista, si el valor que necesita no existe, por favor delo de alta en la lista global de Proveedores</inlineHelpText>
        <label>Identificador Proveedor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_Lista_Proveedores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_IsReadyCTI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si el proveedor esta preparado para la integración con Salesforce</description>
        <label>CTI Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_TieneSegmento__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo que indica si el proveedor permite la segmentación de campañas</description>
        <label>Segmentado</label>
        <type>Checkbox</type>
    </fields>
    <label>ProveedorCTI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Proveedores</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProveedoresCTI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_RegistroObjeciones__c.object
<CustomObject>
    <description>Mantiene la relación entre las objeciones y los registros de Lead y Opportunity</description>
    <fields>
        <fullName>MX_SB_VTS_CatObjecion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indica la Objeción que se aplico a un registro</description>
        <label>Catalogo objeciones</label>
        <referenceTo>MX_SB_VTS_CatalogoObjeciones__c</referenceTo>
        <relationshipLabel>Registros de Objeciones</relationshipLabel>
        <relationshipName>Registros_de_Objeciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Indica la llamada por la cual se generaron las objeciones</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LLamada Activa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_TipoObjecion__c</fullName>
        <description>Indica el tipo de objeción que se aplico</description>
        <label>Tipo Objeción</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Registro Objeciones</label>
    <nameField>
        <displayFormat>ObjecSelect-{00000}</displayFormat>
        <label>Nombre de Registro Objeciones</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de Objeciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Campo para referenciar la Tarea de llamada activa</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Tarea Activa</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Información para la cotización.</description>
        <label>Motivo de la Oportunidad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Venta Pre emisión</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC del asegurado.</description>
        <label>RFC del Asegurado</label>
        <length>25</length>
        <type>Text</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
     <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <description>Campo para especificar el nombre del proveedor al que esta asignado un usuario</description>
        <label>ProveedorCTI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_Lista_Proveedores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <label>RFC</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/MX_SB_VTS_Lista_Proveedores.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ninguno</fullName>
        <default>true</default>
        <label>Ninguno</label>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>VCIP</fullName>
    </customValue>
    <customValue>
        <fullName>SMART CENTER</fullName>
    </customValue>
    <description>Lista de nombres de proveedores</description>
    <masterLabel>Nombres Proveedores</masterLabel>
</GlobalValueSet>

src/classes/MX_SB_VTS_Objeciones_tst.cls
/**
 * @File Name          : MX_SB_VTS_Objeciones_tst.cls
 * @Description        : Clase test de MX_SB_VTS_Objeciones_cls
 * @Author             : Eduardo Hernández Cuamatzi
 * @Group              : BBVA
 * @Last Modified By   : Eduardo Hernández Cuamatzi
 * @Last Modified On   : 7/10/2019 20:38:36
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    12/9/2019   Eduardo Hernández Cuamatzi     Initial Version
**/
@isTest
private class MX_SB_VTS_Objeciones_tst {
    /** valor precio alto */
    final static String OBJECIONSTR= 'Precio Alto';
    /** valor objeciones reales */
    final static String OBJECIONTREALSTR= 'Objeciones Reales';
    /** valor objeciones */
    final static String OBJECIONTOBLSTR= 'Objeciones';
    /** valores iaso */
    final static String TXTPOST = 'POST', URLLOCAL = 'local.MXSBVTSCache',URLEXA='http://www.example.com';

    @TestSetup
    static void makeData() {//NOSONAR
        final User usr = MX_WB_TestData_cls.crearUsuario('Auto Assigner', System.label.MX_SB_VTS_ProfileAdmin);
        usr.RFC__c = 'LEAS190719VTS';
        insert usr;

        final Product2 proTst = MX_WB_TestData_cls.productNew ( 'Hogar' );
        proTst.IsActive = true;
        insert proTst;

        final Lead leadAuto = MX_WB_TestData_cls.vtsTestLead('TestObjec', System.Label.MX_SB_VTS_Telemarketing_LBL);
        leadAuto.OwnerId = usr.Id;
        insert leadAuto;

        final Task taskCall = MX_WB_TestData_cls.crearTarea(null, leadAuto.Id, System.Label.MX_SB_VTS_TaskCall, 'Llamada', 'No Iniciado');
        taskCall.Priority = 'Normal';
        insert taskCall;

        leadAuto.MX_SB_VTS_LookActivity__c = taskCall.Id;
        update leadAuto;

        final MX_SB_VTS_CatalogoObjeciones__c catObj = new MX_SB_VTS_CatalogoObjeciones__c();
        catObj.MX_SB_VTS_DetOjecion__c = 'Objecion1';
        catObj.MX_SB_VTS_NombreObjecion__c = OBJECIONSTR;
        catObj.MX_SB_VTS_ObjecionActiva__c = true;
        catObj.MX_SB_VTS_ProductoObjecion__c = proTst.Id;
        catObj.MX_SB_VTS_Relevancia__c = 1;
        catObj.MX_SB_VTS_TipoObjecion__c = OBJECIONTOBLSTR;
        insert catObj;

        final MX_SB_VTS_CatalogoObjeciones__c catObjR = new MX_SB_VTS_CatalogoObjeciones__c();
        catObjR.MX_SB_VTS_DetOjecion__c = 'Objecion det';
        catObjR.MX_SB_VTS_NombreObjecion__c = 'Mal trato';
        catObjR.MX_SB_VTS_ObjecionActiva__c = true;
        catObjR.MX_SB_VTS_ProductoObjecion__c = proTst.Id;
        catObjR.MX_SB_VTS_Relevancia__c = 1;
        catObjR.MX_SB_VTS_TipoObjecion__c = OBJECIONTOBLSTR;
        insert catObjR;

        final MX_SB_VTS_CatalogoObjeciones__c catObj2 = new MX_SB_VTS_CatalogoObjeciones__c();
        catObj2.MX_SB_VTS_DetOjecion__c = 'Objecion2';
        catObj2.MX_SB_VTS_NombreObjecion__c = OBJECIONSTR;
        catObj2.MX_SB_VTS_ObjecionActiva__c = true;
        catObj2.MX_SB_VTS_ProductoObjecion__c = proTst.Id;
        catObj2.MX_SB_VTS_Relevancia__c = 1;
        catObj2.MX_SB_VTS_TipoObjecion__c = OBJECIONTREALSTR;
        insert catObj2;

        final Account accToAssign = MX_WB_TestData_cls.crearCuenta('Doe', 'PersonAccount');
        accToAssign.PersonEmail = 'test@test.com.leas';
        insert accToAssign;

        final Opportunity oppTelemarketing = MX_WB_TestData_cls.crearOportunidad('OppTelemarketing', accToAssign.Id, usr.Id, System.Label.MX_SB_VTS_Telemarketing_LBL);
        oppTelemarketing.Producto__c = System.Label.MX_SB_VTS_Hogar;
        oppTelemarketing.Reason__c = 'Venta';
        insert oppTelemarketing;

        final Task taskCallOpp = MX_WB_TestData_cls.crearTarea(oppTelemarketing.Id, null, System.Label.MX_SB_VTS_TaskCall, 'Llamada', 'No Iniciado');
        taskCallOpp.Priority = 'Normal';
        insert taskCallOpp;
        oppTelemarketing.MX_SB_VTS_LookActivity__c = taskCallOpp.Id;
        update oppTelemarketing;

        final MX_SB_VTS_ProveedoresCTI__c smartProv = new MX_SB_VTS_ProveedoresCTI__c();
        smartProv.Name = 'Smart Center';
        smartProv.MX_SB_VTS_Identificador_Proveedor__c = 'SMART CENTER';
        smartProv.MX_SB_VTS_TieneSegmento__c = true;
        smartProv.MX_SB_VTS_IsReadyCTI__c = true;
        insert smartProv;

        final MX_SB_VTS_Lead_tray__c leadTray = new MX_SB_VTS_Lead_tray__c();
        leadTray.MX_SB_VTS_Description__c = 'HotLeads';
        leadTray.MX_SB_VTS_ID_Bandeja__c = '6';
        leadTray.MX_SB_VTS_ProveedorCTI__c = smartProv.Id;
        leadTray.MX_SB_VTS_Producto__c = proTst.Id;
        leadTray.MX_SB_VTS_Tipo_bandeja__c = 'HotLeads';
        leadTray.MX_SB_VTS_ServicioID__c = '2';
        insert leadTray;

        insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenters_Crear_Carga', iaso__Url__c = URLEXA, iaso__Cache_Partition__c = URLLOCAL);
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'Authentication', iaso__Url__c = 'https://validation/ok', iaso__Cache_Partition__c = URLLOCAL);
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenter', iaso__Url__c = 'https://bbvacifrado.smartcenterservicios.com/ws_salesforce_desarrollo/api/login/authenticate', iaso__Cache_Partition__c = URLLOCAL);

    }

    @isTest
    private static void getObjeciones() {
        Test.startTest();
        final Lead leadRecord = [Select Id from Lead where LastName = 'TestObjec'];
        final Id activeCall = MX_SB_VTS_Objeciones_cls.getActiveCall(leadRecord.Id, true);
        final Map<String, Object> response = MX_SB_VTS_Objeciones_cls.getObjetions(leadRecord.Id, System.Label.MX_SB_VTS_Hogar, true);
        System.assertEquals(response.get('activeCall'), activeCall, 'Exito getObjeciones');
        Test.stopTest();
    }

    @isTest
    private static void getObjecionesOpp() {
        Test.startTest();
        final Opportunity oppRecord = [Select Id from Opportunity where Name = 'OppTelemarketing'];
        final Id activeCall = MX_SB_VTS_Objeciones_cls.getActiveCall(oppRecord.Id, false);
        final Map<String, Object> response = MX_SB_VTS_Objeciones_cls.getObjetions(oppRecord.Id, System.Label.MX_SB_VTS_Hogar, false);
        System.assertEquals(response.get('activeCall'), activeCall, 'Exito getObjecionesOpp');
        Test.stopTest();
    }

    @isTest
    private static void saveObjects() {
        Test.startTest();
        final Lead leadRecord = [Select Id from Lead where LastName = 'TestObjec'];
        final MX_SB_VTS_CatalogoObjeciones__c catOb = [Select Id, MX_SB_VTS_NombreObjecion__c, MX_SB_VTS_TipoObjecion__c
            from MX_SB_VTS_CatalogoObjeciones__c where MX_SB_VTS_NombreObjecion__c =: OBJECIONSTR AND MX_SB_VTS_TipoObjecion__c =: OBJECIONTOBLSTR];
        final Id activeCall = MX_SB_VTS_Objeciones_cls.getActiveCall(leadRecord.Id, true);
        final List<MX_SB_VTS_RegistroObjeciones__c> lstObjects = new List<MX_SB_VTS_RegistroObjeciones__c>();
        final MX_SB_VTS_RegistroObjeciones__c regOb = new MX_SB_VTS_RegistroObjeciones__c(
            MX_SB_VTS_CatObjecion__c = catOb.Id,
            MX_SB_VTS_LeadLook__c = leadRecord.Id,
            MX_SB_VTS_LookActivity__c = activeCall,
            MX_SB_VTS_NoUsoObjecion__c = false,
            MX_SB_VTS_ObjecionUtil__c = true,
            MX_SB_VTS_TipoObjecion__c = catOb.MX_SB_VTS_TipoObjecion__c
        );
        lstObjects.add(regOb);
        MX_SB_VTS_Objeciones_cls.saveObjectionscls(lstObjects);
        final MX_SB_VTS_RegistroObjeciones__c regObj = [Select Id,MX_SB_VTS_CatObjecion__r.MX_SB_VTS_NombreObjecion__c from MX_SB_VTS_RegistroObjeciones__c where MX_SB_VTS_LeadLook__c =: leadRecord.Id];
        System.assertEquals(catOb.MX_SB_VTS_NombreObjecion__c, regObj.MX_SB_VTS_CatObjecion__r.MX_SB_VTS_NombreObjecion__c, 'Exito saveObjeciones');
        Test.stopTest();

    }

    @isTest
    private static void saveObjectsOpp() {
        Test.startTest();
        final Opportunity oppRecrod = [Select Id from Opportunity where Name = 'OppTelemarketing'];
        final MX_SB_VTS_CatalogoObjeciones__c catOb = [Select Id, MX_SB_VTS_NombreObjecion__c, MX_SB_VTS_TipoObjecion__c
            from MX_SB_VTS_CatalogoObjeciones__c where MX_SB_VTS_NombreObjecion__c =: OBJECIONSTR AND MX_SB_VTS_TipoObjecion__c =: OBJECIONTREALSTR];
        final Id activeCall = MX_SB_VTS_Objeciones_cls.getActiveCall(oppRecrod.Id, false);
        final List<MX_SB_VTS_RegistroObjeciones__c> lstObjects = new List<MX_SB_VTS_RegistroObjeciones__c>();
        final MX_SB_VTS_RegistroObjeciones__c regOb = new MX_SB_VTS_RegistroObjeciones__c(
            MX_SB_VTS_CatObjecion__c = catOb.Id,
            MX_SB_VTS_ObjecionOpp__c = oppRecrod.Id,
            MX_SB_VTS_LookActivity__c = activeCall,
            MX_SB_VTS_NoUsoObjecion__c = false,
            MX_SB_VTS_ObjecionUtil__c = true,
            MX_SB_VTS_TipoObjecion__c = catOb.MX_SB_VTS_TipoObjecion__c
        );
        lstObjects.add(regOb);
        MX_SB_VTS_Objeciones_cls.saveObjectionscls(lstObjects);
        final MX_SB_VTS_RegistroObjeciones__c regObj = [Select Id,MX_SB_VTS_CatObjecion__r.MX_SB_VTS_NombreObjecion__c from MX_SB_VTS_RegistroObjeciones__c where MX_SB_VTS_ObjecionOpp__c =: oppRecrod.Id];
        System.assertEquals(catOb.MX_SB_VTS_NombreObjecion__c, regObj.MX_SB_VTS_CatObjecion__r.MX_SB_VTS_NombreObjecion__c, 'Exito saveObjeOpp');
        Test.stopTest();
    }

    @isTest
    private static void getSavedRecObjs() {
        final Lead leadRecord = [Select Id from Lead where LastName = 'TestObjec'];
        final MX_SB_VTS_CatalogoObjeciones__c catOb = [Select Id, MX_SB_VTS_NombreObjecion__c, MX_SB_VTS_TipoObjecion__c
            from MX_SB_VTS_CatalogoObjeciones__c where MX_SB_VTS_NombreObjecion__c =: 'Mal trato' AND MX_SB_VTS_TipoObjecion__c =: OBJECIONTOBLSTR];
        final Id activeCall = MX_SB_VTS_Objeciones_cls.getActiveCall(leadRecord.Id, true);
        final MX_SB_VTS_RegistroObjeciones__c regOb = new MX_SB_VTS_RegistroObjeciones__c(
            MX_SB_VTS_CatObjecion__c = catOb.Id,
            MX_SB_VTS_LeadLook__c = leadRecord.Id,
            MX_SB_VTS_LookActivity__c = activeCall,
            MX_SB_VTS_NoUsoObjecion__c = false,
            MX_SB_VTS_ObjecionUtil__c = true,
            MX_SB_VTS_TipoObjecion__c = catOb.MX_SB_VTS_TipoObjecion__c
        );
        insert regOb;
        Test.startTest();
            final Map<String, Object> response = MX_SB_VTS_Objeciones_cls.getObjetions(leadRecord.Id, System.Label.MX_SB_VTS_Hogar, true);
            System.assertEquals(response.get('activeCall'), activeCall, 'Exito getSaveRecords');
        Test.stopTest();
    }

    @isTest
    private static void errorGetObjects() {
        Test.startTest();
            try {
                MX_SB_VTS_Objeciones_cls.getObjetions('', System.Label.MX_SB_VTS_Hogar, true);
            } catch (AuraHandledException auEx) {
                auEx.setMessage(System.Label.MX_WB_lg_TlmktError);
                System.assertEquals(auEx.getMessage(), System.Label.MX_WB_lg_TlmktError, 'Fallo esperado');
            }
        Test.stopTest();
    }
    
    @isTest
    private static void updateLeadsTray() {
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
            iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
            final Id bandejaId = [Select Id from MX_SB_VTS_Lead_tray__c where MX_SB_VTS_ID_Bandeja__c = '6'].Id;
            final Map<String, Object> response = MX_SB_VTS_Objeciones_cls.updateLeadsTray(bandejaId);
            System.assert((Boolean)response.get('isOk'), 'Guardado');
        Test.stopTest();
    }
}