src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_de_cliente__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>No. de cliente</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UG__c</fullName>
        <formula>Owner.UG__c</formula>
        <label>UG</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>BPyP_tre_Cliente</fullName>
        <active>true</active>
        <description>Tipo de registro para clientes de BPyP - Personas morales</description>
        <label>Cliente BPyP - Morales</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grupo</fullName>
        <active>true</active>        <!-- <compactLayoutAssignment>dwp_cglp__Group_Compact_Layout</compactLayoutAssignment> -->
        <description>Grupos de clientes</description>
        <label>Grupo</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_RTL_Familia__c</fullName>
        <description>Listado de familia de productos</description>
        <label>Familia</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Captación</fullName>
                </value>
                <value>
                    <fullName>Colocación</fullName>
                </value>
                <value>
                    <fullName>Servicios</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_RTL_Producto__c</fullName>
        <description>Listado de los productos dependientes de la familia seleccionada en la oportunidad</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_RTL_Familia__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cuenta en Dólares</fullName>
                </value>
                <value>
                    <fullName>Fondos de Inversión</fullName>
                </value>
                <value>
                    <fullName>Maestra Patrimonial Dólares</fullName>
                </value>
                <value>
                    <fullName>Membresía BP</fullName>
                </value>
                <value>
                    <fullName>Nómina</fullName>
                </value>
                <value>
                    <fullName>Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Producto 21</fullName>
                </value>
                <value>
                    <fullName>MLB</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Consumo</fullName>
                </value>
                <value>
                    <fullName>Hipotecario</fullName>
                </value>
                <value>
                    <fullName>TDC</fullName>
                </value>
                <value>
                    <fullName>PrePaid Forward</fullName>
                </value>
                <value>
                    <fullName>Collares</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Domiciliaciones</fullName>
                </value>
                <value>
                    <fullName>Servicios No Financieros</fullName>
                </value>
                <value>
                    <fullName>Traspaso Patrimonial</fullName>
                </value>
                <value>
                    <fullName>One Team</fullName>
                </value>
                <value>
                    <fullName>Fideicomiso</fullName>
                </value>
                <value>
                    <fullName>Socios Globales</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Gastos Médicos Mayores Indemnizatorio</fullName>
                </value>
                <value>
                    <fullName>Hogar Seguro Plus</fullName>
                </value>
                <value>
                    <fullName>Vida Segura Patrimonial</fullName>
                </value>
                <value>
                    <fullName>Meta Segura</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>op_amountPivote_dv__c</fullName>
        <description>Campo auxiliar para ligar los montos de oportunidad al Campo Amount. (Puente para salvar la relación que se crea con Product2 y OpportunityLineItem</description>
        <label>Monto de la Oportunidad</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Oportunidad__c</fullName>
        <description>las oportunidades incrementales, nuevas y de renovación en los diferentes productos de la Banca de Empresas y Gobierno, con el propósito de generar un historial comercial puntual de cada una de las acciones comerciales llevadas a cabo en la RED.</description>
        <label>Tipo de oportunidad</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adquisición de Afiliación</fullName>
                </value>
                <value>
                    <fullName>Disminución</fullName>
                </value>
                <value>
                    <fullName>Disposición</fullName>
                </value>
                <value>
                    <fullName>Establecimiento</fullName>
                </value>
                <value>
                    <fullName>Incremental</fullName>
                </value>
                <value>
                    <fullName>Incremento</fullName>
                </value>
                <value>
                    <fullName>Modificación</fullName>
                </value>
                <value>
                    <fullName>Nueva</fullName>
                </value>
                <value>
                    <fullName>Ratificación</fullName>
                </value>
                <value>
                    <fullName>Reactivación</fullName>
                </value>
                <value>
                    <fullName>Recontratacion</fullName>
                    <label>Recontratación</label>
                </value>
                <value>
                    <fullName>Renovación</fullName>
                </value>
                <value>
                    <fullName>Renovación Incremental</fullName>
                </value>
                <value>
                    <fullName>Revisión Anual</fullName>
                </value>
                <value>
                    <fullName>Seleccionar</fullName>
                    <default>true</default>
                    <label>Seleccionar</label>
                </value>
                <value>
                    <fullName>Renovación de Contrato</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Trigger_Oportunidad__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Enciende/apaga los trigger del objeto oportunidad.</description>
    <fields>
        <fullName>EG009_AC_FinanciamientoPipeline_cls__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checkbox encargado de desactivar/activar el Trigger: EG009_AC_FinanciamientoPipeline_cls</description>
        <inlineHelpText>Al activar este checkbox se activa la funcionalidad del trigger EG009_AC_FinanciamientoPipeline_cls del proyecto financiamiento pipeline.</inlineHelpText>
        <label>EG009_AC_FinanciamientoPipeline_cls</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger_Oportunidad</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <description>Unidad gestora</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>UG</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segmento_Ejecutivo__c</fullName>
        <label>Segmento Ejecutivo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MEDIANA EMPRESA</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVO</fullName>
                </value>
                <value>
                    <fullName>EMPRESARIAL</fullName>
                </value>
                <value>
                    <fullName>FEDERAL</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO RESTO</fullName>
                </value>
                <value>
                    <fullName>GRANDES CUENTAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Divisi_n__c</fullName>
        <label>División</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>VP_ls_Banca__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BAJIO</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO CENTRO</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA</fullName>
                </value>
                <value>
                    <fullName>NORESTE</fullName>
                </value>
                <value>
                    <fullName>NOROESTE</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE</fullName>
                </value>
                <value>
                    <fullName>SUR</fullName>
                </value>
                <value>
                    <fullName>SURESTE</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVA</fullName>
                </value>
                <value>
                    <fullName>BAJIO PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA NORTE PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA SUR PYME</fullName>
                </value>
                <value>
                    <fullName>NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>NOROESTE PYME</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>SUR PYME</fullName>
                </value>
                <value>
                    <fullName>SURESTE PYME</fullName>
                </value>
                <value>
                    <fullName>METRO NORTE</fullName>
                </value>
                <value>
                    <fullName>METRO SUR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EG009_UtilitysUnitTest_tst.cls
/*-----------------------------------------------------------------------------------------
*----------------------------------Desarrollado por INDRA----------------------------------
*Autor:			Ing. Pedro Alan Hernandez Sierra
*Proyecto:		MAX 3.0 - BBVA Bancomer
*Descripción:	Clase "TEST" general de utilería para otros métodos de prueba
*_______________________________________________________________________________________
*Versión	Fecha			Autor								Descripción
*1.0        14/NOV/2017     Ing. Pedro Alan Hernandez Sierra    Creación.
*1.1        16/NOV/2017     Ing. Pedro Alan Hernandez Sierra    Modificación para agregar OtroAdmin
*1.2        30/ENE/2018     Ing. Pedro Alan Hernandez Sierra    Se agregan métodos: CreaCotizador y CreaOLI
*1.2        07/FEB/2018     Lic. Luis Ruben Quinto Muñoz	    Se Modifican métodos de creacion de usuarios
*1.3        15/FEB/2018     Lic. Luis Ruben Quinto Muñoz	    Se Modifican métodos de creacion de Oportunidad
*1.4        06/MAR/2018     Lic. Luis Ruben Quinto Muñoz	    Se Cambian metodos de prueba para creación de oportunidades
*1.5        05/JUN/2018     Lic. Luis Ruben Quinto Muñoz	    Se agrega el campo Divisi_n__c para que pase por una regla de validación
*2.0		31-07-2018      Ricardo Hernandez Reyes             Actualizo Versión API 43, Agrego label Administrador
*2.1        03-10-2018      Fernando Jaime						Se actualiza label de español por la de ingles
*2.2		09/07/2019		Jair Ignacio Gonzalez Gayosso		Se depuro clase con los metodos confirmados en la migracion de bpyp y pymes
-----------------------------------------------------------------------------------------*/
@isTest
public class EG009_UtilitysUnitTest_tst {

	/** String en_Us */
	static final String STGEN_US = 'en_US';

	@isTest
	/** Clase de prueba para EG009_Utility_cls */
	public static void ambientacionGeneral() {

		final Id profileId = [SELECT Id, Name FROM Profile WHERE Name =: System.label.MX_PERFIL_SystemAdministrator].Id;
		//Tipos de registro de Cuentas y Oportundiades
		final Map<String, RecordType> allRT = new Map<String, RecordType>();
		for(RecordType iteraRT : [SELECT Id, DeveloperName FROM RecordType WHERE (SobjectType = 'Account' OR SobjectType = 'Opportunity')]) {
			allRT.put(iteraRT.DeveloperName, iteraRT);
		}

		final User admin = new User(
            Alias = 'userUno',
            Email='adminBBVA@bbva.tst.deploy.com',
            EmailEncodingKey='ISO-8859-1',
            LastName='Prueba',
            LanguageLocaleKey=STGEN_US,
            LocaleSidKey=STGEN_US,
            ProfileId = profileId,
            UG__c = '0008134',
            Divisi_n__c = 'NOROESTE',
            Segmento_Ejecutivo__c = 'EMPRESARIAL',
            TimeZoneSidKey='America/Mexico_City',
            UserName='adminBBVA@bbva.tst.deploy.com',
            VP_ls_Banca__c = 'Red BEyG',
            IsActive=true
        );
        insert admin;

        final User otroAdmin = new User(
	            Alias = 'userDos',
	            Email = 'OtroAdmin@bbva.tst.deploy.com',
	            EmailEncodingKey='ISO-8859-1',
	            LastName = 'OtroAdmin',
	            LanguageLocaleKey=STGEN_US,
	            LocaleSidKey = STGEN_US,
	            ProfileId = profileId,
	            UG__c = '0008135',
	            Divisi_n__c = 'NOROESTE',
	            Segmento_Ejecutivo__c = 'EMPRESARIAL',
	            TimeZoneSidKey = 'America/Mexico_City',
	            UserName = 'OtroAdmin@bbva.tst.deploy.com',
	            VP_ls_Banca__c = 'Red BEyG',
	            IsActive = true
	        );
		insert otroAdmin;

		System.runAs(admin) {
			UtilitysDataTest_tst.crearProdForm('Colocación', 'Collares');

			final Trigger_Oportunidad__c setting = new Trigger_Oportunidad__c();
			setting.EG009_AC_FinanciamientoPipeline_cls__c = true;
			Insert setting;

			final Account grupoEconomico = new Account(
				Name = 'Grupo Económico [Alan Sierra]',
		        RecordTypeId = allRT.get('BPyP_tre_Cliente').Id
			);
	        insert grupoEconomico;

			final Account cliente = new Account(
				Name = 'Cliente [Alan Sierra]',
				No_de_cliente__c = '55218555',
		        RecordTypeId = allRT.get('BPyP_tre_Cliente').Id
			);
	        insert cliente;

            Test.startTest();
			System.assertNotEquals(null, cliente.Id);
			Test.stopTest();
    	}
	}

	/** Manda a llamar el metodo creaOportunidad */
	public static Opportunity creaOportunidad(Id cliente, Id tipoRegistro) {
		return creaOportunidad(cliente, tipoRegistro, null, null);
	}

	/** Crea una Oportunidad */
	public static Opportunity creaOportunidad(Id cliente, Id tipoRegistro, String producto, string familia) {
		final Opportunity opp = new Opportunity();
        opp.Name = 'Oportunidad Hija 01';
        opp.CloseDate = Date.today().addMonths(12);
        opp.Tipo_de_Oportunidad__c = 'Nueva';
        opp.AccountID = cliente;
		opp.RecordTypeId = tipoRegistro;
        opp.StageName = 'Abierta';
		opp.MX_RTL_Familia__c = familia;
        opp.MX_RTL_Producto__c = producto;
        opp.Amount = 123123123;
        opp.op_amountPivote_dv__c = 15000000 ;
	    insert opp;
	    return opp;
	}

}