src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BPyP_Un_Numero_Promotor__c</fullName>
        <description>Número promotor para BPyP</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Número promotor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Información sector del cliente definido desde el Data Mart</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Registro_Manual__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tipo de Registro Manual</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_BPP_SectorCodes__mdt.object
<CustomObject>
    <description>Permite guardar los códigos de sector que corresponden a cada tipo de cuenta, por ejemplo, para el tipo de cuenta personal se pueden guardar los códigos de sector F32  y F33.</description>
    <fields>
        <fullName>MX_BPP_SectorAccountType__c</fullName>
        <description>Permite elegir el tipo de cuenta que requiere cada código de sector, por ejemplo, el código de sector F32 corresponde a una cuenta personal, mientras que el código de sector M31 corresponde a una cuenta empresarial.</description>
        <label>Tipo de cuenta para el sector</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cuenta empresarial</fullName>
                    <default>true</default>
                    <label>Cuenta empresarial</label>
                </value>
                <value>
                    <fullName>Cuenta personal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_BPP_SectorCode__c</fullName>
        <description>Código de sector, por ejemplo, F32, M31.</description>
        <label>Código de sector</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Configuración de códigos de sector</label>
    <pluralLabel>Configuraciones de códigos de sector</pluralLabel>
</CustomObject>

src/objects/Trigger_Oportunidad__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Enciende/apaga los trigger del objeto oportunidad.</description>
    <fields>
        <fullName>BPyP_ClienteImportar_cls__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Campo de verificación para BPyP_ClienteImportar_cls__c</description>
        <inlineHelpText>Si se encuentra seleccionado se ejecuta el trigger BPyP_ClienteImportar_cls__c</inlineHelpText>
        <label>BPyP_ClienteImportar_cls</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger_Oportunidad</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BPyP_ClienteImportar_clsTest.cls
/*----------------------------------Desarrollado por INDRA---------------------------------
*Autor:         Ricardo Almanza Angeles
*Proyecto:      Max BBVA PI8
*Descripción:   Manejador para el trigger de BPyP de asignación de Clientes.
*_______________________________________________________________________________________
*Versión    Fecha       Autor                           Descripción
*1.0        14/FEB/2018 Ricardo Almanza Angeles         Creación
*1.1        27/AGO/2019 Cindy Arianna Hernández Nieto   Se modifica el método test_AsignaBkm
                                                        para crear cuentas personales y
                                                        corporativas.
                                                        Se cambia el nombre del método
                                                        test_AsignaBkm por testAsignaBkm.
-----------------------------------------------------------------------------------------*/
@isTest
private class BPyP_ClienteImportar_clsTest {

    /**
     * This is a test method for AsignaBkm
     */
    static testMethod void testAsignaBkm() {
        final User user1 = [Select Id,Name,VP_ls_Banca__c from User where Id=:UserInfo.getUserId()];
        final User user2 = MX_BPP_AccountDataFactory.getBPYPStandardUser();
        insert user2;
        System.debug('ralm bt Trigger_Oportunidad__c.getInstance().BPyP_ClienteImportar_cls__c '+Trigger_Oportunidad__c.getInstance().BPyP_ClienteImportar_cls__c);
        insert new Trigger_Oportunidad__c(BPyP_ClienteImportar_cls__c = true);
        System.debug('ralm at Trigger_Oportunidad__c.getInstance().BPyP_ClienteImportar_cls__c '+Trigger_Oportunidad__c.getInstance().BPyP_ClienteImportar_cls__c);
        user1.EmployeeNumber='123';
        Test.startTest();
        update user1;
        final Account[] accl=new List<Account>();
        Account[] accl2=new List<Account>();
        final Id[] idAcc=new List<Id>();
        final List<MX_BPP_SectorCodes__mdt> personAccCodes = [SELECT MX_BPP_SectorCode__c FROM MX_BPP_SectorCodes__mdt WHERE MX_BPP_SectorAccountType__c = 'Cuenta personal' LIMIT 1];
        Account personAcc;
        for(Integer i = 0; i < 200; i++) {
			personAcc = new Account();
	        personAcc.Tipo_de_Registro_Manual__c = 'BPYP_PRE';
	        personAcc.BPyP_Un_Numero_Promotor__c = '123';
	        personAcc.FirstName = 'Test ' + i;
            personAcc.LastName = 'Test';
	        personAcc.OwnerId = user2.Id;
            personAcc.Sector__c = personAccCodes[0].MX_BPP_SectorCode__c;
	        accl.add(personAcc);
	    }
        final Account businessAcc = new Account();
        businessAcc.Tipo_de_Registro_Manual__c = 'BPYP_PRE';
        businessAcc.BPyP_Un_Numero_Promotor__c = '123';
        businessAcc.Name = 'Test Business Acc';
        businessAcc.Sector__c = 'M31';
        businessAcc.OwnerId = user2.Id;
        accl.add(businessAcc);
        insert accl;
        Test.stopTest();
        for(Account ac: accl) {idAcc.add(ac.Id); }
        accl2 = [SELECT Id,Name,OwnerId FROM Account WHERE Id in :idAcc];
        for(Account ac: accl2) {
        	System.assertEquals(ac.OwnerId, user1.Id, 'Correcta asignación de usuario');
        }
    }

}