src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Canal__c</fullName>
        <description>Canal de venta</description>
        <formula>CASE( AccountSource  ,&quot;Outbound&quot;, &quot;Web&quot;, &quot;Inbound&quot;, &quot;Telemarketing&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Canal</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_Beneficiario__c.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_AMaterno_Beneficiario__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Apellido Materno del Beneficiario</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_APaterno_Beneficiario__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Apellido Paterno del Beneficiario</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Parentesco__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Parentesco</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Porcentaje__c</fullName>
        <label>Porcentaje</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cotización</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Beneficiarios</relationshipLabel>
        <relationshipName>Beneficiarios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Beneficiario</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Beneficiario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agencia__c</fullName>
        <description>Campo utilizado para cotización.</description>
        <label>Agencia</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Canal__c</fullName>
        <description>Campo para hacer una cotización.</description>
        <formula>IF( ISBLANK(Account.Canal__c), TEXT(LeadSource), Account.Canal__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Canal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origen__c</fullName>
        <label>Origen</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <description>Datos del vehículo.</description>
        <label>Servicio</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Usuario__c</fullName>
        <formula>Owner.Usuario__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Usuario</label>
        <type>Text</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_Folio_Cotizacion__c</fullName>
        <description>Folio de la póliza.</description>
        <label>Folio Cotizacion</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/URL_Auto_Seguro_Bancomer__mdt.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tipoUsoVehiculoCot__c</fullName>
        <label>tipoUsoVehiculoCot</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>URL Auto Seguro Bancomer</label>
    <pluralLabel>URL Auto Seguros Bancomer</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Agencia__c</fullName>
        <label>Agencia</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Canal__c</fullName>
        <label>Canal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <label>Servicio</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Canal__c</fullName>
        <label>Sub Canal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Usuario__c</fullName>
        <label>Usuario</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_Cotizador_ext.cls
/**
 * @File Name          : MX_SB_VTS_Cotizador_ext.cls
 * @Description        : Extension para clase MX_WB_TM_Cotizador_cls
 * @Author             : Eduardo Hernández Cuamatzi
 * @Group              : BBVA
 * @Last Modified By   : Eduardo Hernández Cuamatzi
 * @Last Modified On   : 4/6/2019 16:35:08
 * @Modification Log   :
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    27/5/2019 12:53:45   Eduardo Hernández Cuamatzi     Initial Version
 * 1.1    19/7/2019            Jaime Terrats                Se actualiza pase de parametros
**/
public without sharing class MX_SB_VTS_Cotizador_ext {

    /** Metadata Personalizada para URL Seguro Moto Bancomer **/
    static final String STR_ML_SMB = 'URLMSB';
    /** Metadata Personalizada para URL Seguro Fronterizo **/
    static final String STR_ML_SF = 'URLSFN';
    /** Metadata Personalizada para URL Auto Seguro Bancomer **/
    static final String STR_ML_ASD = 'URLASB';
    /** String para Datos de Usuario **/
    static String strDatosUsuario;
    /** String para Fecha **/
    static String strFechaMilisApex;
    /** String para Firma **/
    static String strFirmaMain;
    /** Inicialización **/
    static {
        strDatosUsuario = '';
        strFechaMilisApex = '';
        strFirmaMain = '';
    }

    /**
     * MX_SB_VTS_Cotizador_ext Constructor privado
     * @return   Evita singleton
     */
    private MX_SB_VTS_Cotizador_ext() { //NOSONAR

    }

    /**
    * Elabora el prefijo del URL con datos del Usuario y Firma Encriptada en MD5
    * @return String prefijo de URL generado
    **/
    public static String createUrlPrefix () {
        try {
            String strUsuario, strCanal, strSubCanal, strAgencia, strServicio, strUrlBegin;
            final User objUser = [ SELECT Id, Usuario__c, Canal__c, Sub_Canal__c, Agencia__c, Servicio__c FROM User WHERE Id =: UserInfo.getUserId() ];
            strFechaMilisApex = Utilities.fnGeneradorFechaMilis();
            strUsuario =validFieldUrl( objUser.Usuario__c );
            strCanal = validFieldUrl( objUser.Canal__c );
            strSubCanal = validFieldUrl( objUser.Sub_Canal__c );
            strAgencia = validFieldUrl( objUser.Agencia__c );
            strServicio = validFieldUrl( objUser.Servicio__c );
            strFirmaMain = Utilities.fnGeneradorMD5 ( strFechaMilisApex, strUsuario, strCanal, strSubCanal, strAgencia, strServicio );
            strDatosUsuario = '&usuario=' + strUsuario + '&servicio=' + strServicio + '&agencia=' + strAgencia + '&canal=' + strCanal + '&subcanal=' + strSubCanal;
            strUrlBegin = '?' + 'fechaMilis=' + strFechaMilisApex + strDatosUsuario + '&firma=' + strFirmaMain;
            return strUrlBegin;
        } catch ( QueryException quEx ) {
            throw new AuraHandledException(System.Label.MX_WB_ERROR+quEx);
        }
    }

    /**
    * Valida y crea el OpportunityLineItem y PricebookEntry
    * @param ID idOppor Oportunidad a asignar producto
    * @return boolean si pudo hacer el cambio o no
    **/
    public static String getMasterLabelValidation (ID idProd) {
        String strMasterLabel = '';
        String strProdName = [ SELECT Name FROM Product2 WHERE Id =: idProd ].Name;
        if ( String.isNotBlank( strProdName ) ) {
            strProdName = strProdName.touppercase( System.Label.MX_WB_CL_LocaleString );
            switch on strProdName {
                when 'SEGURO DE MOTO BANCOMER' {
                    strMasterLabel = STR_ML_SMB;
                }
                when 'SEGURO FRONTERIZO' {
                    strMasterLabel = STR_ML_SF;
                }
                when 'SEGURO DE AUTO FRONTERIZO BANCOMER' {
                    strMasterLabel = STR_ML_SF;
                }
                when 'SEGURO DE AUTO NACIONALIZADO' {
                    strMasterLabel = STR_ML_SF;
                }
                when 'AUTO SEGURO DINÁMICO' {
                    strMasterLabel = STR_ML_ASD;
                }
                when 'AUTO SEGURO DINAMICO' {
                    strMasterLabel = STR_ML_ASD;
                }
            }
        }
        return strMasterLabel;
    }

     /**
    * corretName description
    * @param  producto producto description
    * @return          return description
    */
    public static String correctName (String producto) {
        String correctName = producto;
        correctName = MX_SB_VTS_ValidCorrectNamesASD.validProASD(producto);
        final String vartem1 = correctName;
        correctName = MX_SB_VTS_ValidCorrectNamesASD.validProMoto(vartem1);
        final String vartem2 = correctName;
        correctName = MX_SB_VTS_ValidCorrectNamesASD.validProFront(vartem2);
        final String vartem3 = correctName;
        correctName = MX_SB_VTS_ValidCorrectNamesASD.validProLegal(vartem3);
        return correctName;
    }

    /**
     * validPostalCode Valida el código postal
     * @param  postalCode recibe el valor de un string
     * @return            Retorna un código postal
     */
    public static String validPostalCode (String postalCode, String postalCodeT) {
        String stringPostalCode = postalCode;
        stringPostalCode = String.isNotBlank(stringPostalCode) ? postalCode : postalCodeT;
        stringPostalCode = String.isNotBlank(stringPostalCode) ? stringPostalCode : '';
        return StringPostalCode;
    }

    /**
     * validFieldUrl Valida campos vacios
     * @param  valueEvalue valor a evaluar
     * @return            Retorna un valor String
     */
    public static String validFieldUrl (String valueEvalue) {
        String finalValue = '';
        if(String.isNotBlank(valueEvalue)) {
            finalValue = valueEvalue;
        }
        return finalValue;
    }

    /**
     * validOrigin valida origen
     * @param  origen  Origen LeadSource
     * @param  origenT Origen__c
     * @return         origen valido
     */
    public static String validOrigin (String origen, String origenT) {
        String finalOrigen = origen;
        finalOrigen = String.isNotBlank(finalOrigen) ? origen : origenT;
        finalOrigen = String.isNotBlank(finalOrigen) ? finalOrigen : '';
        return finalOrigen;
    }

    /**
     * crearURLSeguroHoVi description
     * @param  accountData Datos de cuenta
     * @param  quoteData   Datos de cotización
     * @param  strUrlBegin urlBase
     * @param  quoliData   Datos de partida de cotizacion
     * @return             retorna UrlCotizador
     */
    public static String crearURLSeguroHoVi (Account accountData, Quote quoteData, String strUrlBegin, QuoteLineItem quoliData, String strMasterLabel) {
        String urlSeg = '';
        final Map<String, String> valuesStr = new Map<String, String>();
        final String postalCode = MX_SB_VTS_Cotizador_ext.validPostalCode(String.valueOf(quoteData.BillingPostalCode), String.valueOf(accountData.BillingPostalCode));
        final boolean blFolio = String.isBlank(quoteData.MX_SB_VTS_Folio_Cotizacion__c) ? false : true;
        final URL_Auto_Seguro_Bancomer__mdt objMSB = [ SELECT DeveloperName, URL__c, tipoUsoVehiculoCot__c FROM URL_Auto_Seguro_Bancomer__mdt
         WHERE MasterLabel =: strMasterLabel];
        final String strTelfAseg = String.isNotBlank(quoteData.Phone) ? quoteData.Phone :'';
        final String strOrigen = MX_SB_VTS_Cotizador_ext.validOrigin(quoteData.Opportunity.LeadSource, quoteData.Opportunity.Origen__c);
        valuesStr.put('strOrigen', strOrigen);
        valuesStr.put('postalCode', postalCode);
        valuesStr.put('blFolio', String.valueOf(blFolio));
        valuesStr.put('strTelfAseg', strTelfAseg);
        switch on strMasterLabel {
            when 'URLHSB' {
                urlSeg = objMSB.URL__c + strUrlBegin +MX_SB_VTS_UrlBaseMultiproducts.urlBaseHogar(quoteData, accountData, valuesStr, quoliData)+ '#/paso1-datos-basicos';
            }
            when 'URLVSB' {
                final List<MX_SB_vTS_Beneficiario__c> beneficiarios = [select Name, MX_SB_VTS_APaterno_Beneficiario__c, MX_SB_VTS_AMaterno_Beneficiario__c, MX_SB_VTS_Parentesco__c, MX_SB_VTS_Porcentaje__c from MX_SB_vTS_Beneficiario__c where MX_SB_VTS_Quote__c =: quoteData.Id];
                urlSeg = objMSB.URL__c + strUrlBegin + MX_SB_VTS_UrlBaseMultiproducts.urlBaseVida(quoteData, accountData, valuesStr, quoliData, beneficiarios)+ objMSB.tipoUsoVehiculoCot__c + '#/paso1-datos-basicos';
            }
        }
        return urlSeg;
    }

    /**
    * Valida y crea el OpportunityLineItem y PricebookEntry
    * @param ID idOppor Oportunidad a asignar producto
    * @return boolean si pudo hacer el cambio o no
    **/
    public static String getMasterLabelHoVi (QuoteLineItem quoliData) {
        String strMasterLabel = '';
        String strProdName = [ SELECT Name FROM Product2 WHERE Id =: quoliData.Product2Id].Name;
        if ( String.isNotBlank( strProdName ) ) {
            strProdName = strProdName.touppercase( System.Label.MX_WB_CL_LocaleString );
            switch on strProdName {
                 when 'VIDA' {
                    strMasterLabel = System.Label.MX_SB_VTS_CustoMasterVida_LBL;
                }
                when 'HOGAR' {
                    strMasterLabel = System.Label.MX_SB_VTS_CustoMasterHogar_LBL;
                }
            }
        }
        return strMasterLabel;
    }
}