src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CR__c</fullName>
        <description>Este campo permite capturar el Cetro Responsable al que pertenece una cuenta.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Centro Responsable</inlineHelpText>
        <label>CR</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_de_cliente__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>No. de cliente</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UG__c</fullName>
        <formula>Owner.UG__c</formula>
        <label>UG</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EU001_RI__c.object
<CustomObject>
    <description>Contiene los datos necesarios de la RI para su asociacion con los Compromisos</description>
    <fields>
        <fullName>EG001_Valoracion_de_RI_DO__c</fullName>
        <description>La valoración que el Director de Oficina le da a la RI.</description>
        <label>Valoracion de RI DO</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Bueno</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Muy Bueno</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Excelente</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EG_001_ls_Valoracion_de_RI__c</fullName>
        <label>Valoracion de RI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Bueno</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Muy Bueno</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Excelente</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EU001_ft_Fecha_Inicio__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Fecha y hora de inicio de la RI</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de Inicio</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EU001_tl_Comentario_DO__c</fullName>
        <description>El comentario que proporciona el Director de Oficina al momento de valorar la RI.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comentario DO</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EU001_tl_Comentario_EV__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comentario EV</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EU001_tx_Estado__c</fullName>
        <description>Estado en que se encuentra la RI</description>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparación</fullName>
                    <default>true</default>
                    <label>Preparación</label>
                </value>
                <value>
                    <fullName>Presentación</fullName>
                </value>
                <value>
                    <fullName>Evaluacion</fullName>
                    <label>Evaluación</label>
                </value>
                <value>
                    <fullName>Finalizacion</fullName>
                    <label>Finalización</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reunión Individual</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>No RI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reunión Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EU_001_Compromiso__c.object
<CustomObject>
    <description>Compromisos Experiencia Única</description>
    <fields>
        <fullName>EU_001_Rb_Revisi_n_Individual_RI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Revisión Individual (RI)</description>
        <label>Reunión Individual</label>
        <referenceTo>EU001_RI__c</referenceTo>
        <relationshipLabel>Compromiso EU</relationshipLabel>
        <relationshipName>Compromiso_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compromiso EU</label>
    <nameField>
        <displayFormat>EUCP-{0000}</displayFormat>
        <label>Compromiso EU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compromiso EU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExpUni_Tablero_Grupal__c.object
<CustomObject>
    <fields>
        <fullName>EU_001_Un_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_001_tx_Atributo__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Concepto</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_001_tx_Indicador__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Indicador</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_Indicador__c</fullName>
        <description>Indicador que proviene del Tablero de Gestión que define el tipo Cartera que se esta manejando.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Agrupador</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_UG__c</fullName>
        <description>Numero de identificador del usuario</description>
        <encryptionScheme>None</encryptionScheme>
        <label>UG</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <label>Tablero de Gestión</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Nombre de Tablero Grupal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tablero de Gestión</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <description>Unidad gestora</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>UG</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segmento_Ejecutivo__c</fullName>
        <label>Segmento Ejecutivo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MEDIANA EMPRESA</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVO</fullName>
                </value>
                <value>
                    <fullName>EMPRESARIAL</fullName>
                </value>
                <value>
                    <fullName>FEDERAL</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO RESTO</fullName>
                </value>
                <value>
                    <fullName>GRANDES CUENTAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CR</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_BPP_RI_ListaCompromisos_Test.cls
/**
*Proyecto:               Digital Workplace Retail
*Descripción:            Clase Test para la clase MX_BPP_RI_ListCompromisos_Ctrl
*
*Cambios (Versiones)
*-------------------------------------------------------------------------------
*No.         Fecha            Autor                           Descripción
*------   ----------------   --------------------   ----------------------------
*1.0      24-06-2019         Cindy Hernández          Creación. Se crea a partir de la clase EU001_ConsolaDirector_test.
*1.0      24-06-2019         Cindy Hernández          Se modifica el método insertaCompromisosError para agregar el try catch y el System.assert.
													  Se modifica el método generaNuevoRITest agregando un tipo de registro correcto para BPyP.
													  Se agrega el método listaCompConstructor.
**/
@isTest
public  class MX_BPP_RI_ListaCompromisos_Test {
    /** Mapa perfilMapa*/
    static Map<String, Profile> perfilMapa = new Map<String, Profile>();
    /** Mapa RolMapa*/
    static Map<String, UserRole> RolMapa = new Map<String, UserRole>();
    /** Lista p*/
    static List<Profile> p;
    /** Lista userRole*/
    static List<UserRole> userRole;

    static {
        p = new List<Profile>([SELECT Id, Name FROM Profile WHERE Name = 'BPyP Director Oficina']);
        userRole = new List<UserRole>([SELECT Id, Name FROM UserRole WHERE Name = 'BPYP DIRECTOR OFICINA LOMAS']);

        for(Profile perfil:p) { perfilMapa.put(perfil.Name, perfil); }
        for(UserRole ur:userRole) { RolMapa.put(ur.Name, ur); }
    }

        @isTest static void insertaCompromisosError() {
        String recordTypeComp = RecordTypeMemory_cls.getRecType('EU_001_Compromiso__c', 'BPyP Captación');

        User u = new User();
        u.Alias = 'Director';
        u.Email='do.empresas1@bbva.tst.deploy.com';
        u.EmailEncodingKey='ISO-8859-1';
        u.LastName='Prueba1';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = perfilMapa.get('BPyP Director Oficina').Id;
        u.UserRoleId = rolMapa.get('BPYP DIRECTOR OFICINA LOMAS').Id;
        u.CR__c = '11121';
        u.UG__c = '524689';
        u.Segmento_Ejecutivo__c = 'EMPRESARIAL';
        u.TimeZoneSidKey='America/Mexico_City';
        u.UserName='Director@bbva.tst.deploy.com';
        u.VP_ls_Banca__c = 'Red BPyP';
        u.IsActive=true;
        insert u;
        User u2 = MX_BPP_UserAndRIDataFactory.creaUser2();
        u2.UG__c = '3342';
        insert u2;
        test.startTest();
        System.runAs(u2) {
            ExpUni_Tablero_Grupal__c tablero1= new ExpUni_Tablero_Grupal__c();
            tablero1.EU_UG__c = u2.UG__c;
            tablero1.EU_001_tx_Indicador__c = EU001_CLS_CONSTANTES.EU001_STR_PROMEDIO_DOR_POT;
            tablero1.EU_Indicador__c =EU001_CLS_CONSTANTES.EU001_STR_PROMEDIO_DOR_POT;
            tablero1.EU_001_tx_Atributo__c = EU001_CLS_CONSTANTES.EU001_STR_PROMEDIO_DOR_POT;
            tablero1.EU_001_Un_Valor__c =140234;
            insert tablero1;
            Account cuenta = new Account();
            cuenta.Name = 'Javier ';
            cuenta.No_de_cliente__c = '8364608932';
            insert cuenta;
        }
        System.runAs(u) {

            EU001_RI__c ri = MX_BPP_UserAndRIDataFactory.creaRI(u.Id);
            insert ri;

            EU_001_Compromiso__c comp = new EU_001_Compromiso__c();
            comp.EU_001_Rb_Revisi_n_Individual_RI__c=ri.id;
            comp.RecordTypeId = recordTypeComp;
            insert comp;

            MX_BPP_RI_ListaCompromisos_Ctrl.getTableCompromisos(ri.Id,'Abierto', null, null, null, null,null,null);
            MX_BPP_RI_ListaCompromisos_Ctrl.getTableCompromisos(ri.Id,'Vencido', null, null, null, null,null,null);
            MX_BPP_RI_ListaCompromisos_Ctrl.getTableCompromisos(ri.Id,'Abierto', null, null, null, null,'Captación','Nómina');
            MX_BPP_RI_ListaCompromisos_Ctrl.getTableCompromisos(ri.Id,'', null, 'Generales', '2018-12-12', '2018-12-12',null,null);
            Account ac= new Account();
			String errorMessage = '';
        	try {
            	MX_BPP_RI_ListaCompromisos_Ctrl.getInsertaCompromiso(recordTypeComp, ac,'Otros','0','2000-01-01','',0,ri.Id);
	        } catch (Exception e) {
    	        errorMessage = e.getMessage();
        	}
        	System.assertEquals('Script-thrown exception', errorMessage);
        }
        test.stopTest();
    }

    @isTest static void generaNuevoRITest(){
        User usr = MX_BPP_UserAndRIDataFactory.creaUser();
        insert usr;

        MX_BPP_RI_ListaCompromisos_Ctrl.getRecordTypeId('EU_001_Compromiso__c','BPyP Captación');
        MX_BPP_RI_ListaCompromisos_Ctrl.VerificaDirector();

        Test.startTest();

        Test.stopTest();
        System.assert(true,'This Works!');
    }


    @isTest static void ValoracionRI() {

        String[] ug = new List<String>();
        ug.add('789001');
        ug.add('789011');
        String [] evaluador = new List<String>();
        evaluador.add('EV');
        evaluador.add('DO');

        List<User> users = MX_BPP_UserAndRIDataFactory.createTestRecordsUser(ug, false);

        EU001_RI__c nuevoRi = new EU001_RI__c();
        nuevoRi.EU001_tx_Estado__c = 'Preparación';
        nuevoRi.EU001_ft_Fecha_Inicio__c = system.now();
        nuevoRi.ownerId = users.get(0).Id;

        insert nuevoRi;
        test.StartTest();

        MX_BPP_RI_ListaCompromisos_Ctrl.getUser(nuevoRi.id);

        nuevoRI.EU001_tl_Comentario_EV__c='HOLA';
        nuevoRI.EU001_tl_Comentario_DO__c='ADIOS';
        nuevoRI.EG_001_ls_Valoracion_de_RI__c='2';
        nuevoRI.EG001_Valoracion_de_RI_DO__c='3';
        update nuevoRI;

        system.debug('user name: ' +UserInfo.getName());

        System.assert(true, 'assert');
        test.stopTest();
    }

    @isTest
    static void listaCompConstructor() {
        String errorMessage = '';
        test.startTest();
        try {
	        MX_BPP_RI_ListaCompromisos_Ctrl listaComp = new MX_BPP_RI_ListaCompromisos_Ctrl();
            System.assert(listaComp != null);
        } catch (Exception e) {
            errorMessage = e.getMessage();
        }
        test.stopTest();
        System.assertEquals('', errorMessage);
    }

}