src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Division1__c</fullName>
        <formula>TEXT(Owner.Divisi_n__c)</formula>
        <label>División Usuario</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_de_cliente__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>No. de cliente</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UG__c</fullName>
        <formula>Owner.UG__c</formula>
        <label>UG</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>VP_tre_Cliente_PyME</fullName>
        <active>true</active>
        <description>Clientes PyME</description>
        <label>Cliente PyME</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <description>Unidad gestora</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>UG</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Director_divisional__c</fullName>
        <label>Director divisional</label>
        <relationshipName>Directores_Divisional</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Divisi_n__c</fullName>
        <label>División</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>VP_ls_Banca__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BAJIO</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO CENTRO</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA</fullName>
                </value>
                <value>
                    <fullName>NORESTE</fullName>
                </value>
                <value>
                    <fullName>NOROESTE</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE</fullName>
                </value>
                <value>
                    <fullName>SUR</fullName>
                </value>
                <value>
                    <fullName>SURESTE</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVA</fullName>
                </value>
                <value>
                    <fullName>BAJIO PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA NORTE PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA SUR PYME</fullName>
                </value>
                <value>
                    <fullName>NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>NOROESTE PYME</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>SUR PYME</fullName>
                </value>
                <value>
                    <fullName>SURESTE PYME</fullName>
                </value>
                <value>
                    <fullName>METRO NORTE</fullName>
                </value>
                <value>
                    <fullName>METRO SUR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_PyME_MassiveTransfer_Test.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name         MX_PyME_MassiveTransfer_Tst
* @Author       BBVA
* @Date         Created :  2019-05-14
* @Group        PYME
* @Description  Class that implements and tests methods from MX_PyME_MassiveTransfer_Cls
* @Changes      (most recent first)
*  |2019-05-14 |                   | First version
*  |2019-07-23 | Cindy Hernández   | Resolución de code smells detectados por sonar.
                                     Se utliza la etiqueta NOSONAR para falsos positivos con
                                     "Potentially unused variable" en variables que si se utilizan.
*  |2019-08-05 | Cindy Hernández   | Se crea el método createCaseWithAdmin.
* ------------------------------------------------------------------------------------------------
*/

@isTest
private class MX_PyME_MassiveTransfer_Test {
    /*------------------------------------------------------------------------------------------------------
    *@Description This method tests when a case is successfully created and when two accounts are in one request
    * -----------------------------------------------------------------------------------------------------
    * @Author   Daniel García
    * @Date     2019-05-14
    * @param    None
    * @return   Void
    * @example  createCase()
    * */

/**
* String with value 'Red PyME'
*/
    static final String PYME_STRING = 'Red PyME';
/**
* String with value 'METROPOLITANA NORTE PYME'
*/
    static final String NORTE_STRING = 'METROPOLITANA NORTE PYME';
/**
* String with value 'TEST'
*/
    static final String TEST_STRING = 'TEST';
/**
* String with value '12345'
*/
    static final String CLT_NO_STRING = '12345';
/**
* String with value 'EJEC PYME PLUS AGUASCALIENTES'
*/
    static final String ROL_STRING = 'EJEC PYME PLUS AGUASCALIENTES';
/**
* String with value 'Ejecutivo PyME Plus'
*/
    static final String PROFILE_STRING = 'Ejecutivo PyME Plus';
/**
* String with value 'Name'
*/
    static final String NAME_STRING = 'Name';

    @isTest static void createCaseWithAdmin() {
        final User dirDivisionalPyME = UtilitysDataTest_tst.crearUsuario('USUARIO DIV', 'D Divisional - D. PN PyME', 'D DIVISIONAL - D. PN BAJIO');
        dirDivisionalPyME.VP_ls_Banca__c = PYME_STRING;
        insert dirDivisionalPyME;

        final User adminUser = UtilitysDataTest_tst.crearUsuario('USUARIO ADMIN', Label.MX_PERFIL_SystemAdministrator, 'BBVA Bancomer');
        adminUser.VP_ls_Banca__c = PYME_STRING;
        adminUser.Divisi_n__c = NORTE_STRING;
        adminUser.Director_divisional__c = dirDivisionalPyME.id;
        insert adminUser;

        final User ejecPyMEOrigen = UtilitysDataTest_tst.crearUsuario('USUARIO EJEC', PROFILE_STRING, ROL_STRING);
        ejecPyMEOrigen.VP_ls_Banca__c = PYME_STRING;
        ejecPyMEOrigen.Divisi_n__c = NORTE_STRING;
        insert ejecPyMEOrigen;

        final User ejecPyMEDestino = UtilitysDataTest_tst.crearUsuario('USUARIO EJEC 2', PROFILE_STRING, ROL_STRING);
        ejecPyMEDestino.VP_ls_Banca__c = PYME_STRING;
        ejecPyMEDestino.Divisi_n__c = NORTE_STRING;
        insert ejecPyMEDestino;

        System.runAs(adminUser) {
            final List<String> idfixed = new List<String>();
            final Account acc = UtilitysDataTest_tst.crearCuenta(TEST_STRING,'VP_tre_Cliente_PyME');
            acc.No_de_cliente__c = CLT_NO_STRING;
            acc.OwnerId = ejecPyMEOrigen.id;
            insert acc;

            idfixed.add(acc.Id);
            Test.setFixedSearchResults(idfixed);

            final String accmap = MX_PyME_MassiveTransfer_Cls.searchDB('Account',NAME_STRING, 'Id','No_de_cliente__c','','', 'Division1__c', '' ,4,NAME_STRING, TEST_STRING );
            MX_PyME_MassiveTransfer_Cls.searchDB('User',NAME_STRING, 'Id','','UG__c','Divisi_n__c', '', 'VP_ls_Banca__c' ,4,NAME_STRING, TEST_STRING );

            final Object obj = (Object) accmap;
            system.debug(obj instanceof String);
            List<Object> lstObjCase = new List<Object>();
            final List<Object> lstobj = new List<Object>();
            lstObjCase = MX_PyME_MassiveTransfer_Cls.checkDuplicatedRecords(lstobj, obj);
            final String listaString = String.valueOf(lstObjCase).remove('([').remove('])');
            final List<Object> objs = new List<Object>();
            final Object cliente1 = (Object) listaString;
            final String obj2Str = String.valueOf(cliente1).replace(CLT_NO_STRING,'56789').replace(TEST_STRING,'TEST 2');
            final String obj3Str = String.valueOf(cliente1).replace(CLT_NO_STRING,'98234').replace(TEST_STRING,'TEST 3');
            final String obj4Str = String.valueOf(cliente1).replace(CLT_NO_STRING,'74635').replace(TEST_STRING,'TEST 4');
            final String obj5Str = String.valueOf(cliente1).replace(CLT_NO_STRING,'64532').replace(TEST_STRING,'TEST 5');
            final Object cliente2 = (Object) obj2Str;
            final Object cliente3 = (Object) obj3Str;
            final Object cliente4 = (Object) obj4Str;
            final Object cliente5 = (Object) obj5Str;
            objs.add(cliente1);
            objs.add(cliente2);
            objs.add(cliente3);
            objs.add(cliente4);
            objs.add(cliente5);
            final String userDestino = '{"val":"'+ ejecPyMEDestino.id +'","unidadG":"'+ ejecPyMEDestino.UG__c +'","text":"'+ ejecPyMEDestino.LastName +'","objName":"User","clientNumber":"","divCl":"","div":"'+ ejecPyMEDestino.Divisi_n__c +'","banca":"'+ PYME_STRING +'"}';
            MX_PyME_MassiveTransfer_Cls.createCase(objs,userDestino,true);
            final List<Case> casosCreados = [Select id from Case where status = 'Solicitada'];
            System.assertEquals(1, casosCreados.size(),'Caso creado y enviado para aprobación correctamente');
            MX_PyME_MassiveTransfer_Cls.createCase(objs,userDestino,true);
        }
    }

}