src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GBL_WF_Grupo_Comercial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo para la aplicación Workflow, se usa para seleccionar un Giro Comercial del proveedor</description>
        <label>Grupo Comercial</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Grupos Comerciales</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cuentas (Grupo Comercial)</relationshipLabel>
        <relationshipName>Cuentas3</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>GBL_WF_Comercios</fullName>
        <active>true</active>
        <description>Tipo de registro para Comercios en la Aplicación Workflow Campañas</description>
        <label>Comercios</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_WF_Campa_a_es_regional__c</fullName>
        <description>Campo para la aplicación WF, permite determinar si una campaña es regional o no para poder filtrar en el componente Lista campañas</description>
        <formula>IF(  LEN(CRM_WF_URL_Bines_y_Afiliaciones__c ) = 0 , &quot;No&quot;, &quot;Sí&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaña es regional</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_WF_Fecha_de_publicacion__c</fullName>
        <description>Fecha de publicación de promoción</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de publicación</label>
        <type>Date</type>
    </fields>
    <!--
-->
    <recordTypes>
        <fullName>CRM_WF_Alianzas_Comerciales</fullName>
        <active>true</active>
        <label>Alianzas Comerciales</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_WF_Catalogo_tarjetas__c.object
<CustomObject>
    <description>Objeto para la aplicación WF, que almacena los productos del banco</description>
    <fields>
        <fullName>MX_WF_CAT__c</fullName>
        <description>Campo de tipo porcentaje que permite almacenar el CAT de una tarjeta</description>
        <label>CAT</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MX_WF_Marca__c</fullName>
        <description>Campo de tipo lista de selección que permite especificar la marca de una tajeta</description>
        <label>Marca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WF_Mes_de_ltima_modificaci_n__c</fullName>
        <description>Campo de tipo texto que permite especificar la última fecha en la que se modificó el CAT de la tarjeta</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de última modificación</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MX_WF_Nombre_Producto__c</fullName>
        <description>Campo que almacena el nombre corto de la tarjeta</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre Producto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_WF_Producto__c</fullName>
        <description>Campo para la aplicación WF, permite almacenar el nombre del producto</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Crédito</fullName>
                </value>
                <value>
                    <fullName>Débito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Catálogo tarjetas</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre detallado del Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogo tarjetas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_WF_CampanasController.cls
/**
* ------------------------------------------------------------------------------
* @Nombre: MX_WF_CampanasController
* @Autor: Sandra Ventura García
* @Proyecto: Workflow Campañas
* @Descripción : Apex controller para componentes CmpListaCampanias, CmpListaTarjetas, CmpListaComercios
* ------------------------------------------------------------------------------
* @Versión       Fecha           Autor                         Descripción
* ------------------------------------------------------------------------------
* 1.0           18/09/2019     Sandra Ventura García	         test
* ------------------------------------------------------------------------------
*/
public with sharing class MX_WF_CampanasController {
   
  /**
  * @description: construnctor sin argumentos
  * @author Sandra Ventura
  */    
    @TestVisible
    private MX_WF_CampanasController() {}

  /**
  * @description: Devuelve lista de campañas.
  * @author Sandra Ventura
  */    
    @AuraEnabled
    public static List<Campaign> getListCampanas(String fFinVigCamp, String fIniVigCamp) { 
        try { 
             final Date fFinVigCampd = Date.valueOf(fFinVigCamp); 
             final Date fIniVigCampd = Date.valueOf(fIniVigCamp);
             return  [SELECT ID, Name, MX_WF_Campa_a_es_regional__c, StartDate,EndDate,MX_WF_Fecha_de_publicacion__c,Status FROM Campaign 
                      WHERE EndDate >= :fFinVigCampd  AND MX_WF_Fecha_de_publicacion__c<= :fIniVigCampd AND Status='Ejecución' AND MX_WF_Campa_a_es_regional__c='No' AND RecordType.DeveloperName = 'CRM_WF_Alianzas_Comerciales' ORDER BY Name ASC]; 
        } catch (Exception e) {
            throw new AuraHandledException(System.Label.MX_WF_ErrorGeneralWFC + e);
        }
    }
    
  /**
  * @description: Devuelve lista de tarjetas.
  * @author Sandra Ventura
  */ 
	@AuraEnabled
	public static List<MX_WF_Catalogo_tarjetas__c> getListTarjetas(String vfecha) {
        try {
            final Date vfechaH = Date.valueOf(vfecha); 
            return [SELECT id, Name, MX_WF_CAT__c, MX_WF_Marca__c,  MX_WF_Producto__c, MX_WF_Nombre_Producto__c 
                    FROM MX_WF_Catalogo_tarjetas__c WHERE MX_WF_Mes_de_ltima_modificaci_n__c <=: vfechaH ORDER BY MX_WF_Producto__c ASC];
        } catch(Exception e) {
			throw new AuraHandledException(System.Label.MX_WF_ErrorGeneralWFC + e);
		}
    }
    
  /**
  * @description: Devuelve lista de comercios.
  * @author Sandra Ventura
  */ 
	 @AuraEnabled
	public static List<Account> getListComercios(String grupoComercial) {
        try {
            final Id idGrupo = Id.valueOf(grupoComercial);
            return [SELECT ID, Name,  GBL_WF_Grupo_Comercial__r.Name  FROM Account WHERE  RecordType.DeveloperName = 'GBL_WF_Comercios' AND GBL_WF_Grupo_Comercial__r.Id =: idGrupo ORDER BY Name ASC];
           } catch(Exception e) {
			throw new AuraHandledException(System.Label.MX_WF_ErrorGeneralWFC+ e);
		} 
    }
}