src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <formula>Owner.UG__c</formula>
        <label>UG</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_PYME_Productos__c</fullName>
        <description>Productos Seleccionados para la Oportunidad</description>
        <label>Productos</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agencia Houston Cheques</fullName>
                </value>
                <value>
                    <fullName>Ahorro</fullName>
                </value>
                <value>
                    <fullName>Ahorro Liquido</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aplinet</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Financiero</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Puro</fullName>
                </value>
                <value>
                    <fullName>Asset Management Gestión Terceros</fullName>
                </value>
                <value>
                    <fullName>Asset Management Previsión Social</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Auto Flotilla Única</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bancomer.com</fullName>
                </value>
                <value>
                    <fullName>Bancomer Net Cash</fullName>
                </value>
                <value>
                    <fullName>Bonds (Garantías)</fullName>
                </value>
                <value>
                    <fullName>Cadenas NAFIN</fullName>
                </value>
                <value>
                    <fullName>Cajeros Automáticos (ATMs)</fullName>
                </value>
                <value>
                    <fullName>Cambios</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito PyME</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Cheques</fullName>
                </value>
                <value>
                    <fullName>Cheques cuenta de grupo / GL</fullName>
                </value>
                <value>
                    <fullName>Ciclos de Vida/ Previsión Social</fullName>
                </value>
                <value>
                    <fullName>CIE Electrónico</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE Ventanilla</fullName>
                </value>
                <value>
                    <fullName>Cobertura/Renta Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cond__Account_Campaign__c.object
<CustomObject>
    <description>Junction object to relate Campaigns with Clients</description>
    <label>Account Campaign</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

    <recordTypes>
        <fullName>MX_BPP_RedBpyp</fullName>
        <active>true</active>
        <businessProcess>BPyP</businessProcess>
        <description>Tipo de Registro para la banca BPyP</description>
        <label>BPyP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Banca__c</fullName>
        <description>Indica la banca al que pertenece el producto.</description>
        <label>Banca</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Banca</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <description>Unidad gestora</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>UG</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Banca.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Red BEyG</fullName>
    </customValue>
    <customValue>
        <fullName>Red PyME</fullName>
    </customValue>
    <customValue>
        <fullName>Red HI</fullName>
    </customValue>
    <customValue>
        <fullName>Red CF</fullName>
    </customValue>
    <customValue>
        <fullName>Red HP</fullName>
    </customValue>
    <customValue>
        <fullName>Red Hipotecaria</fullName>
    </customValue>
    <customValue>
        <fullName>Red HI Venta Remota</fullName>
    </customValue>
    <customValue>
        <fullName>Red BPyP</fullName>
    </customValue>
    <customValue>
        <fullName>Red HIP</fullName>
        <isActive>false</isActive>
        <label>Red HIP</label>
    </customValue>
    <masterLabel>Banca</masterLabel>
</GlobalValueSet>

src/classes/MX_PyME_Campaign_GenOpp_Cls.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     MX_PyME_Campaign_GenOpp_cls
* @Author   Jhovanny De La Cruz Cruz jhovanny.delacruz.contractor@bbva.com
* @Date     Created: 2019-01-29
* @Group    Account Campaign Opportunities
* @Description Generating class of Opportunities from products coming from Campaigns
* @Changes
*
*  |2019-01-29  jhovanny.delacruz.contractor@bbva.com
*				Account Campaign Opportunities functionality class
*/

public with sharing class MX_PyME_Campaign_GenOpp_Cls {

    /** String Id RecordType*/
    static String idRtOpp;

    @TestVisible
	private MX_PyME_Campaign_GenOpp_Cls() {

    }
/*------------------------------------------------------------------------------------------------------
*@Description Method to obtain the necessary fields of the account campaign
* -----------------------------------------------------------------------------------------------------
* @Author   Jhovanny De La Cruz Cruz
* @Date     2019-01-29
* @param    idCampaign ID of the current Account Campaign
* @return   cond__Account_Campaign__c  Account Campaign
* @example  var action = component.get("c.getAccountCampaignFields"); javascript method
* */

    @AuraEnabled
    public static cond__Account_Campaign__c getAccountCampaignFields(String idCampaign) {
        cond__Account_Campaign__c accCamp = new cond__Account_Campaign__c();
        try {
            accCamp = [SELECT id,Name,cond__participant_id__c,cond__campaign_id__c FROM cond__Account_Campaign__c WHERE id =: idCampaign LIMIT 1]; //NOSONAR
        } catch (Exception e) { throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return accCamp;
    }

/*------------------------------------------------------------------------------------------------------
*@Description Method to obtain all the related products in the main campaign
* -----------------------------------------------------------------------------------------------------
* @Author   Jhovanny De La Cruz Cruz
* @Date     2019-01-29
* @param    idCampaign ID of the current Account Campaign
* @return   List<Product2>
* @example  var action = component.get("c.getProductCampaign"); javascript method
* */
    @AuraEnabled
    public static List<Product2> getProductCampaign(String idCampaign) {
        List<cond__Account_Campaign__c> accCamp = new List<cond__Account_Campaign__c>();
        List<Campaign> camps = new List<Campaign>();
        final List<String> prodValues = new List<String>();
        List<Product2> lsProd2 = new List<Product2>(); //NOSONAR
        try {
            String banca = '';
            banca = [SELECT id,Name,UG__c,VP_ls_Banca__c FROM User WHERE isActive = true AND Id =: UserInfo.getUserId()].VP_ls_Banca__c; //NOSONAR
            accCamp = [SELECT id,Name,cond__participant_id__c,cond__campaign_id__c FROM cond__Account_Campaign__c WHERE id =: idCampaign LIMIT 1];
            if(!accCamp.isEmpty()) {
                camps = [SELECT id,Name,MX_PYME_Productos__c,recordtypeId FROM Campaign WHERE id =: accCamp[0].cond__campaign_id__c LIMIT 1];
            }
            if(!camps.isEmpty()) {
                if(camps[0].MX_PYME_Productos__c == null) {
                    prodValues.add('');
                } else {
                    prodValues.addall(camps[0].MX_PYME_Productos__c.split(';'));
                }
            }
            if (!prodValues.isEmpty()) {
                lsProd2 = [SELECT id,Name,Family,ProductCode,Banca__c FROM Product2 WHERE IsActive = true AND ProductCode IN:prodValues AND Banca__c INCLUDES (:banca)]; //NOSONAR
            }
        } catch (Exception e) { throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return lsProd2;
    }

/*------------------------------------------------------------------------------------------------------
*@Description Method to obtain the banking opportunity related to the products of the campaign
* -----------------------------------------------------------------------------------------------------
* @Author   Jhovanny De La Cruz Cruz
* @Date     2019-01-29
* @param    idProduct2 id of the related product2
* @return   String  recordtypeid of the type of record of the opportunity to generate
* @example  var action = component.get("c.relatedRecordType"); javascript method
* */
    @AuraEnabled
    public static String relatedRecordType() {
        try {
        idRtOpp=[SELECT id,Name,DeveloperName FROM Recordtype WHERE SobjectType = 'Opportunity' AND DeveloperName =: 'MX_BPP_RedBpyp' LIMIT 1].id; //NOSONAR
        } catch (Exception e) { throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return idRtOpp;
    }
}