src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MX_SB_BCT_Id_Cliente_Banquero__c</fullName>
        <description>Este campo almacena el Id del Cliente como Id Externo</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Id Cliente Banquero</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Banquero__c.object
<CustomObject>
    <fields>
        <fullName>MX_SB_BCT_Id_Banquero__c</fullName>
        <description>Identificador del Banquero</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Id Banquero</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_BCT_Id_Cliente__c</fullName>
        <description>Identificador del Cliente</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Id Cliente</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Banquero</label>
    <nameField>
        <displayFormat>BCT-{0000}</displayFormat>
        <label>Identificador del banquero</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banqueros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_Generica__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista Genérica para múltiples valores del flujo de venta.</description>
	<fields>
        <fullName>MX_SB_BCT_user_Banquero_Default__c</fullName>
        <description>Id Salesforce Banquero base al que se asignan las cuentas al no existir un banquero asignado.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Id Salesforce Banquero base al que se asignan las cuentas al no existir un banquero asignado.</inlineHelpText>
        <label>MX_SB_BCT_user_Banquero_Default</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>MX_SB_VTS_Generica</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_Aplica_Cierre__c</fullName>
        <description>Indica si ya se cuenta con contrato para permitir el cierre de la oportunidad</description>
        <defaultValue>false</defaultValue>
        <label>Aplica Cierre</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Información para la cotización.</description>
        <label>Motivo de la Oportunidad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Venta Pre emisión</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_SB_BCT_Ban_Convert_tst.cls
/*
*
* @author Tania Vazquez
* @description This class will be used to test MX_SB_BCT_BanqueroTriggerHandler
*
*           No  |     Date     |     Author      |    Description
* @version  1.0    08/10/2019     Tania Vazquez     Create Banquero__c, cuentas
*
*/
@isTest
public class MX_SB_BCT_Ban_Convert_tst {
    @testSetup
    static void testData() {
		final User admin = MX_WB_TestData_cls.crearUsuario('test hogar', system.label.MX_SB_VTS_ProfileAdmin);
        Insert admin;
        final User admin2 = MX_WB_TestData_cls.crearUsuario('test hogar2', system.label.MX_SB_VTS_ProfileAdmin);
        admin2.FederationIdentifier='MX000011';
        Insert admin2;
        System.runAs(admin) {
        MX_WB_TestData_cls.createStandardPriceBook2();
            final Product2 producto = MX_WB_TestData_cls.productNew('Hogar');
            producto.isActive = true;
            Insert producto;
            final PricebookEntry pbe = MX_WB_TestData_cls.priceBookEntryNew(producto.Id);
            Insert pbe;
            final Account acc = MX_WB_TestData_cls.crearCuenta('Doe', 'MX_WB_rt_PAcc_Telemarketing');
            acc.MX_SB_BCT_Id_Cliente_Banquero__c ='99';
            Insert acc;
            final Opportunity opp = MX_WB_TestData_cls.crearOportunidad('OppTest Hogar', acc.Id, admin.Id, 'ASD');
            opp.Producto__c = 'Hogar';
            opp.Reason__c = 'Venta';
            opp.MX_SB_VTS_Aplica_Cierre__c = true;
            Insert opp;
            final Contract contr = MX_WB_TestData_cls.vtsCreateContract(acc.Id, admin.Id, producto.Id);
            Insert contr;
            final MX_SB_VTS_Generica__c generica = MX_WB_TestData_cls.GeneraGenerica('MX_SB_BCT_user_Banquero', 'CP5');
            generica.MX_SB_BCT_user_Banquero_Default__c=admin2.FederationIdentifier;
            insert generica;
                
    	}
    }
    
    @isTest static void valo() {
        Test.startTest();
            final User admin = MX_WB_TestData_cls.crearUsuario('test hogar2', system.label.MX_SB_VTS_ProfileAdmin);
            Insert admin;
            final Opportunity idcompara = [select id, OwnerId from Opportunity where name='OppTest Hogar'];
            System.runAs(admin) {
            final List<Banquero__c> ban = new List<Banquero__c>();
            final Banquero__c banque = new Banquero__c(MX_SB_BCT_Id_Banquero__c='990099',MX_SB_BCT_Id_Cliente__c='99');
            ban.add(banque);
            final Banquero__c banque1 = new Banquero__c(MX_SB_BCT_Id_Banquero__c='1234',MX_SB_BCT_Id_Cliente__c='7');
            ban.add(banque1);
            final Banquero__c banque2 = new Banquero__c(MX_SB_BCT_Id_Banquero__c='1234',MX_SB_BCT_Id_Cliente__c='5');
            ban.add(banque2);
            final Banquero__c banque3 = new Banquero__c(MX_SB_BCT_Id_Banquero__c='1234',MX_SB_BCT_Id_Cliente__c='878');
            ban.add(banque3);
            insert ban;
            final Opportunity idcomparafuture = [select id, OwnerId from Opportunity where name='OppTest Hogar'];  
            system.assertNotEquals(idcomparafuture.OwnerId, idcompara.OwnerId, 'Flujo Correcto');
        Test.stopTest();
        }
    }
     @isTest static void updateAccountQuickAction2() {
         Test.startTest();
         String result2;
             try {
                  result2 = MX_SB_BCT_UpdateAccountcla.UpdateAcc('123');
             } catch(System.AuraHandledException e) {
                  system.assert(String.isEmpty(result2),'Funcionó');
             }
     }
             
}