src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_de_cliente__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>No. de cliente</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>VP_tre_Cliente_PyME</fullName>
        <active>true</active>
        <description>Clientes PyME</description>
        <label>Cliente PyME</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_PYME_Productos__c</fullName>
        <description>Productos Seleccionados para la Oportunidad</description>
        <label>Productos</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agencia Houston Cheques</fullName>
                </value>
                <value>
                    <fullName>Ahorro</fullName>
                </value>
                <value>
                    <fullName>Ahorro Liquido</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aplinet</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Financiero</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Puro</fullName>
                </value>
                <value>
                    <fullName>Asset Management Gestión Terceros</fullName>
                </value>
                <value>
                    <fullName>Asset Management Previsión Social</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Auto Flotilla Única</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bancomer.com</fullName>
                </value>
                <value>
                    <fullName>Bancomer Net Cash</fullName>
                </value>
                <value>
                    <fullName>Bonds (Garantías)</fullName>
                </value>
                <value>
                    <fullName>Cadenas NAFIN</fullName>
                </value>
                <value>
                    <fullName>Cajeros Automáticos (ATMs)</fullName>
                </value>
                <value>
                    <fullName>Cambios</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito PyME</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Cheques</fullName>
                </value>
                <value>
                    <fullName>Cheques cuenta de grupo / GL</fullName>
                </value>
                <value>
                    <fullName>Ciclos de Vida/ Previsión Social</fullName>
                </value>
                <value>
                    <fullName>CIE Electrónico</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE Ventanilla</fullName>
                </value>
                <value>
                    <fullName>Cobertura/Renta Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cond__Account_Campaign__c.object
<CustomObject>
    <description>Junction object to relate Campaigns with Clients</description>
    <label>Account Campaign</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Campaigns</pluralLabel>
    <recordTypes>
        <fullName>MX_PYME_Campania_Cargada</fullName>
        <active>true</active>
        <label>Campaña Cargada</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>cond__participant_campaign_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Campaign</label>
        <referenceTo>cond__Account_Campaign__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>

    <recordTypes>
        <fullName>MX_BPP_RedBpyp</fullName>
        <active>true</active>
        <businessProcess>BPyP</businessProcess>
        <description>Tipo de Registro para la banca BPyP</description>
        <label>BPyP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_PYME_AccCampOpp_Test.cls
/*******************************************************************************
@Name                   MX_PYME_AccCampOpp_Test
Desarrollado por:       Indra
@Author                 Ricardo Almanza
@Date                   2019-01-17
Proyecto:               PYME
@Group                  Trigger Oportunidad
*************************************************************************************
@Description            Clase de test para la clase MX_PYME_AccCampOpp
*************************************************************************************
@Changes
2019-04-04  ricardo.almanza.contractor@bbva.com     Uso de etiqueta para multilenguajes
2019-07-11  jairignacio.gonzalez.contractor@bbva.com    Se depuro clase con los metodos confirmados en la migracion de bpyp y pymes
/*******************************************************************************/
@isTest
public with sharing class MX_PYME_AccCampOpp_Test {
    @isTest static void testGeneracionOpp() {
        final User csidmnvl = UtilitysDataTest_tst.crearUsuario('MX_PYME_Test', Label.MX_PERFIL_SystemAdministrator, 'DIRECCIÓN GENERAL BMI');
        insert csidmnvl;

        System.runAs(csidmnvl) {
            final Account cliente = UtilitysDataTest_tst.crearCuenta('UsuarioTest', 'VP_tre_Cliente_PyME');
            cliente.no_de_cliente__c = '01234567';
            insert cliente;
            final cond__Account_Campaign__c accCamp = UtilitysDataTest_tst.crearAccCampaign(csidmnvl.Id, 'MX_PYME_Campania_Cargada', 'T123', '01234567');
            insert accCamp;
            final Campaign camp = [Select Id, MX_PYME_Productos__c, cond__campaign_id__c from Campaign where cond__campaign_id__c = 'T123'];
            System.assertNotEquals(null, camp.Id,'Campaña creada por trigger');
            camp.MX_PYME_Productos__c = 'Auto';
            update camp;

            UtilitysDataTest_tst.crearProdForm('Colocación', 'Auto');
            final Opportunity opp = UtilitysDataTest_tst.crearOportunidad('Test AccCamp', cliente.Id, csidmnvl.Id, 'Colocación', 'Auto', null, 'MX_BPP_RedBpyp');
            opp.cond__participant_campaign_id__c = accCamp.Id;
            Insert opp;
            System.assertNotEquals(null, opp.Id,'Oportunidad creada y enlazada a campaña');
            final cond__Account_Campaign__c accCamp2 = UtilitysDataTest_tst.crearAccCampaign(csidmnvl.Id, 'MX_PYME_Campania_Cargada', 'T123', '01234568');
            insert accCamp2;
            opp.cond__participant_campaign_id__c = accCamp2.Id;
            try {
                update opp;
            } catch(System.DmlException e) {
                system.assert(e.getMessage().contains(Label.MX_PYME_AccCampAccErrOpp), 'Error controlado de no cliente asociado');
            }
            delete opp;
        }
    }
}