src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MX_SB_BCT_Id_Cliente_Banquero__c</fullName>
        <description>Este campo almacena el Id del Cliente como Id Externo</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Id Cliente Banquero</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Banquero__c.object
<CustomObject>
    <label>Banquero</label>
    <nameField>
        <displayFormat>BCT-{0000}</displayFormat>
        <label>Identificador del banquero</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banqueros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_SB_BCT_UpdateAccountcla_tst.cls
/*
*
* @author Tania Vazquez
* @description This class will be used to test MX_SB_BCT_BanqueroTriggerHandler
*
*           No  |     Date     |     Author      |    Description
* @version  1.0    08/10/2019     Tania Vazquez     Create Banquero__c, cuentas
*
*
*/
@isTest
public class MX_SB_BCT_UpdateAccountcla_tst {
    
     @testSetup
    static void testData() {
		final User admin = MX_WB_TestData_cls.crearUsuario('test hogar', system.label.MX_SB_VTS_ProfileAdmin);
        Insert admin;
        final User admin2 = MX_WB_TestData_cls.crearUsuario('test hogar2', system.label.MX_SB_VTS_ProfileAdmin);
        admin2.FederationIdentifier='MX000011';
        Insert admin2;
        System.runAs(admin) {
        MX_WB_TestData_cls.createStandardPriceBook2();
            final Account acc = MX_WB_TestData_cls.crearCuenta('Doe', 'MX_WB_rt_PAcc_Telemarketing');
            acc.MX_SB_BCT_Id_Cliente_Banquero__c ='99';
            Insert acc;
    	}
    }
    @isTest static void updateAccountQuickAction() {
            Test.startTest();
        	Final Account acc = [select id, OwnerId from Account where FirstName='Doe'];
                final String result = MX_SB_BCT_UpdateAccountcla.UpdateAcc(acc.Id);
        		system.assert(String.isNotEmpty(result),'Funcionó');
            Test.stopTest();
    }
}