src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <formula>Owner.UG__c</formula>
        <label>UG</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_RTL_Familia__c</fullName>
        <description>Listado de familia de productos</description>
        <label>Familia</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Captación</fullName>
                </value>
                <value>
                    <fullName>Colocación</fullName>
                </value>
                <value>
                    <fullName>Servicios</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_RTL_Producto__c</fullName>
        <description>Listado de los productos dependientes de la familia seleccionada en la oportunidad</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_RTL_Familia__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cuenta en Dólares</fullName>
                </value>
                <value>
                    <fullName>Fondos de Inversión</fullName>
                </value>
                <value>
                    <fullName>Maestra Patrimonial Dólares</fullName>
                </value>
                <value>
                    <fullName>Membresía BP</fullName>
                </value>
                <value>
                    <fullName>Nómina</fullName>
                </value>
                <value>
                    <fullName>Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Producto 21</fullName>
                </value>
                <value>
                    <fullName>MLB</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Consumo</fullName>
                </value>
                <value>
                    <fullName>Hipotecario</fullName>
                </value>
                <value>
                    <fullName>TDC</fullName>
                </value>
                <value>
                    <fullName>PrePaid Forward</fullName>
                </value>
                <value>
                    <fullName>Collares</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Domiciliaciones</fullName>
                </value>
                <value>
                    <fullName>Servicios No Financieros</fullName>
                </value>
                <value>
                    <fullName>Traspaso Patrimonial</fullName>
                </value>
                <value>
                    <fullName>One Team</fullName>
                </value>
                <value>
                    <fullName>Fideicomiso</fullName>
                </value>
                <value>
                    <fullName>Socios Globales</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Gastos Médicos Mayores Indemnizatorio</fullName>
                </value>
                <value>
                    <fullName>Hogar Seguro Plus</fullName>
                </value>
                <value>
                    <fullName>Vida Segura Patrimonial</fullName>
                </value>
                <value>
                    <fullName>Meta Segura</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>op_amountPivote_dv__c</fullName>
        <description>Campo auxiliar para ligar los montos de oportunidad al Campo Amount. (Puente para salvar la relación que se crea con Product2 y OpportunityLineItem</description>
        <label>Monto de la Oportunidad</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Oportunidad__c</fullName>
        <description>las oportunidades incrementales, nuevas y de renovación en los diferentes productos de la Banca de Empresas y Gobierno, con el propósito de generar un historial comercial puntual de cada una de las acciones comerciales llevadas a cabo en la RED.</description>
        <label>Tipo de oportunidad</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adquisición de Afiliación</fullName>
                </value>
                <value>
                    <fullName>Disminución</fullName>
                </value>
                <value>
                    <fullName>Disposición</fullName>
                </value>
                <value>
                    <fullName>Establecimiento</fullName>
                </value>
                <value>
                    <fullName>Incremental</fullName>
                </value>
                <value>
                    <fullName>Incremento</fullName>
                </value>
                <value>
                    <fullName>Modificación</fullName>
                </value>
                <value>
                    <fullName>Nueva</fullName>
                </value>
                <value>
                    <fullName>Ratificación</fullName>
                </value>
                <value>
                    <fullName>Reactivación</fullName>
                </value>
                <value>
                    <fullName>Recontratacion</fullName>
                    <label>Recontratación</label>
                </value>
                <value>
                    <fullName>Renovación</fullName>
                </value>
                <value>
                    <fullName>Renovación Incremental</fullName>
                </value>
                <value>
                    <fullName>Revisión Anual</fullName>
                </value>
                <value>
                    <fullName>Seleccionar</fullName>
                    <default>true</default>
                    <label>Seleccionar</label>
                </value>
                <value>
                    <fullName>Renovación de Contrato</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_de_Registro_Manual2__c</fullName>
        <description>Tipo de registro asociado a la oportunidad</description>
        <inlineHelpText>Tipo de Registro Manual</inlineHelpText>
        <label>Tipo de Registro de la Oportunidad</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adquirente</fullName>
                </value>
                <value>
                    <fullName>Adquirente v2</fullName>
                </value>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aportaciones</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>Banca de Inversión Empresas (BIE)</fullName>
                </value>
                <value>
                    <fullName>Banca electrónica</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bcom</fullName>
                </value>
                <value>
                    <fullName>BPyP</fullName>
                </value>
                <value>
                    <fullName>Cadenas de valor</fullName>
                </value>
                <value>
                    <fullName>CIB</fullName>
                </value>
                <value>
                    <fullName>CIE</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE V2</fullName>
                </value>
                <value>
                    <fullName>Coberturas y derivados</fullName>
                </value>
                <value>
                    <fullName>Comercio internacional</fullName>
                </value>
                <value>
                    <fullName>Consumer Finance</fullName>
                </value>
                <value>
                    <fullName>Cotización Arrendamiento</fullName>
                    <default>true</default>
                    <label>Cotización Arrendamiento</label>
                </value>
                <value>
                    <fullName>DEM</fullName>
                </value>
                <value>
                    <fullName>DEM V2</fullName>
                </value>
                <value>
                    <fullName>DIE</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Disposición</fullName>
                </value>
                <value>
                    <fullName>Domiciliación</fullName>
                </value>
                <value>
                    <fullName>Domiciliación PyME</fullName>
                </value>
                <value>
                    <fullName>Domiciliación V2</fullName>
                </value>
                <value>
                    <fullName>Fiduciario</fullName>
                </value>
                <value>
                    <fullName>Fiduciario V2</fullName>
                </value>
                <value>
                    <fullName>Financiamiento</fullName>
                </value>
                <value>
                    <fullName>Colocación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <recordTypes>
        <fullName>MX_BPP_RedBpyp</fullName>
        <active>true</active>
        <businessProcess>BPyP</businessProcess>
        <description>Tipo de Registro para la banca BPyP</description>
        <label>BPyP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <description>Unidad gestora</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>UG</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segmento_Ejecutivo__c</fullName>
        <label>Segmento Ejecutivo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MEDIANA EMPRESA</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVO</fullName>
                </value>
                <value>
                    <fullName>EMPRESARIAL</fullName>
                </value>
                <value>
                    <fullName>FEDERAL</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO RESTO</fullName>
                </value>
                <value>
                    <fullName>GRANDES CUENTAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Opportunity_Trigger_TEST.cls
/********************************************************************************
*   Autor:      Desconocido
*   Proyecto:    MAX 3.0 - BBVA Bancomer
*   Descripción:  Clase de Prueba para Opportunity_Tgr
*   -------------------------------------------------------------------------------------------
*   Versión    Fecha      		Autor                		Descripción
*   1.0      XX-XX-xxxx	    	 	  						Creación.
*   1.1 	26/ENE/2018		Ing. Arsenio Perez Lopez  	Se Aislan costantes detectadas por sonarCUbe
*   1.2      24/05/18       Luis Fernando Romero        se agrega linea para cubrir afterDelete
*   1.3     01-10-2018      Fernando Jaime              Se cambia Administrador del sistema por etiqueta personalizada
*   1.4		11/07/2019		Jair I Gonzalez 		    Se depuro clase con los metodos confirmados en la migracion de bpyp
*********************************************************************************/
@isTest
public without sharing class Opportunity_Trigger_TEST {

    /** Comentario de prueba */
	static list<String> constan = new list<string>{'Esto es un comentario de prueba','Otro'};

	@testSetup static void setup() {
        final User admin = new User(
            Alias = 'userUno',
            Email='adminBBVA@bbva.tst.deploy.com',
            EmailEncodingKey='ISO-8859-1',
            LastName='Prueba',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = [SELECT Id, Name FROM Profile WHERE Name =: Label.MX_PERFIL_SystemAdministrator].Id,
            UG__c = '0008134',
            Segmento_Ejecutivo__c = 'EMPRESARIAL',
            TimeZoneSidKey='America/Mexico_City',
            UserName='adminBBVA@bbva.tst.deploy.com',
            VP_ls_Banca__c = 'Red BPyP',
            IsActive=true
        );
        insert admin;

        System.runAs(admin) {
            final Account cliente = new Account();
            cliente.name = 'Prueba';
            insert cliente;

            UtilitysDataTest_tst.crearProdForm('Colocación', 'Collares');

            final Opportunity opp = new Opportunity();
            //opp.CR_REL_NombreAval__c = cliente.Id;
            opp.AccountID = cliente.Id;
            opp.StageName = 'Abierta';
            opp.Tipo_de_Oportunidad__c = 'Nueva';
            opp.CloseDate = Date.today();
            opp.Name = 'Prueba';
            opp.MX_RTL_Familia__c = 'Colocación';
            opp.MX_RTL_Producto__c = 'Collares';
            opp.Tipo_de_Registro_Manual2__c = 'Adquirente TPV';
            opp.op_amountPivote_dv__c = 100;
            opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName =: 'MX_BPP_RedBpyp'].Id;
            insert opp;
        }

	}

     @isTest static void actualizaOportunidadCambioEtapa() {

         final User user = [SELECT Id, VP_ls_Banca__c FROM User WHERE Email = 'adminBBVA@bbva.tst.deploy.com'];
         System.runAs(user) {
             final Opportunity oportunidadCreada = [SELECT Id, Name, StageName FROM Opportunity LIMIT 1];
             oportunidadCreada.StageName = 'Cerrada Ganada';
             Test.startTest();
             Update oportunidadCreada;
             system.assertEquals(oportunidadCreada.StageName , 'Cerrada Ganada','Funciono');
             Test.stopTest();
         }

     }

}