src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Correo_Electronico__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Campo utilizado como external ID</description>
        <externalId>true</externalId>
        <label>Correo Electrónico</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Genero__c</fullName>
        <description>Género del cliente.</description>
        <label>Género</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Masculino</fullName>
                </value>
                <value>
                    <fullName>Femenino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <fields>
        <fullName>Poliza__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo de busqueda de la oportunidad para presentarlo como numero de poliza</description>
        <label>Póliza</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <errorMessage>El cliente no tiene una póliza emitida asociada. Verifique los datos con el área de ventas.</errorMessage>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Opportunity.Estatus__c</field>
                <operation>equals</operation>
                <value>Emitida</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Casos</relationshipLabel>
        <relationshipName>Casos</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--App Casos-->
    <!--App Casos-->
<!--Multiasistencia-->
    <!--Multiasistencia-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>Genero__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CargaInicial__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sincronización con clipert</description>
        <label>Carga Inicial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CorreoCliente__c</fullName>
        <description>Correo del asegurado.</description>
        <label>Correo del Asegurado</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>correoElectronicoContratante__c</fullName>
        <label>Correo Electronico Contratante</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Estatus__c</fullName>
        <description>Estatus de la cotización.</description>
        <label>Estatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Creada</fullName>
                </value>
                <value>
                    <fullName>Tarificada</fullName>
                </value>
                <value>
                    <fullName>Formalizada</fullName>
                </value>
                <value>
                    <fullName>Emitida</fullName>
                </value>
                <value>
                    <fullName>Cobrada</fullName>
                </value>
                <value>
                    <fullName>Cancelada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FolioCotizacion__c</fullName>
        <description>Folio para dar seguimiento a la cotización.</description>
        <externalId>true</externalId>
        <label>Folio Cotizacion</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Motivoelegibilidad__c</fullName>
        <label>Motivo de no elegibilidad</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Motivo uso comercial</fullName>
                </value>
                <value>
                    <fullName>Uso de taxi</fullName>
                </value>
                <value>
                    <fullName>Mayor a 3.5 toneladas</fullName>
                </value>
                <value>
                    <fullName>Antiguedad</fullName>
                </value>
                <value>
                    <fullName>Fronterizo / legalizado</fullName>
                </value>
                <value>
                    <fullName>Salvamento / Siniestrado</fullName>
                </value>
                <value>
                    <fullName>Auto fuera de base</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumerodePoliza__c</fullName>
        <description>Número de póliza para cotización.</description>
        <externalId>true</externalId>
        <label>Número de Póliza</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sexo_conductor__c</fullName>
        <description>Sexo del conductor para evaluación del cliente.</description>
        <label>Sexo conductor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Masculíno</fullName>
                </value>
                <value>
                    <fullName>Femenino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>telefonoCelularContratante__c</fullName>
        <description>Teléfono celular del contratante.</description>
        <label>Teléfono Celular Asegurado</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>TipoPersonaCliente__c</fullName>
        <label>Tipo de Persona</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Física</fullName>
                </value>
                <value>
                    <fullName>Moral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TemporalCasosPolizas__c.object
<CustomObject>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Casos - Polizas</relationshipLabel>
        <relationshipName>TemporalCasosPolizas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NoPoliza__c</fullName>
        <label>No de Poliza</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Temporal Casos - Polizas</label>
    <nameField>
        <label>Número de Caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temporal Casos - Polizas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WB_CrearData_cls.cls
/****************************************************************************************************
    Información general
    -------------------
    author: Javier Armando Tibamoza Cubillos
    email: jtibamoza@avanxo.com
    company: Avanxo Colombia
    Project: Implementación Salesforce
    Customer: WIBE
    Description: Crear clase para crear Data

    Information about changes (versions)
    -------------------------------------
    Number    Dates           Author                       Description
    ------    --------        --------------------------   -----------
    1.0       08-Mar-2016     Javier Tibamoza              Creación de la Clase
	1.1       10-Ene-2019     José David Mendoza           Se agrega TipoPersonaCliente__c a la creación de la oportunidad
****************************************************************************************************/
@isTest
public class WB_CrearData_cls {
    /** Method getCliente*/
    public static Account getCliente( String sNombre, String sApellido ) {
        final Account oCliente = new Account();
        oCliente.Firstname = sNombre;
        oCliente.Lastname = sApellido;
        oCliente.Correo_Electronico__c = 'prueba@test.com';
        oCliente.PersonEmail = 'prueba@test.com';
        oCliente.Phone = '3224446655';
        oCliente.Genero__c = 'Masculino';
        oCliente.PersonBirthdate = system.today().addYears(-35);
        oCliente.AccountSource = 'Call me back';
        return oCliente;
    }
    /** Method getLead*/
    public static Lead getLead() {
        final Lead oLead = new Lead();
        oLead.Lastname = 'Prueba Lead';
        oLead.Firstname = 'Nombre Lead';
        oLead.status = 'Creado';
        return oLead;
    }
    /** Method getOportunidad*/
    public static Opportunity getOportunidad(Account oCliente ,String sFolio, String sProducto) {
        Decimal decRan = Math.random();
        decRan = Math.round( decRan*1000 );
        final Opportunity oOpp = new Opportunity();
        oOpp.FolioCotizacion__c = sFolio;
        oOpp.AccountId = oCliente.Id;
        oOpp.Name = 'Opp Test' + decRan;
        oOpp.StageName = 'Prospecting';
        oOpp.CloseDate = system.today().addDays(10);
        oOpp.Estatus__c = 'Emitida';
        oOpp.Motivoelegibilidad__c = 'Motivo uso comercial';
        oOpp.Sexo_conductor__c = 'Masculino';
        oOpp.telefonoCelularContratante__c = '3224446655';
        oOpp.correoElectronicoContratante__c = oCliente.PersonEmail;
        oOpp.CorreoCliente__c = oCliente.PersonEmail;
        oOpp.Producto__c = sProducto;
        oOpp.CargaInicial__c = true;
        oOpp.NumerodePoliza__c = '1234567890';
        oOpp.TipoPersonaCliente__c = 'MORAL';
        return oOpp;
    }
    /** Method*/
    public static TemporalCasosPolizas__c getTemporalCasosPolizas(String sIdCase) {

        final TemporalCasosPolizas__c oTempCasosPoli = new TemporalCasosPolizas__c();
        oTempCasosPoli.Caso__c = sIdCase;
        oTempCasosPoli.NoPoliza__c = '1234567890';
        oTempCasosPoli.Name = '1234567890';

        return oTempCasosPoli;
    }
    /** */
    public static case getCase(Id OpportunityId) {
        final Case oCase = new Case();
        oCase.Subject = 'Prueba CASE';
        oCase.status = 'Abierto';
        oCase.Priority = 'Media';
        oCase.Poliza__c = OpportunityId;
        
  
        return oCase;
    
        
    }

}