src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MX_WB_ph_Telefono1__c</fullName>
        <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
        <label>Teléfono 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MX_WB_ph_Telefono2__c</fullName>
        <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
        <label>Telefono 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MX_WB_ph_Telefono3__c</fullName>
        <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
        <label>Telefono 3</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>Folio_Cotizacion__c</fullName>
    <label>Folio Cotización</label>
    <length>10</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>EnviarCTI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EnviarCTI</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_ContadorRemarcado__c</fullName>
    <label>Contador remarcado</label>
    <length>50</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>MX_WB_lst_EstatusBloqueado__c</fullName>
    <description>Nuevo campo Estatus Bloqueado de Tele marketing</description>
    <label>Estatus Bloqueado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estatusdecotizacion__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bloqueo 1 año</fullName>
            </value>
            <value>
                <fullName>Bloqueo definitivo</fullName>
            </value>
            <value>
                <fullName>Bloqueo posibilidad de regreso</fullName>
            </value>
            <value>
                <fullName>No Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono1__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 1</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono2__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 2</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono3__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 3</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_Convertido__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar si el Lead ha sido convertido o no.</description>
    <label>Convertido</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_TM_Congelado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo sirve para no enviar el prospecto a CTI cuando tenga el valor activo</description>
    <label>Congelado</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_ContadorRemarcado__c</fullName>
    <label>Contador remarcado</label>
    <length>50</length>
    <type>Text</type>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>MX_WB_rt_Telemarketing</fullName>
    <active>true</active>
    <businessProcess>MX_WB_PC_Telemarketing</businessProcess>
    <label>Outbound</label>
</recordTypes>
</CustomObject>

src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caso_Relacionado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso Relacionado</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnviarCTI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Se hace validación, si fue verdadera envia a closed de CTI para dar atención.</description>
        <label>Enviar a CTI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_WB_ContadorRemarcado__c</fullName>
        <description>Contador de remarcados</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Contador de llamadas.</inlineHelpText>
        <label>Contador remarcado</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_OppCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Oportunidades (Caso)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_EnvioCTICupon__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo para cotización.</description>
        <label>EnvioCTICupon</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_WB_lst_EstatusBloqueado__c</fullName>
        <description>Nuevo campo Estatus Bloqueado de Tele marketing</description>
        <label>Estatus Bloqueado</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_WB_estatusCotizacion__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bloqueo 1 año</fullName>
                </value>
                <value>
                    <fullName>Bloqueo definitivo</fullName>
                </value>
                <value>
                    <fullName>Bloqueo posibilidad de regreso</fullName>
                </value>
                <value>
                    <fullName>No Bloqueado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Información para la cotización.</description>
        <label>Motivo de la Oportunidad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Venta Pre emisión</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <description>Telefono contratante.</description>
        <formula>Account.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Teléfono celular Contratante</label>
        <type>Text</type>
    </fields>

	<recordTypes>
        <fullName>MX_WB_RT_Telemarketing</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>Outbound</label>

    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProcNotiOppNoAten__c.object
<CustomObject>
    <description>Objeto que se usa para habilitar un trigger que levante los procesos cada 15 minutos.</description>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Horario__c</fullName>
        <label>Horario</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Matutino</fullName>
                </value>
                <value>
                    <fullName>Vespertino</fullName>
                </value>
                <value>
                    <fullName>A los</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minutos__c</fullName>
        <label>Minutos</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>55</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proceso__c</fullName>
        <label>Proceso</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ProcNotiOppNoAten</label>
    <nameField>
        <displayFormat>PNOA-{00000}</displayFormat>
        <label>Nombre de ProcNotiOppNoAten</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProcNotiOppNoAten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_Familia_Productos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación a familia de producto.</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Presupuestos</relationshipLabel>
        <relationshipName>Presupuestos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Folio_Cotizacion__c</fullName>
        <description>Folio de la póliza.</description>
        <label>Folio Cotizacion</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Movil_txt__c</fullName>
        <description>Número de teléfono en texto para búsqueda</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Movil</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WB_ProcNotif_cls.cls
/**-------------------------------------------------------------------------
* Nombre: WB_ProcNotif_cls
* @author Karen Sanchez (KB)
* Proyecto: MW WB Tlmkt - BBVA Bancomer
* Descripción : Clase que activa los procesos de tiempo para el envio de CTI tanto del objeto Lead como el de la Oportunidad

* --------------------------------------------------------------------------
*                         Fecha           Autor                   Desripción
* -------------------------------------------------------------------
* @version 2.0           28/01/2019      Karen Sanchez            Actualización
* @version 2.1           28/06/2019      Julio/jaime/Arsenio      Modificacion y aislamiento de fecha creacion
* @version 2.1.1         04/07/2019      Eduardo Hernández        Filtro para envios de productos Hogar y vida en VCIP
* @version 2.1.2         19/07/2019      Eduardo Hernández        Filtro para folios vacios
* --------------------------------------------------------------------------*/



public with sharing class WB_ProcNotif_cls {

    /*
    *Método: Se ejecuta cuando se actualiza un registro del objeto ProcNotiOppNoAten__c para ejecutar 3 batch dependiendo del proceso
    *28-01-2019
    *Karen Belem Sanchez Ruiz*/
    public static void agendarProcesoNotif(List<ProcNotiOppNoAten__c>lsNotif, Map<Id,ProcNotiOppNoAten__c>mapOldNotif) {

        for (ProcNotiOppNoAten__c procNoti : lsNotif) {

            final OppUpdEnvEmailSch_cls objOppUpdEnvEmailSch = new OppUpdEnvEmailSch_cls();
            objOppUpdEnvEmailSch.isCupon = false;
            final String sHorario = procNoti.Minutos__c;
            String sEstatusProcess = '';
            String sch = '';
            String sQuery = '';
            final String leadSource = 'Outbound TLMK';
            final Integer contadorRemarcado = 5;
            final String noBloqueado = 'No bloqueado';
            final Integer sCantidadEnvio = Integer.valueOf(label.MX_WB_CantidadEnvioCTI);
	        final String sTypeRecord = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('MX_WB_rt_Telemarketing').getRecordTypeId();
            sQuery = 'Select Opportunity.Id, Opportunity.AccountId, Status, Opportunity.EnviarCTI__c, Opportunity.LastModifiedDate, ';
            sQuery += ' MX_SB_VTS_Folio_Cotizacion__c, Opportunity.OwnerId,Opportunity.Producto__c, Opportunity.Account.PersonEmail, MX_SB_VTS_Movil_txt__c From Quote ';
            sQuery += ' Where Opportunity.EnviarCTI__c = false ';
            sQuery += ' And Opportunity.LeadSource = \'Tracking Web\'';
            sQuery += ' And Opportunity.AccountId != null';
	        sQuery += ' And MX_SB_VTS_Folio_Cotizacion__c != null';
            sQuery += ' And Opportunity.Reason__c != \'' + System.Label.SAN163_WSOppotunityBlackListValues + '\'';
            sQuery += ' And Opportunity.StageName != \'' + System.Label.SAN163_WSOppotunityBlackListStageName + '\'';
            sQuery += ' And CreatedDate >= ' + System.label.MX_SB_VTS_SCHEDULE_DATE_LBL;
            sQuery += ' And Opportunity.Caso_Relacionado__c = null';
            sQuery += ' And Opportunity.MX_SB_VTS_OppCase__c = null';
            sQuery += ' And MX_SB_VTS_Familia_Productos__r.Name = \'' + System.label.MX_SB_VTS_FamiliaASD + '\'';
            if (procNoti.Activo__c && !mapOldNotif.get(procNoti.id).Activo__c && String.isBlank(procNoti.Proceso__c)) {

                sEstatusProcess = 'Creada-Formalizada-Tarificada';
                sch = '';
                sch = '0 ' + procNoti.Minutos__c + ' 0-23 1-31 1-12 ?';
                sQuery += ' And Opportunity.MX_WB_EnvioCTICupon__c = false ';

                objOppUpdEnvEmailSch.sQuery = sQuery;
                objOppUpdEnvEmailSch.sMinuto = sHorario;

                final String sNombreProc = procNoti.Horario__c + ' : ' + procNoti.Minutos__c + ' estatus : ' + sEstatusProcess;
                System.schedule(sNombreProc, sch, objOppUpdEnvEmailSch);
            } else {
                final String campaingMembers = sQueryOutboundMiembros();
                sch = '0 ' + procNoti.Minutos__c + ' 0-23 1-31 1-12 ?';
                String sNombreProc = procNoti.Horario__c + ' : ' + procNoti.Minutos__c + ' : ' + procNoti.Proceso__c;
                switch on (procNoti.Proceso__c) {
                    when 'Outbound'{
                        sQuery = 'SELECT l.Id,l.Folio_Cotizacion__c,l.OwnerId,l.FirstName,l.MX_WB_ph_Telefono1__c,l.MX_WB_ph_Telefono2__c,l.MX_WB_ph_Telefono3__c,l.MX_WB_ContadorRemarcado__c, l.EnviarCTI__c,CreatedDate';
                        sQuery += ', l.LeadSource, l.RecordTypeId, l.MX_WB_TM_Congelado__c,(SELECT Id, Motivos_CONTACTO__c, Telefono__c from Tasks) From Lead l WHERE MX_WB_Convertido__c = false AND MX_WB_TM_Congelado__c = false AND RecordTypeId =\'' + sTypeRecord + '\''+' AND LeadSource =\''+leadSource + '\''+'AND MX_WB_lst_EstatusBloqueado__c !=  \''+ noBloqueado+ '\''+' AND MX_WB_ContadorRemarcado__c <= \''+ contadorRemarcado + '\''+'AND Id in'+campaingMembers+'limit '+sCantidadEnvio;
                        final MX_WB_EnvioLeadsCTI_shc objEnvioLeadsShc = new MX_WB_EnvioLeadsCTI_shc();
                        objEnvioLeadsShc.sQuery = sQuery;
                        System.schedule(sNombreProc, sch, objEnvioLeadsShc);
                    }
                    when 'Cupon' {
                        sEstatusProcess = 'Cupon';
                        sch = '';
                        sch = '0 0 11 1-31 1-12 ?';
                        sQuery += ' And Opportunity.MX_WB_EnvioCTICupon__c = true';
                        sQuery += ' And Opportunity.CreatedDate >= YESTERDAY ';
                        sQuery += ' And Status != \'Emitida\'';

                        objOppUpdEnvEmailSch.sQuery = sQuery;
                        objOppUpdEnvEmailSch.isCupon = true;

                        sNombreProc = procNoti.Horario__c + ' : 11:00 AM : ' + sEstatusProcess;

                        System.schedule(sNombreProc, sch, objOppUpdEnvEmailSch);
                    }
                }
            }
        }
    }

    /*
    *Método: Regresa los miembros de la campaña activa para mandar a CTI
    *28-01-2019
    *Karen Belem Sanchez Ruiz*/
    public static String sQueryOutboundMiembros() {
        String campaingMembers = '(';
                for(CampaignMember miembro: [Select LeadId From CampaignMember Where Campaign.isActive=true]) {
                    campaingMembers += '\''+miembro.LeadId+'\',';
                }
                campaingMembers = campaingMembers.removeEnd(',');
                campaingMembers += ')';

        return campaingMembers;

    }
}