src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Correo_Electronico__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Campo utilizado como external ID</description>
        <externalId>true</externalId>
        <label>Correo Electrónico</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CorreodelCliente__c</fullName>
        <description>Correo del Contratante.</description>
        <formula>Account.Correo_Electronico__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Correo del Contratante</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FolioCotizacion__c</fullName>
        <description>Folio para dar seguimiento a la cotización.</description>
        <externalId>true</externalId>
        <label>Folio Cotizacion</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo de relación hacia producto para asociar la oportunidad a un producto específico.</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cotizaciones</relationshipLabel>
        <relationshipName>Cotizaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sexo_conductor__c</fullName>
        <description>Sexo del conductor para evaluación del cliente.</description>
        <label>Sexo conductor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Masculíno</fullName>
                </value>
                <value>
                    <fullName>Femenino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <description>Telefono contratante.</description>
        <formula>Account.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Teléfono celular Contratante</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TelefonoCliente__c</fullName>
        <label>Teléfono Asegurado</label>
        <type>Phone</type>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
	<recordTypes>
        <fullName>MX_WB_RT_Telemarketing</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>Outbound</label>

    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Products (Familia de productos)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_WB_OppoLineItemUtil_tst.cls
/**-------------------------------------------------------------------------
 * Nombre: MX_WB_OppoLineItemUtil_tst
 * Autor Ing. Daniel Goncalves
 * Proyecto: MW WB TM - BBVA Bancomer
 * Descripción : Clase Test de MX_WB_OppoLineItemUtil_cls
 * --------------------------------------------------------------------------
 * Versión      Fecha           Autor                   Descripción
 * -------------------------------------------------------------------
 * 1.0          11/02/2019      Ing. Daniel Goncalves   Creación
 * --------------------------------------------------------------------------
 */
@isTest
public class MX_WB_OppoLineItemUtil_tst {
    /**
    * Setup the data for the tests
    * @return List String
    **/
    @testSetup static void setup() {
        final User testUser = MX_WB_TestData_cls.crearUsuario ( 'TestLastName', 'System Administrator' );
        insert testUser;
        final Account accRec = MX_WB_TestData_cls.crearCuenta ( 'LastName', 'MX_WB_rt_PAcc_Telemarketing' );
        accRec.OwnerId = testUser.Id;
        accRec.Correo_Electronico__c = 'prueba@wibe.com';
        insert accRec;
        final Opportunity oppRec = MX_WB_TestData_cls.crearOportunidad ( 'Test', accRec.Id, testUser.Id, 'MX_WB_RT_Telemarketing' );
        oppRec.FolioCotizacion__c = null;
        oppRec.TelefonoCliente__c = '1234567890';
        insert oppRec;
        final MX_WB_FamiliaProducto__c objFamilyPro = MX_WB_TestData_cls.createProductsFamily ( 'ASD' );
        insert objFamilyPro;
        final Product2 proTst = MX_WB_TestData_cls.productNew ( 'Seguro de Moto Bancomer' );
        proTst.IsActive = true;
        proTst.MX_WB_FamiliaProductos__c = objFamilyPro.Id;
        insert proTst;
        MX_WB_TestData_cls.createStandardPriceBook2 ();
    }
    /**
    * Prueba para crear un PricebookEntry
    **/
    @isTest static void crearPricebookEntrytst () {
        final String strProId = [ SELECT ID FROM Product2 WHERE Name =: 'Seguro de Moto Bancomer' ].Id;
        Test.startTest();
        final PricebookEntry objPriBoEnt = MX_WB_OppoLineItemUtil_cls.crearPricebookEntry ( strProId, 0.00 );
        System.assertEquals ( strProId, objPriBoEnt.Product2Id, ' Test Creación PricebookEntry Caso Éxito ' );
        Test.stopTest();
    }
    /**
    * Prueba que crea un PricebookEntry Caso Existe el Pricebook
    **/
    @isTest static void crearPricebookEntryHasPriBootst () {
        final String strProId = [ SELECT ID FROM Product2 WHERE Name =: 'Seguro de Moto Bancomer' ].Id;
        PricebookEntry objPriceBookEntry;
        for ( Pricebook2 objPriBoo : [ SELECT ID FROM Pricebook2 WHERE isStandard = true LIMIT 1 ]) {
            objPriceBookEntry = new PricebookEntry();
            objPriceBookEntry.Pricebook2Id = objPriBoo.Id;
            objPriceBookEntry.Product2Id = strProId;
            objPriceBookEntry.IsActive = true;
            objPriceBookEntry.UnitPrice = 0;
        }
        insert objPriceBookEntry;
        Test.startTest();
        final PricebookEntry objPriBoEnt = MX_WB_OppoLineItemUtil_cls.crearPricebookEntry ( strProId, 0.00 );
        System.assertEquals ( strProId, objPriBoEnt.Product2Id, ' Test Creación PricebookEntry Caso Éxito ' );
        Test.stopTest();
    }
    /**
    * Prueba que crea un OpportunityLineItem
    **/
    @isTest static void crearOpportunityLineItemtst () {
        final Opportunity objOpp = [ SELECT ID, Name, CorreodelCliente__c, TelefonoCliente__c, Description, MX_WB_Producto__c, Sexo_conductor__c, Telefono__c FROM Opportunity LIMIT 1 ];
        final PricebookEntry objPriBoEnt = new PricebookEntry();
        Test.startTest();
        final OpportunityLineItem objOppLinIteTst = MX_WB_OppoLineItemUtil_cls.crearOpportunityLineItem ( objOpp, objPriBoEnt );
        System.assertEquals ( objOpp.ID, objOppLinIteTst.OpportunityId, ' Test Creación OpportunityLineItem Caso Éxito ' );
        Test.stopTest();
    }
}