src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ApellidoMaterno__c</fullName>
        <description>Apellido Materno del Cliente</description>
        <label>Apellido Materno</label>
        <length>150</length>
        <type>Text</type>
    </fields>
	<fields> 
        <fullName>MX_SB_SAC_Homoclave__c</fullName>
        <description>Homoclave de Contratante en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Homoclave</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Colonia__c</fullName>
        <description>Colonia domicilio de cliente</description>
        <label>Colonia</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delegacion__c</fullName>
        <description>Delegación del domicilio de cliente.</description>
        <label>Población</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genero__c</fullName>
        <description>Género del cliente.</description>
        <label>Género</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Masculino</fullName>
                </value>
                <value>
                    <fullName>Femenino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nacionalidad__c</fullName>
        <description>Nacionalidad de Cliente.</description>
        <label>Nacionalidad</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profesion__c</fullName>
        <description>Profesión del cliente.</description>
        <label>Profesión</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC de cliente.</description>
        <label>RFC</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_Oficina__c</fullName>
        <description>Teléfono de oficina de cliente.</description>
        <label>Teléfono de Oficina</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Tipo_Persona__c</fullName>
        <description>Persona Física o Moral</description>
        <label>Tipo de Persona</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Física</fullName>
                    <default>true</default>
                    <label>Física</label>
                </value>
                <value>
                    <fullName>Moral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject >
	<fields>
        <fullName>MX_SB_SAC_FechaFinContrato__c</fullName>
        <description>Campo para almacernar campo de Clipert: fechaFinVigencia.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Fin de Vigencia</label>
        <type>DateTime</type>
    </fields>
	 <fields>
        <fullName>MX_SB_SAC_FormaPago__c</fullName>
        <description>Datos de Pago: FormaPago de Clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Forma de Pago</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_FechaVenta__c</fullName>
        <description>Datos Póliza: Fecha Venta en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de Venta</label>
        <type>DateTime</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Anio__c</fullName>
        <description>Datos vehículo: Año en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Año</label>
        <length>4</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Agencia__c</fullName>
        <description>Datos Vehículo: Agencia en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Agencia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_TipoPago__c</fullName>
        <description>Datos de pago: Tipo de Pago de Clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Tipo de Pago</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_NoCuenta__c</fullName>
        <description>Datos Póliza: Número de Cuenta en Clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Número de Cuenta</label>
        <length>16</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_NumeroFolio__c</fullName>
        <description>Datos Póliza: Número de Folio en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Número de Folio</label>
        <length>10</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Operador__c</fullName>
        <description>Datos Póliza: Operador en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Operador</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Plan__c</fullName>
        <description>Datos Póliza: Plan en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Promocion__c</fullName>
        <description>Datos de Pago: Promoción de Clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Promoción</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Renovacion__c</fullName>
        <description>Datos Póliza: Renovación de Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Renovación</label>
        <length>4</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Servicio__c</fullName>
        <description>Datos Vehículo: Servicio en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Servicio</label>
        <length>30</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_SolicitudFactura__c</fullName>
        <description>Datos de Pago: Solicitud de Factura en Clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Solicitud de Factura</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Subcanal__c</fullName>
        <description>Datos Póliza: Subcanal en Clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Subcanal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Subproducto__c</fullName>
        <description>Datos Póliza: SUbproducto en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Subproducto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Version__c</fullName>
        <description>Datos vehículo: Version en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Versión</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_ZonaCirculacion__c</fullName>
        <description>Datos Póliza: ZonaCirculación de Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Zona de Circulación</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nombre_Intermediario__c</fullName>
        <description>Intermediario de póliza de auto.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre intermediario</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Precio_Anual__c</fullName>
        <description>Precio total a pagar al año.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Precio Anual</label>
        <length>20</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Agencia__c</fullName>
        <description>Datos Vehículo: Agencia en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Agencia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Anio__c</fullName>
        <description>Datos vehículo: Año en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Año</label>
        <length>4</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_BeneficiarioPreferente__c</fullName>
        <description>Datos Póliza: BeneficiarioPreferente en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiario Preferente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Canal__c</fullName>
        <description>Datos Póliza: Canal en Clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Canal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_Capacidad__c</fullName>
        <description>Datos Vehículo: Capacidad en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Capacidad</label>
        <length>2</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_ClaveSB__c</fullName>
        <description>Datos vehículo: Clave SB de Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Clave SB</label>
        <length>10</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_DescuentoFacultado__c</fullName>
        <description>Datos de Pago: Descuento Facultado de Clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Descuento Facultado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_EstatusPoliza__c</fullName>
        <description>Datos póliza: EstatusPoliza en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Estatus de Poliza</label>
        <length>30</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MX_SB_SAC_FechaAltaPoliza__c</fullName>
        <description>Datos Póliza: FechaAltaPoliza en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Alta de Poliza</label>
        <type>DateTime</type>
    </fields>
	
    <fields>
        <fullName>MX_WB_Marca__c</fullName>
        <description>Marca del vehículo asegurado.</description>
        <label>Marca</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_Sexo__c</fullName>
        <description>Sexo del asegurado</description>
        <label>Sexo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WB_Tipo_de_auto__c</fullName>
        <description>Tipo de auto asegurado</description>
        <label>Tipo de auto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>SUV</fullName>
                </value>
                <value>
                    <fullName>Pick Up</fullName>
                </value>
                <value>
                    <fullName>Camion (+3.5 Toneladas)</fullName>
                </value>
                <value>
                    <fullName>Moto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WB_apellidoMaternoAsegurado__c</fullName>
        <description>Apellido materno del asegurado</description>
        <label>Apellido materno del asegurado</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_apellidoPaternoAsegurado__c</fullName>
        <description>Apellido paterno del asegurado</description>
        <label>Apellido paterno del asegurado</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_celularAsegurado__c</fullName>
        <label>Celular Asegurado</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_WB_emailAsegurado__c</fullName>
        <description>Email del asegurado</description>
        <label>Email del asegurado</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_noPoliza__c</fullName>
        <description>Se almacena el número de póliza generado en la venta.</description>
        <inlineHelpText>Número de póliza emitida</inlineHelpText>
        <label>Número de Póliza</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_nombreAsegurado__c</fullName>
        <description>Nombre del asegurado</description>
        <label>Nombre del asegurado</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_numeroSerie__c</fullName>
        <description>Número de serie del vehículo asegurado</description>
        <label>Número de serie</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_placas__c</fullName>
        <description>Placas del vehículo asegurado</description>
        <label>Placas</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_subMarca__c</fullName>
        <description>Sub marca del vehículo asegurado</description>
        <label>Sub marca</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_telefonoAsegurado__c</fullName>
        <label>Teléfono Asegurado</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación a producto.</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contratos</relationshipLabel>
        <relationshipName>Contratos_Producto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_noMotor__c</fullName>
        <description>Indica el número de motor del vehículo asegurado.</description>
        <label>Número de motor</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_Beneficiario__c.object
<CustomObject>
    <fields>
        <fullName>MX_SB_SAC_Homoclave__c</fullName>
        <description>Homoclave de Beneficiario en Cliper.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Homoclave</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Beneficiario</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Beneficiario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_SB_SAC_Poliza_Cls.cls
/**
* @File Name          : MX_SB_SAC_Poliza_Cls.cls
* @Description        :
* @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
* @Group              :
* @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
* @Last Modified On   : 19/8/2019 17:43:14
* @Modification Log   :
*==============================================================================
* Ver         Date                     Author               Modification
*==============================================================================
* 1.0    19/8/2019 13:55:56   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
* 2.0    29/08/2019           José Luis Vargas Lara           Se reestructura la clase y se hacen ajustes marcados por sonnar
*                                                             Se agrega guardado de asegurado y conductor
* 3.0    26/09/2019           Michelle Valderrama Yapor       Se agregan tods los campos de Clipert a campos en Salesforce.
**/
public with sharing class MX_SB_SAC_Poliza_Cls {//NOSONAR

  /**
  * @description Constante con el genero masculino
  * @author José Luis Vargas Lara
  */
  public static final string MASCULINO = 'MASCULINO';
 /**
  * @description Constante con el tipo de persona
  * @author José Luis Vargas Lara
  */
  public static final string MORAL = 'MORAL';
 /**
  * @description Constante con el nombre de asegurado
  * @author José Luis Vargas Lara
  */
  public static final string ASEGURADO = 'nombreAsegurado';
  /**
  * @description Clase usada para el response de la consulta de poliza
  * @author José Luis Vargas Lara
  */
  public class RespRestGetPolizaPorNumeroDePoliza {
    /**
    * @description String nombreMetod
    * @author José Luis Vargas Lara
    */
    public String nombreMetodo {get; set;}
    /**
    * @description String error
    * @author José Luis Vargas Lara
    */
    public Boolean error {get; set;}
    /**
    * @description String detalle
    * @author José Luis Vargas Lara
    */
    public String detalle {get; Set;}
    /**
    * @description String json
    * @author José Luis Vargas Lara
    */
    public String jsonRes {get; set;}
  }
  /**
  * @description: Realiza la consulta de una poliza en Clipert
  * @author José Luis Vargas Lara
  * @param String jsonParams, parametros de busqueda
  * @param String sUrl, url del servicio Clippert
  * @param String sToken, Token generado para autorizacion de consulta
  * @param String sMetAction, Tipo de consulta a realizar
  * @return RespRestGetPolizaPorNumeroDePoliza con el resutado del proceso de consulta
  */
  public static RespRestGetPolizaPorNumeroDePoliza getPoliza(String jsonParams, String sUrl, String sToken, String sMetAction) {//NOSONAR
    final RespRestGetPolizaPorNumeroDePoliza objRespRestLoc = new RespRestGetPolizaPorNumeroDePoliza();
    String jsonBody = '';
    try {
      jsonBody = jsonParams;
      final String endpoint = sUrl + '' + sMetAction;
      HttpRequest request = new HttpRequest();
      request.setEndpoint(endpoint);
      request.setMethod('POST');
      request.setHeader('Accept', 'application/json, text/plain, */*');
      request.setHeader('Content-Type', 'application/json;charset=UTF-8');
      request.setTimeout(120000);
      request.setBody(jsonBody);
      request.setHeader('acces-token', sToken);
      final HTTPResponse res = new Http().send(request);
      final String sJasonRes = res.getBody();
      objRespRestLoc.nombreMetodo = sMetAction;
      objRespRestLoc.detalle = sJasonRes;
      objRespRestLoc.jsonRes = sJasonRes;
      objRespRestLoc.error = String.valueOf(res).contains('200') ? false :  true;
    } catch(Exception ex) {
      objRespRestLoc.Error = true;
      objRespRestLoc.Detalle = ex.getMessage();
    }
    return objRespRestLoc;
  }
  /**
  * @description: Crea la informacion del contrato y poliza en salesforce
  * @author José Luis Vargas Lara
  * @param String objPolizaDto, Objeto PolizaDto con el detalle de la poliza obtenido en clipert
  * @param String numeroPoliza, Numero de poliza consultado
  * @return Map<string, object> con el resutado del proceso
  */
  public static Map<String, Object> getPolizasSFDC(string objPolizaDto, string numeroPoliza) {
    Map<String, Object> processResp = new Map<String, Object>();
    final Map<String, Object> mapJson = (Map<String, Object>) JSON.deserializeUntyped(objPolizaDto);
    final String emailContrato =  MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('correoElectronicoContratante'));
    if (String.isNotBlank(emailContrato)) {
      final List<Account> oAccountPoliza = [SELECT Id, Name, PersonEmail FROM Account WHERE PersonEmail =: emailContrato];
      final String tipoPersona = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('tipoPersonaContratante'));
      Account cteUpsNvo = new Account();
      cteUpsNvo.Genero__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('generoContratante'));
      if(oAccountPoliza != null && !oAccountPoliza.isEmpty()) {
        cteUpsNvo.Id = oAccountPoliza[0].Id;
      }
      if(tipoPersona.equalsIgnoreCase(MORAL)) {
        cteUpsNvo.Name = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('nombreContratante'));
        cteUpsNvo.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Empresarial').getRecordTypeId();
      } else {
        cteUpsNvo.FirstName = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('nombreContratante'));
        cteUpsNvo.LastName = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('apellidoPaternoContratante'));
        cteUpsNvo.ApellidoMaterno__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('apellidoMaternoContratante'));
        cteUpsNvo.PersonBirthdate = MX_SB_SAC_Utils_Cls.fechaDDMMYYYYTOYYYYMMDD((String)mapJson.get('fechaNacimientoContratante'));
        cteUpsNvo.PersonHomePhone = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('telefonoCasaContratante'));
      }
      cteUpsNvo.Profesion__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('profesionAsegurado'));
      cteUpsNvo.Nacionalidad__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('nacionalidadContratante'));
      cteUpsNvo.Telefono_Oficina__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('telefonoOficinaContratante'));
      cteUpsNvo.Phone = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('telefonoCelularContratante'));
      cteUpsNvo.PersonEmail = emailContrato;
      cteUpsNvo.RFC__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('rfcContratante'));
      cteUpsNvo.Tipo_Persona__c = tipoPersona;
      cteUpsNvo.BillingStreet = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('direccionContratante'));
      cteUpsNvo.Colonia__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('coloniaContratante'));
      cteUpsNvo.Delegacion__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('poblacionContratante'));
      cteUpsNvo.BillingState = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('estadoContratante'));
      cteUpsNvo.BillingPostalCode = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('cpContratante'));
      cteUpsNvo.MX_SB_SAC_Homoclave__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('homoclaveContratante'));
      upsert cteUpsNvo;
      processResp = arrContract(cteUpsNvo, mapJson, numeroPoliza);
    }
    return processResp;
  }

  /**
  * @description: Crea la informacion del contrato en salesforce
  * @author José Luis Vargas Lara
  * @param Account cuentaContrato, Cuenta asociada al  contrato
  * @param Map<String, Object> mapJson, Mapa con el detalle de la poliza
  * @param string numeroPoliza, Numero de poliza
  * @return Map<string, object> con el resutado del proceso
  */
  public static Map<String, Object> arrContract(Account cuentaContrato, Map<String, Object> mapJson, string numeroPoliza) {
    final Map<String, Object> arrAccCont = new Map<String, Object>();
    string generoContratante = '';
    final List<Contract> contExt = [SELECT Id, Name, MX_WB_noPoliza__c FROM Contract WHERE MX_WB_noPoliza__c =: numeroPoliza];
    Contract contratoNew = new Contract();
    contratoNew.MX_WB_nombreAsegurado__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get(ASEGURADO));
    if(contExt != null && !contExt.isEmpty()) {
      contratoNew.Id=contExt[0].Id;
    }
    generoContratante = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('generoAsegurado'));
    if(generoContratante.toUpperCase() == MASCULINO) {
      generoContratante = 'H';
    } else {
      generoContratante = 'M';
    }
    contratoNew.MX_WB_nombreAsegurado__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get(ASEGURADO));
    contratoNew.MX_WB_apellidoMaternoAsegurado__c =MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('apellidoMaternoAsegurado'));
    contratoNew.MX_WB_apellidoPaternoAsegurado__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('apellidoPaternoAsegurado'));
    contratoNew.MX_WB_Sexo__c = generoContratante;
    contratoNew.MX_WB_emailAsegurado__c = cuentaContrato.PersonEmail;
    contratoNew.MX_WB_celularAsegurado__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('telefonoCelularAsegurado'));
    contratoNew.MX_WB_telefonoAsegurado__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('telefonoCelularAsegurado'));
    contratoNew.AccountId = cuentaContrato.Id;
    contratoNew.MX_WB_noPoliza__c = numeroPoliza;
    contratoNew.StartDate = MX_SB_SAC_Utils_Cls.fechaYYYYMMDDHHMMSS(MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('fechaInicioVigencia')));
    final Product2 prod = MX_SB_SAC_Business_Cls.getProductSAC(MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('producto')));
    if(prod != null) {
      contratoNew.MX_WB_Producto__c = prod.Id;
    }
    camposContrato(contratoNew,mapJson);
    upsert contratoNew;
    GuardarAsegurado(mapJson, contratoNew.Id);
    GuardarConductor(mapJson, contratoNew.Id);
    arrAccCont.put('status','OK');
    arrAccCont.put('msjResponse','Póliza creada y/o actualizada correctamente');
    arrAccCont.put('arrAcctCont',contratoNew);
    return arrAccCont;
  }
  /**
  * @description: Crea la informacion del contrato parte 2 en salesforce (modificación para Sonar)
  * @author Michelle Valderrama Yapor
  * @param Contract contratoNew, contrato a actualizar
  * @param Map<String, Object> mapJson, Mapa con el detalle de la poliza
  */
  public static void camposContrato(Contract contratoNew, Map<String, Object> mapJson) {
    contratoNew.status = 'Draft';
    contratoNew.MX_WB_numeroSerie__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('numeroSerie'));
    contratoNew.MX_WB_noMotor__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('numeroMotor'));
    contratoNew.MX_WB_placas__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('placas'));
    contratoNew.MX_WB_subMarca__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('submarca'));
    contratoNew.MX_WB_Marca__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('marca'));
    contratoNew.MX_WB_Tipo_de_auto__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('tipoVehiculo'));
    contratoNew.MX_SB_SAC_ClaveSB__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('clavesb'));
    contratoNew.MX_SB_SAC_Anio__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('anio'));
    contratoNew.MX_SB_SAC_Version__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('version'));
    contratoNew.MX_SB_MLT_DescripcionVehiculo__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('descripcion'));
    contratoNew.MX_SB_SAC_Servicio__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('servicio'));
    contratoNew.MX_SB_SAC_Agencia__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('agencia'));
    contratoNew.MX_SB_SAC_Capacidad__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('capacidad'));
    contratoNew.MX_SB_SAC_FechaVenta__c = MX_SB_SAC_Utils_Cls.fechaYYYYMMDDHHMMSS(MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('fechaVenta')));
    contratoNew.MX_SB_SAC_FechaAltaPoliza__c = MX_SB_SAC_Utils_Cls.fechaYYYYMMDDHHMMSS(MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('fechaAltaPoliza')));
    contratoNew.MX_SB_SAC_Plan__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('plan'));
    contratoNew.MX_SB_SAC_EstatusPoliza__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('estatusPoliza'));
    contratoNew.MX_SB_SAC_NumeroFolio__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('noFolio'));
    contratoNew.MX_SB_VTS_Nombre_Intermediario__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('intermediario'));
    contratoNew.MX_SB_SAC_Subproducto__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('subProducto'));
    contratoNew.MX_SB_SAC_Renovacion__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('renovacion'));
    contratoNew.MX_SB_SAC_BeneficiarioPreferente__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('beneficiarioPreferente'));
    contratoNew.MX_SB_SAC_ZonaCirculacion__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('zonaCirculacion'));
    contratoNew.MX_SB_SAC_Operador__c =MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('operador'));
    contratoNew.MX_SB_SAC_Canal__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('canal'));
    contratoNew.MX_SB_SAC_Subcanal__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('subcanal'));
    contratoNew.MX_SB_SAC_NoCuenta__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('numeroCuenta'));
    contratoNew.MX_SB_SAC_SolicitudFactura__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('solicitudFactura'));
    contratoNew.MX_SB_SAC_TipoPago__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('tipoPago'));
    contratoNew.MX_SB_SAC_Promocion__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('promocion'));
    contratoNew.MX_SB_SAC_DescuentoFacultado__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('descuentoFacultado'));
    contratoNew.MX_SB_SAC_FormaPago__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('formaPago'));
    contratoNew.MX_SB_VTS_Precio_Anual__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('importe'));
    contratoNew.MX_SB_SAC_FechaFinContrato__c = MX_SB_SAC_Utils_Cls.fechaYYYYMMDDHHMMSS(MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('fechaFinVigencia')));
  }
  /**
  * @description: Guarda el asegurado de la poliza
  * @author José Luis Vargas Lara
  * @param Map<String, Object> mapJson, Mapa con la informacion de la poliza
  * @param Id contractId, Id de contrato
  * @return Void
  */
  public static void guardarAsegurado(Map<String, Object> mapJson, Id contractId) {
    final Id rTypeAsegurado = MX_SB_VTS_Beneficiario__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('Asegurado').getRecordTypeId();
    final List<MX_SB_VTS_Beneficiario__c> lstAsegurado = [SELECT Id FROM MX_SB_VTS_Beneficiario__c WHERE MX_SB_VTS_Contracts__c =: contractId AND RecordTypeId =: rTypeAsegurado];
    MX_SB_VTS_Beneficiario__c oAseguradoNew = new MX_SB_VTS_Beneficiario__c();
    oAseguradoNew.Name = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get(ASEGURADO));
    if(lstAsegurado != null && !lstAsegurado.isEmpty()) {
      oAseguradoNew.Id = lstAsegurado[0].Id;
    }
    oAseguradoNew.Name = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get(ASEGURADO));
    oAseguradoNew.MX_SB_VTS_APaterno_Beneficiario__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('apellidoPaternoAsegurado'));
    oAseguradoNew.MX_SB_VTS_AMaterno_Beneficiario__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('apellidoMaternoAsegurado'));
    oAseguradoNew.MX_SB_SAC_FechaNacimiento__c = MX_SB_SAC_Utils_Cls.fechaDDMMYYYYTOYYYYMMDD((String)mapJson.get('fechaNacimientoAsegurado'));
    oAseguradoNew.MX_SB_SAC_Genero__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('generoAsegurado'));
    oAseguradoNew.MX_SB_SAC_Profesion__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('profesionAsegurado'));
    oAseguradoNew.MX_SB_SAC_Nacionalidad__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('nacionalidadAsegurado'));
    oAseguradoNew.MX_SB_SAC_TelefonoOficina__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('telefonoOficinaAsegurado'));
    oAseguradoNew.MX_SB_SAC_TelefonoCelular__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('telefonoCelularAsegurado'));
    oAseguradoNew.MX_SB_SAC_Email__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('correoElectronicoAsegurado'));
    oAseguradoNew.MX_SB_SAC_RFC__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('rfcAsegurado'));
    oAseguradoNew.MX_SB_SAC_Direccion__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('direccionAsegurado'));
    oAseguradoNew.MX_SB_SAC_Colonia__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('coloniaAsegurado'));
    oAseguradoNew.MX_SB_SAC_Poblacion__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('poblacionAsegurado'));
    oAseguradoNew.MX_SB_SAC_EstadoRepublica__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('estadoAsegurado'));
    oAseguradoNew.MX_SB_SAC_CodigoPostal__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('cpAsegurado'));
    oAseguradoNew.MX_SB_SAC_Homoclave__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('homoclaveAsegurado'));
    oAseguradoNew.RecordTypeId = rTypeAsegurado;
    oAseguradoNew.MX_SB_VTS_Contracts__c = contractId;
    Upsert oAseguradoNew;
  }
  /**
  * @description: Guarda el conductor de la poliza
  * @author José Luis Vargas Lara
  * @param Map<String, Object> mapJson, Mapa con la informacion de la poliza
  * @param Id contractId, Id de contrato
  * @return Void
  */
  public static void guardarConductor(Map<String, Object> mapJson, Id contractId) {
    Id rTypeConductor;
    List<MX_SB_VTS_Beneficiario__c> lstAsegurado;
    if(string.isNotBlank((String)mapJson.get('nombreConductorAsignado'))) {
      MX_SB_VTS_Beneficiario__c oConductorNew = new MX_SB_VTS_Beneficiario__c();
      oConductorNew.Name = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('nombreConductorAsignado'));
      rTypeConductor = MX_SB_VTS_Beneficiario__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('Conductor').getRecordTypeId();
      lstAsegurado = [SELECT Id FROM MX_SB_VTS_Beneficiario__c WHERE MX_SB_VTS_Contracts__c =: contractId AND RecordTypeId =: rTypeConductor];
      if(lstAsegurado != null && !lstAsegurado.isEmpty()) {
        oConductorNew.Id = lstAsegurado[0].Id;
      }
      oConductorNew.Name = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('nombreConductorAsignado'));
      oConductorNew.MX_SB_VTS_APaterno_Beneficiario__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('apellidoPaternoConductorAsignado'));
      oConductorNew.MX_SB_VTS_AMaterno_Beneficiario__c = MX_SB_SAC_Utils_Cls.validaDatoVacio((String)mapJson.get('apellidoMaternoConductorAsignado'));
      oConductorNew.MX_SB_SAC_FechaNacimiento__c = MX_SB_SAC_Utils_Cls.fechaDDMMYYYYTOYYYYMMDD((String)mapJson.get('fecNacConductorAsignado'));
      oConductorNew.RecordTypeId = rTypeConductor;
      oConductornEW.MX_SB_VTS_Contracts__c = contractId;
      Upsert oConductorNew;
    }
  }
}