src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BPyP_Un_Numero_Promotor__c</fullName>
        <description>Número promotor para BPyP</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Número promotor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Información sector del cliente definido desde el Data Mart</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Registro_Manual__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tipo de Registro Manual</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>BPyP_tre_Cliente</fullName>
        <active>true</active>
        <description>Tipo de registro para clientes de BPyP - Personas morales</description>
        <label>Cliente BPyP - Morales</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_BPP_SectorCodes__mdt.object
<CustomObject>
    <description>Permite guardar los códigos de sector que corresponden a cada tipo de cuenta, por ejemplo, para el tipo de cuenta personal se pueden guardar los códigos de sector F32  y F33.</description>
    <fields>
        <fullName>MX_BPP_SectorAccountType__c</fullName>
        <description>Permite elegir el tipo de cuenta que requiere cada código de sector, por ejemplo, el código de sector F32 corresponde a una cuenta personal, mientras que el código de sector M31 corresponde a una cuenta empresarial.</description>
        <label>Tipo de cuenta para el sector</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cuenta empresarial</fullName>
                    <default>true</default>
                    <label>Cuenta empresarial</label>
                </value>
                <value>
                    <fullName>Cuenta personal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_BPP_SectorCode__c</fullName>
        <description>Código de sector, por ejemplo, F32, M31.</description>
        <label>Código de sector</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Configuración de códigos de sector</label>
    <pluralLabel>Configuraciones de códigos de sector</pluralLabel>
</CustomObject>

src/classes/BPyP_ClienteImportar_cls.cls
/*----------------------------------Desarrollado por INDRA---------------------------------
*Autor:         Ricardo Almanza Angeles
*Proyecto:      Max BBVA PI8
*Descripción:   Manejador para el trigger de BPyP de asignación de Clientes.
*_______________________________________________________________________________________
*Versión    Fecha           Autor                               Descripción
*1.0        02/FEB/2018     Ricardo Almanza Angeles             Creación
*1.1        14/FEB/2018     Ricardo Almanza Angeles             Mejora por parte de salud de la org con mayor uso de mapas
*1.2        27/AGO/2019     Cindy Arianna Hernández Nieto       Se modifica el método updateAccountInfo para incluir el
																tipo de registro MX_BPP_PersonAcc_Client. El tipo de
																registro de la cuenta se elige en base al campo Sector__c.
-----------------------------------------------------------------------------------------*/
public with sharing class BPyP_ClienteImportar_cls {

	@TestVisible
	private BPYP_ClienteImportar_cls() {
	}
	/**Metodo asignaBkm */
	public static void asignaBkm(Map<Id, RecordType> mapRecordTypes,List<Account> newtrigacc) {
		final Map<String, RecordType> mapRecordInverso = new Map<String, RecordType>();
		for(RecordType tmp : mapRecordTypes.values()) {
			mapRecordInverso.put(tmp.DeveloperName, tmp);
		}
		final Set<String> empNum = getEmployees(newtrigacc);
		final Map<String, User> mapUser = getEmployeesByNumber(empNum);
		updateAccountInfo(newtrigacc, mapUser, mapRecordInverso);
	}

	private static Set<String> getEmployees(List<Account> newtrigacc) {
		final Set<String> empNum = new Set<String>();
		for(Account ac: newtrigacc) {
			if(ac.Tipo_de_Registro_Manual__c == 'BPYP_PRE' && String.isNotBlank(ac.BPyP_Un_Numero_Promotor__c)) {
				empNum.add(ac.BPyP_Un_Numero_Promotor__c);
			}
		}
		return empNum;
	}

	private static Map<String, User> getEmployeesByNumber(Set<String> empNum) {
		final Map<String, User> mapUser = new Map<String, User>();
		for(User usr : [Select Id,Name,EmployeeNumber from User where EmployeeNumber in :empNum]) {
			mapUser.put(usr.EmployeeNumber, usr);
		}
		return mapUser;
	}

	private static void updateAccountInfo(List<Account> newtrigacc, Map<String, User> mapUser, Map<String, RecordType> mapRecordInverso) {
		final List<MX_BPP_SectorCodes__mdt> personAccCodes = [SELECT MX_BPP_SectorCode__c FROM MX_BPP_SectorCodes__mdt WHERE MX_BPP_SectorAccountType__c = 'Cuenta personal'];
		final List<String> personAccStrCodes = new List<String>();
		for(MX_BPP_SectorCodes__mdt sectorCode : personAccCodes ) {
			personAccStrCodes.add(sectorCode.MX_BPP_SectorCode__c);
		}
		for(Account acc : newtrigacc) {
			if(mapUser.containsKey(acc.BPyP_Un_Numero_Promotor__c) && acc.Tipo_de_Registro_Manual__c == 'BPYP_PRE') {
				acc.OwnerId = mapUser.get(acc.BPyP_Un_Numero_Promotor__c).Id;
				acc.Tipo_de_Registro_Manual__c= '';
				if(personAccStrCodes.contains(acc.Sector__c)) {
					acc.RecordTypeId = mapRecordInverso.get('MX_BPP_PersonAcc_Client').Id;
				} else {
					acc.RecordTypeId = mapRecordInverso.get('BPyP_tre_Cliente').Id;
				}
			}
		}
	}
}