src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Colonia__c</fullName>
        <description>Colonia domicilio de cliente</description>
        <label>Colonia</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delegacion__c</fullName>
        <description>Delegación del domicilio de cliente.</description>
        <label>Población</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Edad__c</fullName>
        <description>Edad de cliente</description>
        <label>Edad</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Genero__c</fullName>
        <description>Género del cliente.</description>
        <label>Género</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Masculino</fullName>
                </value>
                <value>
                    <fullName>Femenino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nacionalidad__c</fullName>
        <description>Nacionalidad de Cliente.</description>
        <label>Nacionalidad</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_Exterior__c</fullName>
        <description>Número exterior del domicilio de cliente.</description>
        <label>Número Exterior</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_Interior__c</fullName>
        <description>Número interior del domicilio de cliente.</description>
        <label>Número Interior</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profesion__c</fullName>
        <description>Profesión del cliente.</description>
        <label>Profesión</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC de cliente.</description>
        <label>RFC</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_rtwCotFillData.cls
/**
 * @File Name          : MX_SB_VTS_rtwCotFillData.cls
 * @Description        : 
 * @Author             : Eduardo Hernández Cuamatzi
 * @Group              : 
 * @Last Modified By   : Eduardo Hernández Cuamatzi
 * @Last Modified On   : 31/5/2019 9:05:30
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    30/5/2019 11:08:34   Eduardo Hernández Cuamatzi     Initial Version
**/
public with sharing class MX_SB_VTS_rtwCotFillData {
    
    /**
     * MX_SB_VTS_rtwCotFillData Constructor
     * @return   Corrección Singleton
     */
    private MX_SB_VTS_rtwCotFillData() {} //NOSONAR

    /**
     * fillBeneficiarioRTC description
     * @param  aseguradoOriginal aseguradoOriginal description
     * @return                   return description
     */
    public static infoCompbeneficiario fillBeneficiarioRTC(infoCompbeneficiario objinfoCompbeneficiario, Account aseguradoOriginal) {
        objinfoCompbeneficiario.fechaNacimiento =  validHappyDate(aseguradoOriginal.PersonBirthdate);
        objinfoCompbeneficiario.edad = validAge(Integer.valueOf(aseguradoOriginal.edad__c));
        objinfoCompbeneficiario.sexoDelConductor = aseguradoOriginal.Genero__c;
        objinfoCompbeneficiario.rfc = aseguradoOriginal.RFC__c;                   
        objinfoCompbeneficiario.origen = aseguradoOriginal.AccountSource;
        objinfoCompbeneficiario.ciudad = aseguradoOriginal.BillingCity;
        objinfoCompbeneficiario.estado = aseguradoOriginal.BillingState;
        objinfoCompbeneficiario.pais = aseguradoOriginal.BillingCountry;
        objinfoCompbeneficiario.delegacion = aseguradoOriginal.Delegacion__c;
        objinfoCompbeneficiario.nacionalidad = aseguradoOriginal.Nacionalidad__c;
        objinfoCompbeneficiario.profesion = aseguradoOriginal.Profesion__c;
        objinfoCompbeneficiario.colonia = aseguradoOriginal.Colonia__c;
        objinfoCompbeneficiario.calleOAvenida = aseguradoOriginal.BillingStreet;
        objinfoCompbeneficiario.codigoPostal = aseguradoOriginal.BillingPostalCode;
        objinfoCompbeneficiario.numeroExterior = aseguradoOriginal.Numero_Exterior__c;
        objinfoCompbeneficiario.numeroInterior = aseguradoOriginal.Numero_Interior__c;
        return objinfoCompbeneficiario;
    }

    /**
     * validHappyDate description
     * @param  dateStr dateStr description
     * @return         return description
     */
    public static String validHappyDate (Date dateStr) {
        String valdate = '';
        if(String.isNotBlank(String.valueOf(dateStr))) {
            valdate =String.valueOf(dateStr);
        }
        return valdate;
    }

    /**
     * validAge description
     * @param  ageDate ageDate description
     * @return         return description
     */
    public static String validAge(Integer ageDate) {
        String finalAge = '';
        if(String.isNotBlank(String.valueOf(ageDate))) {
            finalAge = String.valueOf(ageDate);
        }
        return finalAge;
    }

    /**
     * validEmptyStr description
     * @param  textVal textVal description
     * @return         return description
     */
    public static String validEmptyStr (String textVal) {
        String finalStr = '';
        if(String.isNotBlank(textVal)) {
            finalStr = textVal;
        }
        return finalStr;
    }

    /**
     * validOppsAccount description
     * @param  accountFor     accountFor description
     * @param  finalNuAccount finalNuAccount description
     * @param  reqCot         reqCot description
     * @return                return description
     */
    public static Account validOppsAccount (Account accountFor, Account finalNuAccount, reqCotizacion reqCot) {
        Account finalAccount = new Account();
        if(accountFor.Opportunities.isEmpty()) {
            finalAccount.Id = reqCot.cliente;
        } else {
            finalAccount = finalNuAccount;
        }
        return finalAccount;
    }
}