src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BPyP_tx_ActividadGiro__c</fullName>
        <description>Actividad o Giro asociado al cliente</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Actividad o Giro</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Registro_Manual__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tipo de Registro Manual</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>VP_tre_Cliente_PyME</fullName>
        <active>true</active>
        <description>Clientes PyME</description>
        <label>Cliente PyME</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Divisi_n__c</fullName>
        <label>División</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>VP_ls_Banca__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BAJIO</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO CENTRO</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA</fullName>
                </value>
                <value>
                    <fullName>NORESTE</fullName>
                </value>
                <value>
                    <fullName>NOROESTE</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE</fullName>
                </value>
                <value>
                    <fullName>SUR</fullName>
                </value>
                <value>
                    <fullName>SURESTE</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVA</fullName>
                </value>
                <value>
                    <fullName>BAJIO PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA NORTE PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA SUR PYME</fullName>
                </value>
                <value>
                    <fullName>NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>NOROESTE PYME</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>SUR PYME</fullName>
                </value>
                <value>
                    <fullName>SURESTE PYME</fullName>
                </value>
                <value>
                    <fullName>METRO NORTE</fullName>
                </value>
                <value>
                    <fullName>METRO SUR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_PYME_Acc_OwnerAssignment_Test.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     MX_PYME_Acc_OwnerAssignment_Test
* @Author   Jhovanny De La Cruz Cruz jhovanny.delacruz.contractor@bbva.com
* @Date     Created: 2019-02-06
* @Group    Test Clase for MX_PYME_Acc_OwnerAssignment_cls
* @Description Test Clase for MX_PYME_Acc_OwnerAssignment_cls
* @Changes
*
*  |2019-02-06  jhovanny.delacruz.contractor@bbva.com
*               Creation MX_PYME_Acc_OwnerAssignment_Test functionality class
*  |2019-04-01  Daniel García Domínguez
*               Account of manual record type "MASA_PYME" added
*/
@isTest
public class MX_PYME_Acc_OwnerAssignment_Test {
    /** */
    public static User creaUserEjecPyme() {
        return UtilitysDataTest_tst.crearUsuario('USUARIO EJEC', 'Ejecutivo PyME Plus', 'EJEC PYME PLUS AGUASCALIENTES');
    }
    /** */
    public static User creaUserDcnpPyme() {
        return UtilitysDataTest_tst.crearUsuario('USUARIO DCNP', 'D. CN PyME', 'D. CN PyME AGUASCALIENTES');
    }
    static Testmethod void newAccountPyME() {
        User udcnp = creaUserEjecPyme();
        udcnp.VP_ls_Banca__c = 'Red PyME';
        udcnp.Divisi_n__c = 'BAJIO PYME';
        udcnp.FederationIdentifier = 'mb01023';
        insert udcnp;
        User masaUser = creaUserDcnpPyme();
        masaUser.CommunityNickname = 'NoCarPyME';
        insert masaUser;
        System.runAs(udcnp) {
            Account acc = UtilitysDataTest_tst.crearCuenta('New Clients PyME', 'VP_tre_Cliente_PyME');
            acc.BPyP_tx_ActividadGiro__c = udcnp.FederationIdentifier;
            acc.Tipo_de_Registro_Manual__c = 'PYME';
            insert acc;
            Account clMas = UtilitysDataTest_tst.crearCuenta('Cl Masa PyME', 'VP_tre_Cliente_PyME');
            clMas.Tipo_de_Registro_Manual__c = 'MASA_PYME';
            insert clMas;
            List<Account> AccOnwerAssignment = [SELECT id FROM Account LIMIT 1];
            System.assertEquals(!AccOnwerAssignment.isEMpty(), true ,'Error al realizar la carterización única de clientes PyME');
        }
    }
    static Testmethod void newAccountPyMEError() {
        User udcnp = creaUserEjecPyme();
        udcnp.VP_ls_Banca__c = 'Red PyME';
        udcnp.Divisi_n__c = 'BAJIO PYME';
        udcnp.FederationIdentifier = 'mb01023';
        insert udcnp;
        System.runAs(udcnp) {
            Account acc = UtilitysDataTest_tst.crearCuenta('New Clients PyME', 'VP_tre_Cliente_PyME');
            acc.BPyP_tx_ActividadGiro__c = '';
            acc.Tipo_de_Registro_Manual__c = 'PYME';
            try {
                insert acc;
            }catch(DmlException e) {
                System.assertEquals(acc.id, null,Label.MX_PyME_Error_9_Referencia_a_propietario_del_cliente);
            }
        }
    }
}