src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC de cliente.</description>
        <label>RFC</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>RFC__c</fullName>
    <label>RFC</label>
    <length>25</length>
    <type>Text</type>
</fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
 <fields>
        <fullName>MX_SB_VTS_Numero_de_Llamadas__c</fullName>
		<description>Describre le numero de llamadas por actividad.</description>
        <label>Numero de Llamadas</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>ASD</fullName>
    <active>true</active>
    <businessProcess>ASD</businessProcess>
    <label>ASD</label>
</recordTypes>
</CustomObject>

src/objects/MX_WB_MotivosNoContacto__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Esta configuración almacena los Motivos de no contacti por los que un Prospecto puede no ser enviado nuevamente a CTI</description>
    <fields>
        <fullName>MX_SB_VTS_HoraDuracion__c</fullName>
        <description>Duración en Horas de la acción</description>
        <inlineHelpText>Horas de duración</inlineHelpText>
        <label>Duración</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_IDACCION__c</fullName>
        <description>Numero de accion a detonar.</description>
        <inlineHelpText>Acción a detonar (1,2,3)</inlineHelpText>
        <label>Numero de accion</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_10__c</fullName>
        <description>Décimo nivel de tipificación de árbol de decisión.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Décimo nivel de tipificación de árbol de decisión.</inlineHelpText>
        <label>Nivel 10</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_1__c</fullName>
        <description>Nivel 1 del arbol de tipificación</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Nivel 1 de revision</inlineHelpText>
        <label>Nivel 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_2__c</fullName>
        <description>Crea el segundo nivel de iteración en el árbol de tipificación.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Segundo nivel de iteración</inlineHelpText>
        <label>Nivel 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_3__c</fullName>
        <description>Tercer Nivel de Iteración del árbol de decisiones.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Tercer nivel de Iteración.</inlineHelpText>
        <label>Nivel 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_4__c</fullName>
        <description>Cuarto Nivel de Iteración del árbol de tipificación</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Cuarto nivel de Tipificación</inlineHelpText>
        <label>Nivel 4</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_5__c</fullName>
        <description>Quinto Nivel de Tipificación del árbol de procesos.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quinto Nivel de tipificación</inlineHelpText>
        <label>Nivel 5</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_6__c</fullName>
        <description>Sexto Nivel de tipificación del árbol de procesos.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Sexto nivel de tipificación.</inlineHelpText>
        <label>Nivel 6</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_7__c</fullName>
        <description>Séptimo nivel de tipificación del árbol de tipificación.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Séptimo nivel de tipificación.</inlineHelpText>
        <label>Nivel 7</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_8__c</fullName>
        <description>Octavo nivel de tipificación de árbol de decisión.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Octavo nivel de tipificación de árbol de decisión.</inlineHelpText>
        <label>Nivel 8</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Nivel_9__c</fullName>
        <description>Noveno nivel de tipificación de árbol de decisión.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Noveno nivel de tipificación de árbol de decisión.</inlineHelpText>
        <label>Nivel 9</label>
        <length>100</length>
        <type>Text</type>
    </fields>	
    <fields>
        <fullName>MX_WB_MotivoNoContacto__c</fullName>
        <label>Motivo no contacto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Motivos de no contacto</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Numero_de_Llamadas__c</fullName>
        <label>Numero de llamadas</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Información para la cotización.</description>
        <label>Motivo de la Oportunidad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Venta Pre emisión</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC del asegurado.</description>
        <label>RFC del Asegurado</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <label>ASD</label>
    </recordTypes>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Cuenta personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RFC__c</fullName>
        <label>RFC</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_SMARTNOCONTACTO_tst.cls
/**
*
* @author Arsenio Perez Lopez
* @description API to auto assign leads from Smart Center to call center agents
*
*           No  |     Date     |     Author      |    Description
* @version  1.0    24/07/2019     Arsenio Perez      Create API for Smart Center
* @version  1.0    24/07/2019     Arsenio Perez      Code smell
* @version  1.1    25/09/2019     Jaime Terrats      Class Update for new params
*/

@isTest
private class MX_SB_VTS_SMARTNOCONTACTO_tst {
    /** */
    final static String IDGRABACION = 'no contesto',
        IDCERTIFICACION ='',
        CALLID = '1',
        URI = '/services/apexrest/leadNoContacto',
        METHOD = 'POST',
        TXTCERTIFICADA ='Certificada', TXTTIDGRABACION='IDGrabacion',TXTTIPO='Tipo',TXTMOTIVO='MotivoNocontacto',
        TXTLEADID='LeadId';
    /** */
    @TestSetup
    static void makeData() {
        final User usr = MX_WB_TestData_cls.crearUsuario('Auto Assigner', system.label.MX_SB_VTS_ProfileAdmin);
        usr.RFC__c = 'LEAS190719VTS';
        Insert usr;
        final MX_WB_MotivosNoContacto__c no_cont = new MX_WB_MotivosNoContacto__c(
            Name='1', MX_SB_VTS_Nivel_1__c='1', MX_SB_VTS_Nivel_2__c='1', MX_SB_VTS_Nivel_3__c='1',
            MX_SB_VTS_Nivel_4__c='1', MX_SB_VTS_Nivel_5__c='1', MX_SB_VTS_Nivel_6__c='1',
            MX_SB_VTS_Nivel_7__c='1', MX_SB_VTS_Nivel_8__c='1', MX_SB_VTS_Nivel_9__c='1',
            MX_SB_VTS_Nivel_10__c='1', MX_SB_VTS_IDACCION__c=1, MX_WB_MotivoNoContacto__c='1',
            MX_SB_VTS_HoraDuracion__c=1
        );
        final MX_WB_MotivosNoContacto__c no_cont2 = new MX_WB_MotivosNoContacto__c(
            Name='2', MX_SB_VTS_Nivel_1__c='', MX_SB_VTS_Nivel_2__c='Creada', MX_SB_VTS_Nivel_3__c='',
            MX_SB_VTS_Nivel_4__c='', MX_SB_VTS_Nivel_5__c='', MX_SB_VTS_Nivel_6__c='',
            MX_SB_VTS_Nivel_7__c='', MX_SB_VTS_Nivel_8__c='', MX_SB_VTS_Nivel_9__c='',
            MX_SB_VTS_Nivel_10__c='', MX_SB_VTS_IDACCION__c=1, MX_WB_MotivoNoContacto__c='',
            MX_SB_VTS_HoraDuracion__c=1
        );
        insert no_cont;
        insert no_cont2;
        System.runAs(usr) {
            final Lead leadToAssign = MX_WB_TestData_cls.createLead('Lead Auto Assigner');
            insert leadToAssign;
            final Account accToAssign = MX_WB_TestData_cls.crearCuenta('Doe', 'PersonAccount');
            accToAssign.PersonEmail = 'test@test.com.leas';
            insert accToAssign;
            final Opportunity oppToAssign = MX_WB_TestData_cls.crearOportunidad('Opp Auto Assigner', accToAssign.Id, usr.Id, 'ASD');
            oppToAssign.Producto__c = 'Hogar';
            oppToAssign.Reason__c = 'Venta';
            insert oppToAssign;
        }
    }
    /** */
    @isTest
    private static void testNocontactoXcons() {
        test.startTest();
        Boolean tbolean = true;
        try {
        MX_SB_VTS_SMARTNOCONTACTO_cls x = new MX_SB_VTS_SMARTNOCONTACTO_cls(); //NOSONAR
        } catch(Exception s) {
            tbolean = false;
        }
        System.assert(tbolean, 'Correcto ');
        test.stopTest();
    }
    /** */
    @isTest
    private static void testNocontacto() {
        final Lead getLead = [select Id from Lead where Name = 'Lead Auto Assigner'];
        final RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf('{ "'+TXTLEADID+'": "' + getLead.Id + '", "'+TXTMOTIVO+'": "' + CALLID + '", "'+ TXTTIPO + '": "' + TXTMOTIVO + '", "'+TXTTIDGRABACION+'": "' + IDGRABACION +'", "'+TXTCERTIFICADA+'": "' + IDCERTIFICACION +'" }');
        request.requestURI = URI;
        request.httpMethod = METHOD;
        RestContext.request = request;
        Test.startTest();
        final String testAssigner = MX_SB_VTS_SMARTNOCONTACTO_cls.leadActionCont();
        System.assertNotEquals(testAssigner, System.Label.MX_WB_LG_ErrorBack, 'Exito testNocontacto');
        Test.stopTest();
    }
    /** */
    @isTest
    private static void testNocontacto2() {
        final RestRequest request = new RestRequest();
        final Lead getLead = [select Id from Lead where Name = 'Lead Auto Assigner'];
        request.requestURI = URI;
        request.httpMethod = METHOD;
        request.requestBody = Blob.valueOf('{ "'+TXTLEADID+'": "' + getLead.Id + '", "'+TXTMOTIVO+'": "' + CALLID + '", "'+ TXTTIPO + '": "Grabacion", "'+TXTTIDGRABACION+'": "' + IDGRABACION +'", "'+TXTCERTIFICADA+'": "' +IDCERTIFICACION+'" }');
        RestContext.request = request;
        Test.startTest();
        final String testAssigner = MX_SB_VTS_SMARTNOCONTACTO_cls.leadActionCont();
        System.assertNotEquals(testAssigner, System.Label.MX_WB_LG_ErrorBack, 'Exito testNocontacto2');
        Test.stopTest();
    }
    /** */
    @isTest
    private static void testNocontacto3() {
        final Lead getLead = [select Id from Lead where Name = 'Lead Auto Assigner'];
        final RestRequest request = new RestRequest();
		request.requestBody = Blob.valueOf('{ "'+TXTLEADID+'": "' + getLead.Id + '", "'+TXTMOTIVO+'": "' + CALLID + '", "'+ TXTTIPO + '": "", "'+TXTTIDGRABACION+'": "' + IDGRABACION +'", "'+TXTCERTIFICADA+'": "' + IDCERTIFICACION + '"}');
        request.httpMethod = METHOD;
        request.requestURI = URI;
        RestContext.request = request;
        Test.startTest();
        final String testAssigner = MX_SB_VTS_SMARTNOCONTACTO_cls.leadActionCont();
        System.assertEquals(testAssigner, System.Label.MX_WB_LG_ErrorBack, 'Exito testNocontacto3');
        Test.stopTest();
    }
    /** */
    @isTest
    private static void testNocontacto4() {
        final Lead getLead = [select Id from Lead where Name = 'Lead Auto Assigner'];
        getLead.MX_SB_VTS_Numero_de_Llamadas__c= 1;
        update getLead;
        final RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf('{ "'+TXTLEADID+'": "' + getLead.Id + '", "'+TXTMOTIVO+'": "' + CALLID + '", "'+ TXTTIPO + '": "' + TXTMOTIVO + '", "'+TXTTIDGRABACION+'": "' + IDGRABACION +'", "'+TXTCERTIFICADA+'": "' +IDCERTIFICACION+ '"}');
        request.requestURI = URI;
        request.httpMethod = METHOD;
        RestContext.request = request;
        Test.startTest();
        final String testAssigner = MX_SB_VTS_SMARTNOCONTACTO_cls.leadActionCont();
        System.assertNotEquals(testAssigner, System.Label.MX_WB_LG_ErrorBack, 'Exito testNocontacto4');
        Test.stopTest();
    }
    /** */
    @isTest
    private static void testNocontacto5() {
        final Task Tarea          = new Task();
        Tarea.Description   = 'Call';
        Tarea.Priority      = 'Normal';
        Tarea.Status        = 'No Iniciado';
        Tarea.Subject       = 'call';
        Tarea.MX_WB_idGrabacion__c='12345';
        insert Tarea;
        final Lead getLead = [select Id from Lead where Name = 'Lead Auto Assigner'];
        getLead.MX_SB_VTS_Numero_de_Llamadas__c= 1;
        update getLead;
        final RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf('{ "'+TXTLEADID+'": "' + getLead.Id + '", "'+TXTMOTIVO+'": "' + CALLID + '", "'+ TXTTIPO + '": "Grabacion", "'+TXTTIDGRABACION+'": "' + IDGRABACION +'", "'+TXTCERTIFICADA+'": "' + IDCERTIFICACION +'"}');
        request.requestURI = URI;
        request.httpMethod = METHOD;
        RestContext.request = request;
        Test.startTest();
        final String testAssigner = MX_SB_VTS_SMARTNOCONTACTO_cls.leadActionCont();
        System.assertNotEquals(testAssigner, System.Label.MX_WB_LG_ErrorBack, 'Exito testNocontacto5');
        Test.stopTest();
    }
    /** */
    @isTest
    private static void testNocontacto6() {
        final Opportunity getOppor = [select Id from Opportunity where Name = 'Opp Auto Assigner'];
        final RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf('{ "'+TXTLEADID+'": "' + getOppor.Id + '", "'+TXTMOTIVO+'": "' + CALLID + '", "'+ TXTTIPO + '": "' + TXTMOTIVO + '", "'+TXTTIDGRABACION+'": "' + IDGRABACION +'", "'+TXTCERTIFICADA+'": "'+IDCERTIFICACION+ '" }');
        request.requestURI = URI;
        request.httpMethod = METHOD;
        RestContext.request = request;
        Test.startTest();
        final String testAssigner = MX_SB_VTS_SMARTNOCONTACTO_cls.leadActionCont();
        System.assertNotEquals(testAssigner, System.Label.MX_WB_LG_ErrorBack, 'Exito testNocontacto6');
        Test.stopTest();
    }
    /** */
    @isTest
    private static void testNocontacto7() {
        final Opportunity getOppor = [select Id from Opportunity where Name = 'Opp Auto Assigner'];
        getOppor.MX_SB_VTS_ContadorRemarcado__c=1;
        update getOppor;
        final RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf('{ "'+TXTLEADID+'": "' + getOppor.Id + '", "'+TXTMOTIVO+'": "' + CALLID + '", "'+ TXTTIPO + '": "' + TXTMOTIVO + '", "'+TXTTIDGRABACION+'": "' + IDGRABACION +'", "'+TXTCERTIFICADA+'": "'+IDCERTIFICACION+'"}');
        request.requestURI = URI;
        request.httpMethod = METHOD;
        RestContext.request = request;
        Test.startTest();
        String testAssigner = MX_SB_VTS_SMARTNOCONTACTO_cls.leadActionCont();
        System.assertNotEquals(testAssigner, System.Label.MX_WB_LG_ErrorBack, 'Exito testNocontacto7');
        getOppor.MX_SB_VTS_ContadorRemarcado__c=5;
        update getOppor;
        testAssigner = MX_SB_VTS_SMARTNOCONTACTO_cls.leadActionCont();
        System.assertNotEquals(testAssigner, System.Label.MX_WB_LG_ErrorBack, 'Exito testNocontacto7_2');
        Test.stopTest();
    }
}