src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC de cliente.</description>
        <label>RFC</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>RFC__c</fullName>
    <label>RFC</label>
    <length>25</length>
    <type>Text</type>
</fields>
	<fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Campo que permite identificar cual es la tarea actual que se esta trabajando durante el proceso de venta Telemarketing</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LLamada Activa</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>ASD</fullName>
    <active>true</active>
    <businessProcess>ASD</businessProcess>
    <label>ASD</label>
</recordTypes>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Campo para referenciar la Tarea de llamada activa</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Tarea Activa</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Información para la cotización.</description>
        <label>Motivo de la Oportunidad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Venta Pre emisión</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC del asegurado.</description>
        <label>RFC del Asegurado</label>
        <length>25</length>
        <type>Text</type>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <label>ASD</label>
    </recordTypes>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Cuenta personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RFC__c</fullName>
        <label>RFC</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_LeadAutoAssigner_Test.cls
/**-------------------------------------------------------------------------
* Nombre: MX_SB_VTS_Hogar_Service_Test
* @author Jaime (JT)
* Proyecto: MX_Ventas - BBVA Bancomer
* Descripción : Clase test que sirve para la cobertura de la clase MX_SB_VTS_LeadAutoAssigner
*
* --------------------------------------------------------------------------
*                         Fecha           Autor                   Desripción
* --------------------------------------------------------------------------
* @version 1.0           19/07/2019      Jaime T                   Creación
* @version 1.0           27/08/2019      Jaime T                   Codesmell
* --------------------------------------------------------------------------*/
@isTest
private class MX_SB_VTS_LeadAutoAssigner_Test {
    /*static var*/
    final static String TIPIFICACION = 'no contesto',
                        CALLID = '1',
                        URI = '/services/apexrest/leadAutoAssigner',
                        METHOD = 'POST';
    /**
    * Test setup method
     */
	@testSetup
    public static void makeData() {
       	final User usr = MX_WB_TestData_cls.crearUsuario('Auto Assigner', system.label.MX_SB_VTS_ProfileAdmin);
        usr.RFC__c = 'LEAS190719VTS';
        Insert usr;

        System.runAs(usr) {
            final Lead leadToAssign = MX_WB_TestData_cls.createLead('Lead Auto Assigner');
            insert leadToAssign;

            final Account accToAssign = MX_WB_TestData_cls.crearCuenta('Doe', 'PersonAccount');
            accToAssign.PersonEmail = 'test@test.com.leas';
            insert accToAssign;

            final Opportunity oppToAssign = MX_WB_TestData_cls.crearOportunidad('Opp Auto Assigner', accToAssign.Id, usr.Id, 'ASD');
            oppToAssign.Producto__c = 'Hogar';
            oppToAssign.Reason__c = 'Venta';
            insert oppToAssign;
        }
    }

    /**
    * Success test to assign lead
    */
    @isTest
    private static void testLeadAssignment() {
        final User usr = [select RFC__c from User where Name = 'Auto Assigner'];
        final Lead getLead = [select Id from Lead where Name = 'Lead Auto Assigner'];
        final String expectedURI = System.Url.getSalesforceBaseUrl().toExternalForm() + '/' + getLead.Id;
        final RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf('{ "recordId": "' + getLead.Id + '", "rfc": "' + usr.RFC__c + '", "callId": "' + CALLID + '", "tipificacion": "' + TIPIFICACION + '"}');
        request.requestURI = URI;
        request.httpMethod = METHOD;
        RestContext.request = request;
        Test.startTest();
        final String testLeadAutoAssigner = MX_SB_VTS_LeadAutoAssigner.assignLead();
        System.assertEquals(testLeadAutoAssigner, expectedURI, 'Exito');
        Test.stopTest();
    }

    /**
    * Success Test to assign opp
    */
    @isTest
    private static void testOppAssignment() {
        final User usr = [select RFC__c from User where Name = 'Auto Assigner'];
        final Opportunity getOpp = [select Id,MX_SB_VTS_LookActivity__c from Opportunity where Name = 'Opp Auto Assigner'];
        final String expectedURI = System.Url.getSalesforceBaseUrl().toExternalForm() + '/' + getOpp.Id;
        final RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf('{ "recordId": "' + getOpp.Id + '", "rfc": "' + usr.RFC__c + '", "callId": "' + CALLID + '", "tipificacion": "' + TIPIFICACION + '"}');
        request.httpMethod = METHOD;
        request.requestURI = URI;
        RestContext.request = request;
        Test.startTest();
        final String testLeadAutoAssigner = MX_SB_VTS_LeadAutoAssigner.assignLead();
        System.assertEquals(testLeadAutoAssigner, expectedURI, 'Exito');
        Test.stopTest();
    }
    /**
    * Fail scenario
    */
    @isTest
    private static void failTest() {
		final RestRequest request = new RestRequest();
		request.requestBody = Blob.valueOf('{ "recordId" : "", "rfc": "", "tipificacion":"", "callId":"" }');
        request.httpMethod = METHOD;
        request.requestURI = URI;
        RestContext.request = request;
        Test.startTest();
        final String testLeadAutoAssigner = MX_SB_VTS_LeadAutoAssigner.assignLead();
        System.assertEquals(testLeadAutoAssigner, System.Label.MX_WB_LG_ErrorBack, 'Fallo esperado');
        Test.stopTest();
    }
}