src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MX_GroupItBelongs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relacion de grupo al que pertenece utilizado para Family group para modelo person account en BPyP</description>
        <label>Grupo al que pertenece</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cuentas (Grupo al que pertenece)</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_de_cliente__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>No. de cliente</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MX_GroupItBelongs__c</fullName>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>UG__c</fullName>
        <formula>Owner.UG__c</formula>
        <label>UG</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>BPyP_tre_Cliente</fullName>
        <active>true</active>
        <description>Tipo de registro para clientes de BPyP - Personas morales</description>
        <label>Cliente BPyP - Morales</label>
    </recordTypes>
    <recordTypes>
        <fullName>BPyP_tre_familyGroup</fullName>
        <active>true</active>        <!-- <compactLayoutAssignment>BPyP_fco_Family_Group</compactLayoutAssignment> -->
        <description>Tipo de registro para family groups de BPyP</description>
        <label>Family Group BPyP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grupo</fullName>
        <active>true</active>        <!-- <compactLayoutAssignment>dwp_cglp__Group_Compact_Layout</compactLayoutAssignment> -->
        <description>Grupos de clientes</description>
        <label>Grupo</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HI_ls_MotivoDescarte__c</fullName>
        <description>Lista de selección para descartar en Banca Hipotecaria Individual</description>
        <label>Motivo de descarte</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Buró comercial / interno</fullName>
                </value>
                <value>
                    <fullName>Contacto cercano con otro banco</fullName>
                </value>
                <value>
                    <fullName>Contingencias del cliente</fullName>
                </value>
                <value>
                    <fullName>Dictamen jurídico</fullName>
                </value>
                <value>
                    <fullName>Precio</fullName>
                </value>
                <value>
                    <fullName>Producto</fullName>
                </value>
                <value>
                    <fullName>Regulatorio</fullName>
                </value>
                <value>
                    <fullName>Tema técnico</fullName>
                </value>
                <value>
                    <fullName>Tiempos de respuesta</fullName>
                </value>
                <value>
                    <fullName>Declinado por riesgos</fullName>
                </value>
                <value>
                    <fullName>Dictamen legal no favorable</fullName>
                </value>
                <value>
                    <fullName>Dictamen técnico no favorable</fullName>
                </value>
                <value>
                    <fullName>No hay acuerdo en condiciones de crédito</fullName>
                </value>
                <value>
                    <fullName>Precio / Sobretasa</fullName>
                </value>
                <value>
                    <fullName>Se fue con otro banco</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
                <value>
                    <fullName>No fue aprobado por Riesgos</fullName>
                </value>
                <value>
                    <fullName>Cliente no posee las garantías adecuadas</fullName>
                </value>
                <value>
                    <fullName>No aprobado por notaría</fullName>
                </value>
                <value>
                    <fullName>CSC no autorizó la liberación de recursos</fullName>
                </value>
                <value>
                    <fullName>Requerimientos del Seguro no satisfechos</fullName>
                </value>
                <value>
                    <fullName>Expediente incompleto</fullName>
                </value>
                <value>
                    <fullName>Cliente rechaza por demora en el proceso (autorización de Dirección General)</fullName>
                </value>
                <value>
                    <fullName>Cliente rechaza por demora en el proceso (otros factores)</fullName>
                </value>
                <value>
                    <fullName>Oferta no fue atractiva para el cliente</fullName>
                </value>
                <value>
                    <fullName>Otros factores (campo abierto)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <recordTypes>
        <fullName>MX_BPP_RedBpyp</fullName>
        <active>true</active>
        <businessProcess>BPyP</businessProcess>
        <description>Tipo de Registro para la banca BPyP</description>
        <label>BPyP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Trigger_Oportunidad__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Enciende/apaga los trigger del objeto oportunidad.</description>
    <fields>
        <fullName>ContarOppsGrupo__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Switch ContarOppsGrupo</description>
        <label>ContarOppsGrupo</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger_Oportunidad</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <description>Unidad gestora</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>UG</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Director_de_oficina__c</fullName>
        <label>Director de oficina</label>
        <relationshipName>Directores_oficina</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContarOppsGrupo_tst.cls
/*
Empresa:        Softtek
Autor:                  Emmanuel Cruz Barajas
Proyecto:               Bancomer
Descripción:            Clase de prueba para desencadenador ContarOppsGrupo
--------------------------------------------------------------------------
No.     Fecha               Autor                   Descripción
------  ----------  ----------------------      --------------------------
1.0     02-09-2014  Emmanuel Cruz Barajas(ECB)  Creación
1.1   21-09-2015  Eduardo Godinez Loza(EGL) Se agrega metodo cancelacion de solicitud
1.2     13-09-2017    Jhovanny De La Cruz Cruz        Creación
1.3     20-04-2018   Carlos Ricardo Hernandez R.  Agrega un update para cambiar el propietario de la Opp.
1.4     08-05-2018   Sergio Ortiz                 Se agrega assert
1.5     03-10-2018  Fernando Jaime				Se cambia Administrador del sistema por etiqueta de personalizada
												Se agrega producto en uso para corregir fallo en metodo
2.0		10-10-2018	Cristian Espinosa			Se elimina dependencia hacia producto custom.
												*Se re estructura la clase para que cumpla con los estándares actuales.
2.1     11/07/2019  Jair Ignacio Gonzalez G     Se depuro clase con los metodos confirmados en la migracion de bpyp y pymes
*/
@isTest
private class ContarOppsGrupo_tst {

    /** Colocación */
    static final String STGFAM = 'Colocación';
    /** Collares */
    static final String STGPROD = 'Collares';
    /** MX_BPP_RedBpyp */
    static final String STGRTOPP = 'MX_BPP_RedBpyp';
    /** Cliente */
    static Account cliente;
    /** Grupo */
    static Account grupo;
    /** Usuarios */
    static User usuario,usuario2;
    /** Usuario actual */
    static User thisUser = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];

    static void crearUsuario() {
        usuario = UtilitysDataTest_tst.crearUsuario('Prueba', Label.MX_PERFIL_SystemAdministrator, 'EJECUTIVO GOBIERNO Y EMPRESAS OAXACA');
        usuario.Alias = 'userUno';
        usuario.UG__c = '2468135';
        usuario.Director_de_oficina__c = usuario2.Id;
        insert usuario;
    }

    static void crearUsuario2() {
        usuario2 = UtilitysDataTest_tst.crearUsuario('Prueba2', Label.MX_PERFIL_SystemAdministrator, 'EJECUTIVO GOBIERNO Y EMPRESAS OAXACA');
        usuario2.Alias = 'userDos';
        usuario2.UG__c = '2468136';
        insert usuario2;
    }

    static void crearGrupo() {
        grupo = UtilitysDataTest_tst.crearCuenta('Prueba grupo', 'BPyP_tre_familyGroup');
        grupo.No_de_cliente__c = '1234765';
        grupo.OwnerId = usuario.Id;
        insert grupo;
    }

    static void crearCliente() {
        cliente = UtilitysDataTest_tst.crearCuenta('Prueba cliente', 'BPyP_tre_Cliente');
        cliente.No_de_cliente__c = '1234768';
        cliente.OwnerId = usuario.Id;
        cliente.MX_GroupItBelongs__c = grupo.Id;
        insert cliente;
    }

    static testMethod void contarOppsGrupoTest() {
        System.runAs(thisUser) {
            crearUsuario2();
            crearUsuario();
        }
        final Integer maxQuery = Limits.getLimitQueries();
        final Integer numQuery = maxQuery - 1;
        final Trigger_Oportunidad__c setting = new Trigger_Oportunidad__c();
        setting.ContarOppsGrupo__c = true;
        insert setting;

        System.runAs(usuario) {
        	crearGrupo();
        }
        crearCliente();
        UtilitysDataTest_tst.crearProdForm('Colocación', 'Collares');
        final List<Opportunity> listaOps = new List<Opportunity>();
        final Opportunity opp = UtilitysDataTest_tst.crearOportunidad('Op Abierta', cliente.Id, usuario.Id, STGFAM, STGPROD, null, STGRTOPP);
        listaOps.add(opp);

        final Opportunity opp2 = UtilitysDataTest_tst.crearOportunidad('Op Cerrada', cliente.Id, usuario.Id, STGFAM, STGPROD, null, STGRTOPP);
        listaOps.add(opp2);

        final Opportunity opp3 = UtilitysDataTest_tst.crearOportunidad('Op Descartado', cliente.Id, usuario.Id, STGFAM, STGPROD, null, STGRTOPP);
        listaOps.add(opp3);

        final Opportunity opp4 = UtilitysDataTest_tst.crearOportunidad('Op Abierta2', cliente.Id, usuario.Id, STGFAM, STGPROD, null, STGRTOPP);
        listaOps.add(opp4);

        final Opportunity opp5 = UtilitysDataTest_tst.crearOportunidad('Op Cerrada2', cliente.Id, usuario.Id, STGFAM, STGPROD, null, STGRTOPP);
        listaOps.add(opp5);

        final Opportunity opp6 = UtilitysDataTest_tst.crearOportunidad('Op Descartado2', cliente.Id, usuario.Id, STGFAM, STGPROD, null, STGRTOPP);
        listaOps.add(opp6);
        insert listaOps;

        listaOps[0].ownerId = usuario2.id;
        update listaOps[0];

        System.runAs(usuario) {
            for(Opportunity o :listaOps) {
                if(o.Name == 'Op Cerrada' || o.Name == 'Op Cerrada2') {
                    //o.op_ca_productoUso__c = true;
                    o.StageName = 'Cerrada Ganada';
                }

                if(o.Name == 'Op Descartado' || o.Name == 'Op Descartado2') {
                    o.StageName = 'Descartada / Rechazada';
                    o.HI_ls_MotivoDescarte__c = 'Expediente incompleto';
                }
            }
            update listaOps;
            //Handler_Recursividad.UnaVez = true;

            borrarOpp(listaOps);

        }
        System.assert(Limits.getQueries() < numQuery, 'numero de querys dentro del rango  permitido');
    }

    static void borrarOpp(List<Opportunity> listaOps) {
        final List<Opportunity> listaBorrar = new List<Opportunity>();
            for(Opportunity o :listaOps) {
                if(o.Name == 'Op Abierta' || o.Name == 'Op Cerrada' || o.Name == 'Op Descartado') {
                    listaBorrar.add(o);
                }
            }
    }

}