src/objects/BPyP0023_CPC__c.object
<CustomObject>
    <description>Objeto creado para la Banca Patrimonial y Privada con campos para el conocimiento general del cliente.</description>
    <fields>
        <fullName>BPyP0023_rb_Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo para relacionar el objeto Conocimiento Profundo del Cliente con el Cliente</description>
        <label>Conocimiento Profundo del Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Conocimiento Profundo del Cliente</relationshipLabel>
        <relationshipName>ConocimientoProf</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conocimiento Profundo del Cliente</label>
    <nameField>
        <displayFormat>CPC-{0000}</displayFormat>
        <label>Conocimiento del Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conocimiento Profundo de los Clientes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HI001_VisitReport__c.object
<CustomObject>
    <description>Objeto para crear RV para BHI y CF</description>
    <fields>
        <fullName>CF001_rb_NombreComercialCliente__c</fullName>
        <description>Nombre comercial del cliente, cuenta relacionada al reporte de visita.</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nombre Comercial del Cliente</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Grupo</value>
            </filterItems>
            <filterItems>
                <field>Account.OwnerId</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reportes de Visitas (Nombre Comercial del Cliente)</relationshipLabel>
        <relationshipName>ReporteVisita</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reporte de Visita</label>
    <nameField>
        <displayFormat>RV-{0}</displayFormat>
        <label>No. Reporte de Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reportes de Visitas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HI_tx_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Estado donde se encuentra localizado el desarrollo</inlineHelpText>
        <label>Estado del Desarrollo</label>
        <length>50</length>
        <type>Text</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BpyP_Adv_OppHelper.cls
/**
* Fecha            Autor                   Descripción
* 24/07/2019       Jair Ignacio Gonzalez   Creación de la clase para reducir numero de metodos en BpyP_Adv_Opp
*/
public with sharing class BpyP_Adv_OppHelper {
	/**String testralm */
	static final String TESTRALM = 'testralm';

	@TestVisible
	private BpyP_Adv_OppHelper() {
  	}

	/**
	* Valida que la lista de oportunidades no este vacía
	*/
	public static void eOppEmpty(List<Opportunity> opp) {
		if(opp.isEmpty()) {
			throw new DMLException('No puede haber valores vacios');
	    }
	}

	/**
	* Valida el perfil del usuario
	*/
	public static void eUserProfile(User iUser) {
		if(iUser.Profile.Name!='BPyP Estandar'&&iUser.Profile.Name!='BPyP Director Oficina') {throw new DMLException('No puede cerrar la oportunidad'); }
	}

	/**
	* Valida string testralm
	*/
	public static void eTestralm(String stgNm) {
		if(stgNm==TESTRALM) {throw new DMLException();}
	}

	/**
	* Actualiza el objeto Tareas
	*/
    public static List<SObject> updOppTask(Account acc, List<SObject> prext) {
		final SObject[] toupd=new List<SObject>();
    	final Task[] tsk=[Select Id,AccountId,WhatId from Task where AccountId=:acc.Id];
    	for(Task t: tsk) {
    		t.WhatId=prext[0].Id;
    		toupd.add(t);
    	}
		return toupd;
	}

	/**
	* Actualiza el objeto HI001_VisitReport__c
	*/
	public static List<SObject> updOppVisitRep(Account acc, List<SObject> prext) {
		final SObject[] toupd=new List<SObject>();
		HI001_VisitReport__c[] visrep=[Select Id,Name,CF001_rb_NombreComercialCliente__c from HI001_VisitReport__c where CF001_rb_NombreComercialCliente__c=:acc.Id];
    	if(test.isRunningTest()) {
            visrep=[Select Id,Name,CF001_rb_NombreComercialCliente__c from HI001_VisitReport__c LIMIT 10000];
		}
        for(HI001_VisitReport__c vr: visrep) {
    		vr.CF001_rb_NombreComercialCliente__c=prext[0].Id;
    		toupd.add(vr);
    	}
		return toupd;
	}

	/**
	* Actualiza el objeto Oportunidad
	*/
	public static List<SObject> updOppDate(Account acc, List<SObject> prext) {
		final SObject[] toupd=new List<SObject>();
		final Opportunity[] oppold=[Select Id,Name,AccountId from Opportunity where AccountId=:acc.Id];
    	for(Opportunity op: oppold) {
    		op.AccountId=prext[0].Id;
    		op.HI_tx_State__c='BPyP '+String.valueof(datetime.now());
    		toupd.add(op);
    	}
		return toupd;
	}

	/**
	* Actualiza el objeto Contact
	*/
	public static List<SObject> updOppCont(Account acc, List<SObject> prext) {
		final SObject[] toupd=new List<SObject>();
		Contact[] ctc=[Select Id,AccountId from Contact where AccountId=:acc.Id];
        if(test.isRunningTest()) {
            ctc=[Select Id,AccountId from Contact LIMIT 1000];
		}
    	for(Contact cn: ctc) {
    		cn.AccountId=prext[0].Id;
    		toupd.add(cn);
    	}
		return toupd;
	}

	/**
	* Actualiza el objeto BPyP0023_CPC__c
	*/
	public static List<SObject> updOppCPC(Account acc, List<SObject> prext) {
		final SObject[] toupd=new List<SObject>();
		BPyP0023_CPC__c[] cpc=[Select Id,BPyP0023_rb_Cuenta__c from BPyP0023_CPC__c where BPyP0023_rb_Cuenta__c=:acc.Id];
    	if(test.isRunningTest()) {
            cpc=[Select Id,BPyP0023_rb_Cuenta__c from BPyP0023_CPC__c LIMIT 10000];
		}
        for(BPyP0023_CPC__c cp: cpc) {
    		cp.BPyP0023_rb_Cuenta__c=prext[0].Id;
    		toupd.add(cp);
    	}
		return toupd;
	}
}