src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_PYME_Productos__c</fullName>
        <description>Productos Seleccionados para la Oportunidad</description>
        <label>Productos</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agencia Houston Cheques</fullName>
                </value>
                <value>
                    <fullName>Ahorro</fullName>
                </value>
                <value>
                    <fullName>Ahorro Liquido</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aplinet</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Financiero</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Puro</fullName>
                </value>
                <value>
                    <fullName>Asset Management Gestión Terceros</fullName>
                </value>
                <value>
                    <fullName>Asset Management Previsión Social</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Auto Flotilla Única</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bancomer.com</fullName>
                </value>
                <value>
                    <fullName>Bancomer Net Cash</fullName>
                </value>
                <value>
                    <fullName>Bonds (Garantías)</fullName>
                </value>
                <value>
                    <fullName>Cadenas NAFIN</fullName>
                </value>
                <value>
                    <fullName>Cajeros Automáticos (ATMs)</fullName>
                </value>
                <value>
                    <fullName>Cambios</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito PyME</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Cheques</fullName>
                </value>
                <value>
                    <fullName>Cheques cuenta de grupo / GL</fullName>
                </value>
                <value>
                    <fullName>Ciclos de Vida/ Previsión Social</fullName>
                </value>
                <value>
                    <fullName>CIE Electrónico</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE Ventanilla</fullName>
                </value>
                <value>
                    <fullName>Cobertura/Renta Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cond__Account_Campaign__c.object
<CustomObject>
    <description>Junction object to relate Campaigns with Clients</description>
    <label>Account Campaign</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Campaigns</pluralLabel>
    <recordTypes>
        <fullName>MX_PYME_Campania_CargadaPrd</fullName>
        <active>true</active>
        <label>Campaña con Productos</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_PYME_CampTrigHand_Cls.cls
/*******************************************************************************
@Name                   MX_PYME_CampTrigHand_Cls
Desarrollado por:       Indra
@Author                 Ricardo Almanza
@Date                   2019-01-25
Proyecto:               PYME
@Group                  Trigger Campaign
*************************************************************************************
@Description            Clase para métodos de trigger de Campaign Manteniendo relación entre Account Campaign
*************************************************************************************
@Changes
2019-04-02  ricardo.almanza.contractor@bbva.com     Mejora para procesar AccCamp relacionados por batch
/*******************************************************************************/
public with sharing class MX_PYME_CampTrigHand_Cls {

    //Constructor with no arguments
    @TestVisible
    private MX_PYME_CampTrigHand_Cls() {}

    /*
    *@Description   Update AccCamp when Campaign has Products
    *@param         newCamp List of Campaign updated to Match changes and update related Account Campaigns
    *@param         oldCamp List of old Campaign updated to Match changes and update related Account Campaigns
    *@return        void
    *@example       updAccCamponPrd(newCamp, oldCamp)
    */
    public static void updAccCamponPrd(Map<Id,Campaign> newCamp,Map<Id,Campaign> oldCamp) {
        Map<Id,Campaign> newCampPrd = new Map<Id,Campaign>();
        for (Campaign camp : newCamp.values()) {
            if(camp.MX_PYME_Productos__c != null && (oldCamp == null || oldCamp.get(camp.Id).MX_PYME_Productos__c == null)) {
                newCampPrd.put(camp.Id, camp);
            }
        }
        if(!newCampPrd.isEmpty()) {
            MX_PYME_AccCamp_ActRecType_Batch_Cls bacc = new MX_PYME_AccCamp_ActRecType_Batch_Cls(newCampPrd.keySet() , 'MX_PYME_Campania_CargadaPrd' , 'Select Id, RecordTypeId from cond__Account_Campaign__c where cond__campaign_id__c in (' , ')' );
            database.executebatch(bacc , 2000);
        }
    }
}