src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_FamiliaProducto_Proveedor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Campo relación para filtrar familia de productos autorizada por proveedor</description>
        <inlineHelpText>Ramo al que pertenece la campaña</inlineHelpText>
        <label>Familia de producto</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.MX_SB_VTS_Identificador_Proveedor__c</field>
                <operation>equals</operation>
                <valueField>$User.MX_SB_VTS_ProveedorCTI__c</valueField>
            </filterItems>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.Owner:User.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MX_SB_VTS_FamliaProveedores__c</referenceTo>
        <relationshipLabel>Campañas</relationshipLabel>
        <relationshipName>Campa_as</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Segmentada__c</fullName>
        <description>Valida el valor del segmentado del provedor</description>
        <formula>MX_SB_VTS_FamiliaProducto_Proveedor__r.MX_SB_VTS_ProveedorCTI__r.MX_SB_VTS_TieneSegmento__c</formula>
        <label>Segmentada</label>
        <type>Checkbox</type>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>Apellido_Materno__c</fullName>
    <label>Apellido Materno</label>
    <length>50</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>Fecha_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</fields>
<fields>
    <fullName>Folio_Cotizacion__c</fullName>
    <label>Folio Cotización</label>
    <length>10</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>EnviarCTI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EnviarCTI</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>Producto_Interes__c</fullName>
    <label>Producto de Interés</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compra Perfecta</fullName>
            </value>
            <value>
                <fullName>No especifica</fullName>
            </value>
            <value>
                <fullName>Otros Ramos ( Vida / Salud )</fullName>
            </value>
            <value>
                <fullName>Seguro auto Clasico</fullName>
            </value>
            <value>
                <fullName>Seguro de auto</fullName>
                <label>Seguro De Auto</label>
            </value>
            <value>
                <fullName>Seguro de Auto Otros Usos</fullName>
            </value>
            <value>
                <fullName>Seguro de auto Udi</fullName>
            </value>
            <value>
                <fullName>Seguro de Bicicleta</fullName>
            </value>
            <value>
                <fullName>Seguro de Moto</fullName>
            </value>
            <value>
                <fullName>Seguro de Moto UDI</fullName>
            </value>
            <value>
                <fullName>Seguro Fronterizo</fullName>
            </value>
            <value>
                <fullName>Seguro Legalizado</fullName>
            </value>
            <value>
                <fullName>Wiberizate</fullName>
            </value>
            <value>
                <fullName>Seguro de Moto Bancomer</fullName>
            </value>
            <value>
                <fullName>Seguro de auto fronterizo Bancomer</fullName>
            </value>
            <value>
                <fullName>Seguro de auto nacionalizado</fullName>
            </value>
            <value>
                <fullName>Auto Seguro Dinamico</fullName>
            </value>
            <value>
                <fullName>RC Carretero</fullName>
            </value>
			 <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
        </valueSetDefinition>
    </valueSet>
</fields>
<fields>
    <fullName>MX_WB_EnvioCTI__c</fullName>
    <description>Se almacena la fecha de envió a CTI</description>
    <label>Fecha envió CTI</label>
    <type>Date</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono1__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 1</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono2__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 2</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono3__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 3</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_txt_Prefijo_1__c</fullName>
    <description>Campo de telemarketing prefijo 1</description>
    <label>Prefijo 1</label>
    <length>3</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>MX_WB_Convertido__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar si el Lead ha sido convertido o no.</description>
    <label>Convertido</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_TM_Congelado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo sirve para no enviar el prospecto a CTI cuando tenga el valor activo</description>
    <label>Congelado</label>
    <type>Checkbox</type>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>ASD</fullName>
    <active>true</active>
    <businessProcess>ASD</businessProcess>
    <label>ASD</label>
</recordTypes>
</CustomObject>

src/objects/MX_SB_VTS_FamliaProveedores__c.object
<CustomObject>
    <description>Objeto intermedio para asignar familias a proveedores</description>
    <fields>
        <fullName>MX_SB_VTS_Identificador_Proveedor__c</fullName>
        <description>Código de proveedor.</description>
        <formula>TEXT(MX_SB_VTS_ProveedorCTI__r.MX_SB_VTS_Identificador_Proveedor__c)</formula>
        <label>Identificador Proveedor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nombre del proveedor.</description>
        <label>ProveedorCTI</label>
        <referenceTo>MX_SB_VTS_ProveedoresCTI__c</referenceTo>
        <relationshipLabel>Familia Productos Proveedores</relationshipLabel>
        <relationshipName>Familia_Productos_Proveedores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Familia Producto Proveedor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Familia Producto Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familia Productos Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_Generica__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista Genérica para múltiples valores del flujo de venta.</description>
    <fields>
        <fullName>MX_SB_VTS_FiltroCampanaLabel__c</fullName>
        <description>Label from campaing filtring</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MX_SB_VTS_FiltroCampanaLabel</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_FiltroCampana__c</fullName>
        <description>Campos para filtrado del objeto campaing</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MX_SB_VTS_FiltroCampana</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Type__c</fullName>
        <description>RecordType for the object
CP1-- Object Quoly to Oli
CP2-- Filtro Campaing
CP3-- Servicios Bandejas
CP4
CP5--Id Salesforce Banquero base al que se asignan las cuentas al no existir un banquero asignado.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>RecordType for the object 
CP1 -- Object Quoly to Oli 
CP2 -- Filtro Campaing 
CP3 -- Servicios Bandejas
CP4 --
CP5--Id Salesforce Banquero base al que se asignan las cuentas al no existir un banquero asignado.</inlineHelpText>
        <label>MX_SB_VTS_Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MX_SB_VTS_Generica</label>
</CustomObject>

src/objects/User.object
<CustomObject>
     <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <description>Campo para especificar el nombre del proveedor al que esta asignado un usuario</description>
        <label>ProveedorCTI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_Lista_Proveedores</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/MX_SB_VTS_Lista_Proveedores.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ninguno</fullName>
        <default>true</default>
        <label>Ninguno</label>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>VCIP</fullName>
    </customValue>
    <customValue>
        <fullName>SMART CENTER</fullName>
    </customValue>
    <description>Lista de nombres de proveedores</description>
    <masterLabel>Nombres Proveedores</masterLabel>
</GlobalValueSet>

src/classes/MX_WB_CampaniasCTI_cls.cls
/**-------------------------------------------------------------------------
* Nombre: WB_ProcNotif_cls
* @author Karen Sanchez (KB)
* Proyecto: MW WB Tlmkt - BBVA Bancomer
* Descripción : Clase que se ocupa para enviar datos a CTI y regresar una consulta al componente MX_WB_CampaniasCTI_cmp

* --------------------------------------------------------------------------
*                         Fecha           Autor                   Desripción
* -------------------------------------------------------------------
* @version 1.0           13/01/2019      Karen Sanchez            Creación
*          1.1           17/01/2019      Arsenio Perez            Modificacion de busqueda Ln 30-38
*          1.2           18/06/2019      Arsenio PErez            Modificacion de envios lead para smart center
*          1.2.1         21/06/2019      Jaime Terrats            Se soluciona code smell
* --------------------------------------------------------------------------*/
public without sharing class MX_WB_CampaniasCTI_cls {

    /**Lista AllApiName */
    static final List<String> AllApiName = new List<String>();
    /** Lista searchFilter */
    static final List<String> searchFilter = new List<String>();
    /** variable searchKey, cadena1 */
    static String searchKey, cadena1;
    /** variable tipo objeto*/
    final static String SOBJECTO = 'Lead';
    /** Lista Generica*/
    static final List<MX_SB_VTS_Generica__c> Generica = new List<MX_SB_VTS_Generica__c>();
    /**Mapa mapGenerica */
    static final Map<String,String> mapGenerica = new Map<String, String>();
    static {
        searchKey = '';
        cadena1 = '';
        for(MX_SB_VTS_Generica__c gentemp: MX_SB_VTS_Generica__c.getall().values()) {
            if('CP2'.equals(gentemp.MX_SB_VTS_Type__c)) {
                Generica.add(gentemp);
                mapGenerica.put(gentemp.MX_SB_VTS_FiltroCampanaLabel__c,gentemp.MX_SB_VTS_FiltroCampana__c);
            }
        }
    }

    /*13-01-2019 Función: Regresa la consulta de los miembros de campañas de la campaña activa
    *Karen Belem Sanchez Ruiz*/
    @AuraEnabled
    public static List < CampaignMember > lstCampaignMember(String searchKeyWord, String cadena) {
        try {
        searchKey = searchKeyWord;
        final List<CampaignMember> lstOfCampaign = new List<CampaignMember>();
            final String USerID =UserInfo.getUserId();
            final String tempProvedor= [Select MX_SB_VTS_ProveedorCTI__c from user where id =:USerID].MX_SB_VTS_ProveedorCTI__c;
        String sQuery = 'SELECT LeadId, Lead.MX_WB_EnvioCTI__c, Lead.FirstName, Lead.LastName, Lead.Apellido_Materno__c, Lead.Fecha_Nacimiento__c,';
               sQuery +=' Lead.MX_WB_txt_Prefijo_1__c, Lead.MX_WB_ph_Telefono1__c, Lead.MX_WB_ph_Telefono2__c, Lead.MX_WB_ph_Telefono3__c, Lead.Folio_Cotizacion__c,';
               sQuery +=' Lead.Producto_Interes__c, Lead.OwnerId, Lead.EnviarCTI__c, Lead.MX_WB_TM_Congelado__c, campaign.MX_SB_VTS_Segmentada__c  FROM CampaignMember WHERE campaign.ID =: searchKey';
               sQuery +=' AND lead.MX_WB_Convertido__c = false AND lead.MX_WB_TM_Congelado__c = false AND LeadId != null AND campaign.IsActive = true';
               sQuery +=' AND Campaign.MX_SB_VTS_FamiliaProducto_Proveedor__r.MX_SB_VTS_Identificador_Proveedor__c=: tempProvedor';
        if(String.isNotBlank(cadena)) {
            sQuery = sQuery + cadena;
        }
        List < CampaignMember > lstOfRecords = Database.query(sQuery);//NOSONAR
        for (CampaignMember obj: lstOfRecords) {
            lstOfCampaign.add(obj);
        }
        return lstOfCampaign;
        } catch(QueryException err) {
            throw new AuraHandledException(Label.MX_WB_ERROR + '\nMensaje: ' + err.getMessage() + '\nLinea: ' + err.getLineNumber() + err);
        }
    }

    /*13-01-2019 Función: Regresa la consulta de las etiquetas de un customsetting que sirve para el filtrado de los miembros de campañas
    *Karen Belem Sanchez Ruiz*/
    @AuraEnabled
    public static  List<String> getListSettings(String Segmentado) {
    try {
        final Boolean Segmentado_tem = Boolean.valueOf(Segmentado);
        final List<String> AllLabels = new List<String>();
        if(Segmentado_tem) {
            for(MX_SB_VTS_Generica__c gemtemp: Generica) {
                 AllLabels.add(gemtemp.MX_SB_VTS_FiltroCampanaLabel__c);
            }
        } else {
            final String type = Label.MX_WB_camposFiltrados;
            final Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
            final Schema.SObjectType leadSchema = schemaMap.get(type);
            final Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();
            for (String fieldName: fieldMap.keySet()) {
                if(fieldMap.get(fieldName).getDescribe().isCustom()) {
                    AllLabels.add(fieldMap.get(fieldName).getDescribe().getLabel());
                }
            }
        }
        return AllLabels;
        } catch(QueryException qError) {
            throw new AuraHandledException(Label.MX_WB_ERROR + '\nMensaje: ' + qError.getMessage() + '\nLinea: ' + qError.getLineNumber() + qError);
        }
    }

    /*13-01-2019 Función: Regresa la cadena que se selecciona para filtrar los miembros que se enviarán a CTI
    *Karen Belem Sanchez Ruiz*/
    @AuraEnabled
    public static String getListFilter(String field, String selectedOperator, String addValue, String Segmentado) {
    try {
        final Boolean Segmentadotem = Boolean.valueOf(Segmentado);
        Boolean limitado = false;
        if(Segmentadotem) {
           limitado=Segmentadotemtrue(selectedOperator,  addValue,field);
        } else {
          limitado= Segmentadotemfalse(selectedOperator,  addValue,field);
        }
        if(limitado == true) {
            cadena1 = cadena1 + ' LIMIT '+ addValue;
        }
        return cadena1;
        } catch(QueryException qError) {
            throw new AuraHandledException(Label.MX_WB_ERROR + '\nMensaje: ' + qError.getMessage() + '\nLinea: ' + qError.getLineNumber() + qError);
        }
    }

    /*Función: Regresa la query consultada.*/
    public static String cadenresp(String cadena1, String selectedOperator, String sKeyApiValue, String addValue) {
         String cadena1temp;
         switch on selectedOperator {
                    when 'CONTAINS' {
                        cadena1temp = cadena1 + ' AND Lead.'+sKeyApiValue+' LIKE \'%'+addValue+'%\'';
                    }
                    when 'NOT(CONTAINS)' {
                        cadena1temp = cadena1 + ' AND (NOT Lead.'+sKeyApiValue+' LIKE \'%'+addValue+'%\')';
                    }
                    when else {
                        cadena1temp = cadena1 + ' AND Lead.'+sKeyApiValue+' '+selectedOperator+' \''+addValue+'\'';
                    }
                }
                searchFilter.add(cadena1temp);
                return cadena1temp;
    }
    /**
    *
    */
    public static Boolean Segmentadotemtrue(String selectedOperator, String addValue,string field) {
        String sKeyApiValue;
        Boolean limitado = false;
         for(String fieldName: mapGenerica.keySet()) {
                if(field==fieldName) {
                    sKeyApiValue=mapGenerica.get(field);
                    if('limite__c'.equals(sKeyApiValue)) {
                        limitado = true;
                        break;
                    }
                    cadena1= cadenresp(cadena1,selectedOperator,sKeyApiValue,addValue);
                }
            }
            return limitado;
    }
    /**
    *
    */
    public static Boolean Segmentadotemfalse(String selectedOperator, String addValue, String field) {
        String sKeyApiValue;
        Set<String> setKeyApi = new Set<String>();
        Boolean limitado = false;
        final Map<String, String> mapApiLabel= new Map<String, String>();
        final String type = String.valueOf(label.MX_WB_CamposFiltrados);
        final Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        final Schema.SObjectType leadSchema = schemaMap.get(type);
        final Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();
         for(String fieldName: fieldMap.keySet()) {
                if(field == fieldMap.get(fieldName).getDescribe().getLabel() ) {
                    mapApiLabel.put(fieldName, fieldMap.get(fieldName).getDescribe().getLabel());
                    setKeyApi = mapApiLabel.keySet();
                    for(String sKeyApi:setKeyApi) {
                        sKeyApiValue = sKeyApi;
                    }
                    if('limite__c'.equals(sKeyApiValue)) {
                        limitado = true;
                        break;
                    }
                cadena1= cadenresp(cadena1,selectedOperator,sKeyApiValue,addValue);
                }
            }
            return limitado;
    }
    @AuraEnabled
    /* funcion lstLeadEnviarCTI */
    public static Boolean lstLeadEnviarCTI(List<CampaignMember> searchResult,Boolean Segmentado, String fechaHora, String bandeja) {
        Boolean ret = true;
        try {
        if(Segmentado) {
            lstLeadEnviarSmart(searchResult, fechaHora, bandeja);
        } else {
            lstLeadEnviarCTIe(searchResult);
        }
        } catch(DmlException e) {
            ret = false;
            throw new AuraHandledException(Label.MX_WB_ERROR + '\nMensaje: ' + e.getMessage() + '\nLinea: ' + e.getLineNumber() + e);
        }
        return ret;
    }

    /*13-01-2019 Función: función que sirve para hacer el envio a la funcion futura ftProcesaSol
    *Karen Belem Sanchez Ruiz*/
    public static Boolean lstLeadEnviarCTIe(List<CampaignMember> searchResult) {
        try {
        final Lead objLead = new Lead();
        final Date fechaEnvio = Date.today();
        final List<Sobject> ListUpdate = new List<Sobject>();
        for(CampaignMember camp : searchResult ) {

            objLead.Id = camp.LeadId;
            objLead.Folio_Cotizacion__c = String.ISBLANK(camp.Lead.Folio_Cotizacion__c) ? '' : camp.Lead.Folio_Cotizacion__c;
            objLead.Producto_Interes__c = camp.Lead.Producto_Interes__c == null ? '' : camp.Lead.Producto_Interes__c;
            objLead.OwnerId = camp.Lead.OwnerId;
            objLead.FirstName = camp.Lead.FirstName;
            objLead.MX_WB_ph_Telefono1__c = camp.Lead.MX_WB_ph_Telefono1__c;
            objLead.MX_WB_ph_Telefono2__c = camp.Lead.MX_WB_ph_Telefono2__c;
            objLead.MX_WB_ph_Telefono3__c = camp.Lead.MX_WB_ph_Telefono3__c;

            MX_WB_CTI_cls.ftProcesaSol(String.valueOf(objLead.Id),
                                          String.valueOf(objLead.Folio_Cotizacion__c),
                                          'ASD',
                                          String.valueOf(objLead.OwnerId),
                                          String.valueOf(objLead.FirstName),
                                          String.valueOf(objLead.MX_WB_ph_Telefono1__c), SOBJECTO, 3,
                                          String.valueOf(objLead.MX_WB_ph_Telefono2__c),String.valueOf(objLead.MX_WB_ph_Telefono3__c));
            objLead.MX_WB_EnvioCTI__c = fechaEnvio;
            objLead.MX_WB_TM_Congelado__c = true;
            if(ListUpdate.contains(objLead)==false) {
            	ListUpdate.add(objLead);
            }
        }
            update ListUpdate;
        return true;
        } catch(QueryException qError) {
            throw new AuraHandledException(Label.MX_WB_ERROR + '\nMensaje: ' + qError.getMessage() + '\nLinea: ' + qError.getLineNumber() + qError);
        }
    }
     @AuraEnabled
     /* Funcion fetchLookUpValues */
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName) {
        final String searchKeyForm = searchKeyWord + '%';
        final List < sObject > returnList = new List < sObject > ();
        final String USerID =UserInfo.getUserId();
        final String tempProvedor= [Select MX_SB_VTS_ProveedorCTI__c from user where id =:USerID].MX_SB_VTS_ProveedorCTI__c;
        String sQuery = 'SELECT name,campaign.Id, campaign.Name FROM CampaignMember WHERE campaign.Name LIKE: searchKeyForm';
               sQuery +=' AND lead.MX_WB_Convertido__c = false AND lead.MX_WB_TM_Congelado__c = false AND LeadId != null AND campaign.IsActive = true';
               sQuery +=' AND Campaign.MX_SB_VTS_FamiliaProducto_Proveedor__r.MX_SB_VTS_Identificador_Proveedor__c=: tempProvedor order by createdDate DESC limit 5';
        final List < CampaignMember > lstOfRecords = Database.query(sQuery);
        for (CampaignMember obj: lstOfRecords) {
            final Campaign temcamp = new Campaign(Name=obj.campaign.Name,Id=obj.campaign.Id);
            returnList.add(temcamp);
        }
        return returnList;
    }
    /* Función  lstLeadEnviarSmart */
    public static Boolean lstLeadEnviarSmart(List<CampaignMember> searchResult, String fechaHora, String bandeja) {
        final List<Lead> Litstsend = new List<lead>();
        final Date fechaEnvio = Date.today();
        boolean ret = false;
        for(CampaignMember camp : searchResult ) {
            final Lead lobjLead  =new Lead();
            lobjLead.Id = camp.LeadId;
            lobjLead.Folio_Cotizacion__c = String.ISBLANK(camp.Lead.Folio_Cotizacion__c) ? '' : camp.Lead.Folio_Cotizacion__c;
            lobjLead.Producto_Interes__c = camp.Lead.Producto_Interes__c == null ? '' : camp.Lead.Producto_Interes__c;
            lobjLead.OwnerId = camp.Lead.OwnerId;
            lobjLead.FirstName = camp.Lead.FirstName;
            lobjLead.MX_WB_ph_Telefono1__c = camp.Lead.MX_WB_ph_Telefono1__c;
            lobjLead.MX_WB_ph_Telefono2__c = camp.Lead.MX_WB_ph_Telefono2__c;
            lobjLead.MX_WB_ph_Telefono3__c = camp.Lead.MX_WB_ph_Telefono3__c;
            lobjLead.MX_WB_EnvioCTI__c = fechaEnvio;
            lobjLead.MX_WB_TM_Congelado__c = true;
            Litstsend.add(lobjLead);
        }
        try {
            String strFecha = fechaHora.replace('T', ' ');
            strFecha = strFecha.replace('Z', ' ');
	        final datetime dateFormat = Datetime.valueOf(strFecha);
            final String strConvertedDate = dateFormat.format('dd/MM/yyyy HH:mm:ss','America/New_York');
            final Map<Id, String> dateData = new Map<Id, String>();
            for(Lead tempLead: Litstsend) {
                dateData.put(tempLead.Id, strConvertedDate);
            }
            MX_SB_VTS_SendLead_helper_cls.EntRegistroGestion_invoke(System.label.MX_SB_VTS_Envio_Lead, Litstsend, '', '2', bandeja, dateData);
            update Litstsend;
            ret= true;
        } catch(Exception e) {
            ret= false;
        }
        return ret;
    }
}