src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scripts_Stage_Product__c.object
<CustomObject>
	<fields>
        <fullName>MX_SB_VTS_OrigenOpp__c</fullName>
        <description>Origen de la Oportunidad, para diferenciar scripts de Inbound</description>
        <label>Origen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call me back</fullName>
                </value>
                <value>
                    <fullName>Tracking Web</fullName>
                </value>
                <value>
                    <fullName>SAC</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound TLMK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>MX_WB_Etapa__c</fullName>
        <label>Etapa</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Políticas</fullName>
                </value>
                <value>
                    <fullName>Cotización</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
                <value>
                    <fullName>Venta Autorizada</fullName>
                </value>
                <value>
                    <fullName>Apertura</fullName>
                </value>
                <value>
                    <fullName>Cierre llamada no contacto</fullName>
                </value>
                <value>
                    <fullName>Información y condiciones</fullName>
                </value>
                <value>
                    <fullName>Venta cerrada</fullName>
                </value>
                <value>
                    <fullName>Cierre de llamada sin venta</fullName>
                </value>
                <value>
                    <fullName>Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Familia de productos a los que se les asociará el script</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Scripts Stages Products</relationshipLabel>
        <relationshipName>Scripts_Stages_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_Script__c</fullName>
        <description>Script que será mostrado al asesor. Este script se visualiza dependiendo la etapa y el producto en el que se encuentre.</description>
        <label>Script</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Scripts Stage Product</label>
    <nameField>
        <label>Nombre de Scripts Stage Campaign</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts Stages Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_ScripLead_cls.cls
/**-------------------------------------------------------------------------
* Nombre: MX_SB_VTS_ScripLead_cls
* @author Arsenio Perez Lopez (xemo)
* Proyecto: MW SB VTS - BBVA 
* Descripción : Clase control para componente MX_SB_VTS_ScripLead

* --------------------------------------------------------------------------
*                         Fecha           Autor                   Desripción
* -------------------------------------------------------------------
* @version 1.0           25/04/2019      Arsenio  Perez            Creación
* @version 1.0           25/04/2019      Eduardo Hernandoez        Creación
* --------------------------------------------------------------------------*/
public without sharing class MX_SB_VTS_ScripLead_cls {
    /**
    * @Method: GetScrip: utilizado para obtener el Scrip en base al lead.
    * @Param: strIdOpportunity- Recibe el Id del lead que se va a consultar.
    */
    @AuraEnabled
    public static String getScript(String strIdOpportunity) {
        Campaign objCampana = null;
        Scripts_Stage_Product__c objScriptStageProduct = null;
        String strScript = '';
        try {
            Lead objOpp = [SELECT Id, LeadSource, RecordType.DeveloperName, Status FROM Lead WHERE Id =: strIdOpportunity];
            if(System.Label.MX_SB_VTS_RecordTypeASD.equals(objOpp.RecordType.DeveloperName) || System.Label.MX_SB_VTS_Telemarketing_LBL.equals(objOpp.RecordType.DeveloperName)) {
                if(System.Label.MX_SB_VTS_InboundLabel.equals(objOpp.LeadSource) || System.Label.MX_SB_VTS_OrigenCallMeBack.equals(objOpp.LeadSource )) {
                    objScriptStageProduct = recuperaScripts(objOpp.Status, objOpp.LeadSource);
                }
            } else if(System.Label.MX_SB_VTS_RecordTypeOut.equals(objOpp.RecordType.DeveloperName)) {
                objScriptStageProduct = recuperaScripts(objOpp.Status, objOpp.LeadSource);
            }
            if(String.isNotBlank(objScriptStageProduct.MX_WB_Script__c)) {
                strScript = objScriptStageProduct.MX_WB_Script__c;
            }
        } catch(QueryException ex) {
            throw new AuraHandledException(Label.MX_WB_lg_TlmktError + ex);
        }
        return strScript;
    }
    /**
     * Retrieves the script from the stage and the id of the product to which it is associated.
     * @param String strStageNameOpp 
     */
    public static Scripts_Stage_Product__c recuperaScripts(String strStageNameOpp, String origen) {
        return [SELECT Id, Name, MX_WB_Etapa__c, MX_WB_FamiliaProductos__c, MX_WB_Script__c
                                 FROM Scripts_Stage_Product__c
                                 WHERE MX_WB_Etapa__c =: strStageNameOpp AND MX_SB_VTS_OrigenOpp__c =: origen];
        
    }
}