src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_FamiliaProducto_Proveedor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Campo relación para filtrar familia de productos autorizada por proveedor</description>
        <inlineHelpText>Ramo al que pertenece la campaña</inlineHelpText>
        <label>Familia de producto</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.MX_SB_VTS_Identificador_Proveedor__c</field>
                <operation>equals</operation>
                <valueField>$User.MX_SB_VTS_ProveedorCTI__c</valueField>
            </filterItems>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.Owner:User.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MX_SB_VTS_FamliaProveedores__c</referenceTo>
        <relationshipLabel>Campañas</relationshipLabel>
        <relationshipName>Campa_as</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/iaso__GBL_Rest_Services_Url__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>iaso__Cache_Partition__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cache Partition</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iaso__Url__c</fullName>
        <description>Url of the Rest service</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <label>Rest Services Url</label>
</CustomObject>

src/objects/MX_SB_VTS_FamliaProveedores__c.object
<CustomObject>
    <description>Objeto intermedio para asignar familias a proveedores</description>
    <fields>
        <fullName>MX_SB_VTS_Identificador_Proveedor__c</fullName>
        <description>Código de proveedor.</description>
        <formula>TEXT(MX_SB_VTS_ProveedorCTI__r.MX_SB_VTS_Identificador_Proveedor__c)</formula>
        <label>Identificador Proveedor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nombre del proveedor.</description>
        <label>ProveedorCTI</label>
        <referenceTo>MX_SB_VTS_ProveedoresCTI__c</referenceTo>
        <relationshipLabel>Familia Productos Proveedores</relationshipLabel>
        <relationshipName>Familia_Productos_Proveedores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Familia Producto Proveedor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Familia Producto Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familia Productos Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_Generica__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista Genérica para múltiples valores del flujo de venta.</description>
    <fields>
        <fullName>MX_SB_VTS_Servicio_ID__c</fullName>
        <description>Identificador Único de Lista de servicios.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Identificador de servicios</inlineHelpText>
        <label>MX_SB_VTS_Servicio_ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Servicio_NameCompleto__c</fullName>
        <description>Nombre y valor del servicio para mostrar en pantallas</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Servicio + Nombre</inlineHelpText>
        <label>MX_SB_VTS_Servicio_NameCompleto</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Servicio_Name__c</fullName>
        <description>Nombre del servicio Nombre valido del servicio.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Nombre del servicio.</inlineHelpText>
        <label>MX_SB_VTS_Servicio_Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Type__c</fullName>
        <description>RecordType for the object
CP1-- Object Quoly to Oli
CP2-- Filtro Campaing
CP3-- Servicios Bandejas
CP4
CP5--Id Salesforce Banquero base al que se asignan las cuentas al no existir un banquero asignado.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>RecordType for the object 
CP1 -- Object Quoly to Oli 
CP2 -- Filtro Campaing 
CP3 -- Servicios Bandejas
CP4 --
CP5--Id Salesforce Banquero base al que se asignan las cuentas al no existir un banquero asignado.</inlineHelpText>
        <label>MX_SB_VTS_Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MX_SB_VTS_Generica</label>
</CustomObject>

src/objects/MX_SB_VTS_ProveedoresCTI__c.object
<CustomObject>
    <description>Objeto para registrar y dar de altas Proveedores de llamadas</description>
    <fields>
        <fullName>MX_SB_VTS_Identificador_Proveedor__c</fullName>
        <description>Identificador único de proveedores</description>
        <inlineHelpText>Seleccione un valor de la lista, si el valor que necesita no existe, por favor delo de alta en la lista global de Proveedores</inlineHelpText>
        <label>Identificador Proveedor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_Lista_Proveedores</valueSetName>
        </valueSet>
    </fields>
    <label>ProveedorCTI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Proveedores</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProveedoresCTI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
     <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <description>Campo para especificar el nombre del proveedor al que esta asignado un usuario</description>
        <label>ProveedorCTI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_Lista_Proveedores</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/MX_SB_VTS_Lista_Proveedores.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ninguno</fullName>
        <default>true</default>
        <label>Ninguno</label>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>VCIP</fullName>
    </customValue>
    <customValue>
        <fullName>SMART CENTER</fullName>
    </customValue>
    <description>Lista de nombres de proveedores</description>
    <masterLabel>Nombres Proveedores</masterLabel>
</GlobalValueSet>

src/classes/MX_SB_VTS_GetListCampa_tst.cls
/**
*
* @author Arsenio Perez Lopez 
* @description API to auto assign leads from Smart Center to call center agents
*
*           No  |     Date     |     Author      |    Description
* @version  1.0    24/06/2019     Arsenio Perez      Create test
* @version  1.0    24/06/2019     Arsenio Perez      Code smell
*
*/
@isTest
public class MX_SB_VTS_GetListCampa_tst {  
	/* Variables globales*/
    static String provedorVcip = 'VCIP', uRLexa='http://www.example.com', urlocal='local.MXSBVTSCache', 
        txtDescri ='DESCRIPCION', txtnombre='Campania PreubaTLMKT3000';
    @TestSetup
    static void makeData() {
        final MX_WB_FamiliaProducto__c testfamilia =  MX_WB_TestData_cls.createProductsFamily('Test Familia');
        insert testFamilia;
        final MX_SB_VTS_ProveedoresCTI__c ProvedorCTI = MX_WB_TestData_cls.ProvedorCTI(provedorVcip);
        ProvedorCTI.MX_SB_VTS_Identificador_Proveedor__c=provedorVcip;
        Insert ProvedorCTI;
        final MX_SB_VTS_FamliaProveedores__c familiaProvedor = MX_WB_TestData_cls.FamiliaProvedores(testFamilia.Id, ProvedorCTI.Id);
        Insert familiaProvedor;
        final Campaign objCampaign = MX_WB_TestData_cls.createCampania(txtnombre);
        objCampaign.MX_SB_VTS_FamiliaProducto_Proveedor__c=familiaProvedor.id;
        insert objCampaign;
    }
    @isTest
    private static void testMethod1() {
        final MX_SB_VTS_Generica__c gen = new MX_SB_VTS_Generica__c (
            Name='Servicio_01',
            MX_SB_VTS_Type__c='CP3',
            MX_SB_VTS_Servicio_ID__c='2',
            MX_SB_VTS_Servicio_Name__c='HOGAR SEGURO',
            MX_SB_VTS_Servicio_NameCompleto__c ='2 HOGAR SEGURO');
        insert gen;
        Test.startTest();
        Boolean teste;
        try {
            MX_SB_VTS_GetListCampa_cls.searchServicios();
            teste = true;
        } catch (Exception w) {
            teste = false;
        }
        system.assert(teste, 'Funciono');
        Test.stopTest();
    }
    @isTest
    private static void testMethod2() {
        Test.startTest();
        Boolean teste;
        try {
            MX_SB_VTS_GetListCampa_cls.searchServicios();
            teste = true;
        } catch (Exception w) {
            teste = false;
        }
        system.assert(teste, 'Funciono');
        Test.stopTest();
    }
    @isTest static void testMethod3() {
        final String sQuery = 'SELECT id, Name FROM Campaign WHERE Name =\''+txtnombre+'\'';
        final List<Campaign> lstCampanias = Database.query(sQuery);
        final User usuarios= MX_WB_TestData_cls.crearUsuario('Usuarioadmin', Label.MX_SB_VTS_ProfileAdmin);
        usuarios.MX_SB_VTS_ProveedorCTI__c=provedorVcip;
        insert usuarios;
        system.runAs(usuarios) {
            Test.startTest();
            if(lstCampanias.isEmpty() == false) {
                final List < Campaign > miembrosCampanias = MX_SB_VTS_GetListCampa_cls.fetchLookUpValues(lstCampanias[0].Name, '');
                System.assertNotEquals(miembrosCampanias.isEmpty(),false,'No se encontraron registros');
            }
            Test.stopTest();
        }
    }    
    @isTest static void testMethod4() {
        final String sQuery = 'SELECT id, Name FROM Campaign WHERE Name =\''+txtnombre+'\'';
        final List<Campaign> lstCampanias = Database.query(sQuery);
        final User usuarios= MX_WB_TestData_cls.crearUsuario('Usuarioadmin', Label.MX_SB_VTS_ProfileAdmin);
        usuarios.MX_SB_VTS_ProveedorCTI__c=provedorVcip;
        insert usuarios;
        system.runAs(usuarios) {
            Test.startTest();
            if(lstCampanias.isEmpty() == false) {
                final List < Object > miembrosCampanias = MX_SB_VTS_GetListCampa_cls.searchBandejas('temps');
                System.assertNotEquals(miembrosCampanias.isEmpty(),false,'No se encontraron registros');
            }
            Test.stopTest();
        }
    }
    @isTest static void testmethodone() {
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenters_Crear_Carga', iaso__Url__c = uRLexa, iaso__Cache_Partition__c = urlocal);
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'Authentication', iaso__Url__c = 'https://validation/ok', iaso__Cache_Partition__c = urlocal);
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenter', iaso__Url__c = 'https://bbvacifrado.smartcenterservicios.com/ws_salesforce_desarrollo/api/login/authenticate', iaso__Cache_Partition__c = urlocal);
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        final User userTest = MX_WB_TestData_cls.crearUsuario('UserOwnerTest01', Label.MX_SB_VTS_ProfileAdmin);
        System.runAs(userTest) {
            Test.startTest();
            final System.HttpRequest req = new System.HttpRequest();
            req.setEndpoint(uRLexa);
            req.setHeader('SERVICEID', '2');
            req.setHeader(txtDescri, txtDescri);
            req.setMethod('POST');
            MX_SB_VTS_GetListCampa_cls.Carga_invoke('2','Prueba generacion 26','nombre',null,null,'DEscr'	);
            final Integer result = 1 + 2;
            System.assertEquals(3, result,'Correcto');
            Test.stopTest();            
        }
    }    
    @isTest static void testmethodsix() {
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenters_Crear_Carga', iaso__Url__c = uRLexa, iaso__Cache_Partition__c = urlocal);
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'Authentication', iaso__Url__c = 'https://validation/ok', iaso__Cache_Partition__c = urlocal);
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenter', iaso__Url__c = 'https://bbvacifrado.smartcenterservicios.com/ws_salesforce_desarrollo/api/login/authenticate', iaso__Cache_Partition__c = urlocal);
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        final User userTest = MX_WB_TestData_cls.crearUsuario('UserOwnerTest01', Label.MX_SB_VTS_ProfileAdmin);
        System.runAs(userTest) {
            Test.startTest();
            try {
                final System.HttpRequest req = new System.HttpRequest();
                req.setEndpoint(uRLexa);
                req.setHeader('SERVICEID', '2');
                req.setHeader(txtDescri, txtDescri);
                req.setMethod('POST');
                MX_SB_VTS_GetListCampa_cls.Carga_invoke(null,null,null,null,null,null);
            } catch(Exception e) {
                system.assert(e.getMessage()!=null,'Correcto');
            }
            Test.stopTest();
        }
    }
}