src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_FamiliaProducto_Proveedor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Campo relación para filtrar familia de productos autorizada por proveedor</description>
        <inlineHelpText>Ramo al que pertenece la campaña</inlineHelpText>
        <label>Familia de producto</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.MX_SB_VTS_Identificador_Proveedor__c</field>
                <operation>equals</operation>
                <valueField>$User.MX_SB_VTS_ProveedorCTI__c</valueField>
            </filterItems>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.Owner:User.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MX_SB_VTS_FamliaProveedores__c</referenceTo>
        <relationshipLabel>Campañas</relationshipLabel>
        <relationshipName>Campa_as</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Campañas</relationshipLabel>
        <relationshipName>Campanas</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_FamliaProveedores__c.object
<CustomObject>
    <description>Objeto intermedio para asignar familias a proveedores</description>
    <fields>
        <fullName>MX_SB_VTS_Familia_de_productos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nombre de la familia de productos.</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Familia Productos Proveedores</relationshipLabel>
        <relationshipName>Familia_Productos_Proveedores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Familia Producto Proveedor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Familia Producto Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familia Productos Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo de relación hacia producto para asociar la oportunidad a un producto específico.</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cotizaciones</relationshipLabel>
        <relationshipName>Cotizaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
	<recordTypes>
        <fullName>MX_WB_RT_Telemarketing</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>Outbound</label>

    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Products (Familia de productos)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_SAC_Proceso__c</fullName>
        <description>Indica a que proceso pertenece cada producto.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Proceso</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Scripts_Stage_Product__c.object
<CustomObject>
	<fields>
        <fullName>MX_WB_Etapa__c</fullName>
        <label>Etapa</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Políticas</fullName>
                </value>
                <value>
                    <fullName>Cotización</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
                <value>
                    <fullName>Venta Autorizada</fullName>
                </value>
                <value>
                    <fullName>Apertura</fullName>
                </value>
                <value>
                    <fullName>Cierre llamada no contacto</fullName>
                </value>
                <value>
                    <fullName>Información y condiciones</fullName>
                </value>
                <value>
                    <fullName>Venta cerrada</fullName>
                </value>
                <value>
                    <fullName>Cierre de llamada sin venta</fullName>
                </value>
                <value>
                    <fullName>Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Familia de productos a los que se les asociará el script</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Scripts Stages Products</relationshipLabel>
        <relationshipName>Scripts_Stages_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_Script__c</fullName>
        <description>Script que será mostrado al asesor. Este script se visualiza dependiendo la etapa y el producto en el que se encuentre.</description>
        <label>Script</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Scripts Stage Product</label>
    <nameField>
        <label>Nombre de Scripts Stage Campaign</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts Stages Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_WB_TelemarketingController_tst.cls
/**-------------------------------------------------------------------------
* Nombre: MX_WB_TelemarketingController
* Autor Alexis Pérez
* Proyecto: MW WB Tlmkt - BBVA Bancomer
* Descripción : Clase de prueba de la clase MX_WB_TelemarketingController.

* --------------------------------------------------------------------------
* Versión       Fecha           Autor                   Desripción<p />
* -------------------------------------------------------------------
* 1.0           06/12/2018      Alexis Pérez		   	Creación
* 2.0           18/05/2019      Jaime Terrats           Se actualiza clase de prueba
* 2.1           24/06/2019      Eduardo Hernández       Fix clase prueba para proceso de producto
* --------------------------------------------------------------------------
*/
@IsTest
public class MX_WB_TelemarketingController_tst {

    /**
     * Return the relevant script based on the opportunity
     * @param String strIdOpportunity
     * @return String The required script.
     */
    @testSetup
    public static void insertData() {
		final String idRecordTypeOppOutbound = [SELECT id from RecordType where Name ='Outbound' AND SObjectType = 'Opportunity'].Id;

        final MX_WB_FamiliaProducto__c objFamProd = new MX_WB_FamiliaProducto__c();
        objFamProd.Name = 'ASD';
        insert objFamProd;

        final MX_SB_VTS_FamliaProveedores__c objFamProdProve = new MX_SB_VTS_FamliaProveedores__c();
        objFamProdProve.MX_SB_VTS_Familia_de_productos__c = objFamProd.Id;
        objFamProdProve.Name = 'ASDvcip';
        insert objFamProdProve;

        final Product2 objProducto = new Product2();
        objProducto.Name = 'TestProductoMinion001';
        objProducto.IsActive = true;
        objProducto.MX_WB_FamiliaProductos__c = objFamProd.Id;
        objProducto.MX_SB_SAC_Proceso__c = 'VTS';
        insert objProducto;

        final Scripts_Stage_Product__c objScriptStageProduct = new Scripts_Stage_Product__c();
        objScriptStageProduct.MX_WB_Etapa__c = 'Contacto Efectivo';
        objScriptStageProduct.MX_WB_FamiliaProductos__c = objFamProd.Id;
        objScriptStageProduct.MX_WB_Script__c = 'MinionTestScript001';
        insert objScriptStageProduct;


        final Date objDTHoy = Date.today();
        final Campaign objCampana = new Campaign();
        objCampana.Name = 'TestMinion001';
        objCampana.IsActive = true;
        objCampana.StartDate = objDThoy;
        objCampana.EndDate = objDTHoy.addDays(30);
        objCampana.MX_WB_FamiliaProductos__c = objFamProd.Id;
        objCampana.MX_SB_VTS_FamiliaProducto_Proveedor__c = objFamProdProve.Id;
        insert objCampana;

        final Opportunity objCotizacion = new Opportunity();
        objCotizacion.Name = 'TestCotizacionMinion001';
        objCotizacion.StageName = 'Contacto Efectivo';
        objCotizacion.CampaignId = objCampana.Id;
        objCotizacion.CloseDate = objDTHoy.addDays(30);
        objCotizacion.RecordTypeId = idRecordTypeOppOutbound;
        objCotizacion.MX_WB_Producto__c=objProducto.Id;
        objCotizacion.Producto__c= 'TestProductoMinion001';
        insert objCotizacion;

        final Product2 objProducto2 = new Product2();
        objProducto2.Name = System.Label.MX_SB_VTS_PRODUCTO_AUTO_DINAMICO_LBL;
        objProducto2.IsActive = true;
        objProducto2.MX_WB_FamiliaProductos__c = objFamProd.Id;
        insert objProducto2;
    }

    @IsTest
    /** 
    */
    public static void TestDatosCorrectos_Marketing() {
        Test.startTest();
        final Opportunity objCotizacion = [SELECT Id FROM Opportunity WHERE Name = 'TestCotizacionMinion001'];
        objCotizacion.RecordTypeId=[Select id from RecordType where DeveloperName ='MX_WB_RT_Telemarketing' AND SObjectType = 'Opportunity'].Id;
        update objCotizacion;
        final String strScript = MX_WB_TelemarketingController.getScript(objCotizacion.Id);
        System.assertEquals('MinionTestScript001', strScript, 'Valor esperado');
        Test.stopTest();
    }
    @IsTest
    /** 
    */
    public static void TestDatosCorrectos_asd() {
        Test.startTest();
        final Opportunity objCotizacion = [SELECT Id FROM Opportunity WHERE Name = 'TestCotizacionMinion001'];
        objCotizacion.RecordTypeId=[Select id from RecordType where DeveloperName ='ASD' AND SObjectType = 'Opportunity'].Id;
        update objCotizacion;

        final String strScript = MX_WB_TelemarketingController.getScript(objCotizacion.Id);
        System.assertEquals('MinionTestScript001', strScript, 'Valor esperado');
        Test.stopTest();
    }

    @IsTest
    /** 
    */
    public static void TestExcepcionOpp() {
        Test.startTest();
        try {
            MX_WB_TelemarketingController.getScript('FallId');
        } catch(AuraHandledException ex) {
            ex.setMessage('Script-thrown exception');
            System.assertEquals('Script-thrown exception', ex.getMessage(), 'Testeo de excepcion: Valor esperado');
        }
        Test.stopTest();
    }
}