src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_FamiliaProducto_Proveedor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Campo relación para filtrar familia de productos autorizada por proveedor</description>
        <inlineHelpText>Ramo al que pertenece la campaña</inlineHelpText>
        <label>Familia de producto</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.MX_SB_VTS_Identificador_Proveedor__c</field>
                <operation>equals</operation>
                <valueField>$User.MX_SB_VTS_ProveedorCTI__c</valueField>
            </filterItems>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.Owner:User.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MX_SB_VTS_FamliaProveedores__c</referenceTo>
        <relationshipLabel>Campañas</relationshipLabel>
        <relationshipName>Campa_as</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Campañas</relationshipLabel>
        <relationshipName>Campanas</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_FamliaProveedores__c.object
<CustomObject>
    <description>Objeto intermedio para asignar familias a proveedores</description>
    <fields>
        <fullName>MX_SB_VTS_Familia_de_productos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nombre de la familia de productos.</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Familia Productos Proveedores</relationshipLabel>
        <relationshipName>Familia_Productos_Proveedores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Familia Producto Proveedor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Familia Producto Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familia Productos Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo de relación hacia producto para asociar la oportunidad a un producto específico.</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cotizaciones</relationshipLabel>
        <relationshipName>Cotizaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origen__c</fullName>
        <label>Origen</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Products (Familia de productos)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_SAC_Proceso__c</fullName>
        <description>Indica a que proceso pertenece cada producto.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Proceso</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Scripts_Stage_Product__c.object
<CustomObject>
	<fields>
        <fullName>MX_SB_VTS_OrigenOpp__c</fullName>
        <description>Origen de la Oportunidad, para diferenciar scripts de Inbound</description>
        <label>Origen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call me back</fullName>
                </value>
                <value>
                    <fullName>Tracking Web</fullName>
                </value>
                <value>
                    <fullName>SAC</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound TLMK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>MX_WB_Etapa__c</fullName>
        <label>Etapa</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Políticas</fullName>
                </value>
                <value>
                    <fullName>Cotización</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
                <value>
                    <fullName>Venta Autorizada</fullName>
                </value>
                <value>
                    <fullName>Apertura</fullName>
                </value>
                <value>
                    <fullName>Cierre llamada no contacto</fullName>
                </value>
                <value>
                    <fullName>Información y condiciones</fullName>
                </value>
                <value>
                    <fullName>Venta cerrada</fullName>
                </value>
                <value>
                    <fullName>Cierre de llamada sin venta</fullName>
                </value>
                <value>
                    <fullName>Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Familia de productos a los que se les asociará el script</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Scripts Stages Products</relationshipLabel>
        <relationshipName>Scripts_Stages_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_Script__c</fullName>
        <description>Script que será mostrado al asesor. Este script se visualiza dependiendo la etapa y el producto en el que se encuentre.</description>
        <label>Script</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Scripts Stage Product</label>
    <nameField>
        <label>Nombre de Scripts Stage Campaign</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts Stages Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_WB_TelemarketingController.cls
/**-------------------------------------------------------------------------
* Nombre: MX_WB_TelemarketingController
* Autor Alexis Pérez
* Proyecto: MW WB Tlmkt - BBVA Bancomer
* Descripción : Controller del componente lightning MX_WB_CMP_Telemarketing.

* --------------------------------------------------------------------------
* Versión       Fecha           Autor                   Desripción<p />
* -------------------------------------------------------------------
* 1.0           06/12/2018      Alexis Pérez		   	Creación
* 2.0			05/02/2019		Alexis Pérez			Cambio de producto a familia de producto.
* 2.1		05/02/2019	Eduardo Hernández	Cambio a familia de productos por proveedor para Outbound
* 2.1			23/06/2019		Eduardo Hernandez   	Fix coincidencias de productos
* --------------------------------------------------------------------------
*/
public without sharing class MX_WB_TelemarketingController {

    private MX_WB_TelemarketingController() {}

    /**
     * Return the relevant script based on the opportunity
     * @param String strIdOpportunity
     * @return String The required script.
     */
    @AuraEnabled
    public static String getScript(String strIdOpportunity) {

        Opportunity objOpp = null;
        Campaign objCampana = null;
        Scripts_Stage_Product__c objScriptStageProduct = null;
        String strScript = '';

        try {
            if(String.isNotBlank(strIdOpportunity)) {
                objOpp = [SELECT Id, CampaignId, Producto__c, StageName, Origen__c, LeadSource, RecordTypeId, RecordType.DeveloperName,MX_WB_Producto__c FROM Opportunity WHERE Id =: strIdOpportunity];
                String origen = String.isNotBlank(objOpp.Origen__c) ? objOpp.Origen__c : objOpp.LeadSource;
                if( objOpp.RecordType.DeveloperName.equals(System.Label.MX_SB_VTS_RecordTypeOutOpp) ) {
                    objCampana = recuperaCampana(objOpp.CampaignId);
                    objScriptStageProduct = recuperaScripts(objOpp.StageName, objCampana.MX_SB_VTS_FamiliaProducto_Proveedor__r.MX_SB_VTS_Familia_de_productos__c, origen);
                } else if( objOpp.RecordType.DeveloperName.equals(System.Label.MX_SB_VTS_RecordTypeASD) || objOpp.RecordType.DeveloperName.equals(System.Label.MX_SB_VTS_Telemarketing_LBL)) {
                    String prodCorrectName = MX_SB_VTS_CierreOpp.validacionproducto(objOpp.Producto__c);
                    Product2 product = findCorrectProd(prodCorrectName, objOpp.MX_WB_Producto__c);
                    objScriptStageProduct = recuperaScriptsInbound(objOpp.StageName, product.MX_WB_FamiliaProductos__c, origen);
                }
                if(String.isNotBlank(objScriptStageProduct.MX_WB_Script__c)) {
                    strScript = objScriptStageProduct.MX_WB_Script__c;
                }
            }
        } catch(QueryException ex) {
            throw new AuraHandledException(Label.MX_WB_lg_TlmktError + ex);
        }
        return strScript;
    }

    /**
     * Retrieve a campaign from your id.
     * @param String idCampana
     * @return Campaign The campaign object.
     */
    public static Campaign recuperaCampana(String idCampana) {
        Campaign objCampana = null;
        objCampana = [SELECT Id, Name, MX_SB_VTS_FamiliaProducto_Proveedor__r.MX_SB_VTS_Familia_de_productos__c
                      FROM Campaign
                      WHERE Id =: idCampana AND IsActive = true];

        return objCampana;
    }

    /**
     * Retrieves the script from the stage and the id of the product to which it is associated.
     * @param String strStageNameOpp, String strProducto
     * @return Scripts_Stage_Product__c The Scripts_Stage_Product__c object.
     */
    public static Scripts_Stage_Product__c recuperaScripts(String strStageNameOpp, String strFamProducto, String origen) {
        Scripts_Stage_Product__c objScriptStageProduct = null;
        objScriptStageProduct = [SELECT Id, Name, MX_WB_Etapa__c, MX_WB_FamiliaProductos__c, MX_WB_Script__c
                                 FROM Scripts_Stage_Product__c
                                 WHERE MX_WB_Etapa__c =: strStageNameOpp AND MX_WB_FamiliaProductos__c =: strFamProducto
                                 AND MX_SB_VTS_OrigenOpp__c =: origen];

        return objScriptStageProduct;
    }

     /**
     * Retrieves the script from the stage and the id of the product to which it is associated.
     * @param String strStageNameOpp, String strProducto
     * @return Scripts_Stage_Product__c The Scripts_Stage_Product__c object.
     */
    public static Scripts_Stage_Product__c recuperaScriptsInbound(String strStageNameOpp, String strFamProducto, String origen) {
        return [SELECT Id, Name, MX_WB_Etapa__c, MX_WB_FamiliaProductos__c, MX_WB_Script__c FROM Scripts_Stage_Product__c WHERE MX_WB_Etapa__c =: strStageNameOpp AND MX_WB_FamiliaProductos__c =: strFamProducto AND MX_SB_VTS_OrigenOpp__c =: origen];
    }

    /**
     * findCorrectProd Recupera registro correcto de productos
     * @param  nameProd nombre correcto
     * @param  prodId   id producto de la oportunidad
     * @return          retorna producto correcto
     */
    public static Product2 findCorrectProd(String nameProd, String prodId) {
        Product2 prod = new Product2();
        for(Product2 prods : [Select Id, Name,MX_WB_FamiliaProductos__c from Product2 where (Id =: prodId OR Name =: nameProd) AND MX_SB_SAC_Proceso__c = 'VTS']) {
            if(prods.Name.equals(nameProd)) {
                prod = prods;
            }
        }
        return prod;
    }
}