src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_PYME_Productos__c</fullName>
        <description>Productos Seleccionados para la Oportunidad</description>
        <label>Productos</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agencia Houston Cheques</fullName>
                </value>
                <value>
                    <fullName>Ahorro</fullName>
                </value>
                <value>
                    <fullName>Ahorro Liquido</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aplinet</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Financiero</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Puro</fullName>
                </value>
                <value>
                    <fullName>Asset Management Gestión Terceros</fullName>
                </value>
                <value>
                    <fullName>Asset Management Previsión Social</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Auto Flotilla Única</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bancomer.com</fullName>
                </value>
                <value>
                    <fullName>Bancomer Net Cash</fullName>
                </value>
                <value>
                    <fullName>Bonds (Garantías)</fullName>
                </value>
                <value>
                    <fullName>Cadenas NAFIN</fullName>
                </value>
                <value>
                    <fullName>Cajeros Automáticos (ATMs)</fullName>
                </value>
                <value>
                    <fullName>Cambios</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito PyME</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Cheques</fullName>
                </value>
                <value>
                    <fullName>Cheques cuenta de grupo / GL</fullName>
                </value>
                <value>
                    <fullName>Ciclos de Vida/ Previsión Social</fullName>
                </value>
                <value>
                    <fullName>CIE Electrónico</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE Ventanilla</fullName>
                </value>
                <value>
                    <fullName>Cobertura/Renta Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cond__Account_Campaign__c.object
<CustomObject>
    <description>Junction object to relate Campaigns with Clients</description>
    <fields>
        <fullName>MX_PYME_RelOpp__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Numero de oportunidades relacionadas con la campaña del Cliente</description>
        <label>Oportunidades Relacionadas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Campaign</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Campaigns</pluralLabel>
    <recordTypes>
        <fullName>MX_PYME_Campania_CargadaPrd</fullName>
        <active>true</active>
        <label>Campaña con Productos</label>
    </recordTypes>
    <recordTypes>
        <fullName>MX_PYME_ValAccCamp</fullName>
        <active>true</active>
        <description>Campaña PYME Validada</description>
        <label>Campaña Validada</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>cond__participant_campaign_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Campaign</label>
        <referenceTo>cond__Account_Campaign__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_RTL_Producto__c</fullName>
        <description>Listado de los productos dependientes de la familia seleccionada en la oportunidad</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_RTL_Familia__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cuenta en Dólares</fullName>
                </value>
                <value>
                    <fullName>Fondos de Inversión</fullName>
                </value>
                <value>
                    <fullName>Maestra Patrimonial Dólares</fullName>
                </value>
                <value>
                    <fullName>Membresía BP</fullName>
                </value>
                <value>
                    <fullName>Nómina</fullName>
                </value>
                <value>
                    <fullName>Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Producto 21</fullName>
                </value>
                <value>
                    <fullName>MLB</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Consumo</fullName>
                </value>
                <value>
                    <fullName>Hipotecario</fullName>
                </value>
                <value>
                    <fullName>TDC</fullName>
                </value>
                <value>
                    <fullName>PrePaid Forward</fullName>
                </value>
                <value>
                    <fullName>Collares</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Domiciliaciones</fullName>
                </value>
                <value>
                    <fullName>Servicios No Financieros</fullName>
                </value>
                <value>
                    <fullName>Traspaso Patrimonial</fullName>
                </value>
                <value>
                    <fullName>One Team</fullName>
                </value>
                <value>
                    <fullName>Fideicomiso</fullName>
                </value>
                <value>
                    <fullName>Socios Globales</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Gastos Médicos Mayores Indemnizatorio</fullName>
                </value>
                <value>
                    <fullName>Hogar Seguro Plus</fullName>
                </value>
                <value>
                    <fullName>Vida Segura Patrimonial</fullName>
                </value>
                <value>
                    <fullName>Meta Segura</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_PYME_AccCampOpp_Cls.cls
/*******************************************************************************
@Name                   MX_PYME_AccCampOpp_Cls
Desarrollado por:       Indra
@Author                 Ricardo Almanza
@Date                   2019-01-15
Proyecto:               PYME
@Group                  Trigger Oportunidad
*************************************************************************************
@Description            Clase para métodos de trigger de Oportunidad manteniendo relación con AccountCampaign
*************************************************************************************
@Changes                (most recent first)
2019-02-28              Error on comparison making double count of new Opps on AccCamp
2019-02-11              verify Maps to query only when Opps with AccCamp
2019-07-11     Jair Ignacio Gonzalez Gayosso         Se depuro clase con los metodos confirmados en la migracion de bpyp y pymes
/*******************************************************************************/
public with sharing class MX_PYME_AccCampOpp_Cls {

    /** Map de relacion campañas con oportunidades */
    static Map<string,string[]> relAddAccCampOpp = new Map<string,string[]>(),relDelAccCampOpp = new Map<string,string[]>();

    private MX_PYME_AccCampOpp_Cls() {
  	}

    /*
    *@Description   Update AccCamp when adding an Opp related
    *@param         newOpportunity Opp to match relation and identify if new relation
    *@param         oldOpportunity Opp to match relation and identify if new relation
    *@return        void
    *@example       addOppToAccCampaign(newOpportunity, oldOpportunity)
    */
    public static void addOppToAccCampaign(Map<Id,Opportunity> newOpportunity, Map<Id,Opportunity> oldOpportunity) {
        //Map<string,string[]> relAddAccCampOpp = new Map<string,string[]>(),relDelAccCampOpp = new Map<string,string[]>();
        addDelAcc(newOpportunity,oldOpportunity);
        final List<cond__Account_Campaign__c> updDelAccCamp = new List<cond__Account_Campaign__c>(); //NOSONAR
        if(!relDelAccCampOpp.isEmpty()) {
            for(cond__Account_Campaign__c accCampDel  :   [Select id,Name,MX_PYME_RelOpp__c,cond__Campaign_status_approval_type__c,RecordTypeId,cond__campaign_id__c,cond__campaign_id__r.MX_PYME_Productos__c,cond__participant_id__c from cond__Account_Campaign__c where Id =  :  relDelAccCampOpp.keySet()]) {
                accCampDel.MX_PYME_RelOpp__c = accCampDel.MX_PYME_RelOpp__c == null || accCampDel.MX_PYME_RelOpp__c<=1 ? 0 :  accCampDel.MX_PYME_RelOpp__c-1;
                updDelAccCamp.add(accCampDel);
            }
            if(!updDelAccCamp.isEmpty()) {
                update updDelAccCamp;
            }
        }

        //Contar oportunidades y si está en cero poner como aprobada el acc campaign si error opp.addError
        if(!relAddAccCampOpp.isEmpty()) {
            countOppApp(relAddAccCampOpp, newOpportunity);
        }
    }

    /** Agrega Oportunidades a relDelAccCampOpp */
    public static void addDelAcc(Map<Id,Opportunity> newOpportunity, Map<Id,Opportunity> oldOpportunity) {
        String accCampId,oaccCampId;
        string[] opps;
        for(Opportunity opt : newOpportunity.values()) {
            accCampId = opt.cond__participant_campaign_id__c;
            if (oldOpportunity != null) {
                oaccCampId = oldOpportunity.get(opt.Id).cond__participant_campaign_id__c;
            }
            if(String.isNotEmpty(accCampId) && (oldOpportunity == null || !accCampId.equals(oaccCampId))) {
                opps = addAcc(opps, opt, accCampId);
                relAddAccCampOpp.put(accCampId,opps);
            }
            if(String.isNotEmpty(oaccCampId) && !accCampId.equals(oaccCampId)) {
                opps = addDel(opps, opt, oaccCampId);
                relDelAccCampOpp.put(oaccCampId,opps);
            }
        }
    }

    /** Regresa una lista con nuevas oportunidades añadidas para relAddAccCampOpp*/
    public static List<String> addAcc(List<String> opps, Opportunity opt, String accCampId) {
        String[] opps2 = opps == null ? opps : opps.clone();
        opps2 = relAddAccCampOpp.containsKey(accCampId) ? relAddAccCampOpp.get(accCampId) :  new List<string>();
        opps2.add(opt.Id);
        return opps2;
    }

    /** Regresa una lista con nuevas oportunidades añadidas para relDelAccCampOpp*/
    public static List<String> addDel(List<String> opps, Opportunity opt, String oaccCampId) {
        String[] opps2 = opps == null ? opps : opps.clone();
        opps2 = relDelAccCampOpp.containsKey(oaccCampId) ? relDelAccCampOpp.get(oaccCampId) :  new List<string>();
        opps2.add(opt.Id);
        return opps2;
    }

    /** Actualiza las oportunidades */
    public static void countOppApp(Map<string,string[]> relAddAccCampOpp, Map<Id,Opportunity> newOpportunity) {
        List<cond__Account_Campaign__c> updAccCamp = new List<cond__Account_Campaign__c>();
        Opportunity opp;
        String campPrd,oppPrd,campCln,oppCln;
        Boolean err;
        Boolean noClnO,noClnC,diffCam,noPrdO,noPrdCam,diffPrd;
        for(cond__Account_Campaign__c accCamp  :   [Select id,Name,MX_PYME_RelOpp__c,cond__Campaign_status_approval_type__c,RecordTypeId,cond__campaign_id__c,cond__campaign_id__r.MX_PYME_Productos__c,cond__participant_id__c from cond__Account_Campaign__c where Id =  :  relAddAccCampOpp.keySet()]) {
                for(String oppid  :   relAddAccCampOpp.get(accCamp.Id)) {
                    opp = newOpportunity.get(oppid);
                    campPrd = accCamp.cond__campaign_id__r.MX_PYME_Productos__c;
                    oppPrd = opp.MX_RTL_Producto__c;
                    campCln = accCamp.cond__participant_id__c;
                    oppCln = opp.AccountId;
                    noClnO = String.isEmpty(oppCln);
                    noClnC = String.isEmpty(campCln);
                    diffCam = !oppCln.equals(campCln);
                    noPrdO = String.isEmpty(oppPrd);
                    noPrdCam = String.isEmpty(campPrd);
                    diffPrd = (String.isNotEmpty(oppPrd) && !campPrd.containsIgnoreCase(oppPrd));
                    err = (noClnO || noClnC || diffCam || noPrdO || noPrdCam || diffPrd) ? true :  false;
                    if(err) {
                        opp = addErrorOpp(opp,noClnO, noClnC, diffCam, noPrdO, noPrdCam, diffPrd);
                    }
                    if(!err) {
                        updAccCamp = MX_PYME_AccCampTrigHand_Cls.updAccCampaignPls(accCamp,updAccCamp,'MX_PYME_Campania_CargadaPrd','MX_PYME_ValAccCamp');
                    }
                }
            }
            if(!updAccCamp.isEmpty()) {
                update updAccCamp;
            }
    }

    /** Agrega un error a la oportunidad */
    public static Opportunity addErrorOpp(Opportunity opp, Boolean noClnO, Boolean noClnC, Boolean diffCam, Boolean noPrdO, Boolean noPrdCam, Boolean diffPrd) {
        opp.addError(noClnO ? Label.MX_PYME_OppAccErrAccCamp : noClnC ? Label.MX_PYME_AccCampAccErrOpp : diffCam ? Label.MX_PYME_OppAccDifAccCamp : noPrdO ? Label.MX_PYME_OppPrdErrAccCamp : noPrdCam ? Label.MX_PYME_AccCampPrdErrOpp : diffPrd ? Label.MX_PYME_OppPrdDifAccCamp : '');
        return opp;
    }
}