src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>MX_WB_ph_Telefono1__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 1</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono2__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 2</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono3__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 3</label>
    <type>Phone</type>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_WB_Envio4HrsCTI_sch_test.cls
/**
* 
*Creacion de clase MX_WB_Envio4HrsCTI_sch_test
*/
@isTest
public class MX_WB_Envio4HrsCTI_sch_test {

    @testSetup
    static void initData() {
        final MX_WB_FamiliaProducto__c testFamilia = MX_WB_TestData_cls.createProductsFamily('Test Familia');
        insert testFamilia;
        final Campaign testCampaign = MX_WB_TestData_cls.createCampania('Test Camp');
        testCampaign.MX_WB_FamiliaProductos__c = testFamilia.Id;
        insert testCampaign;
        final Lead testLead = MX_WB_TestData_cls.createLead('Test Data');
        testLead.MX_WB_ph_Telefono1__c = '5551040002';
        testLead.MX_WB_ph_Telefono2__c = '5551040003';
        testLead.MX_WB_ph_Telefono3__c = '5551040004';
        testLead.LeadSource = 'Outbound TLMK';
        insert testLead;
        final CampaignMember testMember = MX_WB_TestData_cls.createCampaignMember(testLead.Id, testCampaign.Id);
        insert testMember;
    }

    testMethod static void scheduleTest() {
        Test.StartTest();
        final MX_WB_Envio4HrsCTI_sch sh1 = new MX_WB_Envio4HrsCTI_sch();
        final String sch = '0 0 23 * * ?';
        final String jobId = system.schedule('Test Territory Check', sch, sh1);
        System.assertNotEquals(null, jobId, 'no se ejecuto el chron job');
        Test.stopTest();
    }
}