src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_FamiliaProducto_Proveedor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Campo relación para filtrar familia de productos autorizada por proveedor</description>
        <inlineHelpText>Ramo al que pertenece la campaña</inlineHelpText>
        <label>Familia de producto</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.MX_SB_VTS_Identificador_Proveedor__c</field>
                <operation>equals</operation>
                <valueField>$User.MX_SB_VTS_ProveedorCTI__c</valueField>
            </filterItems>
            <filterItems>
                <field>MX_SB_VTS_FamliaProveedores__c.Owner:User.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MX_SB_VTS_FamliaProveedores__c</referenceTo>
        <relationshipLabel>Campañas</relationshipLabel>
        <relationshipName>Campa_as</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--
-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_FamliaProveedores__c.object
<CustomObject>
    <description>Objeto intermedio para asignar familias a proveedores</description>
    <fields>
        <fullName>MX_SB_VTS_Familia_de_productos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nombre de la familia de productos.</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Familia Productos Proveedores</relationshipLabel>
        <relationshipName>Familia_Productos_Proveedores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Familia Producto Proveedor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Familia Producto Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familia Productos Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_ProveedoresCTI__c.object
<CustomObject>
    <description>Objeto para registrar y dar de altas Proveedores de llamadas</description>
    <label>ProveedorCTI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Proveedores</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProveedoresCTI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_WB_CampaniasNoDuplicadas_tst.cls
/**-------------------------------------------------------------------------
 * Nombre: MX_WB_CampaniasNoDuplicadas_tst
 * Autor Ing. Eduardo Hernandez
 * Proyecto: MW WB Telemarketing - BBVA Bancomer
 * Descripción : Clase Test para el trigger de Campaign
 * --------------------------------------------------------------------------
 * Versión 		Fecha			Autor					Descripción
 * -------------------------------------------------------------------
 * 1.0			13/02/2019		Ing. Eduardo Hernandez	Creación
 * 1.0			13/02/2019		Ing. Eduardo Hernandez	Se cambia el métod0 de assertEquals() ah assert()
 * 1.0			15/02/2018		Eduardo Hernández	 	Downgrade version a 44
 * 1.1          17/04/2019      Arsenio Perez Lopez     Se agrega el metod0 TestTrigger1 para el nuevo modelo de datos.
 * --------------------------------------------------------------------------
 */
@isTest
private class  MX_WB_CampaniasNoDuplicadas_tst {

    
    @TestSetup
    static void makeData() {
        final MX_WB_FamiliaProducto__c testfamilia =  MX_WB_TestData_cls.createProductsFamily('Test Familia');
        insert testFamilia;
        Final MX_SB_VTS_ProveedoresCTI__c provedorCTI = MX_WB_TestData_cls.ProvedorCTI('Provedor');
        Insert ProvedorCTI;
        final MX_SB_VTS_FamliaProveedores__c familiaProvedor = MX_WB_TestData_cls.FamiliaProvedores(testFamilia.Id, provedorCTI.Id);
        Insert familiaProvedor;
    }

    @isTest
    private static void newCampaign() {
        final Campaign testCampaign = MX_WB_TestData_cls.createCampania('Test Camp');
        testCampaign.MX_WB_FamiliaProductos__c =[Select id from MX_WB_FamiliaProducto__c where name = 'Test Familia' limit 1].Id;
        insert testCampaign;
     	final Lead testLead = MX_WB_TestData_cls.createLead('Test Data');
        testLead.LeadSource = 'Outbound TLMK';
     	insert testLead;
        Test.startTest();
        	final CampaignMember testMember = MX_WB_TestData_cls.createCampaignMember(testLead.Id, testCampaign.Id);
            database.insert (testMember, false);
        	System.assert(!String.isBlank(testMember.Id));
        Test.stopTest();
    }
        
    @isTest
    private static void secondNewUpdate() {
        Test.startTest();
        	final Campaign camp = new Campaign();
            Id campId = [Select id from MX_WB_FamiliaProducto__c where name = 'Test Familia' limit 1].Id;
        	camp.Name = 'TestCampaign';
        	camp.IsActive = true;
        	camp.MX_WB_FamiliaProductos__c = campId;
        	camp.StartDate = system.date.Today();
        	camp.EndDate = system.date.Today();
        	insert camp;
            final Campaign testCampaign = MX_WB_TestData_cls.createCampania('Test Camp');
            testCampaign.MX_WB_FamiliaProductos__c = campId;
        	testCampaign.IsActive = true;
            insert testCampaign;
            final Lead testLead = MX_WB_TestData_cls.createLead('Test Data');
            testLead.LeadSource = 'Outbound TLMK';
            insert testLead;
        	MX_WB_TestData_cls.createCampaignMember(testLead.Id, testCampaign.Id);
        	final Campaign testCampaign2 = MX_WB_TestData_cls.createCampania('Test Camp 2');
            testCampaign.MX_WB_FamiliaProductos__c = campId;
            insert testCampaign2;
        	camp.IsActive = true;
        	update camp;
        	System.assert(!String.isBlank(camp.Id));
        Test.stopTest();
    }
    /**
        Test para validar EL funcionamiento del triger de campaing bajo creacion modificacion
        con leads creados activando y desactivando. para el nuevo paradigma del modelo de datos.
     */
    @istest private static void testTrigger1() {
        Test.startTest();
            final Campaign camp = new Campaign();
            Id fampId = [Select id from MX_WB_FamiliaProducto__c where name = 'Test Familia' limit 1].Id;
            Id famProv = [Select id from MX_SB_VTS_FamliaProveedores__c where MX_SB_VTS_Familia_de_productos__c =:fampId limit 1].Id;
        	camp.Name = 'TestCampaign';
        	camp.IsActive = true;
        	camp.MX_WB_FamiliaProductos__c = fampId;
            camp.MX_SB_VTS_FamiliaProducto_Proveedor__c= famProv;
        	camp.StartDate = system.date.Today();
        	camp.EndDate = system.date.Today();
        	insert camp;
            final Campaign testCampaign = MX_WB_TestData_cls.createCampania('Test Camp');
            testCampaign.MX_WB_FamiliaProductos__c = fampId;
            testCampaign.MX_SB_VTS_FamiliaProducto_Proveedor__c= famProv;
        	testCampaign.IsActive = true;
            insert testCampaign;
            final Lead testLead = MX_WB_TestData_cls.createLead('Test Data');
            testLead.LeadSource = 'Outbound TLMK';
            insert testLead;
        	final CampaignMember campmem =MX_WB_TestData_cls.createCampaignMember(testLead.Id, testCampaign.Id);
            insert campmem;
        	final Campaign testCampaign2 = MX_WB_TestData_cls.createCampania('Test Camp 2');
            testCampaign2.MX_WB_FamiliaProductos__c = fampId;
            testCampaign2.MX_SB_VTS_FamiliaProducto_Proveedor__c= famProv;
            insert testCampaign2;
        	camp.IsActive = true;
        	update camp;
            System.assert(camp.IsActive);
        Test.stopTest();
    }
}