src/objects/Case.object
<CustomObject>
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <fields>
        <fullName>MX_SB_SAC_Contrato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación con el objeto de Contratos</description>
        <label>Contrato</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Casos</relationshipLabel>
        <relationshipName>Casos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_SAC_Emisor__c</fullName>
        <description>Se ocupara para identificar el tipo de emisor con el cual nace el caso, se ocupara para el llenado de campo de folio</description>
        <label>Emisor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BMOVIL</fullName>
                </value>
                <value>
                    <fullName>GLOMO</fullName>
                </value>
                <value>
                    <fullName>SAC</fullName>
                </value>
                <value>
                    <fullName>SUCURSAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_SAC_EsCliente__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Campo para identificar un si es cliente o no</description>
        <label>¿Eres cliente seguros BBVA?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_SAC_Estado__c</fullName>
        <label>Estado de la Republica</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Baja California</fullName>
                </value>
                <value>
                    <fullName>Baja California Sur</fullName>
                </value>
                <value>
                    <fullName>Campeche</fullName>
                </value>
                <value>
                    <fullName>Chiapas</fullName>
                </value>
                <value>
                    <fullName>Chihuahua</fullName>
                </value>
                <value>
                    <fullName>Ciudad de México</fullName>
                    <default>true</default>
                    <label>Ciudad de México</label>
                </value>
                <value>
                    <fullName>Coahuila</fullName>
                </value>
                <value>
                    <fullName>Colima</fullName>
                </value>
                <value>
                    <fullName>Durango</fullName>
                </value>
                <value>
                    <fullName>Estado de México</fullName>
                </value>
                <value>
                    <fullName>Guanajuato</fullName>
                </value>
                <value>
                    <fullName>Guerrero</fullName>
                </value>
                <value>
                    <fullName>Hidalgo</fullName>
                </value>
                <value>
                    <fullName>Jalisco</fullName>
                </value>
                <value>
                    <fullName>Michoacán</fullName>
                </value>
                <value>
                    <fullName>Morelos</fullName>
                </value>
                <value>
                    <fullName>Nayarit</fullName>
                </value>
                <value>
                    <fullName>Nuevo León</fullName>
                </value>
                <value>
                    <fullName>Oaxaca</fullName>
                </value>
                <value>
                    <fullName>Puebla</fullName>
                </value>
                <value>
                    <fullName>Querétaro</fullName>
                </value>
                <value>
                    <fullName>Quintana Roo</fullName>
                </value>
                <value>
                    <fullName>San Luis Potosí</fullName>
                </value>
                <value>
                    <fullName>Sinaloa</fullName>
                </value>
                <value>
                    <fullName>Sonora</fullName>
                </value>
                <value>
                    <fullName>Tabasco</fullName>
                </value>
                <value>
                    <fullName>Tamaulipas</fullName>
                </value>
                <value>
                    <fullName>Tlaxcala</fullName>
                </value>
                <value>
                    <fullName>Veracruz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_SAC_TipoContacto__c</fullName>
        <label>Tipo de contacto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apoderado Legal</fullName>
                </value>
                <value>
                    <fullName>Asegurado</fullName>
                </value>
                <value>
                    <fullName>Contratante</fullName>
                </value>
                <value>
                    <fullName>Ejecutivo</fullName>
                </value>
                <value>
                    <fullName>Sucursal</fullName>
                </value>
                <value>
                    <fullName>Tercero</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SiniestroAbierto__c</fullName>
        <label>Siniestro Abierto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sí</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TipoSiniestro__c</fullName>
        <label>Tipo de siniestro</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Colisión</fullName>
                </value>
                <value>
                    <fullName>Cristal</fullName>
                </value>
                <value>
                    <fullName>Robo</fullName>
                </value>
                <value>
                    <fullName>Asistencia Vial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <!--App Casos-->
    <!--App Casos-->
<!--Multiasistencia-->
    <!--Multiasistencia-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MX_SB_SAC_LoginToken__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración personalizada para credenciales de token</description>
    <fields>
        <fullName>Duracion__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Duracion</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pwd__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pwd</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Usr__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Usr</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>MX_SB_SAC_LoginToken</label>
</CustomObject>

src/objects/MX_SB_SAC_ParametrosPoliza__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parámetros para el tipo de búsqueda de Pólizas a Clipert</description>
    <fields>
        <fullName>DescripcionCampos__c</fullName>
        <description>Descripción de los campos que se requiere por tipo de método (tal cual lo pide el json para el body) separados por coma ejemplo (fechaInic, fechaFin)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>DescripcionCampos</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Metodo__c</fullName>
        <description>Descripción del método que permitirá la ejecución del WS a clipert</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Metodo</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>MX_SB_SAC_ParametrosPoliza</label>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>MX_WB_rt_PAcc_Telemarketing</fullName>
        <active>true</active>
        <description>Tipo de registro para el proceso de telemarketing Outbound. Cuentas personales.</description>
        <label>Outbound</label>
    </recordTypes>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Cuenta personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MX_SB_SAC_Proceso__c</fullName>
        <description>Indica a que proceso pertenece cada producto.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Proceso</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_SB_SAC_UtileriasTestCls.cls
/**
* BBVA Next Technologies
* @author           Karen Belem Sanchez Ruiz
* Project:          SB_SAC
* Description:      Clase de utilidad que brinda distintas creaciones de objetos para clases test.
*
* Changes (Version)
* ------------------------------------------------------------------------------------------------
*           No.     Date            Author                  Description
*           -----   ----------      --------------------    --------------------------------------
* @version  1.8     2019-06-13      Ing. Karen Belem Sanchez  Se crea clase
* @version  1.9     2019-06-20      Saúl González Reséndiz    Se agrega métodos para creación de Credenciales
*/
@isTest
public class MX_SB_SAC_UtileriasTestCls {//NOSONAR
    
    /**
    * @Method crearCuenta
    * @param String strName
    * @param String sNameRT
    * @Description Retorna un objeto cliente
    * @return Objeto Account
    **/
    public static Account crearCuenta(String strName, String sNameRT) {
        final Double NoClienteDouble	= Math.random()*10000000;
        final Long NoCliente 			= NoClienteDouble.round();
        final Account cliente           = new Account();
        if(String.isNotBlank(sNameRT) && (sNameRT == 'PersonAccount' || sNameRT == 'MX_WB_rt_PAcc_Telemarketing')) {
            cliente.FirstName           = strName;
            cliente.LastName            = strName;
        } else {
            cliente.Name                = strName;
        }
        cliente.AccountNumber       = String.valueOf(NoCliente);
            if(String.isNotBlank(sNameRT)) {
            cliente.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(sNameRT).getRecordTypeId();
        }
        return cliente;
    }
    
    /**
    * @Method crearContrato
    * @param String cuentaId
    * @param Date startDate
    * @Description Retorna un objeto Contract
    * @return Objeto Contract
    **/
    public static Contract crearContrato(Id cuentaId, Date startDate) {
        final Contract contrato = new Contract();
        contrato.AccountId = cuentaId;
        contrato.startDate = Date.today();
        return contrato;       
    }
    
    /**
    * @Method crearCaso
    * @param String cuentaId
    * @param Date startDate
    * @Description Retorna un objeto Case
    * @return Objeto Case
    **/
    public static Case crearCaso(Id idOpp) {
        final Case caso = new Case();
        caso.MX_SB_SAC_Contrato__c = idOpp;
        caso.TipoSiniestro__c = 'PROCEDENTE DE PAGO';
        caso.Status = '';   
        caso.MX_SB_SAC_EsCliente__c = false;
        caso.Origin = 'ARCO';
        caso.MX_SB_SAC_Estado__c = 'Aguascalientes';
        caso.MX_SB_SAC_Emisor__c = 'BMOVIL';
        caso.MX_SB_SAC_TipoContacto__c = 'Asegurado';
        caso.Reason = 'Consultas';
        caso.SiniestroAbierto__c = 'No';
        return caso;
    }

    /**
    * @Method crearCredencial
    * @Description Retorna un objeto MX_SB_SAC_LoginToken__c
    * @return Objeto MX_SB_SAC_LoginToken__c
    **/
    public static MX_SB_SAC_LoginToken__c creaCredencial() {
        final MX_SB_SAC_LoginToken__c loginToken = new MX_SB_SAC_LoginToken__c();
        loginToken.Duracion__c = '180';
        loginToken.Pwd__c = '';
        loginToken.Url__c = 'https://www.wibe.com/cotizadores/api/commons/controller/polizas/';
        loginToken.Usr__c = '';
        return loginToken;
    } 

    /**
    * @Method creaCSParametros
    * @Description Retorna un objeto MX_SB_SAC_ParametrosPoliza__c
    * @return Custom Settings MX_SB_SAC_ParametrosPoliza__c
    **/
    public static MX_SB_SAC_ParametrosPoliza__c creaCSParametros() {
        final MX_SB_SAC_ParametrosPoliza__c paramsPoliza = new MX_SB_SAC_ParametrosPoliza__c();
		paramsPoliza.Name='Número Póliza';
        paramsPoliza.DescripcionCampos__c='numeroPoliza';
        paramsPoliza.Metodo__c='obtenerPolizaPorNumeroDePoliza';
        return paramsPoliza;
    }

    /**
    * @Method crea producto
    * @Description Retorna un objeto Product2
    * @return Product2
    **/
    public static Product2 creaProducto() {
        final Product2 product = new Product2();
        product.Name = 'WIBE';
        product.MX_SB_SAC_Proceso__c = 'SAC';
        return product;
    }

}