src/objects/Case.object
<CustomObject>
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <fields>
        <fullName>MX_SB_MLT_AMaternoConductor__c</fullName>
        <description>Apellido Materno del Conductor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Apellido Materno Conductor</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_APaternoConductor__c</fullName>
        <description>Apellido Paterno del Conductor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Apellido Paterno Conductor</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Address__c</fullName>
        <description>Dirección del siniestro</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Dirección</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Area__c</fullName>
        <description>Parametro Área de Claim Center usado de Tarea de Datos</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Área</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_BranchKey__c</fullName>
        <description>Parámetro de clasificiación de Claim Center usado en Tarea de Datos</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MX SB MLT BranchKey</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_BranchName__c</fullName>
        <description>Parametro de clasificiación de Claim Center</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MX SB MLT BranchName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_ClauseNumber__c</fullName>
        <description>Inciso o Certificado de la Póliza</description>
        <label>Inciso / Certificado</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_ColorVehiculo__c</fullName>
        <description>Descripción del Vehículo</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Color de Vehículo</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_ComentariosSiniestro__c</fullName>
        <description>Comentarios del Siniestro</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comentarios</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_CostoCristal__c</fullName>
        <description>Parámetro costo Cristal de Claim Center usado en Tarea de Datos</description>
        <label>Costo Cristal</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_DeclaracionSiniestro__c</fullName>
        <description>Declaración de Siniestro</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Declaración Siniestro</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_DescripcionVehiculo__c</fullName>
        <description>Descripción del Vehículo para Póliza</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Descripción del Vehículo</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Email__c</fullName>
        <description>Correo Electronico del reportante</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Correo Electrónico</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_EstadoCivilConductor__c</fullName>
        <description>Estado civil del condutor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Estado Civil Conductor</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Event__c</fullName>
        <description>Parametro Evento de Claim Center usado en Tarea de Datos</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Evento</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_External_Id__c</fullName>
        <description>Identificador externo</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Identificador Externo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_FechaNacimientoConductor__c</fullName>
        <description>Fecha de Nacimiento del Conductor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Nacimiento Conductor</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_FechaVencimientoLicencia__c</fullName>
        <description>Fecha de vencimiento de licencia del Conductor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Vencimiento Licencia</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_FolioCC__c</fullName>
        <description>Numero de Folio generado por Claim Center</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Folio Claim Center</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_GlassInicidentDate__c</fullName>
        <description>Fecha de Incidente de tipo cristalera</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Incidente</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_GlassInicidentService__c</fullName>
        <description>Fecha de servicio del incidente de cristalera</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Servicio Cristales</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_GlassInicidentTime__c</fullName>
        <description>Hora de incidente de cristalera</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Hora Incidente</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Glass__c</fullName>
        <description>Cristales afectados en siniestro</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cristales Afectados</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_GlasswareKey__c</fullName>
        <description>Código Cristalera</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Clave Cristalera</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_GlasswareName__c</fullName>
        <description>Nombre de Cristalera</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre Cristalera</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_IdService__c</fullName>
        <description>Folio del Servicio</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Identificador del Servicio</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_IdUsuario__c</fullName>
        <description>Id de Usuario</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Identificacdor de Usuario</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_InsuranceCompany__c</fullName>
        <description>Asegurador</description>
        <inlineHelpText>Aseguradora</inlineHelpText>
        <label>Aseguradora</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MX_SB_MLT_Insurance</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_InsuredLastName2__c</fullName>
        <description>Apellido Materno Asegurado</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Apellido Materno</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_InsuredLastName__c</fullName>
        <description>Apellido Paterno de Asegurado</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Apellido Paterno</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_InsuredName__c</fullName>
        <description>Nombre del Asegurado</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_IsVIP__c</fullName>
        <description>¿Es cliente VIP?</description>
        <defaultValue>false</defaultValue>
        <label>Cliente VIP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_LegacySystem__c</fullName>
        <description>Parametro Tipo de Tarea de Claim Center</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Legacy System</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_MarcaCristal__c</fullName>
        <description>Parámetro marca de cristal de Claim Center</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Marca Cristal</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Marca__c</fullName>
        <description>Marca del Vehículo para Póliza</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Marca del Vehículo</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Modelo__c</fullName>
        <description>Modelo del Vehículo de la Póliza</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Modelo de Vehículo</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Motor__c</fullName>
        <description>Número de Serie del Motor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Motor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_NombreConductor__c</fullName>
        <description>Nombre de Conductor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MX SB MLT NombreConductor</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_NumeroLicencia__c</fullName>
        <description>Numero de Licencia del conductor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Licencia</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_NumeroOcupantes__c</fullName>
        <description>Número de Ocupantes del Vehículo</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Ocupantes</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_NumeroSerie__c</fullName>
        <description>Número de serie del vehículo que esta en la Póliza</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Número de Serie</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_OcupacionConductor__c</fullName>
        <description>Ocupacíon del conductor de vehículo</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Ocupación del Conductor</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Phone__c</fullName>
        <description>Teléfono del reportante</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Teléfono</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Placas__c</fullName>
        <description>Placas del Vehículo de la Póliza.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Placas del Vehículo</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_PolizaTD__c</fullName>
        <description>Póliza de Tarea de Datos</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Póliza</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_ProcedenciaCristal__c</fullName>
        <description>Procedencia de Cristal</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Procedencia Cristal</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_RelacionAsegurado__c</fullName>
        <description>Relación de conductor con el asegurado</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Relación Asegurado</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_SegmentClient__c</fullName>
        <description>Segemento del cliente</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Segmento Cliente</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_SexoConductor__c</fullName>
        <description>Sexo del conductor</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Sexo Conductor</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_Subtype__c</fullName>
        <description>Tipo de caso</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Tipo Caso</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_TelefonoCristalera__c</fullName>
        <description>Teléfono de contacto de cristalera</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Teléfono Cristalera</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_TipoAuto__c</fullName>
        <description>Tipo de Automóvil</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehículo</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_TipoCristal__c</fullName>
        <description>Tipo de Cristal afectado</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Tipo de Cristal</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_MLT_URLLocation__c</fullName>
        <description>Latitud y Longitud</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Coordenadas</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <!--App Casos-->
    <!--App Casos-->
<!--Multiasistencia-->
    <!--Multiasistencia-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <recordTypes>
        <fullName>MX_SB_MLT_TomaReporte</fullName>
        <active>true</active>
        <businessProcess>Siniestros</businessProcess>
        <description>Toma de reportes</description>
        <label>Toma Reporte Siniestro</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/MX_SB_MLT_Insurance.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CONTIGO BANCOMER</fullName>
    </customValue>
    <customValue>
        <fullName>CONTIGO BANCOMER PLUS</fullName>
    </customValue>
    <customValue>
        <fullName>EMPRESA SEGURA BANCOMER</fullName>
    </customValue>
    <customValue>
        <fullName>HOGAR SEGURO PLUS SB</fullName>
    </customValue>
    <customValue>
        <fullName>IVR SEGUROS BANCOMER</fullName>
    </customValue>
    <customValue>
        <fullName>MULTIASISTENCIA</fullName>
    </customValue>
    <customValue>
        <fullName>PENSIONES BANCOMER</fullName>
    </customValue>
    <customValue>
        <fullName>SEGURO CASA HABITACION</fullName>
    </customValue>
    <customValue>
        <fullName>SEGUROS BANCOMER</fullName>
    </customValue>
    <customValue>
        <fullName>SEGUROS PATRIMONIAL</fullName>
    </customValue>
    <customValue>
        <fullName>SEGUROS SALUD</fullName>
    </customValue>
    <description>Aseguradoras</description>
    <masterLabel>Aseguradora</masterLabel>
</GlobalValueSet>

src/classes/MX_SB_MLT_TareaDatosBussines_Cls.cls
/**--------------------------------------------------------------------------------
* Nombre: MX_SB_MLT_TareaDatosBussines_Cls
* Autor Oscar Martínez / Saúl Gonzáles
* Proyecto: Siniestros - BBVA Bancomer
* Descripción : Lógica de negocio para parsear los objetos json de Claim Center
* --------------------------------------------------------------------------------
* Versión       Fecha          Autor                                    Descripción
* --------------------------------------------------------------------------------
* 1.0           15/04/2019     Oscar Martínez / Saúl Gonzáles           Creación
* 1.1           26/04/2019     Oscar Martínez                           Se inserta el caso y se asigna a una cola
* 1.2           07/05/2019     Oscar Martínez                           Se refactoriza la clase para obtener los parámetros del Json mediante un mapa
* 1.3           29/08/2019     Daniel Goncalves Vivas                   Se agrega campo LegacySystem
* 1.4           20/09/2019     Daniel Goncalves Vivas                   Se corrigen typos
* 1.5           24/09/2019     Daniel Goncalves Vivas                  	Se elimina variable en desuso, se cambia condición de Costo Cristal
* 1.6			27/08/2019	   Angel Nava                               mapeo de idservicio ARCA
* 1.7			30/09/2019	   Angel Nava								NOSONAR para método con complejidad alta
* 1.8           30/09/2019     Daniel Goncalves Vivas                   Se cambian nombre de variables largos
* 1.9           08/10/2019     Daniel Goncalves Vivas                   Se agrega mapeo de campos de auto
* 1.10          10/10/2019     Daniel Goncalves Vivas                   Se eliminan llamadas a GetDateGlass
* 1.11		    14/10/2019     Juan Carlos Benitez Herrera	        	Se agrega mapeo de campos de auto
* --------------------------------------------------------------------------------
**/

public without sharing class MX_SB_MLT_TareaDatosBussines_Cls {
    
    /*
    * @description parsea el objeto json y almacena los datos en objetos custom Salesforce.
    * @param String json
    * @return String strResponse
    */
    public Map<String,String> creaObjetoTareaDatos (String strJson) {//NOSONAR
        final Map<String, Object> mapJson = (Map<String, Object>) JSON.deserializeUntyped(strJson);
        final Case casoTareaDatos = new Case();
        casoTareaDatos.MX_SB_MLT_Area__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('area'));
        casoTareaDatos.MX_SB_MLT_BranchName__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('branchName'));     
        casoTareaDatos.MX_SB_MLT_InsuranceCompany__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('company')).toUpperCase();
        casoTareaDatos.MX_SB_MLT_Email__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('email'));
        casoTareaDatos.MX_SB_MLT_Glass__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('glass'));        
        casoTareaDatos.MX_SB_MLT_IsVIP__c =  (Boolean) (mapJson.get('isVIP') == null ? false : true);       
        casoTareaDatos.MX_SB_MLT_Phone__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('phone'));           
        casoTareaDatos.MX_SB_MLT_UrlLocation__c =  String.isEmpty((String)mapJson.get('urlLocation')) ? Label.MX_SB_MLT_LATLONG : (String)mapJson.get('urlLocation');
        casoTareaDatos.RecordTypeId = recuperaTipoRegistro('MX_SB_MLT_TomaReporte');
        casoTareaDatos.MX_SB_MLT_Subtype__c = MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('subtype'));
        casoTareaDatos.Origin ='Web';
        casoTareaDatos.MX_SB_MLT_LegacySystem__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('legacySystem'));
        casoTareaDatos.MX_SB_MLT_SegmentClient__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('segmentClient'));
        casoTareaDatos.MX_SB_MLT_NumeroSerie__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('numeroSerie'));
        casoTareaDatos.MX_SB_MLT_Motor__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('numeroMotor'));
        casoTareaDatos.MX_SB_MLT_PolizaTD__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('policyNumber'));
        casoTareaDatos.MX_SB_MLT_TipoAuto__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('vehicleDescription'));
        casoTareaDatos.MX_SB_MLT_ColorVehiculo__c =   MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('vehicleColor'));
        casoTareaDatos.MX_SB_MLT_ClauseNumber__c =  (Integer)mapJson.get('clauseNumber');
        casoTareaDatos.MX_SB_MLT_DescripcionVehiculo__c =   MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('vehicleDescription'));
        casoTareaDatos.MX_SB_MLT_Marca__c =   MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('make'));
        casoTareaDatos.MX_SB_MLT_Modelo__c =   MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('model'));
        casoTareaDatos.MX_SB_MLT_Placas__c =   MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('licensePlate'));

        final Integer idServicio = mapJson.get('idServicio')== null ? 0: (Integer)mapJson.get('idServicio');
        casoTareaDatos.MX_SB_MLT_Event__c = MX_SB_MLT_TareaDatosUtils_Cls.validaEvent(casoTareaDatos.MX_SB_MLT_LegacySystem__c,MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)mapJson.get('event')),idServicio);
        final String [] latLong =  casoTareaDatos.MX_SB_MLT_UrlLocation__c.split(',');
        if (!latLong.isEmpty() && !Test.isRunningTest()) {
            casoTareaDatos.MX_SB_MLT_Address__c = obtieneDireccionMapa(MX_SB_MLT_GoogleGeolocation_Cls.getReverseGeocode(latLong[0],latLong[1]));
        }
        final Map<String,String> mapResponse =  new  Map<String,String>();
        AssignmentRule assignRule = new AssignmentRule(); 
        assignRule = [select id from AssignmentRule where SobjectType = 'Case' and Name ='Siniestros' and Active = true limit 1];           
        final Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.assignmentRuleId= assignRule.id;
        casoTareaDatos.setOptions(dmlOpts);     
        
        insert casoTareaDatos ;
        final Case casoTareaDatosUp = creaObjetoTareaDatos(mapJson);
        casoTareaDatosUp.Id = casoTareaDatos.Id;
        upsert casoTareaDatosUp;        
        
        mapResponse.put('respuesta', Label.MX_SB_MLT_ExitoTDT);
        mapResponse.put('error','');
        mapResponse.put('idSalesforce',casoTareaDatos.Id);
        return mapResponse;
    }

    /*
    * @description parsea el objeto json y almacena los datos en objetos custom Salesforce.
    * @param String jsonMapReq
    * @param String casoReq
    * @return String strResponse
    */
    public static Case creaObjetoTareaDatos (Map<String,Object> jsonMapReq) {
        final Case caseResp = new Case();
        caseResp.MX_SB_MLT_AMaternoConductor__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('aMaternoConductor'));
        caseResp.MX_SB_MLT_APaternoConductor__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('aPaternoConductor'));
        caseResp.MX_SB_MLT_BranchKey__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('branchKey'));
        caseResp.MX_SB_MLT_ComentariosSiniestro__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('comentariosSiniestro'));
        caseResp.MX_SB_MLT_DeclaracionSiniestro__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('declaracionSiniestro'));
        caseResp.MX_SB_MLT_EstadoCivilConductor__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('estadoCivilConductor'));
        caseResp.MX_SB_MLT_FechaNacimientoConductor__c =  MX_SB_MLT_TareaDatosUtils_Cls.getDate((String)jsonMapReq.get('fechaNacimientoConductor'));
        caseResp.MX_SB_MLT_FechaVencimientoLicencia__c =  MX_SB_MLT_TareaDatosUtils_Cls.getDate((String)jsonMapReq.get('fechaVencimientoLicencia'));
        caseResp.MX_SB_MLT_GlassInicidentTime__c =  MX_SB_MLT_TareaDatosUtils_Cls.getTimeGlass((String)jsonMapReq.get('glassIncidentTime'),(String)jsonMapReq.get('glassInicidentDate'));
        caseResp.MX_SB_MLT_GlassInicidentDate__c =  MX_SB_MLT_TareaDatosUtils_Cls.getDate((String)jsonMapReq.get('glassInicidentDate'));
        caseResp.MX_SB_MLT_GlassInicidentService__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('glassIncidentService'));
        caseResp.MX_SB_MLT_GlasswareKey__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('glasswareKey'));
        caseResp.MX_SB_MLT_GlasswareName__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('glasswareName'));
        caseResp.MX_SB_MLT_External_Id__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('id'));
        caseResp.MX_SB_MLT_InsuredLastName__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('insuredLastName'));
        caseResp.MX_SB_MLT_InsuredLastName2__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('insuredLastName2'));
        caseResp.MX_SB_MLT_InsuredName__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('insuredName'));
        caseResp.MX_SB_MLT_NombreConductor__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('nombreConductor'));
        caseResp.MX_SB_MLT_NumeroLicencia__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('numeroLicencia'));
        caseResp.MX_SB_MLT_NumeroOcupantes__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('numeroOcupantes'));
        caseResp.MX_SB_MLT_OcupacionConductor__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('ocupacionConductor'));
        caseResp.MX_SB_MLT_RelacionAsegurado__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('relacionAsegurado'));
        caseResp.MX_SB_MLT_SexoConductor__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('sexoConductor'));
        caseResp.MX_SB_MLT_TelefonoCristalera__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('telefonoCristalera'));
        caseResp.MX_SB_MLT_IdUsuario__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('idUsuario'));
        caseResp.MX_SB_MLT_CostoCristal__c =  jsonMapReq.get('costoCristal')== null ? 0.00 : MX_SB_MLT_TareaDatosUtils_Cls.validaDatoDecimalVacio((String)jsonMapReq.get('costoCristal'));
        caseResp.MX_SB_MLT_MarcaCristal__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('marcaCristal'));
        caseResp.MX_SB_MLT_ProcedenciaCristal__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('procedenciaCristal'));
        caseResp.MX_SB_MLT_TipoCristal__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('tipoCristal '));
        caseResp.MX_SB_MLT_FolioCC__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('folioCC'));
        final Integer servicioInt = jsonMapReq.get('idServicio')== null ? 0 : (Integer)jsonMapReq.get('idServicio');
        final String servicioStr = String.valueOf(servicioInt);
        caseResp.MX_SB_MLT_IdService__c =  servicioStr;
        caseResp.MX_SB_MLT_EstatusSolicitud__c =  (Integer)jsonMapReq.get('estatusSolicitud');
        caseResp.MX_SB_MLT_FechaRegistro__c =  MX_SB_MLT_TareaDatosUtils_Cls.getDate((String)jsonMapReq.get('fechaRegistro'));
        caseResp.MX_SB_MLT_Mensaje__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('mensaje'));
        caseResp.MX_SB_MLT_Mensaje2__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('mensaje2'));
        caseResp.MX_SB_MLT_MensajePDA__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('mensajePDA'));
        caseResp.MX_SB_MLT_MensajePDA2__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('mensajePDA2'));
        caseResp.MX_SB_MLT_Observaciones__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('observaciones'));
        caseResp.MX_SB_MLT_ObservacionesPDA__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('observacionesPDA'));
        caseResp.MX_SB_MLT_ClaimNumber__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('claimNumber'));
        caseResp.MX_SB_MLT_NombreTercero__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('nombreTercero'));
        caseResp.MX_SB_MLT_Origen__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('origen'));
        caseResp.MX_SB_MLT_Telefono__c =  MX_SB_MLT_TareaDatosUtils_Cls.validaDatoVacio((String)jsonMapReq.get('telefono'));
        return caseResp;
    }

    /*
    * @description Method privado que recupera el tipo de registro adecuado para la tarea de datos
    * @param String strDevName
    * @return String strTipoRegistro
    */
    private static String recuperaTipoRegistro(String strDevName) {
        String strTipoRegistro = '';
        final RecordType recordT =[SELECT Id FROM RecordType WHERE SobjectType = 'Case' And DeveloperName =:strDevName];
        strTipoRegistro = recordT.Id;
        return strTipoRegistro;
    }

    /*
    * @description Method privado que recupera la dirección del mapa de google.
    * @param HttpResponse res
    * @return String strDireccion
    */
    private static String obtieneDireccionMapa(HttpResponse res) {
        String strDireccion = '';
        final Map<String,Object> mapGr = (Map<String,Object>)JSON.deserializeUntyped(res.getBody());
        final List<Object> results = (List<Object>)mapGr.get('results');
        if(!results.isEmpty()) {
            final Map<String,Object> firstResult = (Map<String,Object>)results[0];
            strDireccion = (string)firstResult.get('formatted_address');
        }
        return strDireccion ;
    }
}