src/objects/Case.object
<CustomObject>
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <fields>
        <fullName>EU001_fh_Fecha_propuesta_de_cierre__c</fullName>
        <description>Fecha Propuesta de cierre Experiencia única</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha propuesta de cierre</label>
        <type>Date</type>
    </fields>
    <!--App Casos-->
    <!--App Casos-->
<!--Multiasistencia-->
    <!--Multiasistencia-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <recordTypes>
        <fullName>Apoyos</fullName>
        <active>true</active>
        <businessProcess>Apoyos</businessProcess>
        <description>Apoyos experiencia Unica</description>
        <label>Apoyos</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EU001_RI__c.object
<CustomObject>
    <description>Contiene los datos necesarios de la RI para su asociacion con los Compromisos</description>
    <fields>
        <fullName>EG001_Valoracion_de_RI_DO__c</fullName>
        <description>La valoración que el Director de Oficina le da a la RI.</description>
        <label>Valoracion de RI DO</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Bueno</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Muy Bueno</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Excelente</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EG_001_ls_Valoracion_de_RI__c</fullName>
        <label>Valoracion de RI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Bueno</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Muy Bueno</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Excelente</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EU001_fm_UG_Propietario__c</fullName>
        <description>UG del propietario del registro</description>
        <formula>$User.UG__c</formula>
        <label>UG Propietario</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU001_ft_Fecha_Cierre__c</fullName>
        <description>Fecha y hora de termino de la RI</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de Finalización</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EU001_ft_Fecha_Inicio__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Fecha y hora de inicio de la RI</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de Inicio</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EU001_tl_Comentario_DO__c</fullName>
        <description>El comentario que proporciona el Director de Oficina al momento de valorar la RI.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comentario DO</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EU001_tl_Comentario_EV__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comentario EV</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MX_BPP_OwnerEmplNum__c</fullName>
        <formula>Owner:User.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MX_BPP_OwnerEmplNum</label>
        <type>Text</type>
    </fields>
    <label>Reunión Individual</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>No RI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reunión Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExpUni_Tablero_Grupal__c.object
<CustomObject>
    <fields>
        <fullName>EU_001_Un_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_001_nu_Real_Manual__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Campo real para ajuste manual</description>
        <label>Real Manual</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_001_tx_AtributoII__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Atributo II</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_001_tx_Atributo__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Concepto</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_001_tx_Indicador__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Indicador</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_Backlog__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Campo que se llena por mediante una formula  orientada a los montos de las oportunidades</description>
        <label>Backlog</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Busca_Usuario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Busqueda de Usuario Experiencia Única</description>
        <label>Usuario</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tablero_Grupales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EU_Compromiso__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Monto o meta a la que se comprete el Ejecutivo a cubrir en la RI</description>
        <label>Compromiso</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Fe_Act__c</fullName>
        <description>Ultima fecha de actualizacion del Indicador</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fe_Act</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EU_GAP__c</fullName>
        <description>Monto que proviene del Tablero de Gestión</description>
        <label>GAP</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Indicador__c</fullName>
        <description>Indicador que proviene del Tablero de Gestión que define el tipo Cartera que se esta manejando.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Agrupador</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_Logro_Proy_Bklog__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Valor que se tiene como resultado del calculo del Backlog en un tiempo determinado</description>
        <label>Logro_Proy_Bklog</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Logro_Proy_Comp__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Valor que se obtiene en base a un calculo del Logrado Proyectado definido por los Compromisos en un tiempo determinado</description>
        <label>Logro_Proy_Comp</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Logro__c</fullName>
        <description>Valor que proviene del Tablero de Gestión y define el logro alcanzado por el Ejecutivo.</description>
        <label>Valor 2</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Peso__c</fullName>
        <description>Tipo de moneda definido establecido en ese periodo de la generación del Tablero de Gestión</description>
        <label>Peso</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Presupuesto__c</fullName>
        <description>Valor que se obtiene del Tablero de Gestión y es la cantidad que se tiene disponible el Ejecutivo</description>
        <label>Presupuesto</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Puntos__c</fullName>
        <description>Valor que se obtiene del Tablero de Gestión y hace referencia a los puntos acumulados que tiene el Ejecutivo</description>
        <label>Puntos</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_Real__c</fullName>
        <description>Valor que se obtiene del Tablero de Gestión</description>
        <label>Real</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_UG__c</fullName>
        <description>Numero de identificador del usuario</description>
        <encryptionScheme>None</encryptionScheme>
        <label>UG</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_BPP_Codigo_Tablero__c</fullName>
        <description>Nuevo campo para identificar el código para la carga de tablero</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Código Tablero</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_BPP_NumEmpleado__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>MX_BPP_NumEmpleado__c</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MX_BPP_TableroID__c</fullName>
        <description>Nuevo campo para identificar código e identificador de tablero</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>BPyP Identificador Tablero</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MX_BPP_Valor3__c</fullName>
        <label>MX_BPP_Valor3__c</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_BPP_Valor4__c</fullName>
        <label>MX_BPP_Valor4__c</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_BPP_Valor5__c</fullName>
        <label>MX_BPP_Valor5__c</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tablero de Gestión</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Nombre de Tablero Grupal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tablero de Gestión</pluralLabel>
    <recordTypes>
        <fullName>MX_BPP_Cintillo</fullName>
        <active>true</active>
        <label>MX_BPP_Cintillo</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UG__c</fullName>
        <description>Unidad gestora</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>UG</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segmento_Ejecutivo__c</fullName>
        <label>Segmento Ejecutivo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MEDIANA EMPRESA</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVO</fullName>
                </value>
                <value>
                    <fullName>EMPRESARIAL</fullName>
                </value>
                <value>
                    <fullName>FEDERAL</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO RESTO</fullName>
                </value>
                <value>
                    <fullName>GRANDES CUENTAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Liga__c</fullName>
        <label>Liga</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Empresas Platino</fullName>
                </value>
                <value>
                    <fullName>Empresas Diamante</fullName>
                </value>
                <value>
                    <fullName>Empresas Oro</fullName>
                </value>
                <value>
                    <fullName>Empresas Plata</fullName>
                </value>
                <value>
                    <fullName>Empresas Bronce</fullName>
                </value>
                <value>
                    <fullName>Gobierno Platino</fullName>
                </value>
                <value>
                    <fullName>Gobierno Diamante</fullName>
                </value>
                <value>
                    <fullName>Gobierno Oro</fullName>
                </value>
                <value>
                    <fullName>Gobierno Plata</fullName>
                </value>
                <value>
                    <fullName>Gobierno Bronce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_BPP_VistaRI_Ctrl.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     MX_BPP_VistaRI_Ctrl
* @Author   Cindy Hernández cindyarianna.hernandez.nieto.contractor@bbva.com
* @Date     Created: 2019-06-12
* @Group    Digital Workplace Retail
* @Description Get the cases owned by the banker
* @Comments Created from the clipped code from the EU001_cls_ConsolaDirector class
* @Changes
**/

public With Sharing class MX_BPP_VistaRI_Ctrl {

    //Constructor with no arguments
    @TestVisible
    private MX_BPP_VistaRI_Ctrl() {
    }

    /** */
    private static final Integer START_POSITION = 0;
    /** */
    private static final Integer END_POSITION = 3;
    /** */
    private static List<String> equipoDO = new List<String>();
    /** */
    private static List<String> equipoDOUG = new List<String>();
    /** */
    private static List<String> equipoDONC = new List<String>();
    /** */
    private static List<User> equipoDOUSR = new List<User>();
    /** */
    private static List<Decimal> ganaMasEq = new List<Decimal>();

    @AuraEnabled
    /**Metodo updateComentarios */
    public static void updateComentarios(String recordId, String comentario, String evaluador) {
        final Id sesssionOwner = userInfo.getUserId();
        try {
            final EU001_RI__c toUpdate = [SELECT EU001_tl_Comentario_EV__c, EU001_tl_Comentario_DO__c, EG_001_ls_Valoracion_de_RI__c, EG001_Valoracion_de_RI_DO__c, OwnerId FROM EU001_RI__c WHERE id =: recordId];
            if(sesssionOwner == toUpdate.OwnerId) {
                toUpdate.EU001_tl_Comentario_EV__c = comentario;
            } else {
                toUpdate.EU001_tl_Comentario_DO__c = comentario;
            }
            update toUpdate;
            if(toUpdate.EG_001_ls_Valoracion_de_RI__c != null && toUpdate.EG001_Valoracion_de_RI_DO__c != null) {
                MX_BPP_VistaRI_Utilities.updateEstatus(recordId);
            }
            if (Test.isRunningTest()) {
            	throw new DmlException();
            }
        } catch (QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        catch(DmlException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        catch(Exception e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
    }

    /*@Descripción
    *Calcula el Promedio DOR Potencial
    *Metodo Francisco J Licona
    */
    @AuraEnabled
    public static Decimal PromedioPotDOR_DO(String UgUser) {
        Decimal PromDORP = 0;
        Decimal ContPDOR = 0;
        getEsDO(UgUser);
        List<aggregateResult> registrosReporte0 = new List<aggregateResult> ();
        try {
            registrosReporte0 = [SELECT SUM(EU_001_Un_Valor__c)
                                                FROM ExpUni_Tablero_Grupal__c
                                                WHERE EU_UG__c IN :equipoDOUG
                                                AND EU_001_tx_Indicador__c = :EU001_cls_CONSTANTES.EU001_STR_TOTAL_DOR_POTENCIAL GROUP By EU_UG__c];
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        if(!equipoDOUG.isEmpty()) {
            for(aggregateResult tab : registrosReporte0) {
                final String val = String.valueOf(tab.get('expr0'));
                Decimal val0 = Decimal.valueOf(val);
                val0 = val0 > 150.0 ? 150.0 : val0;
                PromDORP = PromDORP + val0;
                ContPDOR++;
            }
            if(ContPDOR>0) {
                PromDORP=PromDORP/ContPDOR;
            } else {
                ContPDOR=0;
            }
        }

        return PromDORP.setScale(1);
    }

    /*@Descripción
    *Calcula el Promedio DOR
    *Metodo Francisco J Licona
    */
    @AuraEnabled
    public static Decimal PromedioDOR_DO(String UgUser) {
        Decimal PromDOR=0;
        Decimal ContDOR=0;
        getEsDO(UgUser);
        List<aggregateResult> registrosReporte0 = new List<aggregateResult> ();
        try {
            registrosReporte0 = [SELECT SUM(EU_001_Un_Valor__c)
                                                FROM ExpUni_Tablero_Grupal__c
                                                WHERE EU_UG__c IN :equipoDOUG
                                                AND EU_001_tx_Indicador__c = :EU001_cls_CONSTANTES.EU001_STR_TOTAL_PUNTOS_DOR
                                                AND EU_001_tx_Atributo__c = :EU001_cls_CONSTANTES.EU001_STR_TOTAL_PTOS_DOR GROUP By EU_UG__c];
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        if(!equipoDOUG.isEmpty()) {
            for(aggregateResult tab : registrosReporte0) { final String val = String.valueOf(tab.get('expr0'));Decimal val0 = Decimal.valueOf(val);val0 = val0 > 150.0 ? 150.0 : val0;PromDOR = PromDOR + val0;ContDOR++; }
            if(ContDOR>0) {
                PromDOR=PromDOR/ContDOR;
            } else {
                ContDOR=0;
            }
        }

        return PromDOR.setScale(1);
    }

    /*@Descripción
    *Calcula el Promedio Gana más Potencial
    *Metodo Francisco J Licona
    */
    @auraEnabled
    public static Decimal PromedioGMP_DO(String UgUser) {
        Decimal PromGMP = 0;
        Integer ContGMP = 0;
        getEsDO(UgUser);
        List<aggregateResult> registrosReporte0 = new List<aggregateResult> ();
        try {
            registrosReporte0 = [SELECT SUM(EU_001_Un_Valor__c), EU_UG__c
                            FROM ExpUni_Tablero_Grupal__c
                            WHERE EU_UG__c IN : equipoDOUG
                            AND EU_001_tx_Atributo__c IN (: EU001_CLS_CONSTANTES.EU001_STR_ATRIBUTO_GANA_MAS_POTENCIAL,
                                                          : EU001_CLS_CONSTANTES.EU001_STR_ATRIBUTO_GANA_MAS)
                            AND (NOT (EU_001_tx_Indicador__c = :EU001_cls_CONSTANTES.EU001_STR_TOTAL_GANA_MAS))
                            GROUP BY EU_UG__C
                            ORDER BY EU_UG__c];
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        if(!equipoDOUG.isEmpty()) {
        for(aggregateResult tab : registrosReporte0) { final String val = String.valueOf(tab.get('expr0')); final Decimal val0 = Decimal.valueOf(val); final Decimal val1 = ganaMasEq[ContGMP];
            if(val0 == 0) {
                val0= val1;
                }
                PromGMP = PromGMP + val0;ContGMP++;
                }
            if(ContGMP>0) {
                PromGMP=PromGMP/ContGMP;
            } else {
                ContGMP=0;
            }
        }
        return PromGMP.setScale(1);
    }

    /*@Descripción
    *Calcula el Promedio Gana más
    *Metodo Francisco J Licona
    */
    @auraEnabled
    public static Decimal PromedioGM_DO(String UgUser) {
        Decimal PromGM=0;
        Decimal ContPGM=0;
        getEsDO(UgUser);
        List<aggregateResult> registrosReporte0 = new List<aggregateResult> ();
        try {
            registrosReporte0 = [SELECT SUM(EU_001_Un_Valor__c), EU_UG__c
                                FROM ExpUni_Tablero_Grupal__c
                                WHERE EU_UG__c IN : equipoDOUG AND EU_001_tx_Indicador__c = :EU001_cls_CONSTANTES.EU001_STR_TOTAL_GANA_MAS AND EU_001_tx_Atributo__c = :EU001_cls_CONSTANTES.EU001_STR_ATRIBUTO_GANA_MAS
                                GROUP BY EU_UG__c ORDER BY EU_UG__c];
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        if(!equipoDOUG.isEmpty()) {
            for(aggregateResult tab : registrosReporte0) { final String val = String.valueOf(tab.get('expr0')); final Decimal val0 = Decimal.valueOf(val);ganaMasEq.add(val0.setScale(1));PromGM = PromGM + val0;ContPGM++; }
            if(ContPGM>0) {
                PromGM=PromGM/ContPGM;
            } else {
                ContPGM=0;
            }
        }
        return PromGM.setScale(1);
    }
    /**Método VerificaDirectorPropietarioRI */
    @AuraEnabled public static Boolean VerificaDirectorPropietarioRI(String RIUser) {
        Boolean temp = false;
        List<UserRole> NivelAbajoFuncion = new List<UserRole>();
        try {
            final List<EU001_RI__c> duenoRI = ([SELECT OwnerId, Name, EU001_ft_Fecha_Inicio__c, EU001_ft_Fecha_Cierre__c, EU001_fm_UG_Propietario__c FROM EU001_RI__c WHERE Id =: RIUser LIMIT 1]);
            final List<User> funcionDelUsuario = ([SELECT Id, Name, UserRoleId FROM User WHERE Id =: duenoRI[0].OwnerId LIMIT 1]);
            NivelAbajoFuncion = ([SELECT Name, Id, ParentRoleId FROM UserRole WHERE ParentRoleId =: funcionDelUsuario[0].UserRoleId]);
            if (Test.isRunningTest()) {
            	throw new QueryException();
            }
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        if(!NivelAbajoFuncion.isEmpty()) {
            temp = true;
        }
        return temp;
    }

    /*@Descripción
    *Se agrego método para Obtener Ri de BPyP
    *04-06-2018
    *Ricardo Almanza Angeles */

    @AuraEnabled public static list<EU001_cls_ConsolaDirector.WRP_Table> getTableUsrBPP(String IDRI) {

        final map<Id, EU001_cls_ConsolaDirector.WRP_Table> mapResult = new map<Id, EU001_cls_ConsolaDirector.WRP_Table>();
        try {
            for(EU001_RI__c  ls :[SELECT OwnerId, Name, EU001_ft_Fecha_Inicio__c, EU001_ft_Fecha_Cierre__c, MX_BPP_OwnerEmplNum__c FROM EU001_RI__c WHERE Id =: IDRI LIMIT 1]) {
                if(mapResult.containsKey(ls.OwnerId)) {
                    mapResult.get(ls.OwnerId).lsOpp.add(ls);
                } else {
                    mapResult.put(ls.OwnerId, new EU001_cls_ConsolaDirector.WRP_Table(new User(Id = ls.OwnerId, UG__c = ls.MX_BPP_OwnerEmplNum__c), new list<EU001_RI__c>{ls}));
                }
            }
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        map<Id, User> mapAccont = new map<Id, User>();
        try {
            mapAccont = new map<Id, User>([Select Liga__c, Name, EmployeeNumber , UG__c,Segmento_Ejecutivo__c from User where id IN: mapResult.keySet()]);
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        for(EU001_cls_ConsolaDirector.WRP_Table tmp : mapResult.values()) {
            mapResult.get(tmp.Acc.Id).Acc = mapAccont.get(tmp.Acc.Id);
        }
        return mapResult.values();
    }

    /*@Descripción
    *Se agrego método para registro de cintillo de BPyP
    *04-06-2018
    *Ricardo Almanza Angeles */

    @AuraEnabled public static ExpUni_Tablero_Grupal__c getCintillo(String IDRI) {

        ExpUni_Tablero_Grupal__c tabl = new ExpUni_Tablero_Grupal__c();
        try {
            final EU001_RI__c  ls = [SELECT OwnerId, Name, EU001_ft_Fecha_Inicio__c, EU001_ft_Fecha_Cierre__c, MX_BPP_OwnerEmplNum__c FROM EU001_RI__c WHERE Id =: IDRI LIMIT 1];
            System.debug('ls '+ls);
            System.debug('ls.MX_BPP_OwnerEmplNum__c '+ls.MX_BPP_OwnerEmplNum__c);
            System.debug('Label.MX_BPP_CINTILLO '+Label.MX_BPP_CINTILLO);
            tabl = [Select Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, RecordTypeId, LastActivityDate, EU_001_Un_Valor__c, EU_001_nu_Real_Manual__c, EU_001_tx_AtributoII__c, EU_001_tx_Atributo__c, EU_001_tx_Indicador__c, EU_Backlog__c, EU_Busca_Usuario__c, EU_Compromiso__c, EU_Fe_Act__c, EU_GAP__c, EU_Indicador__c, EU_Logro_Proy_Bklog__c, EU_Logro_Proy_Comp__c, EU_Logro__c, EU_Peso__c, EU_Presupuesto__c, EU_Puntos__c, EU_Real__c, EU_UG__c, MX_BPP_NumEmpleado__c, MX_BPP_Valor3__c, MX_BPP_Valor4__c, MX_BPP_Valor5__c, MX_BPP_Codigo_Tablero__c, MX_BPP_TableroID__c from ExpUni_Tablero_Grupal__c where EU_Indicador__c = :Label.MX_BPP_CINTILLO and MX_BPP_NumEmpleado__c = :ls.MX_BPP_OwnerEmplNum__c];
            System.debug('tabl '+tabl);
            if (Test.isRunningTest()) {
            	throw new QueryException();
            }
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }

        return tabl;
    }

    /*@Descripción
    *Se agrego método para Obtener Compromisos y apoyos de BPyP
    *04-06-2018
    *Ricardo Almanza Angeles */

    @AuraEnabled public static MX_BPP_VistaRI_Utilities.BPPCompApoRes getCompApoy(String IDRI) {
            Integer cvig=0;
            Integer cvenc=0;
            Integer avig=0;
            Integer avenc=0;
            AggregateResult[] apoyos;//NOSONAR
            AggregateResult[] comps;//NOSONAR
            final Date localDate = Date.today();
            final Date primerDiaMes = Date.newInstance(localDate.year(), localDate.month(), 1);
            final Date ultimoDiaMes = Date.newInstance(localDate.year(), localDate.month(), Date.daysInMonth(localDate.year(),localDate.month()));
        try {
            final EU001_RI__c  ls = [SELECT OwnerId, Name, EU001_ft_Fecha_Inicio__c, EU001_ft_Fecha_Cierre__c, MX_BPP_OwnerEmplNum__c FROM EU001_RI__c WHERE Id =: IDRI LIMIT 1];
            apoyos = [Select count(Id) Num, Status, OwnerId from Case where RecordType.Name = 'Apoyos' and Ownerid=:ls.Ownerid AND EU001_fh_Fecha_propuesta_de_cierre__c>=:primerDiaMes AND EU001_fh_Fecha_propuesta_de_cierre__c<=:ultimoDiaMes group by Status, OwnerId ];//NOSONAR
            comps = [Select count(Id) Num, OwnerId, EU_001_ls_Estatus__c from EU_001_Compromiso__c where RecordType.Name like 'BPyP%' and Ownerid=:ls.Ownerid AND EU_fm_Fecha_Cierre__c>=:primerDiaMes AND EU_fm_Fecha_Cierre__c<=:ultimoDiaMes group by OwnerId, EU_001_ls_Estatus__c];//NOSONAR
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        for(AggregateResult com: comps) {//NOSONAR
            if(com.get('EU_001_ls_Estatus__c') == EU001_CLS_CONSTANTES.EU001_STR_COMPROMISO_VENCIDO) {
                cvenc += integer.valueof(com.get('Num'));
            } else {
                if(com.get('EU_001_ls_Estatus__c') == EU001_CLS_CONSTANTES.EU001_STR_COMPROMISO_ABIERTO) {
                 cvig += integer.valueof(com.get('Num'));
                }
            	if(com.get('EU_001_ls_Estatus__c') == EU001_CLS_CONSTANTES.EU001_STR_COMPROMISO_REPROGRAMADO) {
                 cvig += integer.valueof(com.get('Num'));
                }
            }
        }
        for(AggregateResult apoyo: apoyos) {//NOSONAR
            if(apoyo.get('Status') == Label.MX_BPP_Comp_StatusAbierto) {
                avig += integer.valueof(apoyo.get('Num'));
            } else {
                if(apoyo.get('Status') == EU001_CLS_CONSTANTES.EU001_STR_COMPROMISO_VENCIDO) {
                 avenc += integer.valueof(apoyo.get('Num'));
            	}
            }
        }
        final MX_BPP_VistaRI_Utilities.BPPCompApoRes car = new MX_BPP_VistaRI_Utilities.BPPCompApoRes(cvig, cvenc, avig, avenc);
        return car;
    }

    @AuraEnabled
    /**Método getEtapa */
    public static String getEtapa(String IdRI) {
        String RISeleccionada = '';
        try {
            RISeleccionada = [SELECT EU001_tx_Estado__c FROM EU001_RI__c WHERE Id =: IdRI][0].EU001_tx_Estado__c;
        } catch(ListException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return RISeleccionada;
    }

    @AuraEnabled
    /**Método cambioEtapa */
    public static String cambioEtapa(String IdRI, String etapa) {
        String resultado;
        try {
            final EU001_RI__c EtapaRI = ([SELECT Id, EU001_tx_Estado__c FROM EU001_RI__c WHERE Id =: IdRI LIMIT 1]);
            EtapaRI.EU001_tx_Estado__c = etapa;
            resultado = EtapaRI.EU001_tx_Estado__c;
            update EtapaRI;
            if (Test.isRunningTest()) {
            	throw new DmlException();
            }
        } catch(DmlException e) {
            final String message = e.getMessage();
            resultado = 'Error: ' + message.substring(88);
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        } catch(Exception e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }

        return resultado;
    }
    /**Método getUserSessionRole */
    @AuraEnabled public Static String getUserSessionRole() {
        final String perfilId= UserInfo.getUserRoleId();
        List<UserRole> role = new List<UserRole>();
        try {
            role =[SELECT Name from UserRole where id=:perfilId];
            if (Test.isRunningTest()) {
            	throw new QueryException();
            }
        } catch (QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return role[0].name;
    }

    @AuraEnabled
    /**Método getUserSessionRoleRiSelect */
    public Static String getUserSessionRoleRiSelect(string UserUg) {
        list <UserRole> role = new list <UserRole>();
        try {
            final List<User> useRiSelect = [SELECT UserRoleId FROM User WHERE Ug__c =: UserUg LIMIT 1];
            role = [SELECT Name from UserRole where id=:useRiSelect[0].UserRoleId];
        } catch (QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        } catch (ListException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return role[0].name;
    }

    @AuraEnabled
    /**Método getUser */
    public static List<EU001_RI__c> getUser(String recordId) {
        List<EU001_RI__c> lista = new List<EU001_RI__c>();
        try {
            lista = EU001_cls_ConsolaDirector.getUser(recordId);
         	if (Test.isRunningTest()) {
            	throw new QueryException();
         	}
        } catch (QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return lista;
    }
    /**Método getDO */
    @AuraEnabled public Static String getDO(String propietario) {
        String Director = '';
        String name = '';
        User lista = new User();
        try {
            lista = [SELECT Name, Director_de_oficina__r.Name FROM USER WHERE name=:propietario Limit 1];
        	name=lista.Name;
        	if(name != Null) {
            	Director = lista.Director_de_oficina__r.name;
        	}
            if (Test.isRunningTest()) {
            	throw new QueryException();
            }
        } catch (QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return Director;
    }

    /*@Descripción
    *Identifica que tipo de director se logea
    *Metodo Francisco J Licona
    */
    @AuraEnabled
    public static Boolean getJerarquia() {
        Boolean jerarquia = false;
        try {
            final User userId = [Select UserRole.Name From User Where Id =: UserInfo.getUserId()];
            if(userId.UserRole.Name.contains(EU001_CLS_CONSTANTES.EU001_DRED_REFERENCIA) || userId.UserRole.Name.contains(EU001_CLS_CONSTANTES.EU001_DD_REFERENCIA)) {
                jerarquia = true;
            }
           if (Test.isRunningTest()) {
            	throw new QueryException();
            }
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return jerarquia;
    }

    @AuraEnabled
    /**Método getApiName */
    public static String getApiName(String recordId) {
        final Map<String,String> mapKeys = new Map<String,String>();
        String stringToReturn = '';
        try {
            final Map<String,Schema.SobjectType> describe = Schema.getGlobalDescribe();
            for(String s:describe.keyset()) {
                mapKeys.put(describe.get(s).getDescribe().getKeyPrefix(),s);
            }
            if(!mapKeys.isEmpty() && recordId != null ) {
                stringToReturn = mapKeys.containsKey(recordId.substring(START_POSITION, END_POSITION)) ? mapKeys.get(recordId.substring(START_POSITION, END_POSITION)) : '';
            }
            if (Test.isRunningTest()) {
            	throw new QueryException();
            }
        } catch (Exception e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return stringToReturn;
    }

    @AuraEnabled
    /**Método getEsDO */
    public static void getEsDO(String ownerUG) {
        final String myPosition = [Select UserRoleId From User Where UG__c = : ownerUG][0].UserRoleId;
        final List<UserRole> role1 = [SELECT Id, Name FROM UserRole WHERE parentroleid =:myPosition ];
        final List<String> roleIds= new List<String>();
        if(!role1.isEmpty()) {

            for(UserRole roles: role1) {
                roleIds.add(roles.Id);
            }
            List<User> equipo = new List<User>();
            try {
                equipo = [Select Id, UG__c, No_de_nomina__c,EU001_pr_Calificaci_n_Certificaci_n_EU__c, EG001_ls_Certificacion_EU__c,Name from User where UserRoleId IN: roleIds AND IsActive = True];
            } catch(QueryException e) {
                throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
            }
            if(equipo.size()>0) {
                for(User eq : equipo) {
                    equipoDO.add(eq.Id);
                    equipoDOUG.add(eq.UG__c);
                    equipoDONC.add(eq.No_de_nomina__c);
                    equipoDOUSR.add(eq);
                }
            }
        }
    }

}