src/objects/Case.object
<CustomObject>
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <fields>
        <fullName>EU001_fh_Fecha_propuesta_de_cierre__c</fullName>
        <description>Fecha Propuesta de cierre Experiencia única</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha propuesta de cierre</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EU001_ls_Tipo_de_apoyo__c</fullName>
        <description>Tipo de apoyo para experiencia unica</description>
        <label>Tipo de apoyo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Proceso de crédito</fullName>
                </value>
                <value>
                    <fullName>Producto</fullName>
                </value>
                <value>
                    <fullName>Capacitación</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Visitas</fullName>
                </value>
                <value>
                    <fullName>IReNe</fullName>
                </value>
                <value>
                    <fullName>Otros</fullName>
                </value>
                <value>
                    <fullName>Capacitación a Oficina / Ejecutivo</fullName>
                </value>
                <value>
                    <fullName>Capacitación al Cliente</fullName>
                </value>
                <value>
                    <fullName>Cotización de Producto</fullName>
                </value>
                <value>
                    <fullName>Manejo de Objeción con el Cliente</fullName>
                </value>
                <value>
                    <fullName>Presentación de Producto</fullName>
                </value>
                <value>
                    <fullName>Apoyo General</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Oportunidad</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Alerta CRM</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Propuesta Comercial</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Plan de Cuenta</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Caso</fullName>
                </value>
                <value>
                    <fullName>Análisis de crédito</fullName>
                    <isActive>false</isActive>
                    <label>Análisis de crédito</label>
                </value>
                <value>
                    <fullName>Plan de Cuenta</fullName>
                    <isActive>false</isActive>
                    <label>Plan de Cuenta</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reuni_n_Individual_RI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reunión Individual (RI)</label>
        <referenceTo>EU001_RI__c</referenceTo>
        <relationshipLabel>Apoyos</relationshipLabel>
        <relationshipName>Casos</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--App Casos-->
    <!--App Casos-->
<!--Multiasistencia-->
    <!--Multiasistencia-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <recordTypes>
        <fullName>Apoyos</fullName>
        <active>true</active>
        <businessProcess>Apoyos</businessProcess>
        <description>Apoyos experiencia Unica</description>
        <label>Apoyos</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EU001_RI__c.object
<CustomObject>
    <description>Contiene los datos necesarios de la RI para su asociacion con los Compromisos</description>
    <fields>
        <fullName>EG001_Valoracion_de_RI_DO__c</fullName>
        <description>La valoración que el Director de Oficina le da a la RI.</description>
        <label>Valoracion de RI DO</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Bueno</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Muy Bueno</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Excelente</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EG_001_ls_Valoracion_de_RI__c</fullName>
        <label>Valoracion de RI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Bueno</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Muy Bueno</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Excelente</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EU001_ft_Fecha_Inicio__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Fecha y hora de inicio de la RI</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de Inicio</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EU001_tx_Estado__c</fullName>
        <description>Estado en que se encuentra la RI</description>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparación</fullName>
                    <default>true</default>
                    <label>Preparación</label>
                </value>
                <value>
                    <fullName>Presentación</fullName>
                </value>
                <value>
                    <fullName>Evaluacion</fullName>
                    <label>Evaluación</label>
                </value>
                <value>
                    <fullName>Finalizacion</fullName>
                    <label>Finalización</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reunión Individual</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>No RI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reunión Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EU_001_Compromiso__c.object
<CustomObject>
    <description>Compromisos Experiencia Única</description>
    <fields>
        <fullName>EU_001_Rb_Revisi_n_Individual_RI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Revisión Individual (RI)</description>
        <label>Reunión Individual</label>
        <referenceTo>EU001_RI__c</referenceTo>
        <relationshipLabel>Compromiso EU</relationshipLabel>
        <relationshipName>Compromiso_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EU_001_dv_Compromiso__c</fullName>
        <description>Monto en pesos para el compromiso de Experiencia única</description>
        <inlineHelpText>Pesos</inlineHelpText>
        <label>Compromiso</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EU_001_ls_Estatus__c</fullName>
        <description>Estatus para identificar el compromiso Experiencia única</description>
        <label>Estatus del Compromiso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abierto</fullName>
                    <default>true</default>
                    <label>Abierto</label>
                </value>
                <value>
                    <fullName>Descartado</fullName>
                </value>
                <value>
                    <fullName>En Gestion</fullName>
                    <label>En Gestión</label>
                </value>
                <value>
                    <fullName>Hecho</fullName>
                </value>
                <value>
                    <fullName>Reprogramado</fullName>
                </value>
                <value>
                    <fullName>Vencido</fullName>
                </value>
                <value>
                    <fullName>Cambiar Fecha de disposición</fullName>
                    <isActive>false</isActive>
                    <label>Cambiar Fecha de disposición</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EU_fm_Fecha_Cierre__c</fullName>
        <description>Fecha de cierre Experiencia única</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de cierre</label>
        <type>Date</type>
    </fields>
    <label>Compromiso EU</label>
    <nameField>
        <displayFormat>EUCP-{0000}</displayFormat>
        <label>Compromiso EU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compromiso EU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExpUni_Tablero_Grupal__c.object
<CustomObject>
    <fields>
        <fullName>EU_001_Un_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_001_tx_Atributo__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Concepto</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_001_tx_Indicador__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Indicador</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_Indicador__c</fullName>
        <description>Indicador que proviene del Tablero de Gestión que define el tipo Cartera que se esta manejando.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Agrupador</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_Logro__c</fullName>
        <description>Valor que proviene del Tablero de Gestión y define el logro alcanzado por el Ejecutivo.</description>
        <label>Valor 2</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_UG__c</fullName>
        <description>Numero de identificador del usuario</description>
        <encryptionScheme>None</encryptionScheme>
        <label>UG</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <label>Tablero de Gestión</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Nombre de Tablero Grupal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tablero de Gestión</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EU_Contador_Test.cls
/**
*Desarrollado por:       Indra
*Autor:                  ABRAHAM TINAJERO
*Proyecto:               Experiencia Unica
*Descripción:            Clase Test para la clase ContadorExpUni_Class
*
*Cambios (Versiones)
*-------------------------------------------------------------------------------
*No.         Fecha            Autor                           Descripción
*------   ----------------   --------------------   ----------------------------
*1.0      04-07-2017         Abraham Tinajero        Creación
*1.0      14-08-2017         Monserrat Gonzalez      Método CalculoImpacto para Experiencia única
*1.2      28-02-2018         Abraham Tinajero        Se actualiza metodo par creación de planes de cuenta
*1.3      15-03-2018         Abraham Tinajero        Se actualiza metodo para los nuevos indicadores
*1.4      20-06-2018         Mario Rodríguez         Se cambian referencias de Tipos de Registros por método Developer Name SHIELD
*2.0      28-03-2019         Francisco J Licona      Se corrige creación de usuario para asignación de UG en la creación del tablero
*3.0      19-06-2019         Cindy Hernández         Se eliminan los métodos que no se utilizan y se agrega el método contadorConstructor
**/
@isTest
public with sharing class EU_Contador_Test {

    @isTest static void CreacionRIError1() {
        test.StartTest();
        final String[] ug = new List<String>();
        ug.add('37025');
        ug.add('37024');
        final List<User> users = MX_BPP_UserAndRIDataFactory.createTestRecordsUser(ug,false);

        final EU001_RI__c nuevoRi = new EU001_RI__c();
        nuevoRi.EU001_tx_Estado__c = 'Preparación';
        nuevoRi.EU001_ft_Fecha_Inicio__c = system.now();
        nuevoRi.ownerId = users.get(0).Id;

        insert nuevoRi;

        try {
            final EU001_RI__c nuevoRi01 = new EU001_RI__c();
            nuevoRi01.EU001_tx_Estado__c = 'Preparación';
            nuevoRi01.EU001_ft_Fecha_Inicio__c = system.now();
            nuevoRi01.ownerId = users.get(0).Id;

            final Database.SaveResult result = Database.insert(nuevoRi01);
            System.assertEquals(true, result.isSuccess(), 'Se realizó la inserción correctamente');
        } catch (DmlException e) {
            final String message = e.getMessage();
            System.assertEquals(true, message.contains('Aún existe una RI en estado Preparación, Presentación o Evaluación, debes finalizar esta RI para poder generar una nueva'), 'No ocurrió un error como se esperaba');
        }
        Test.stopTest();
    }

    @isTest static void CreacionTableroError2() {
        test.StartTest();
         try {
            final ExpUni_Tablero_Grupal__c tablero1 = new ExpUni_Tablero_Grupal__c();
            tablero1.EU_UG__c ='37020';
            tablero1.EU_001_tx_Indicador__c ='Cartera Vigente CP';
            tablero1.EU_Indicador__c ='Real';
            tablero1.EU_001_tx_Atributo__c = 'a)Real';
            tablero1.EU_001_Un_Valor__c =147000;
            tablero1.EU_Logro__c = 0;

            final Database.SaveResult result = Database.insert(tablero1);
            System.assertEquals(true, result.isSuccess(), 'Se realizó la inserción correctamente');
        } catch (DmlException e) {
            final String message = e.getMessage();
            System.assertEquals(true, message.contains('La UG no tiene Ejecutivo Asignado (insertar)'), 'No ocurrió un error como se esperaba');
        }
        Test.stopTest();
    }

    @isTest static void heredaRI() {
        final EU001_RI__c nuevoRI = new EU001_RI__c();

        insert nuevoRI;

        final EU_001_Compromiso__c comp = new EU_001_Compromiso__c();
        comp.RecordTypeId = RecordTypeMemory_cls.getRecType('EU_001_Compromiso__c', 'BPyP Captación');
        comp.EU_001_ls_Estatus__c = EU001_CLS_CONSTANTES.EU001_STR_COMPROMISO_ABIERTO;
        comp.EU_001_dv_Compromiso__c = 135000;
        comp.EU_fm_Fecha_Cierre__c = date.today().addDays(3);
        comp.EU_001_Rb_Revisi_n_Individual_RI__c = nuevoRI.id;

        insert comp;

        final Case casoRI = new Case();
        casoRI.EU001_ls_Tipo_de_apoyo__c = 'Producto';
        casoRI.Subject = 'Test-subject';
        casoRI.EU001_fh_Fecha_propuesta_de_cierre__c = Date.today().addDays(10);
        casoRI.Status = EU001_CLS_CONSTANTES.EU001_STR_COMPROMISO_ABIERTO;
        casoRI.Reuni_n_Individual_RI__c = nuevoRI.id;
        casoRI.RecordTypeId = RecordTypeMemory_cls.getRecType('Case', 'Apoyos');

        insert casoRI;

        nuevoRI.EU001_tx_Estado__c  = EU001_CLS_CONSTANTES.EU001_STR_RI_FINALIZACION;
        nuevoRI.EG_001_ls_Valoracion_de_RI__c ='4';
        nuevoRI.EG001_Valoracion_de_RI_DO__c ='4';

        update nuevoRI;

        final EU001_RI__c nuevoRI_2 = new EU001_RI__c();

        final Database.SaveResult result = Database.insert(nuevoRI_2);
		System.assertEquals(True, result.isSuccess(), 'Se actualizó correctamente la RI.');
    }

    @isTest
    static void contadorConstructor() {
        String errorMessage = '';
        test.startTest();
        try {
	        final ContadorExpUni_Class contadorExpUni = new ContadorExpUni_Class();
            System.assert(contadorExpUni != null);
        } catch (Exception e) {
            errorMessage = e.getMessage();
        }
        test.stopTest();
        System.assertEquals('', errorMessage);
    }

}