src/objects/Case.object
<CustomObject>
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <fields>
        <fullName>EU001_fh_Fecha_propuesta_de_cierre__c</fullName>
        <description>Fecha Propuesta de cierre Experiencia única</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha propuesta de cierre</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EU001_ls_Tipo_de_apoyo__c</fullName>
        <description>Tipo de apoyo para experiencia unica</description>
        <label>Tipo de apoyo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Proceso de crédito</fullName>
                </value>
                <value>
                    <fullName>Producto</fullName>
                </value>
                <value>
                    <fullName>Capacitación</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Visitas</fullName>
                </value>
                <value>
                    <fullName>IReNe</fullName>
                </value>
                <value>
                    <fullName>Otros</fullName>
                </value>
                <value>
                    <fullName>Capacitación a Oficina / Ejecutivo</fullName>
                </value>
                <value>
                    <fullName>Capacitación al Cliente</fullName>
                </value>
                <value>
                    <fullName>Cotización de Producto</fullName>
                </value>
                <value>
                    <fullName>Manejo de Objeción con el Cliente</fullName>
                </value>
                <value>
                    <fullName>Presentación de Producto</fullName>
                </value>
                <value>
                    <fullName>Apoyo General</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Oportunidad</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Alerta CRM</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Propuesta Comercial</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Plan de Cuenta</fullName>
                </value>
                <value>
                    <fullName>Apoyo de Caso</fullName>
                </value>
                <value>
                    <fullName>Análisis de crédito</fullName>
                    <isActive>false</isActive>
                    <label>Análisis de crédito</label>
                </value>
                <value>
                    <fullName>Plan de Cuenta</fullName>
                    <isActive>false</isActive>
                    <label>Plan de Cuenta</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reuni_n_Individual_RI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reunión Individual (RI)</label>
        <referenceTo>EU001_RI__c</referenceTo>
        <relationshipLabel>Apoyos</relationshipLabel>
        <relationshipName>Casos</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--App Casos-->
    <!--App Casos-->
<!--Multiasistencia-->
    <!--Multiasistencia-->
    <!--App Casos-->
    <!--App Casos-->
    <!--App Casos-->
    <recordTypes>
        <fullName>Apoyos</fullName>
        <active>true</active>
        <businessProcess>Apoyos</businessProcess>
        <description>Apoyos experiencia Unica</description>
        <label>Apoyos</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EU001_RI__c.object
<CustomObject>
    <description>Contiene los datos necesarios de la RI para su asociacion con los Compromisos</description>
    <fields>
        <fullName>EG001_Valoracion_de_RI_DO__c</fullName>
        <description>La valoración que el Director de Oficina le da a la RI.</description>
        <label>Valoracion de RI DO</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Bueno</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Muy Bueno</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Excelente</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EG_001_ls_Valoracion_de_RI__c</fullName>
        <label>Valoracion de RI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Bueno</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Muy Bueno</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Excelente</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EU001_tl_Comentario_DO__c</fullName>
        <description>El comentario que proporciona el Director de Oficina al momento de valorar la RI.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comentario DO</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EU001_tl_Comentario_EV__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comentario EV</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EU001_tx_Estado__c</fullName>
        <description>Estado en que se encuentra la RI</description>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparación</fullName>
                    <default>true</default>
                    <label>Preparación</label>
                </value>
                <value>
                    <fullName>Presentación</fullName>
                </value>
                <value>
                    <fullName>Evaluacion</fullName>
                    <label>Evaluación</label>
                </value>
                <value>
                    <fullName>Finalizacion</fullName>
                    <label>Finalización</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reunión Individual</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>No RI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reunión Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_BPP_VistaRI_Utilities.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     MX_BPP_VistaRI_Utilities
* @Author   Cindy Hernández cindyarianna.hernandez.nieto.contractor@bbva.com
* @Date     Created: 2019-06-12
* @Group    Digital Workplace Retail
* @Description Get the cases owned by the banker
* @Comments Created from the clipped code from the EU001_cls_ConsolaDirector class. It supports MX_BPP_VistaRI_Cls.
* @Changes
**/

public With Sharing class MX_BPP_VistaRI_Utilities {

    //Constructor with no arguments
    private MX_BPP_VistaRI_Utilities() {
    }
    /** */
    @RemoteAction public static void updateEstatus(String recordId) {
        EU001_RI__c toUpdate = [SELECT EU001_tl_Comentario_EV__c, EU001_tl_Comentario_DO__c, EG_001_ls_Valoracion_de_RI__c, EG001_Valoracion_de_RI_DO__c FROM EU001_RI__c WHERE id =: recordId];
        if(toUpdate.EU001_tl_Comentario_EV__c <> '' && toUpdate.EU001_tl_Comentario_DO__c <> '' && toUpdate.EG_001_ls_Valoracion_de_RI__c <> '' && toUpdate.EG001_Valoracion_de_RI_DO__c <> '' ) {
            toUpdate.EU001_tx_Estado__c= 'Finalizacion';
        }
        update toUpdate;
    }

    /*@Descripción
    *Se agrego clase para Obtener compromisos y apoyos de BPyP
    *04-06-2018
    *Ricardo Almanza Angeles */

    public class BPPCompApoRes {
        /** */
        @AuraEnabled public Integer compVig {get; set;}
        /** */
        @AuraEnabled public Integer compVenc {get; set;}
        /** */
        @AuraEnabled public Integer apoyVig {get; set;}
        /** */
        @AuraEnabled public Integer apoyVenc {get; set;}
        /** */
        public BPPCompApoRes(Integer cvig,Integer cvenc,Integer avig,Integer avenc) {
            this.compVig=cvig;
            this.compVenc=cvenc;
            this.apoyVig=avig;
            this.apoyVenc=avenc;
        }
    }

    /**
	Descripción: Método para crear un caso.
	*/
    public static Case createCaseTest(String tipoApoyo, String subject, String recType, Integer sts, EU001_RI__c riRecord) {
        final Case caso = new Case();
        caso.EU001_ls_Tipo_de_apoyo__c = tipoApoyo;
        caso.Subject = subject;
        caso.EU001_fh_Fecha_propuesta_de_cierre__c = Date.today().addDays(1);
        Integer statusNumber = 2;
        if(sts == statusNumber) {
            caso.Status = EU001_CLS_CONSTANTES.EU001_STR_COMPROMISO_VENCIDO;
        } else {
            caso.Status = EU001_CLS_CONSTANTES.EU001_STR_COMPROMISO_ABIERTO;
        }
        caso.Reuni_n_Individual_RI__c = riRecord.id;
        caso.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recType).getRecordTypeId();
        return caso;
    }

}