src/objects/Constantes_ASD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Auto_Seguro_Dinamico__c</fullName>
        <label>Auto Seguro Dinamico</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seguro_Fronterizo__c</fullName>
        <label>Seguro Fronterizo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seguro_Moto_Bancomer__c</fullName>
        <label>Seguro Moto Bancomer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Constantes ASD</label>
</CustomObject>

src/objects/URL_Auto_Seguro_Bancomer__mdt.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tipoUsoVehiculoCot__c</fullName>
        <label>tipoUsoVehiculoCot</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>URL Auto Seguro Bancomer</label>
    <pluralLabel>URL Auto Seguros Bancomer</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Agencia__c</fullName>
        <label>Agencia</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Canal__c</fullName>
        <label>Canal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <label>Servicio</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Canal__c</fullName>
        <label>Sub Canal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Turno__c</fullName>
        <label>Turno</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Matutino</fullName>
                </value>
                <value>
                    <fullName>Vespertino</fullName>
                </value>
                <value>
                    <fullName>Intermedio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Usuario__c</fullName>
        <label>Usuario</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_ASD_CargarDatosPrueba_cls.cls
/**
 * ASD_CargarDatosPrueba_cls
 * Author   Edmundo Zacarias   edmundo.zacarias.contracto@bbva.com
 * Date     Created: 2019-02-05
 * Group    Utility Class Test
 * Description Esta clase global es para cargar datos de los que dependen varias clases test.
* Contiene métodos para generar registros sobre Custom Settings y Objetos Custom.
 */
@isTest
public class MX_ASD_CargarDatosPrueba_cls {

    /**
    * Metodo de utilería pra crear usuario
    *
    * @param
    * @return
    */
    @isTest
    public static User crearDatosUsuario() {
        final String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        final Profile prfProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        final User usrUser = new User(Alias = 'adminu', Email='standarduser@testorg.com',
                                      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='es_MX',
                                      LocaleSidKey='es_MX', ProfileId = prfProfile.Id,
                                      TimeZoneSidKey='America/Mexico_City',
                                      UserName=uniqueUserName,Turno__c='Matutino',Usuario__c='ASD000100',Canal__c='1',Sub_Canal__c='2',Agencia__c='VCIP',Servicio__c='VCIP%20SOLUCIONES,%20S.A.%20DE%20C.V.');
        System.assertEquals(usrUser.Alias,'adminu','El alias del usuario es adminu');
        return usrUser;
    }

    /**
    * Metodo de utilería para registro de custom setting
    *
    * @param
    * @return
    */
    public static void crearConstantesASD() {
        final Constantes_ASD__c constantesASD = new Constantes_ASD__c();
        constantesASD.Auto_Seguro_Dinamico__c = 'Auto Seguro Dinamico';
        constantesASD.Seguro_Fronterizo__c = 'Seguro Fronterizo';
        constantesASD.Seguro_Moto_Bancomer__c = 'Seguro de Moto Bancomer';
        System.debug('=====' + constantesASD);
        insert constantesASD;
    }

    /**
    * Metodo que crea la url para el cotizador
    *
    * @param  developername, url, masterlabel
    * @return         url auto seguro dinamico
    */
    public static URL_Auto_Seguro_Bancomer__mdt crearURLAutoSeguroBancomerMdt(String developerName, String url, String masterLabel, String tipoDeUso) {
        final URL_Auto_Seguro_Bancomer__mdt urlAutSegBancMdt = new URL_Auto_Seguro_Bancomer__mdt();
        urlAutSegBancMdt.DeveloperName = developerName;
        urlAutSegBancMdt.URL__c = url;
        urlAutSegBancMdt.MasterLabel = masterLabel;
        urlAutSegBancMdt.tipoUsoVehiculoCot__c = tipoDeUso;
        return urlAutSegBancMdt;
    }

}