src/objects/Contract.object
<CustomObject >
	
    <fields>
        <fullName>MX_WB_noPoliza__c</fullName>
        <description>Se almacena el número de póliza generado en la venta.</description>
        <inlineHelpText>Número de póliza emitida</inlineHelpText>
        <label>Número de Póliza</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación a producto.</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contratos</relationshipLabel>
        <relationshipName>Contratos_Producto</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo de relación hacia producto para asociar la oportunidad a un producto específico.</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cotizaciones</relationshipLabel>
        <relationshipName>Cotizaciones</relationshipName>
        <type>Lookup</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_GetAccountContracts.cls
/**
* BBVA - Mexico
* @Author: Jaime Terrats
* @Description: Controller for lwc mX_SB_VTS_GetAcccountContracts to retrieve all
*               the contracts from the account and show them as a related list in the
*               Opportunity Layout
* @Version: 1.0
**/
public without sharing class MX_SB_VTS_GetAccountContracts {
    /**
    * constructor
    */
    private MX_SB_VTS_GetAccountContracts() {} //NOSONAR

    /**
    * @method: fetchActiveContractsByAccount
    * @description returns a list of contracts
    * @param: oppId
    **/
    @AuraEnabled
    public static List<Contract> fetchActiveContractsByAccount(Id oppId) {
        List<Contract> activeContracts = new List<Contract>();
        try {
            final Id accId = [Select AccountId from Opportunity where Id =: oppId].AccountId;
            activeContracts = [Select Id, MX_WB_noPoliza__c, MX_WB_Producto__r.Name, CreatedDate from Contract where AccountId =: accId and Status = 'Activated'];
        } catch(System.QueryException qEx) {
            throw new AuraHandledException(System.Label.MX_WB_LG_ErrorBack + qEx);
        }

        return activeContracts;
    }
}