src/objects/Contract.object
<CustomObject >
	
    <fields>
        <fullName>MX_WB_Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación entre contrato y oportunidad.</description>
        <label>Cotización</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contratos TLMK</relationshipLabel>
        <relationshipName>Contratos_TLMK</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Motivosnoventa__c</fullName>
        <description>Motivo de no venta para cotización.</description>
        <label>Motivos de no venta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cliente molesto</fullName>
                </value>
                <value>
                    <fullName>Cliente no tiene tiempo</fullName>
                </value>
                <value>
                    <fullName>Cliente cuelga</fullName>
                </value>
                <value>
                    <fullName>No cumple políticas de contratación</fullName>
                </value>
                <value>
                    <fullName>No permite explicación de producto</fullName>
                </value>
                <value>
                    <fullName>Se cortó llamada</fullName>
                </value>
                <value>
                    <fullName>Cliente prefiere ir a sucursal</fullName>
                </value>
                <value>
                    <fullName>Cliente no tiene trabajo</fullName>
                </value>
                <value>
                    <fullName>Cliente lo va a pensar</fullName>
                </value>
                <value>
                    <fullName>Agendar</fullName>
                </value>
                <value>
                    <fullName>Otro idioma</fullName>
                </value>
                <value>
                    <fullName>Cuenta con producto similar BBVA</fullName>
                </value>
                <value>
                    <fullName>Cuenta con producto similar otro banco</fullName>
                </value>
                <value>
                    <fullName>Desconfianza del medio de comunicación</fullName>
                </value>
                <value>
                    <fullName>Desconfianza del producto ofertado</fullName>
                </value>
                <value>
                    <fullName>Desconfianza por llamada reciente</fullName>
                </value>
                <value>
                    <fullName>Economía personal</fullName>
                </value>
                <value>
                    <fullName>Mala experiencia BBVA</fullName>
                </value>
                <value>
                    <fullName>No le gustan los seguros</fullName>
                </value>
                <value>
                    <fullName>No utiliza TDC / TDD</fullName>
                </value>
                <value>
                    <fullName>Precio alto del producto</fullName>
                </value>
                <value>
                    <fullName>Prefiere otros productos</fullName>
                </value>
                <value>
                    <fullName>Producto no cubre expectativas</fullName>
                </value>
                <value>
                    <fullName>Requiere mayor suma asegurada</fullName>
                </value>
                <value>
                    <fullName>TDC / TDD robada o extraviada</fullName>
                </value>
                <value>
                    <fullName>Va a cancelar cuenta</fullName>
                </value>
                <value>
                    <fullName>Bloquear Sanas Prácticas</fullName>
                </value>
                <value>
                    <fullName>(Asistido) Dificil contratar mediante Tmkt</fullName>
                </value>
                <value>
                    <fullName>(Asistido) Dificil contratar mediante App</fullName>
                </value>
                <value>
                    <fullName>Tarjeta rechazada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Aplica_Cierre__c</fullName>
        <description>Indica si ya se cuenta con contrato para permitir el cierre de la oportunidad</description>
        <defaultValue>false</defaultValue>
        <label>Aplica Cierre</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Información para la cotización.</description>
        <label>Motivo de la Oportunidad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Venta Pre emisión</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <label>ASD</label>
    </recordTypes>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Cuenta personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
	<fields>
        <fullName>MX_SB_VTS_Motivos_de_no_venta__c</fullName>
        <description>Motivos de no venta de la cotización.</description>
        <label>Motivos de no venta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cliente molesto</fullName>
                </value>
                <value>
                    <fullName>No cumple políticas de contratación</fullName>
                </value>
                <value>
                    <fullName>Cliente cuelga</fullName>
                </value>
                <value>
                    <fullName>Cliente lo va a pensar</fullName>
                </value>
                <value>
                    <fullName>Cliente no tiene tiempo</fullName>
                </value>
                <value>
                    <fullName>Cliente prefiere ir a sucursal</fullName>
                </value>
                <value>
                    <fullName>Economía personal</fullName>
                </value>
                <value>
                    <fullName>No utiliza TDC / TDD</fullName>
                </value>
                <value>
                    <fullName>Precio alto del producto</fullName>
                </value>
                <value>
                    <fullName>Prefiere otros productos</fullName>
                </value>
                <value>
                    <fullName>Producto no cubre expectativas</fullName>
                </value>
                <value>
                    <fullName>Requiere mayor suma asegurada</fullName>
                </value>
                <value>
                    <fullName>Se cortó llamada</fullName>
                </value>
                <value>
                    <fullName>Agendar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_CierreOpp_Test.cls
/*
*
* @author Jaime Terrats
* @description This class will be used to upsert data coming from Hogar tracking web
*
*           No  |     Date     |     Author      |    Description
* @version  1.0    04/10/2019     Jaime Terrats     Create data structure to get incoming data from web tracking
* @version  1.1    06/17/2019     Jaime Terrats     Update closed won scenario
*
*/
@isTest
private class MX_SB_VTS_CierreOpp_Test {
    /*
    * Variable para Closed Lost
    */
    static final String closedLost = 'Closed Lost';
    /*
    * Variable para Closed Won
    */
	static final String closedWon = 'Closed Won';

    @TestSetup
    static void makeData() {
        final List<Opportunity> tempOpps = new List<Opportunity>();
        final User admin = MX_WB_TestData_cls.crearUsuario('test hogar', system.label.MX_SB_VTS_ProfileAdmin);
        Insert admin;

        System.runAs(admin) {
			final Product2 producto = MX_WB_TestData_cls.productNew('Hogar');
            producto.isActive = true;
            Insert producto;

         	final PricebookEntry pbe = MX_WB_TestData_cls.priceBookEntryNew(producto.Id);
            Insert pbe;
            final Account acc = MX_WB_TestData_cls.crearCuenta('Doe', 'PersonAccount');
            acc.PersonEmail = 'john.doe@test.close.opp.com';
            acc.FirstName = 'John';
            Insert acc;

            final Opportunity opp = MX_WB_TestData_cls.crearOportunidad('OppTest Close Opp', acc.Id, admin.Id, 'ASD');
            opp.Producto__c = 'test product';
            opp.Reason__c = 'Venta';
            final Opportunity opp2 = MX_WB_TestData_cls.crearOportunidad('OppTest Close Opp2', acc.Id, admin.Id, 'ASD');
            opp2.Producto__c = 'test product';
            opp2.Reason__c = 'Venta';
            final Opportunity opp3 = MX_WB_TestData_cls.crearOportunidad('OppTest Close Won', acc.Id, admin.Id, 'ASD');
            opp3.Producto__c = 'Auto Seguro Dinámico';
            opp3.Reason__c = 'Venta';
            opp3.MX_SB_VTS_Aplica_Cierre__c = true;
            tempOpps.add(opp);
            tempOpps.add(opp2);
            tempOpps.add(opp3);
            Insert tempOpps;

            final OpportunityLineItem oli = MX_WB_TestData_cls.oppLineItmNew(opp.Id, pbe.Id, producto.Id, 1, 1);
            Insert oli;

            final Contract contrTemp = new Contract();
            contrTemp.AccountId = acc.Id;
            contrTemp.StartDate = System.today();
            contrTemp.MX_WB_Oportunidad__c = opp3.Id;
			insert contrTemp;

            final Quote quoteTemp = MX_WB_TestData_cls.crearQuote(opp.Id, '999999 1 OppTest Close Opp', '999990');
            Insert quoteTemp;
        }
    }

    @isTest
    static void closedLostOpp1() {
        final Quote quo = [select Id, Name, MX_SB_VTS_Motivos_de_no_venta__c from Quote where Name =: '999999 1 OppTest Close Opp'];
        quo.MX_SB_VTS_Motivos_de_no_venta__c = 'Cliente molesto';
        final Opportunity opp = [select Id, StageName, Motivosnoventa__c from Opportunity where Name =: 'OppTest Close Opp'];
        opp.Motivosnoventa__c = 'Lorem Ipsum';
        opp.StageName = closedLost;
        Test.startTest();
        update quo;
        update opp;
        Test.stopTest();

        System.assertEquals(opp.StageName, closedLost, 'StageName doesnt match');
    }

    @isTest
    static void closedLostOpp2() {
        final Opportunity opp = [select Id, StageName, Motivosnoventa__c
                        from Opportunity where Name =: 'OppTest Close Opp2'];
        opp.Motivosnoventa__c = 'Lorem Ipsum';
        opp.StageName = closedLost;
        Test.startTest();
        update opp;
        Test.stopTest();

        System.assertEquals(opp.StageName, closedLost, 'StageName doesnt match');
    }

    @isTest
    static void closedWon() {
        final Opportunity opp = [select Id, StageName from Opportunity where Name =: 'OppTest Close Won'];
        opp.MX_SB_VTS_Aplica_Cierre__c = true;
        opp.StageName = closedWon;
        Test.startTest();
        update opp;
        Test.stopTest();

        System.assertEquals(opp.StageName, closedWon, 'Stage match');
    }
}