src/objects/EU001_RI__c.object
<CustomObject>
    <description>Contiene los datos necesarios de la RI para su asociacion con los Compromisos</description>
    <label>Reunión Individual</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>No RI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reunión Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EU_001_Compromiso__c.object
<CustomObject>
    <description>Compromisos Experiencia Única</description>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Compromiso EU</relationshipLabel>
        <relationshipName>Compromiso_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EU001_Un_nivelPriorizacion__c</fullName>
        <description>Nivel al que corresponde la priorización del compromio</description>
        <label>Nivel Priorización</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_001_Rb_Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación a Oportunidad Experiencia única</description>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Compromiso EU</relationshipLabel>
        <relationshipName>Compromiso_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EU_001_Rb_Revisi_n_Individual_RI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Revisión Individual (RI)</description>
        <label>Reunión Individual</label>
        <referenceTo>EU001_RI__c</referenceTo>
        <relationshipLabel>Compromiso EU</relationshipLabel>
        <relationshipName>Compromiso_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EU_001_dv_Compromiso__c</fullName>
        <description>Monto en pesos para el compromiso de Experiencia única</description>
        <inlineHelpText>Pesos</inlineHelpText>
        <label>Compromiso</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EU_001_ls_Estatus__c</fullName>
        <description>Estatus para identificar el compromiso Experiencia única</description>
        <label>Estatus del Compromiso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abierto</fullName>
                    <default>true</default>
                    <label>Abierto</label>
                </value>
                <value>
                    <fullName>Descartado</fullName>
                </value>
                <value>
                    <fullName>En Gestion</fullName>
                    <label>En Gestión</label>
                </value>
                <value>
                    <fullName>Hecho</fullName>
                </value>
                <value>
                    <fullName>Reprogramado</fullName>
                </value>
                <value>
                    <fullName>Vencido</fullName>
                </value>
                <value>
                    <fullName>Cambiar Fecha de disposición</fullName>
                    <isActive>false</isActive>
                    <label>Cambiar Fecha de disposición</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EU_001_ls_Indicadores_de_cartera__c</fullName>
        <description>Listado indicadores de cartera para experiencia única</description>
        <label>Tipo de compromiso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cartera Vigente CP</fullName>
                </value>
                <value>
                    <fullName>Cartera Vigente LP</fullName>
                </value>
                <value>
                    <fullName>Cartera Vigente</fullName>
                </value>
                <value>
                    <fullName>Vista MN</fullName>
                </value>
                <value>
                    <fullName>Inversiones</fullName>
                </value>
                <value>
                    <fullName>Resto Captación</fullName>
                </value>
                <value>
                    <fullName>INF Recurrentes</fullName>
                </value>
                <value>
                    <fullName>Stock Nomina</fullName>
                </value>
                <value>
                    <fullName>Usuarios nuevos crédito</fullName>
                </value>
                <value>
                    <fullName>Saneamiento</fullName>
                </value>
                <value>
                    <fullName>Usuario Nvo de Credito</fullName>
                </value>
                <value>
                    <fullName>INF No Recurrentes</fullName>
                </value>
                <value>
                    <fullName>Margen Bruto</fullName>
                </value>
                <value>
                    <fullName>Análisis de crédito</fullName>
                </value>
                <value>
                    <fullName>IReNe</fullName>
                </value>
                <value>
                    <fullName>Plan de Cuenta</fullName>
                </value>
                <value>
                    <fullName>Visitas</fullName>
                </value>
                <value>
                    <fullName>Otros</fullName>
                </value>
                <value>
                    <fullName>Captación</fullName>
                </value>
                <value>
                    <fullName>Colocación</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Servicios</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EU_001_tx_Compromiso__c</fullName>
        <description>Descripción del compromiso</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Describa el compromiso</inlineHelpText>
        <label>Compromiso</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EU_fm_Fecha_Cierre__c</fullName>
        <description>Fecha de cierre Experiencia única</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de cierre</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MX_EU_Avance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Compromiso Actividad/Cierre</description>
        <inlineHelpText>Seleccionado: Actividad,
No seleccionado: Cierre</inlineHelpText>
        <label>Actividad</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_EU_TipoPriorizacion__c</fullName>
        <description>Determina quien priorizó basandose en el campo: nivel de priorización</description>
        <formula>CASE( EU001_Un_nivelPriorizacion__c ,1, &apos;DO&apos; ,2, &apos;DR&apos; ,3, &apos;DD&apos; ,&apos;-&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tipo de Priorización</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU001_Fm_Historico_Cambios_Fecha_Cierre__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Almacena el historico de los cambios de la fecha de cierre del compromiso.</description>
        <label>Historico Cambios Fecha Cierre</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EU_001_Fm_Cliente__c</fullName>
        <description>Nombre comercial del cliente Experiencia única</description>
        <formula>EU_001_Rb_Oportunidad__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cliente</label>
        <type>Text</type>
    </fields>
    <label>Compromiso EU</label>
    <nameField>
        <displayFormat>EUCP-{0000}</displayFormat>
        <label>Compromiso EU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compromiso EU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_RTL_Familia__c</fullName>
        <description>Listado de familia de productos</description>
        <label>Familia</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Captación</fullName>
                </value>
                <value>
                    <fullName>Colocación</fullName>
                </value>
                <value>
                    <fullName>Servicios</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_RTL_Producto__c</fullName>
        <description>Listado de los productos dependientes de la familia seleccionada en la oportunidad</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_RTL_Familia__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cuenta en Dólares</fullName>
                </value>
                <value>
                    <fullName>Fondos de Inversión</fullName>
                </value>
                <value>
                    <fullName>Maestra Patrimonial Dólares</fullName>
                </value>
                <value>
                    <fullName>Membresía BP</fullName>
                </value>
                <value>
                    <fullName>Nómina</fullName>
                </value>
                <value>
                    <fullName>Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Producto 21</fullName>
                </value>
                <value>
                    <fullName>MLB</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Consumo</fullName>
                </value>
                <value>
                    <fullName>Hipotecario</fullName>
                </value>
                <value>
                    <fullName>TDC</fullName>
                </value>
                <value>
                    <fullName>PrePaid Forward</fullName>
                </value>
                <value>
                    <fullName>Collares</fullName>
                </value>
                <value>
                    <fullName>Alertas</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Domiciliaciones</fullName>
                </value>
                <value>
                    <fullName>Servicios No Financieros</fullName>
                </value>
                <value>
                    <fullName>Traspaso Patrimonial</fullName>
                </value>
                <value>
                    <fullName>One Team</fullName>
                </value>
                <value>
                    <fullName>Fideicomiso</fullName>
                </value>
                <value>
                    <fullName>Socios Globales</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro</fullName>
                </value>
                <value>
                    <fullName>Gastos Médicos Mayores Indemnizatorio</fullName>
                </value>
                <value>
                    <fullName>Hogar Seguro Plus</fullName>
                </value>
                <value>
                    <fullName>Vida Segura Patrimonial</fullName>
                </value>
                <value>
                    <fullName>Meta Segura</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_BPP_RI_ListaCompromisos_Ctrl.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     MX_BPP_VistaRI_Ctrl
* @Author   Cindy Hernández cindyarianna.hernandez.nieto.contractor@bbva.com
* @Date     Created: 2019-06-12
* @Group    Digital Workplace Retail
* @Description Get the cases owned by the banker
* @Comments Created from the clipped code from the EU001_cls_ConsolaDirector class
* @Changes
**/

public With Sharing class MX_BPP_RI_ListaCompromisos_Ctrl {

    //Constructor with no arguments
    @TestVisible
    private MX_BPP_RI_ListaCompromisos_Ctrl() {
    }

    @AuraEnabled
    /** Creacion de metodo*/
    public static void getInsertaCompromiso (String RType, Account Cliente,String TipoComp,String Compromiso,string sFechaCierre,String Estatus,Integer HCambios,String sIdRI) {
        String TipoRegistro='';
        date FechaCierre = Date.valueOf(sFechaCierre);
        EU001_RI__c RISeleccionada;

        RISeleccionada = ([SELECT Id, OwnerId FROM EU001_RI__c WHERE Id =: sIdRI LIMIT 1]);
        EU_001_Compromiso__c comp = new EU_001_Compromiso__c();
        if(Cliente!=null) {
            comp.Cliente__c=Cliente.Id;
        }
        comp.EU_001_Rb_Revisi_n_Individual_RI__c=RISeleccionada.Id;
        comp.EU_001_ls_Indicadores_de_cartera__c=TipoComp;

        if(TipoComp==EU001_CLS_CONSTANTES.EU001_STR_SANEAMIENTO) {
            TipoRegistro = getRecordTypeId('EU_001_Compromiso__c',TipoComp);
            comp.EU_001_dv_Compromiso__c=decimal.valueOf(Compromiso);
        } else if (TipoComp ==EU001_CLS_CONSTANTES.EU001_STR_USUARIO_CREDITO) {
            TipoRegistro = getRecordTypeId('EU_001_Compromiso__c',EU001_CLS_CONSTANTES.EU001_TRE_COMPROMISO_NVOS_USUARIOS);
            comp.EU_001_dv_Compromiso__c=decimal.valueOf(Compromiso);
        } else {
            comp.EU_001_tx_Compromiso__c=Compromiso;
            TipoRegistro=RType;
        }

        comp.RecordTypeId=TipoRegistro;
        comp.EU_fm_Fecha_Cierre__c=FechaCierre;
        comp.EU_001_ls_Estatus__c=Estatus;
        comp.EU001_Fm_Historico_Cambios_Fecha_Cierre__c=HCambios;
        comp.OwnerId=RISeleccionada.OwnerId;
        try {
            insert comp;
        } catch(DmlException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
    }

    @AuraEnabled
    /** metodo VerificaDirector*/
    public static Boolean VerificaDirector() {
        Boolean temp = false;
        List<UserRole> NivelAbajoFuncion = new List<UserRole>();
        try {
            List<User> funcionDelUsuario = ([SELECT Id, Name, UserRoleId FROM User WHERE Id =: userInfo.getUserId() LIMIT 1]);
            NivelAbajoFuncion = [SELECT Name, Id, ParentRoleId FROM UserRole WHERE ParentRoleId =: funcionDelUsuario[0].UserRoleId];
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
         if(!NivelAbajoFuncion.isEmpty()) {
            temp = true;
        }
        return temp;
    }

/*@Descripción
10/09/2018       Luis Fernando Romero
Se agregan parametros a búsqueda de compromisos, convierte a query dinámica  */
    @AuraEnabled
    public static list<CompEU_Table> getTableCompromisos(String IdRI, String filtroEstatus, String filtroType, string indicador, string fechainicio, String fechafin, String campoPadre, String campoHijo) {
        map<Id, CompEU_Table> mapResult = new map<Id, CompEU_Table>();
        list<boolean> listType = new list<Boolean>{true, false};
        list<string> lInds = getPickListValues();
        if (!string.isBlank(filtroType)) {
            listType.clear();
            listType.add(Boolean.valueOf(filtroType));
        }
        if (!string.isBlank(indicador)) {
            lInds.clear();
            lInds.add(indicador);
        }
        if('Generales'.equals(indicador)) {
            lInds.addAll(new List<string>{'Análisis de crédito', 'IReNe', 'Saneamiento', 'Usuario Nvo de Credito', 'Plan de Cuenta', 'Visitas', 'Otros'});
        }
        List<EU_001_Compromiso__c> compromisosList = new List<EU_001_Compromiso__c>();
        try {
            compromisosList = getCompromisos(IdRI, filtroEstatus, fechainicio, fechafin, campoPadre, campoHijo, lInds, listType);
        } catch(QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        for(EU_001_Compromiso__c ls : compromisosList) {
           if(mapResult.containsKey(ls.OwnerId)) {
              mapResult.get(ls.OwnerId).lsOpp.add(ls);
            } else {
              mapResult.put(ls.OwnerId, new CompEU_Table(new list<EU_001_Compromiso__c>{ls}));
            }
        }

        return mapResult.values();
    }

/**
* --------------------------------------------------------------------------------------
* @Author       Cindy Hernández cindyarianna.hernandez.nieto.contractor@bbva.com
* Date          17-06-2019
* @Description  Get commitments.
* @Comments     Created from the clipped code block of method getTableCompromisos.
* @param        String IdRI, String filtroEstatus, String fechainicio, String fechafin,
                String campoPadre, String campoHijo, List<string> lInds, List<boolean> listType
* @return       List<EU_001_Compromiso__c>
* @example      public static List<EU_001_Compromiso__c> getCompromisos(String IdRI, String filtroEstatus,
                String fechainicio, String fechafin, String campoPadre, String campoHijo, List<string> lInds, 
                List<boolean> listType){
**/
    public static List<EU_001_Compromiso__c> getCompromisos(String IdRI, String filtroEstatus, String fechainicio, String fechafin, String campoPadre, String campoHijo, List<string> lInds, List<boolean> listType) {
        string query, conditions='';
        list<string> lsEstatus= new list<String>{'Abierto','Reprogramado'};
        if(string.isNotBlank(filtroEstatus)) {
            if('Vencido'.equals(filtroEstatus)||'Default'.equals(filtroEstatus)) {
                query='SELECT OwnerId, Owner.Name, EU_001_ls_Indicadores_de_cartera__c,Name,EU_001_dv_Compromiso__c,EU_fm_Fecha_Cierre__c,EU_001_ls_Estatus__c,EU_001_Rb_Oportunidad__r.Name,EU_001_Rb_Oportunidad__c,EU_001_Rb_Oportunidad__r.MX_RTL_Familia__c,EU_001_Rb_Oportunidad__r.MX_RTL_Producto__c, EU_001_Rb_Oportunidad__r.AccountId, EU_001_Rb_Oportunidad__r.Account.Name, EU_001_Rb_Oportunidad__r.StageName, EU_001_Fm_Cliente__c, Cliente__c, Cliente__r.Name,EU_001_tx_Compromiso__c, MX_EU_TipoPriorizacion__c FROM EU_001_Compromiso__c WHERE EU_001_Rb_Revisi_n_Individual_RI__c =: IdRI and EU_001_ls_Estatus__c=:lsEstatus and EU_001_ls_Indicadores_de_cartera__c=:lInds and MX_EU_Avance__c=:listType ';
            } else {
                query='SELECT OwnerId, Owner.Name, EU_001_ls_Indicadores_de_cartera__c,Name,EU_001_dv_Compromiso__c,EU_fm_Fecha_Cierre__c,EU_001_ls_Estatus__c,EU_001_Rb_Oportunidad__r.Name,EU_001_Rb_Oportunidad__c,EU_001_Rb_Oportunidad__r.MX_RTL_Familia__c,EU_001_Rb_Oportunidad__r.MX_RTL_Producto__c, EU_001_Rb_Oportunidad__r.AccountId, EU_001_Rb_Oportunidad__r.Account.Name, EU_001_Rb_Oportunidad__r.StageName, EU_001_Fm_Cliente__c, Cliente__c, Cliente__r.Name,EU_001_tx_Compromiso__c, MX_EU_TipoPriorizacion__c FROM EU_001_Compromiso__c WHERE EU_001_Rb_Revisi_n_Individual_RI__c =: IdRI and EU_001_ls_Estatus__c=:filtroEstatus and EU_001_ls_Indicadores_de_cartera__c=:lInds and MX_EU_Avance__c=:listType ';
            }
        } else {
				query='SELECT OwnerId, Owner.Name, EU_001_ls_Indicadores_de_cartera__c,Name,EU_001_dv_Compromiso__c,EU_fm_Fecha_Cierre__c,EU_001_ls_Estatus__c,EU_001_Rb_Oportunidad__r.Name,EU_001_Rb_Oportunidad__c,EU_001_Rb_Oportunidad__r.MX_RTL_Familia__c,EU_001_Rb_Oportunidad__r.MX_RTL_Producto__c, EU_001_Rb_Oportunidad__r.AccountId, EU_001_Rb_Oportunidad__r.Account.Name, EU_001_Rb_Oportunidad__r.StageName, EU_001_Fm_Cliente__c, Cliente__c, Cliente__r.Name,EU_001_tx_Compromiso__c, MX_EU_TipoPriorizacion__c FROM EU_001_Compromiso__c WHERE EU_001_Rb_Revisi_n_Individual_RI__c =: IdRI and EU_001_ls_Indicadores_de_cartera__c=:lInds and MX_EU_Avance__c=:listType ';
        }

        if('Vencido'.equals(filtroEstatus)) {
            Date today = Date.today(); //NOSONAR
            conditions+= ' AND EU_fm_Fecha_Cierre__c <: today ';
        }
        if(string.isNotblank(fechainicio)) {
            Date fInicio = Date.valueOf(fechainicio); //NOSONAR
            conditions+= ' AND EU_fm_Fecha_Cierre__c >=:fInicio ';
        }
        if(string.isNotblank(fechafin)) {
            Date fFin = Date.valueOf(fechafin); //NOSONAR
            conditions+= ' AND EU_fm_Fecha_Cierre__c <=:fFin ';
        }
		if(string.isNotblank(campoPadre)) {
            conditions+= ' AND EU_001_Rb_Oportunidad__r.MX_RTL_Familia__c =:campoPadre';
        }
        if(string.isNotblank(campoHijo)) {
            conditions+= ' AND EU_001_Rb_Oportunidad__r.MX_RTL_Producto__c =:campoHijo';
        }
        conditions += ' ORDER BY EU001_Un_nivelPriorizacion__c desc nulls last, EU_fm_Fecha_Cierre__c ASC';
        query += conditions;
        List<EU_001_Compromiso__c> compromisosList = Database.query(query);
        return compromisosList;
    }
    /**metodo CompEU_Table */
    public class CompEU_Table {

        @AuraEnabled
        /** */
        public list<EU_001_Compromiso__c> lsOpp {get; set;}
        /** */
        public CompEU_Table( list<EU_001_Compromiso__c> toOpp) {

            this.lsOpp = toOpp;

        }
    }
    /** Lista*/
    public static List<String> getPickListValues() {
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = EU_001_Compromiso__c.EU_001_ls_Indicadores_de_cartera__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple) {
            pickListValuesList.add(pickListVal.getValue());
        }
        return pickListValuesList;
    }

    @AuraEnabled
    /** Lista getUser*/
    public static List<EU001_RI__c> getUser(String recordId) {
        List<EU001_RI__c> lista = new List<EU001_RI__c>();
        try {
            lista = EU001_cls_ConsolaDirector.getUser(recordId);
        } catch (QueryException e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return lista;
    }

    @AuraEnabled
    /** Metodo getRecordTypeId*/
    public static String getRecordTypeId(String sObjType ,String Concepto) {
        Id IdRType;
        try {
            IdRType = EU001_modApoyos_Ctrl.getRecordTypeId(sObjType , Concepto);
        } catch(Exception e) {
            throw new AuraHandledException(System.Label.MX_BPP_PyME_Error_Generico+ ' ' + e);
        }
        return ''+IdRType;
    }

}