src/objects/EU_001_Compromiso__c.object
<CustomObject>
    <description>Compromisos Experiencia Única</description>
    <fields>
        <fullName>EU_001_dv_Compromiso__c</fullName>
        <description>Monto en pesos para el compromiso de Experiencia única</description>
        <inlineHelpText>Pesos</inlineHelpText>
        <label>Compromiso</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EU_001_ls_Indicadores_de_cartera__c</fullName>
        <description>Listado indicadores de cartera para experiencia única</description>
        <label>Tipo de compromiso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cartera Vigente CP</fullName>
                </value>
                <value>
                    <fullName>Cartera Vigente LP</fullName>
                </value>
                <value>
                    <fullName>Cartera Vigente</fullName>
                </value>
                <value>
                    <fullName>Vista MN</fullName>
                </value>
                <value>
                    <fullName>Inversiones</fullName>
                </value>
                <value>
                    <fullName>Resto Captación</fullName>
                </value>
                <value>
                    <fullName>INF Recurrentes</fullName>
                </value>
                <value>
                    <fullName>Stock Nomina</fullName>
                </value>
                <value>
                    <fullName>Usuarios nuevos crédito</fullName>
                </value>
                <value>
                    <fullName>Saneamiento</fullName>
                </value>
                <value>
                    <fullName>Usuario Nvo de Credito</fullName>
                </value>
                <value>
                    <fullName>INF No Recurrentes</fullName>
                </value>
                <value>
                    <fullName>Margen Bruto</fullName>
                </value>
                <value>
                    <fullName>Análisis de crédito</fullName>
                </value>
                <value>
                    <fullName>IReNe</fullName>
                </value>
                <value>
                    <fullName>Plan de Cuenta</fullName>
                </value>
                <value>
                    <fullName>Visitas</fullName>
                </value>
                <value>
                    <fullName>Otros</fullName>
                </value>
                <value>
                    <fullName>Captación</fullName>
                </value>
                <value>
                    <fullName>Colocación</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Servicios</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EU_fm_Fecha_Cierre__c</fullName>
        <description>Fecha de cierre Experiencia única</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha de cierre</label>
        <type>Date</type>
    </fields>
    <label>Compromiso EU</label>
    <nameField>
        <displayFormat>EUCP-{0000}</displayFormat>
        <label>Compromiso EU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compromiso EU</pluralLabel>
    <recordTypes>
        <fullName>MX_BPP_CompColocacion</fullName>
        <active>true</active>
        <label>BPYP Colocación</label>
    </recordTypes>
    <recordTypes>
        <fullName>MX_BPP_Seguros</fullName>
        <active>true</active>
        <label>BPYP Seguros</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Monto_de_la_oportunidad_Inv__c</fullName>
        <description>Fondos corto plazo, Fondos mediano plazo, Fondos largo plazo y Cobertura/Renta variable</description>
        <inlineHelpText>Monto que el cliente desea invertir en Fondos de Inversión</inlineHelpText>
        <label>Monto de la oportunidad</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>op_amountPivote_dv__c</fullName>
        <description>Campo auxiliar para ligar los montos de oportunidad al Campo Amount. (Puente para salvar la relación que se crea con Product2 y OpportunityLineItem</description>
        <label>Monto de la Oportunidad</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Saldo_promedio__c</fullName>
        <label>Saldo promedio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Registro_Manual2__c</fullName>
        <description>Tipo de registro asociado a la oportunidad</description>
        <inlineHelpText>Tipo de Registro Manual</inlineHelpText>
        <label>Tipo de Registro de la Oportunidad</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adquirente</fullName>
                </value>
                <value>
                    <fullName>Adquirente v2</fullName>
                </value>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aportaciones</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>Banca de Inversión Empresas (BIE)</fullName>
                </value>
                <value>
                    <fullName>Banca electrónica</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bcom</fullName>
                </value>
                <value>
                    <fullName>BPyP</fullName>
                </value>
                <value>
                    <fullName>Cadenas de valor</fullName>
                </value>
                <value>
                    <fullName>CIB</fullName>
                </value>
                <value>
                    <fullName>CIE</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE V2</fullName>
                </value>
                <value>
                    <fullName>Coberturas y derivados</fullName>
                </value>
                <value>
                    <fullName>Comercio internacional</fullName>
                </value>
                <value>
                    <fullName>Consumer Finance</fullName>
                </value>
                <value>
                    <fullName>Cotización Arrendamiento</fullName>
                    <default>true</default>
                    <label>Cotización Arrendamiento</label>
                </value>
                <value>
                    <fullName>DEM</fullName>
                </value>
                <value>
                    <fullName>DEM V2</fullName>
                </value>
                <value>
                    <fullName>DIE</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Disposición</fullName>
                </value>
                <value>
                    <fullName>Domiciliación</fullName>
                </value>
                <value>
                    <fullName>Domiciliación PyME</fullName>
                </value>
                <value>
                    <fullName>Domiciliación V2</fullName>
                </value>
                <value>
                    <fullName>Fiduciario</fullName>
                </value>
                <value>
                    <fullName>Fiduciario V2</fullName>
                </value>
                <value>
                    <fullName>Financiamiento</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EU001_cls_CompHandler_Utilities.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     EU001_cls_CompHandler_Utilities
* @Author   Cindy Hernández cindyarianna.hernandez.nieto.contractor@bbva.com
* @Date     Created: 2019-07-12
* @Group    Digital Workplace Retail
* @Description Utility class for the EU001_cls_CompHandler class
* @Changes
**/
public with sharing class EU001_cls_CompHandler_Utilities {

    //Constructor with no arguments
    @TestVisible
    private EU001_cls_CompHandler_Utilities() {
    }

    /**
* --------------------------------------------------------------------------------------
* @Author       Cindy Hernández cindyarianna.hernandez.contractor@bbva.com
* Date          06-06-2019
* @Description  Obtain the opportunity data to update.
* @Comments     Created from the clipped code block of the method actualizaMonto of the class EU001_cls_CompHandler.
* @param        EU_001_Compromiso__c comp, Opportunity opp
* @return       Opportunity The opportunity with the data to be updated.
* @example      public static Opportunity oppsToUpdate(comp, opp){
**/
    public static Opportunity oppsToUpdate(EU_001_Compromiso__c comp, Opportunity opp) {
        Opportunity newOpp = new Opportunity();
        final List<String> tiposRegistroLista = new List<String>{EU001_cls_CONSTANTES.EU001_STR_FAMILIA_PRD_OPP_COMERCIO_MULTIRECAUDADOR,
            EU001_cls_CONSTANTES.EU001_STR_FAMILIA_PRD_OPP_COMERCIO_DEM,
            EU001_cls_CONSTANTES.EU001_STR_FAMILIA_PRD_OPP_SIT,
            EU001_cls_CONSTANTES.EU001_STR_FAMILIA_PRD_OPP_SWIFTTI,
            EU001_cls_CONSTANTES.EU001_STR_FAMILIA_PRD_OPP_ATM,
            EU001_cls_CONSTANTES.EU001_STR_FAMILIA_PRD_OPP_SEGUROS,
            /**
*************************************************************************************
*No.    |     Fecha      |     Autor                |          Descripción
*************************************************************************************
*1.0    | 07-06-2018     |    Monserrat Gonzalez      | Se agregaron tipos de registro de bypy para la actualización del monto
**/
            Label.MX_BPP_RI_TipoCompromisoCaptacion,
            Label.MX_BPP_RI_TipoCompromisoColocacion,
            Label.MX_BPP_RI_TipoCompromisoSeguros,
            Label.MX_BPP_RI_TipoCompromisoServicios,
            EU001_cls_CONSTANTES.EU001_STR_FAMILIA_PRD_OPP_COMERCIO_INTERNACIONAL};
                if(tiposRegistroLista.contains(opp.Tipo_de_Registro_Manual2__c) || tiposRegistroLista.contains(comp.EU_001_ls_Indicadores_de_cartera__c) &&
                   (opp.closeDate != comp.EU_fm_Fecha_Cierre__c  || opp.op_amountPivote_dv__c != comp.EU_001_dv_Compromiso__c)) {
                       newOpp.Id = opp.Id;
                       newOpp.closeDate = comp.EU_fm_Fecha_Cierre__c;
                       newOpp.op_amountPivote_dv__c = comp.EU_001_dv_Compromiso__c;
                   } else if(opp.Tipo_de_Registro_Manual2__c.equals(EU001_cls_CONSTANTES.EU001_STR_FAMILIA_PRD_OPP_INVERSIONES) && (opp.closeDate != comp.EU_fm_Fecha_Cierre__c  || opp.Monto_de_la_oportunidad_Inv__c != comp.EU_001_dv_Compromiso__c)) {
                       newOpp.Id = opp.Id;
                       newOpp.closeDate = comp.EU_fm_Fecha_Cierre__c;
                       newOpp.Monto_de_la_oportunidad_Inv__c = comp.EU_001_dv_Compromiso__c;
                   } else {
                       newOpp = getOppForDiffSaldo(comp, opp);
                   }

        return newOpp;
    }

    /**
* --------------------------------------------------------------------------------------
* @Author       Cindy Hernández cindyarianna.hernandez.contractor@bbva.com
* Date          07-07-2019
* @Description  Obtain the opportunity data to update.
* @Comments     Created from the clipped code block of the method oppsToUpdate.
* @param        EU_001_Compromiso__c comp, Opportunity opp
* @return       Opportunity The opportunity with the data to be updated.
* @example      getOppForDiffSaldo(comp, opp)
**/
    public static Opportunity getOppForDiffSaldo(EU_001_Compromiso__c comp, Opportunity opp) {
        final Opportunity newOpp = new Opportunity();
        if(opp.closeDate != comp.EU_fm_Fecha_Cierre__c  || opp.Saldo_promedio__c != comp.EU_001_dv_Compromiso__c) {
            newOpp.Id = opp.Id;
            newOpp.closeDate = comp.EU_fm_Fecha_Cierre__c;
            newOpp.Saldo_promedio__c = comp.EU_001_dv_Compromiso__c;
        }
        return newOpp;
    }

    public static void insertarCompromisos(List<EU_001_Compromiso__c> compList){
        if(!compList.isEmpty()) {
            insert compList;
        }
    }

    public static Boolean checkBPyP(String familia){
        Boolean isBPyP = false;
        if(familia.equals(Label.MX_BPP_RI_TipoCompromisoCaptacion) || familia.equals(Label.MX_BPP_RI_TipoCompromisoColocacion)
           || familia.equals(Label.MX_BPP_RI_TipoCompromisoSeguros) || familia.equals(Label.MX_BPP_RI_TipoCompromisoServicios)){
               isBPyP = true;
           }
        return isBPyP;
    }

    public static String setRecordTypeId(String familia){
        String rTypeID;
        if(familia.equals(Label.MX_BPP_RI_TipoCompromisoCaptacion)) {
            rTypeID =  Schema.SObjectType.EU_001_Compromiso__c.getRecordTypeInfosByName().get(Label.MX_BPP_CompCaptacion).getRecordTypeId();
        } else if(familia.equals(Label.MX_BPP_RI_TipoCompromisoColocacion)) {
            rTypeID =  Schema.SObjectType.EU_001_Compromiso__c.getRecordTypeInfosByName().get(Label.MX_BPP_CompColocacion).getRecordTypeId();
        } else if(familia.equals(Label.MX_BPP_RI_TipoCompromisoSeguros)) {
            rTypeID =  Schema.SObjectType.EU_001_Compromiso__c.getRecordTypeInfosByName().get(Label.MX_BPP_Seguros).getRecordTypeId();
        } else if(familia.equals(Label.MX_BPP_RI_TipoCompromisoServicios)) {
            rTypeID =  Schema.SObjectType.EU_001_Compromiso__c.getRecordTypeInfosByName().get(Label.MX_BPP_CompServicios).getRecordTypeId();
        }
        return rTypeID;
    }

}