src/objects/EU_001_Compromiso__c.object
<CustomObject>
    <description>Compromisos Experiencia Única</description>
    <fields>
        <fullName>EU_001_ls_Estatus__c</fullName>
        <description>Estatus para identificar el compromiso Experiencia única</description>
        <label>Estatus del Compromiso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abierto</fullName>
                    <default>true</default>
                    <label>Abierto</label>
                </value>
                <value>
                    <fullName>Descartado</fullName>
                </value>
                <value>
                    <fullName>En Gestion</fullName>
                    <label>En Gestión</label>
                </value>
                <value>
                    <fullName>Hecho</fullName>
                </value>
                <value>
                    <fullName>Reprogramado</fullName>
                </value>
                <value>
                    <fullName>Vencido</fullName>
                </value>
                <value>
                    <fullName>Cambiar Fecha de disposición</fullName>
                    <isActive>false</isActive>
                    <label>Cambiar Fecha de disposición</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compromiso EU</label>
    <nameField>
        <displayFormat>EUCP-{0000}</displayFormat>
        <label>Compromiso EU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compromiso EU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EU001_cls_PickListController_test.cls
/**
*Cambios (Versiones)
*************************************************************************************************************************
*No.    |     Fecha      |         Autor            |                  			Descripción
*************************************************************************************************************************
*1.1    |   17-06-2019   |    Cindy Hernández       | Se agregan métodos TestPickListException y TestPickListConstructor.
**/
@isTest
public class EU001_cls_PickListController_test {

    @isTest
   	static void TestPickList() {
        test.startTest();
		final List<String> TestList = EU001_cls_PickListController.getPickListValuesIntoList('EU_001_Compromiso__c','EU_001_ls_Estatus__c','');
        System.assert(TestList.contains('Abierto'));
        System.assert(true,'This Works!');
        test.stopTest();
    }

    @isTest
    static void TestPickListException() {
        String errorMessage = '';
        test.startTest();
        try {
            EU001_cls_PickListController.getPickListValuesIntoList('NoValidObject__c','EU_001_ls_Estatus__c','');
        } catch (Exception e) {
            errorMessage = e.getMessage();
        }
        test.stopTest();
        System.assertEquals('Script-thrown exception', errorMessage);
    }

    @isTest
    static void TestPickListConstructor() {
        String errorMessage = '';
        test.startTest();
        try {
	        final EU001_cls_PickListController picklist = new EU001_cls_PickListController();
            System.assert(picklist != null);
        } catch (Exception e) {
            errorMessage = e.getMessage();
        }
        test.stopTest();
        System.assertEquals('', errorMessage);
    }
}