src/objects/Evaluacion__c.object
<CustomObject>
    <fields>
        <fullName>Encuestado__c</fullName>
        <label>Asesor wibe</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RepresentanteCalidad__c</fullName>
        <label>Representante Calidad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Evaluación</label>
    <nameField>
        <displayFormat>EVAL-{000000000}</displayFormat>
        <label>Número de Evaluación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WIB_EvaluacionCalidadFirma_cls.cls
/** 
* 
*Creación de clase WIB_EvaluacionCalidadFirma_cls
*/
public with sharing class WIB_EvaluacionCalidadFirma_cls {
	/** variable sIdeval*/
	public String sIdeval {get;Set;}
	/** variable Eval*/
	public Evaluacion__c Eval {get;Set;}

  /**Un constructor por default*/
	public WIB_EvaluacionCalidadFirma_cls() {
		sIdeval = ApexPages.currentPage().getParameters().get('idEval');
    	Eval = [Select id, RepresentanteCalidad__c, Encuestado__c,  CreatedDate
      	From Evaluacion__c Where id =:sIdeval];

  	}
		/** Método */
  	public PageReference cancelEvaluacion() {
    	final PageReference pageRef = new ApexPages.StandardController(Eval).view();
    	pageRef.setRedirect(true);
    	return pageRef;
  	}


}