src/objects/iaso__GBL_Rest_Services_Url__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>iaso__Cache_Partition__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cache Partition</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iaso__Url__c</fullName>
        <description>Url of the Rest service</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <label>Rest Services Url</label>
</CustomObject>

src/objects/MX_SB_VTS_FamliaProveedores__c.object
<CustomObject>
    <description>Objeto intermedio para asignar familias a proveedores</description>
    <fields>
        <fullName>MX_SB_VTS_Familia_de_productos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nombre de la familia de productos.</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Familia Productos Proveedores</relationshipLabel>
        <relationshipName>Familia_Productos_Proveedores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Identificador_Proveedor__c</fullName>
        <description>Código de proveedor.</description>
        <formula>TEXT(MX_SB_VTS_ProveedorCTI__r.MX_SB_VTS_Identificador_Proveedor__c)</formula>
        <label>Identificador Proveedor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nombre del proveedor.</description>
        <label>ProveedorCTI</label>
        <referenceTo>MX_SB_VTS_ProveedoresCTI__c</referenceTo>
        <relationshipLabel>Familia Productos Proveedores</relationshipLabel>
        <relationshipName>Familia_Productos_Proveedores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Familia Producto Proveedor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Familia Producto Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familia Productos Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_Lead_tray__c.object
<CustomObject>
    <description>Objeto Creado para almacenar las bandejas generadas en los servicios. El objeto es Genérico para la creación de nuevos servicios.</description>
    <fields>
        <fullName>MX_SB_VTS_Description__c</fullName>
        <description>Descripción de las bandejas creadas.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Descripción</inlineHelpText>
        <label>Descripcion</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ID_Bandeja__c</fullName>
        <description>Id Generado en el servicio.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>ID de servicio generado.</inlineHelpText>
        <label>ID Bandeja</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Producto Relacionado con la bandeja.</description>
        <inlineHelpText>Inserta el producto relacionado con la bandeja,</inlineHelpText>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bandejas leads</relationshipLabel>
        <relationshipName>Bandejas_leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo relación a proveedor CTI</description>
        <label>ProveedorCTI</label>
        <referenceTo>MX_SB_VTS_ProveedoresCTI__c</referenceTo>
        <relationshipLabel>Bandejas leads</relationshipLabel>
        <relationshipName>Bandejas_leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipo_bandeja__c</fullName>
        <description>Tipo de bandeja</description>
        <label>Tipo bandeja HotLeads</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HotLeads</fullName>
                </value>
                <value>
                    <fullName>TrackingWeb</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bandejas lead</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de la bandeja</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bandejas leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_ProveedoresCTI__c.object
<CustomObject>
    <description>Objeto para registrar y dar de altas Proveedores de llamadas</description>
    <fields>
        <fullName>MX_SB_VTS_Identificador_Proveedor__c</fullName>
        <description>Identificador único de proveedores</description>
        <inlineHelpText>Seleccione un valor de la lista, si el valor que necesita no existe, por favor delo de alta en la lista global de Proveedores</inlineHelpText>
        <label>Identificador Proveedor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_Lista_Proveedores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_IsReadyCTI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si el proveedor esta preparado para la integración con Salesforce</description>
        <label>CTI Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_TieneSegmento__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo que indica si el proveedor permite la segmentación de campañas</description>
        <label>Segmentado</label>
        <type>Checkbox</type>
    </fields>
    <label>ProveedorCTI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Proveedores</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProveedoresCTI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caso_Relacionado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso Relacionado</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnviarCTI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Se hace validación, si fue verdadera envia a closed de CTI para dar atención.</description>
        <label>Enviar a CTI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_OppCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Oportunidades (Caso)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TelefonoCliente__c</fullName>
        <label>Teléfono Asegurado</label>
        <type>Phone</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Cuenta personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcNotiOppNoAten__c.object
<CustomObject>
    <description>Objeto que se usa para habilitar un trigger que levante los procesos cada 15 minutos.</description>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proceso__c</fullName>
        <label>Proceso</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ProcNotiOppNoAten</label>
    <nameField>
        <displayFormat>PNOA-{00000}</displayFormat>
        <label>Nombre de ProcNotiOppNoAten</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProcNotiOppNoAten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Products (Familia de productos)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_Familia_Productos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación a familia de producto.</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Presupuestos</relationshipLabel>
        <relationshipName>Presupuestos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Folio_Cotizacion__c</fullName>
        <description>Folio de la póliza.</description>
        <label>Folio Cotizacion</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Movil_txt__c</fullName>
        <description>Número de teléfono en texto para búsqueda</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Movil</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/MX_SB_VTS_Lista_Proveedores.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ninguno</fullName>
        <default>true</default>
        <label>Ninguno</label>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>VCIP</fullName>
    </customValue>
    <customValue>
        <fullName>SMART CENTER</fullName>
    </customValue>
    <description>Lista de nombres de proveedores</description>
    <masterLabel>Nombres Proveedores</masterLabel>
</GlobalValueSet>

src/classes/MX_SB_VTS_ScheduldOppsTele_tst.cls
/**
 * @File Name          : MX_SB_VTS_ScheduldOppsTele_tst.cls
 * @Description        : 
 * @Author             : Eduardo Hernández Cuamatzi
 * @Group              : 
 * @Last Modified By   : Eduardo Hernández Cuamatzi
 * @Last Modified On   : 7/10/2019 22:38:46
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    7/10/2019   Eduardo Hernández Cuamatzi     Initial Version
**/
@isTest
private class MX_SB_VTS_ScheduldOppsTele_tst { //NOSONAR

    /**Request service */
    final static String TXTPOST = 'POST', URLLOCAL = 'local.MXSBVTSCache',URLEXA='http://www.example.com';
    
    @TestSetup
    static void makeData(){
        final Id idAgente = UserInfo.getUserId();
        final Account accRec = MX_WB_TestData_cls.crearCuenta('LastName', 'PersonAccount');
        accRec.Phone = '5512345678';
        insert accRec;

        final MX_WB_FamiliaProducto__c objFamilyPro2 = MX_WB_TestData_cls.createProductsFamily ( 'Daños' );
        insert objFamilyPro2;

        final Product2 proHogar = MX_WB_TestData_cls.productNew ( System.Label.MX_SB_VTS_Hogar );
        proHogar.IsActive = true;
        proHogar.MX_WB_FamiliaProductos__c = objFamilyPro2.Id;
        insert proHogar;

        final Opportunity opp = MX_WB_TestData_cls.crearOportunidad('LastName', accRec.Id, idAgente, System.Label.MX_SB_VTS_Telemarketing_LBL);
        opp.Producto__c = 'Hogar';
        opp.TelefonoCliente__c = '5512341231';
        insert opp;

        final MX_SB_VTS_ProveedoresCTI__c smartProv = new MX_SB_VTS_ProveedoresCTI__c();
        smartProv.Name = 'Smart Center';
        smartProv.MX_SB_VTS_Identificador_Proveedor__c = 'SMART CENTER';
        smartProv.MX_SB_VTS_TieneSegmento__c = true;
        smartProv.MX_SB_VTS_IsReadyCTI__c = true;
        insert smartProv;
        
        final MX_SB_VTS_FamliaProveedores__c famProSmart = new MX_SB_VTS_FamliaProveedores__c();
        famProSmart.MX_SB_VTS_Familia_de_productos__c = objFamilyPro2.Id;
        famProSmart.Name = 'Daños SmartCenter';
        famProSmart.MX_SB_VTS_ProveedorCTI__c = smartProv.Id;
        insert famProSmart;

        final MX_SB_VTS_Lead_tray__c hotLeadsSmart = new MX_SB_VTS_Lead_tray__c();
        hotLeadsSmart.Name = 'HotLeads VCIP';
        hotLeadsSmart.MX_SB_VTS_Description__c = 'Bandeja para Tracking';
        hotLeadsSmart.MX_SB_VTS_ID_Bandeja__c = '1152';
        hotLeadsSmart.MX_SB_VTS_Producto__c = proHogar.Id;
        hotLeadsSmart.MX_SB_VTS_ProveedorCTI__c = smartProv.Id;
        hotLeadsSmart.MX_SB_VTS_Tipo_bandeja__c = 'HotLeads';
        insert hotLeadsSmart;

        insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenters_Crear_Carga', iaso__Url__c = URLEXA, iaso__Cache_Partition__c = URLLOCAL);
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'Authentication', iaso__Url__c = 'https://validation/ok', iaso__Cache_Partition__c = URLLOCAL);
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'bbvaMexSmartCenter', iaso__Url__c = 'https://bbvacifrado.smartcenterservicios.com/ws_salesforce_desarrollo/api/login/authenticate', iaso__Cache_Partition__c = URLLOCAL);

        final ProcNotiOppNoAten__c objProNotOppNoAten = MX_WB_TestData_cls.createProcNotiOppNoAten(null, '30', 'Matutino', false);
        objProNotOppNoAten.Proceso__c = System.Label.MX_SB_VTS_SchdProces;
		insert objProNotOppNoAten;
        
        final Quote quo2 = MX_WB_TestData_cls.crearQuote(opp.Id, '993 1 OppTest Hogar', '1234');
        quo2.MX_SB_VTS_Familia_Productos__c = objFamilyPro2.Id;
        Insert quo2;
        
    }

    @isTest
    private static void sendOppsSmart() {
        Test.setMock(HttpCalloutMock.class, new MX_SB_VTS_Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new MX_SB_VTS_Integration_MockGenerator());
        String sQuery = 'Select Opportunity.Id, Opportunity.AccountId, Status, Opportunity.EnviarCTI__c, Opportunity.LastModifiedDate, MX_SB_VTS_Familia_Productos__c,';
        sQuery += ' MX_SB_VTS_Folio_Cotizacion__c, Opportunity.OwnerId,Opportunity.Producto__c, Opportunity.Account.PersonEmail, MX_SB_VTS_Movil_txt__c From Quote ';
        sQuery += ' Where Opportunity.LeadSource = \'Tracking Web\'';
        sQuery += ' And Opportunity.AccountId != null';
        sQuery += ' And MX_SB_VTS_Folio_Cotizacion__c != null';
        sQuery += ' And CreatedDate >= ' + System.label.MX_SB_VTS_SCHEDULE_DATE_LBL;
        sQuery += ' And Opportunity.Caso_Relacionado__c = null';
        sQuery += ' And Opportunity.MX_SB_VTS_OppCase__c = null';
        sQuery += ' And MX_SB_VTS_Familia_Productos__r.Name = \'' + System.label.MX_SB_VTS_HogarFam + '\'';
        MX_SB_VTS_SendTrackingTelemarketing_cls sh1 = new MX_SB_VTS_SendTrackingTelemarketing_cls(sQuery, 1);
        Database.BatchableContext batchContext; 
        final List<Quote> scopeQuotes = [Select Id,Opportunity.Account.PersonEmail,Opportunity.TelefonoCliente__c, MX_SB_VTS_Familia_Productos__c from Quote where MX_SB_VTS_Familia_Productos__c NOT IN('')];
        Test.startTest();
        sh1.execute(batchContext, scopeQuotes);
        System.assert(scopeQuotes.isEmpty() == false, 'Execute correcto');
        Test.stopTest(); 
    }
    
    @isTest 
    private static void sendOppsSmartBch() {
        final ProcNotiOppNoAten__c programSch = [Select Id, Activo__c from ProcNotiOppNoAten__c where Proceso__c =: System.Label.MX_SB_VTS_SchdProces];
        Test.startTest();
			programSch.Activo__c = true;
			update programSch;	
			System.assert(programSch.Activo__c, 'Se hizo el cambio correctamente');
		Test.stopTest();
    }
}