src/objects/Lead.object
<CustomObject>
	<fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Campo que permite identificar cual es la tarea actual que se esta trabajando durante el proceso de venta Telemarketing</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LLamada Activa</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
<sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_CatalogoObjeciones__c.object
<CustomObject>
    <description>En este objeto se cargaran todas las objeciones correspondientes  a un producto o flujo de venta</description>
    <fields>
        <fullName>MX_SB_VTS_DetOjecion__c</fullName>
        <description>Texto detallado de la Objeción</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Detalle Objeción</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_NoUsoObjecion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica cuando una objeción no se utiliza</description>
        <label>No uso Objeción</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_NombreObjecion__c</fullName>
        <description>Nombre de la objeción</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre objeción</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ObjecionActiva__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si una objeción se encuentra activa</description>
        <label>Activa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ProductoObjecion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación al producto que aplica la objeción</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Catalogos de objeciones</relationshipLabel>
        <relationshipName>Catalogos_de_objeciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Relevancia__c</fullName>
        <description>Importancia de la Objeción</description>
        <label>Relevancia</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_TipoObjecion__c</fullName>
        <description>Tipo de objeción indica si se utiliza en Lead u Oportunidad</description>
        <label>Tipo Objeción</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_UsoObjecion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si se utilizo una objecion</description>
        <label>Uso Objeción</label>
        <type>Checkbox</type>
    </fields>
    <label>Catalogo objeciones</label>
    <nameField>
        <displayFormat>CatObje-{000}</displayFormat>
        <label>Nombre de Catalogo objectiones</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Catalogos de objeciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_Lead_tray__c.object
<CustomObject>
    <description>Objeto Creado para almacenar las bandejas generadas en los servicios. El objeto es Genérico para la creación de nuevos servicios.</description>
    <fields>
        <fullName>MX_SB_VTS_ID_Bandeja__c</fullName>
        <description>Id Generado en el servicio.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>ID de servicio generado.</inlineHelpText>
        <label>ID Bandeja</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Producto Relacionado con la bandeja.</description>
        <inlineHelpText>Inserta el producto relacionado con la bandeja,</inlineHelpText>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bandejas leads</relationshipLabel>
        <relationshipName>Bandejas_leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ProveedorCTI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo relación a proveedor CTI</description>
        <label>ProveedorCTI</label>
        <referenceTo>MX_SB_VTS_ProveedoresCTI__c</referenceTo>
        <relationshipLabel>Bandejas leads</relationshipLabel>
        <relationshipName>Bandejas_leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipo_bandeja__c</fullName>
        <description>Tipo de bandeja</description>
        <label>Tipo bandeja HotLeads</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HotLeads</fullName>
                </value>
                <value>
                    <fullName>TrackingWeb</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>MX_SB_VTS_ServicioID__c</fullName>
        <description>ID del servicio relacionado con la bandeja</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>ID del servicio relacionado con la bandeja</inlineHelpText>
        <label>Servicio</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Bandejas lead</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de la bandeja</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bandejas leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_ProveedoresCTI__c.object
<CustomObject>
    <description>Objeto para registrar y dar de altas Proveedores de llamadas</description>
    <fields>
        <fullName>MX_SB_VTS_Identificador_Proveedor__c</fullName>
        <description>Identificador único de proveedores</description>
        <inlineHelpText>Seleccione un valor de la lista, si el valor que necesita no existe, por favor delo de alta en la lista global de Proveedores</inlineHelpText>
        <label>Identificador Proveedor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_Lista_Proveedores</valueSetName>
        </valueSet>
    </fields>
    <label>ProveedorCTI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Proveedores</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProveedoresCTI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_SB_VTS_RegistroObjeciones__c.object
<CustomObject>
    <description>Mantiene la relación entre las objeciones y los registros de Lead y Opportunity</description>
    <fields>
        <fullName>MX_SB_VTS_CatObjecion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indica la Objeción que se aplico a un registro</description>
        <label>Catalogo objeciones</label>
        <referenceTo>MX_SB_VTS_CatalogoObjeciones__c</referenceTo>
        <relationshipLabel>Registros de Objeciones</relationshipLabel>
        <relationshipName>Registros_de_Objeciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_LeadLook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indica el registro Lead al cual se le aplico objeción</description>
        <label>Candidato</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Registros de Objeciones</relationshipLabel>
        <relationshipName>Registros_de_Objeciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Indica la llamada por la cual se generaron las objeciones</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LLamada Activa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_NoUsoObjecion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si la objeción no funciono</description>
        <label>No funciono</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ObjecionOpp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indica el registro de Oportunidad al que se le aplico Objeción</description>
        <label>Objeción Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Registros de Objeciones</relationshipLabel>
        <relationshipName>Registros_de_Objeciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ObjecionUtil__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si al asesor telefónico le resulto útil la objeción</description>
        <label>Se utilizo objeción</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_TipoObjecion__c</fullName>
        <description>Indica el tipo de objeción que se aplico</description>
        <label>Tipo Objeción</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Registro Objeciones</label>
    <nameField>
        <displayFormat>ObjecSelect-{00000}</displayFormat>
        <label>Nombre de Registro Objeciones</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de Objeciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Campo para referenciar la Tarea de llamada activa</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Tarea Activa</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/MX_SB_VTS_Lista_Proveedores.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ninguno</fullName>
        <default>true</default>
        <label>Ninguno</label>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>VCIP</fullName>
    </customValue>
    <customValue>
        <fullName>SMART CENTER</fullName>
    </customValue>
    <description>Lista de nombres de proveedores</description>
    <masterLabel>Nombres Proveedores</masterLabel>
</GlobalValueSet>

src/classes/MX_SB_VTS_Objeciones_cls.cls
/**
 * @File Name          : MX_SB_VTS_Objeciones_cls.cls
 * @Description        : 
 * @Author             : Eduardo Hernández Cuamatzi
 * @Group              : 
 * @Last Modified By   : Eduardo Hernández Cuamatzi
 * @Last Modified On   : 24/9/2019 11:35:02
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    4/9/2019   Eduardo Hernández Cuamatzi     Initial Version
**/
public without sharing class MX_SB_VTS_Objeciones_cls { //NOSONAR
    
    /** getObjetions : Recupera las objeciones correspondientes al producto y tipo de objeto */
    @AuraEnabled
    public static Map<String, Object> getObjetions(String recordId, String product, Boolean isLead) {
        final Map<String, Object> response = new Map<String, Object>();
        final String productName = MX_SB_VTS_Cotizador_ext.correctName(product);
        try {
            final String activeCall = getActiveCall(recordId, isLead);
            final Id productId = [Select Id from Product2 where IsActive = true AND Name =: productName].Id;
            final String tipoObjecion = isLead ? 'Objeciones' : 'Objeciones Reales';
            final List<WrapperObjects> lstObjeciones = new List<WrapperObjects>();
            final Map<Id,MX_SB_VTS_CatalogoObjeciones__c> mapObject = new Map<Id, MX_SB_VTS_CatalogoObjeciones__c>([Select Id, MX_SB_VTS_DetOjecion__c,MX_SB_VTS_NombreObjecion__c, 
                MX_SB_VTS_NoUsoObjecion__c, MX_SB_VTS_ObjecionActiva__c, MX_SB_VTS_ProductoObjecion__c, MX_SB_VTS_UsoObjecion__c,MX_SB_VTS_TipoObjecion__c
                from MX_SB_VTS_CatalogoObjeciones__c WHERE MX_SB_VTS_ProductoObjecion__c=: productId AND MX_SB_VTS_TipoObjecion__c=: tipoObjecion 
                AND MX_SB_VTS_ObjecionActiva__c=: true ORDER BY MX_SB_VTS_Relevancia__c ASC]);
            final Map<String,MX_SB_VTS_RegistroObjeciones__c> mapRegistro = new Map<String,MX_SB_VTS_RegistroObjeciones__c>();
            for(MX_SB_VTS_RegistroObjeciones__c recObject : [Select Id,MX_SB_VTS_NoUsoObjecion__c, MX_SB_VTS_CatObjecion__r.MX_SB_VTS_NombreObjecion__c, MX_SB_VTS_CatObjecion__c, MX_SB_VTS_ObjecionUtil__c 
                from MX_SB_VTS_RegistroObjeciones__c WHERE MX_SB_VTS_TipoObjecion__c =: tipoObjecion AND (MX_SB_VTS_LeadLook__c =: recordId OR MX_SB_VTS_ObjecionOpp__c=: recordId) AND MX_SB_VTS_LookActivity__c =: activeCall]) {
                    mapRegistro.put(recObject.MX_SB_VTS_CatObjecion__r.MX_SB_VTS_NombreObjecion__c, recObject);
                }
            for(MX_SB_VTS_CatalogoObjeciones__c catObjec : mapObject.values()) {
                final WrapperObjects objecion = new WrapperObjects();
                objecion.CatObject = catObjec.Id;
                objecion.detObjecion = catObjec.MX_SB_VTS_DetOjecion__c;
                objecion.nomObjecion = catObjec.MX_SB_VTS_NombreObjecion__c;
                objecion.usoObjecion = false;
                objecion.noUsoCatObject = false;
                if(mapRegistro.containsKey(objecion.nomObjecion)) {
                    objecion.noUsoCatObject = mapRegistro.get(objecion.nomObjecion).MX_SB_VTS_NoUsoObjecion__c;
                    objecion.usoObjecion = mapRegistro.get(objecion.nomObjecion).MX_SB_VTS_ObjecionUtil__c;
                    objecion.regObjec = mapRegistro.get(objecion.nomObjecion).Id;
                }
                lstObjeciones.add(objecion);
            }
            response.put('lstObjects', lstObjeciones);
            response.put('activeCall', activeCall);
        } catch(QueryException dEx) {
            throw new AuraHandledException(System.Label.MX_WB_lg_TlmktError + dEx);
        }
        return response;
    }

    /** getActiveCall: Recupera la llamada activa por la que se inicio el flujo*/
    public static String getActiveCall(String recordId, Boolean isLead) {
        String activeCall = '';
        if(isLead) {
           activeCall = [Select Id, MX_SB_VTS_LookActivity__c from Lead where Id =: recordId].MX_SB_VTS_LookActivity__c;
         } else {
             activeCall = [Select Id, MX_SB_VTS_LookActivity__c from Opportunity where Id =: recordId].MX_SB_VTS_LookActivity__c;
         }
         return activeCall;
    }

    /** saveObjectionscls: Genera los registros de las objeciones marcadas*/
    @AuraEnabled
    public static void saveObjectionscls(List<MX_SB_VTS_RegistroObjeciones__c> objeciones) {
        try {
            upsert objeciones;
        } catch (DmlException dEx) {            
            throw new AuraHandledException(System.Label.MX_WB_LG_ErrorBack+dEx);
        }
    }

    /** updateLeadsTray: Actualiza el Id de bandeja de HotLeads*/
    @AuraEnabled
    public static Map<String, Object> updateLeadsTray(String recordId) {
        final Map<String, Object> responseUpdate = new Map<String, Object>();
        try {
            final MX_SB_VTS_Lead_tray__c leadTray = [Select Id, MX_SB_VTS_ID_Bandeja__c, MX_SB_VTS_Producto__c, MX_SB_VTS_ProveedorCTI__c, 
            MX_SB_VTS_ServicioID__c, MX_SB_VTS_Tipo_bandeja__c, MX_SB_VTS_ProveedorCTI__r.MX_SB_VTS_Identificador_Proveedor__c 
            from MX_SB_VTS_Lead_tray__c where Id =:recordId];
            if(leadTray.MX_SB_VTS_Tipo_bandeja__c.equals(System.Label.MX_SB_VTS_HotLeads)) {
                String bandejaId = '';
                switch on leadTray.MX_SB_VTS_ProveedorCTI__r.MX_SB_VTS_Identificador_Proveedor__c {
                   when 'SMART CENTER' {
                       bandejaId = findLeadTraySmart();
                   }
                }
                leadTray.MX_SB_VTS_ID_Bandeja__c = bandejaId;
                update leadTray;
                responseUpdate.put('isOk',true);
            } else {
                responseUpdate.put('isOk',false);
            }
            return responseUpdate;
        } catch (DmlException dEx) {            
            throw new AuraHandledException(System.Label.MX_WB_LG_ErrorBack+dEx);
        }
    }

    /**
     * findLeadTraySmart recupera el Id de bandeja
     * @param  bandeja registro a recuperar
     * @return         Id de bandeja
     */
    public static String findLeadTraySmart() {
        final Map<String,Object> ret = MX_SB_VTS_SendLead_helper_cls.Crear_Carga_invoke(System.Label.MX_SB_VTS_SmartServiceHogar, 'HotLeads');
        return String.valueOf(ret.get('LOADID'));  
    }

    /**Clase wrapper de objeciones */
    public class WrapperObjects {
        /** Registro de catalogo*/
        @AuraEnabled
        public Id catObject {get;set;}
        /** Detalle Objecion*/
        @AuraEnabled
        public String detObjecion {get;set;}
        /** Nombre Tooltip*/
        @AuraEnabled
        public String nomObjecion {get;set;}
        /** Si se uso */
        @AuraEnabled
        public Boolean usoObjecion {get;set;}
        /** Si no se uso */
        @AuraEnabled
        public Boolean noUsoCatObject {get;set;}
        /** Id si ya existe registro */
        @AuraEnabled
        public Id regObjec {get;set;}
    }
}