src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>Hora_contacto__c</fullName>
    <description>Campo para guardar la fecha y hora en la cual el cliente requiere que se le vuelva a contactar.</description>
    <label>Hora De Contacto</label>
    <type>DateTime</type>
</fields>
<fields>
    <fullName>Priority__c</fullName>
    <label>Prioridad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/RTL_Lead_tgr_helper.cls
/** 
*
*@create class 
*/
public class RTL_Lead_tgr_helper {
    
 /**method */   
public static void verificaProducto(List<Lead> lstLeads) {
        for(Lead objLead:lstLeads) {
          	System.debug('HoraContacto: ' + objLead.Hora_contacto__c);
	    	System.debug('EN WB_Lead_Asignacion_cls.verificaProducto objLead: ' + objLead);          	
			//Prioridad 0.
			//Si la hora es igual a la hora actual y el estatus es igual a null entonces se pinta la prioridad 0.
			if(objLead.Priority__c == null && objLead.LeadSource == 'Call me back' && objLead.Hora_contacto__c == null) {
					objLead.Priority__c = '0';
			}
        }
        
    }
}