src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>EnviarCTI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EnviarCTI</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>xmlEnvio__c</fullName>
    <label>xmlEnvio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>
<fields>
    <fullName>xmlRespuesta__c</fullName>
    <label>xmlRespuesta</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/MX_WB_ActualizarLeadOppCTI_cls.cls
/**
 * Clase MX_WB_ActualizarLeadOppCTI_cls
 *
 */
public with sharing class MX_WB_ActualizarLeadOppCTI_cls {
	/**
    * Metodo Actualiza CTI Lead
    *
    * @param sRespuesta, doc y idobjeto
    * @return Lead
    */
	public static void actualizaCTILead(String sRespuesta, String doc, String idObjeto) {
		final Lead entLead = new Lead();
        entLead.Id = IdObjeto;
        entLead.xmlRespuesta__c = sRespuesta;
        entLead.xmlEnvio__c = doc;
        entLead.EnviarCTI__c = true;
        update entLead;
	}
}