src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>Folio_Cotizacion__c</fullName>
    <label>Folio Cotización</label>
    <length>10</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>EnviarCTI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EnviarCTI</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono1__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 1</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono2__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 2</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono3__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 3</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>xmlEnvio__c</fullName>
    <label>xmlEnvio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>
<fields>
    <fullName>xmlRespuesta__c</fullName>
    <label>xmlRespuesta</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>
<fields>
    <fullName>MX_WB_TM_Congelado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo sirve para no enviar el prospecto a CTI cuando tenga el valor activo</description>
    <label>Congelado</label>
    <type>Checkbox</type>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>ASD</fullName>
    <active>true</active>
    <businessProcess>ASD</businessProcess>
    <label>ASD</label>
</recordTypes>
</CustomObject>

src/objects/MX_WB_MotivosNoContacto__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Esta configuración almacena los Motivos de no contacti por los que un Prospecto puede no ser enviado nuevamente a CTI</description>
    <fields>
        <fullName>MX_WB_MotivoNoContacto__c</fullName>
        <label>Motivo no contacto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Motivos de no contacto</label>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Llamada</fullName>
        <active>true</active>
        <label>Llamada</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_WB_EnvioLeads4HrsCTI_bch.cls
/**
*
* Creacion de clase MX_WB_EnvioLeads4HrsCTI_bch
*/
global with sharing class MX_WB_EnvioLeads4HrsCTI_bch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
/**
*
* @
*/
	global String query { get; set; }
    /**
    *
    * @
    */
    public List<MX_WB_MotivosNoContacto__c> listaMotivosNoContacto {
        get { return [Select MX_WB_MotivoNoContacto__c FROM MX_WB_MotivosNoContacto__c];}
    }
     /**
    * 
    * @
    */
	global MX_WB_EnvioLeads4HrsCTI_bch(string query) {
		this.query = query;
	}
     /**
    * 
    * @
    */
	global Database.QueryLocator start(Database.BatchableContext batCbl) {
		return Database.getQueryLocator(this.query);
	}
     /**
    * 
    * @
    */
   	global void execute(Database.BatchableContext batCbl, List<Lead> scope) {
   		for (Lead prospecto : scope) {
            final ReturnLead checkedLead = checkTelephoneCalls(prospecto, prospecto.Tasks);
            final Lead objDetalleCliente = checkedLead.prospecto;
            if(checkedLead.enviarCTI) {
                List<String> sProcesaSol = new List<String>();
                final String Id = objDetalleCliente.Id;
                final String FolioCot = objDetalleCliente.Folio_Cotizacion__c;
                final String OwnerId = objDetalleCliente.OwnerId;
                final String Nombre = objDetalleCliente.FirstName;
                final String Telefono1 = objDetalleCliente.MX_WB_ph_Telefono1__c;
                final String Telefono2 = objDetalleCliente.MX_WB_ph_Telefono2__c;
                final String Telefono3 = objDetalleCliente.MX_WB_ph_Telefono3__c;
                final String Objeto = 'Lead';
                final Integer Tipo = 3;
                sProcesaSol = MX_WB_CTI_cls.procesaSol(Id, FolioCot,'ASD', OwnerId, Nombre, Telefono1,Objeto,Tipo, Telefono2, Telefono3);

                prospecto.EnviarCTI__c = true;
                prospecto.MX_WB_TM_Congelado__c = true;
                prospecto.xmlEnvio__c = sProcesaSol[1];
                prospecto.xmlRespuesta__c = sProcesaSol[0];
            }
   		}

        update scope;
	}
 /**
* 
*@
*/
    public ReturnLead checkTelephoneCalls(Lead lead, List<Task> llamadas) {
        final ReturnLead toReturn = new ReturnLead();
        final List<String> listaMotivos = new List<String>();
        for(MX_WB_MotivosNoContacto__c motivo: listaMotivosNoContacto) {
            listaMotivos.add(motivo.MX_WB_MotivoNoContacto__c);
        }
        Boolean falloTel1 = false;
        Boolean falloTel2 = false;
        Boolean falloTel3 = false;
        for(Task llamada : llamadas) {
            if(lead.MX_WB_ph_Telefono1__c == llamada.Telefono__c && listaMotivos.contains(llamada.Motivos_CONTACTO__c)) {
                falloTel1 = true;
                lead.MX_WB_ph_Telefono1__c = '';
            }
            if(lead.MX_WB_ph_Telefono2__c == llamada.Telefono__c && listaMotivos.contains(llamada.Motivos_CONTACTO__c)) {
                falloTel2 = true;
                lead.MX_WB_ph_Telefono2__c = '';
            }
            if(lead.MX_WB_ph_Telefono3__c == llamada.Telefono__c && listaMotivos.contains(llamada.Motivos_CONTACTO__c)) {
                falloTel3 = true;
                lead.MX_WB_ph_Telefono3__c = '';
            }
        }
        toReturn.prospecto = lead;
        toReturn.enviarCTI = true;
        if(falloTel1 && falloTel2 && falloTel3) {
            toReturn.enviarCTI = false;
        }
        return toReturn;
    }
/**
* 
* @
*/
    public class ReturnLead {
        /**
        *
        * @
        */
        public Lead prospecto {get;set;}
        /**
        *
        * @
        */
        public Boolean enviarCTI {get;set;}
    }
/**
*
* @
*/
	global void finish(Database.BatchableContext batCbl) {
		System.debug('EN MX_WB_EnvioLeadsCTI_bch.finish Hora: ' + DateTime.now());
	}
}