src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>Producto_Interes__c</fullName>
    <label>Producto de Interés</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compra Perfecta</fullName>
            </value>
            <value>
                <fullName>No especifica</fullName>
            </value>
            <value>
                <fullName>Otros Ramos ( Vida / Salud )</fullName>
            </value>
            <value>
                <fullName>Seguro auto Clasico</fullName>
            </value>
            <value>
                <fullName>Seguro de auto</fullName>
                <label>Seguro De Auto</label>
            </value>
            <value>
                <fullName>Seguro de Auto Otros Usos</fullName>
            </value>
            <value>
                <fullName>Seguro de auto Udi</fullName>
            </value>
            <value>
                <fullName>Seguro de Bicicleta</fullName>
            </value>
            <value>
                <fullName>Seguro de Moto</fullName>
            </value>
            <value>
                <fullName>Seguro de Moto UDI</fullName>
            </value>
            <value>
                <fullName>Seguro Fronterizo</fullName>
            </value>
            <value>
                <fullName>Seguro Legalizado</fullName>
            </value>
            <value>
                <fullName>Wiberizate</fullName>
            </value>
            <value>
                <fullName>Seguro de Moto Bancomer</fullName>
            </value>
            <value>
                <fullName>Seguro de auto fronterizo Bancomer</fullName>
            </value>
            <value>
                <fullName>Seguro de auto nacionalizado</fullName>
            </value>
            <value>
                <fullName>Auto Seguro Dinamico</fullName>
            </value>
            <value>
                <fullName>RC Carretero</fullName>
            </value>
			 <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
        </valueSetDefinition>
    </valueSet>
</fields>
<fields>
    <fullName>Resultadollamada__c</fullName>
    <label>Resultado de la llamada</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No contestó</fullName>
            </value>
            <value>
                <fullName>No le interesa</fullName>
            </value>
            <value>
                <fullName>Teléfono equivocado</fullName>
            </value>
            <value>
                <fullName>Teléfono inexistente</fullName>
            </value>
            <value>
                <fullName>Teléfono ocupado</fullName>
            </value>
			<value>
                <fullName>Contacto</fullName>
             </value>
             <value>
                    <fullName>No Contacto</fullName>
              </value>
        </valueSetDefinition>
    </valueSet>
</fields>
<fields>
    <fullName>MX_WB_txt_Clave_Texto__c</fullName>
    <description>Nuevo campo para telemarketing TREADMENCODE generado por affinium en resguardo</description>
    <label>Clave Texto</label>
    <length>25</length>
    <type>Text</type>
</fields>
<fields>
        <fullName>MX_SB_VTS_Tipificacion_LV2__c</fullName>
        <description>Indica el nivel 2 del arbol de tipificación</description>
        <label>¿Contacto Efectivo?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Resultadollamada__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Contacto No Efectivo</fullName>
                </value>
                <value>
                    <fullName>No Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV3__c</fullName>
        <description>Indica el nivel 3 del arbol de tipificación</description>
        <label>¿Interesado?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV2__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Interesado</fullName>
                </value>
                <value>
                    <fullName>No Aplica</fullName>
                </value>
                <value>
                    <fullName>No Interesado</fullName>
                </value>
                <value>
                    <fullName>No Interesado (CNE)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador Llamadas  Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>Contador de llamadas no efectivas al cliente</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador Llamadas  Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>Contador de llamadas no efectivas al cliente</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Contador_Email__c</fullName>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Contador Email</label>
        <type>AutoNumber</type>
    </fields>
<sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV1__c</fullName>
        <label>¿Contacto?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto</fullName>
                </value>
                <value>
                    <fullName>No Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV2__c</fullName>
        <label>¿Contacto Efectivo?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV1__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Contacto No Efectivo</fullName>
                </value>
                <value>
                    <fullName>No Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV3__c</fullName>
        <label>¿Interesado?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV2__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Interesado</fullName>
                </value>
                <value>
                    <fullName>No Aplica</fullName>
                </value>
                <value>
                    <fullName>No Interesado</fullName>
                </value>
                <value>
                    <fullName>No Interesado (CNE)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_WB_txt_Clave_Texto__c</fullName>
        <description>Nuevo campo para telemarketing TREADMENCODE generado por affinium en resguardo</description>
        <label>Clave Texto</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TelefonoCliente__c</fullName>
        <label>Teléfono Asegurado</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_LeadConvert_Ext.cls
/**
* BBVA - Mexico
* @Author: Jaime Terrats
* @Description: Controller extension for MX_WB_ConvertirLeadController
* @version 1.0
**/
public virtual without sharing class MX_SB_VTS_LeadConvert_Ext {//NOSONAR
    /**
    * validateNewFlow valida tipificaciones para saber si el lead se puede convertir
    * @param leadData datos del lead
    * @return Boolean para saber si hubo error o no
    *
    **/
    public static Boolean validateNewFlow(Lead leadData) {
        final Boolean isValid = true;
        final Id usr = UserInfo.getUserId();
        if(System.Label.MX_SB_VTS_Interesado.equals(leadData.MX_SB_VTS_Tipificacion_LV3__c) == false) {
            throw new AuraHandledException(System.Label.MX_SB_VTS_EstatusEfectivo);
        } else if(usr.equals(leadData.OwnerId) == false) {
            throw new AuraHandledException(System.Label.MX_SB_VTS_OwnerLead);
        } else if(System.Label.MX_SB_VTS_ResultadoLlamada.equals(leadData.Resultadollamada__c) == false) {
            throw new AuraHandledException(System.Label.MX_SB_VTS_ErrorTipificaciones);
        } else if(!System.Label.MX_SB_VTS_ContactoEfectivo.equals(leadData.MX_SB_VTS_Tipificacion_LV2__c)) {
            throw new  AuraHandledException(System.Label.MX_SB_VTS_ErrorTipificaciones);
        }
        return isValid;
    }

    /**
    * @Description: creates opp for new business process
    * @params: leadToConvert
    **/
    public static Opportunity createOppExt(Lead leadToConvert, Id accId) {
        final Id oppRtId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(System.Label.MX_SB_VTS_Telemarketing_LBL).getRecordTypeId();
        final Opportunity newOpp = new Opportunity();
        newOpp.AccountId = accId;
        newOpp.Name = leadToConvert.Name;
        newOpp.RecordTypeId = oppRtId;
        final String validProductName = MX_SB_VTS_CierreOpp.validacionproducto(leadToConvert.Producto_Interes__c);
        newOpp.Producto__c = validProductName;
        newOpp.StageName = System.Label.MX_SB_VTS_COTIZACION_LBL;
        newOpp.TelefonoCliente__c = leadToConvert.MobilePhone;
        newOpp.MX_WB_txt_Clave_Texto__c = leadToConvert.MX_WB_txt_Clave_Texto__c;
        newOpp.LeadSource = leadToConvert.LeadSource;
        newOpp.MX_SB_VTS_ContadorLlamadasTotales__c = leadToConvert.MX_SB_VTS_ContadorLlamadasTotales__c;
        newOpp.MX_SB_VTS_ContadorRemarcado__c = leadToConvert.MX_SB_VTS_ContadorRemarcado__c;
        newOpp.MX_SB_VTS_Llamadas_Efectivas__c = leadToConvert.MX_SB_VTS_Llamadas_Efectivas__c;
        newOpp.MX_SB_VTS_Llamadas_No_Efectivas__c = leadToConvert.MX_SB_VTS_Llamadas_No_Efectivas__c;
        newOpp.CloseDate = System.today();
        newOpp.MX_SB_VTS_Tipificacion_LV1__c =  leadToConvert.Resultadollamada__c;
        newOpp.MX_SB_VTS_Tipificacion_LV2__c =  leadToConvert.MX_SB_VTS_Tipificacion_LV2__c;
        newOpp.MX_SB_VTS_Tipificacion_LV3__c =  leadToConvert.MX_SB_VTS_Tipificacion_LV3__c;
        newOpp.Description=leadToConvert.Description;
        return newOpp;
    }
    /** Crea un email dummy si el lead no cuenta con email */
    public static String createDummyEmail(Lead leadToConvert) {
        return leadToConvert.MX_SB_VTS_Contador_Email__c + '@dummy.com';
    }
}