src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion__c</fullName>
        <description>Tipificación de CTI</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Tipificación</label>
        <length>255</length>
        <type>Text</type>
    </fields>
<fields>
    <fullName>RFC__c</fullName>
    <label>RFC</label>
    <length>25</length>
    <type>Text</type>
</fields>
<fields>
        <fullName>MX_SB_VTS_Tipificacion_LV2__c</fullName>
        <description>Indica el nivel 2 del arbol de tipificación</description>
        <label>¿Contacto Efectivo?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Resultadollamada__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Contacto No Efectivo</fullName>
                </value>
                <value>
                    <fullName>No Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV3__c</fullName>
        <description>Indica el nivel 3 del arbol de tipificación</description>
        <label>¿Interesado?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV2__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Interesado</fullName>
                </value>
                <value>
                    <fullName>No Aplica</fullName>
                </value>
                <value>
                    <fullName>No Interesado</fullName>
                </value>
                <value>
                    <fullName>No Interesado (CNE)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV4__c</fullName>
        <description>Indica el nivel 4 del arbol de tipificación</description>
        <label>¿Acepta Cotización / Contratación?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV3__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Aplica(CNE)</fullName>
                </value>
                <value>
                    <fullName>Acepta contratación</fullName>
                </value>
                <value>
                    <fullName>Acepta cotización</fullName>
                </value>
                <value>
                    <fullName>No Aplica</fullName>
                </value>
                <value>
                    <fullName>No acepta cotización</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV5__c</fullName>
        <description>Indica el nivel 5 del arbol de tipificación</description>
        <label>¿Venta?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV4__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acepta cotización</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
                <value>
                    <fullName>No Venta (acepta cotización)</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>No Venta (No contacto)</fullName>
                </value>
                <value>
                    <fullName>No Venta (No acepta cotización)</fullName>
                </value>
                <value>
                    <fullName>No Venta (CNE)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV6__c</fullName>
        <description>Indica el nivel 6 del arbol de tipificación</description>
        <label>Tipificación final</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV5__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_TipificacionNivel6</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador Llamadas  Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>Contador de llamadas no efectivas al cliente</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
	<fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Campo que permite identificar cual es la tarea actual que se esta trabajando durante el proceso de venta Telemarketing</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LLamada Activa</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador Llamadas  Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>Contador de llamadas no efectivas al cliente</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
<sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_LookActivity__c</fullName>
        <description>Campo para referenciar la Tarea de llamada activa</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Tarea Activa</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV1__c</fullName>
        <label>¿Contacto?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto</fullName>
                </value>
                <value>
                    <fullName>No Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV2__c</fullName>
        <label>¿Contacto Efectivo?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV1__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Contacto No Efectivo</fullName>
                </value>
                <value>
                    <fullName>No Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV3__c</fullName>
        <label>¿Interesado?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV2__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Interesado</fullName>
                </value>
                <value>
                    <fullName>No Aplica</fullName>
                </value>
                <value>
                    <fullName>No Interesado</fullName>
                </value>
                <value>
                    <fullName>No Interesado (CNE)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV4__c</fullName>
        <label>¿Acepta Cotización / Contratación?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV3__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Aplica(CNE)</fullName>
                </value>
                <value>
                    <fullName>Acepta contratación</fullName>
                </value>
                <value>
                    <fullName>Acepta cotización</fullName>
                </value>
                <value>
                    <fullName>No Aplica</fullName>
                </value>
                <value>
                    <fullName>No acepta cotización</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV5__c</fullName>
        <label>¿Venta?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV4__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acepta cotización</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
                <value>
                    <fullName>No Venta (acepta cotización)</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>No Venta (No contacto)</fullName>
                </value>
                <value>
                    <fullName>No Venta (No acepta cotización)</fullName>
                </value>
                <value>
                    <fullName>No Venta (CNE)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV6__c</fullName>
        <label>Tipificación final</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV5__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>MX_SB_VTS_TipificacionNivel6</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RFC__c</fullName>
        <description>RFC del asegurado.</description>
        <label>RFC del Asegurado</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorLlamadasTotales__c</fullName>
        <label>Contador Llamadas Totales</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RFC__c</fullName>
        <label>RFC</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/MX_SB_VTS_TipificacionNivel6.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TDC / TDD / BBVA</fullName>
    </customValue>
    <customValue>
        <fullName>TDC / TDD / BBVA MSI</fullName>
    </customValue>
    <customValue>
        <fullName>TDC / TDD Otro Banco</fullName>
    </customValue>
    <customValue>
        <fullName>Tarjeta Digital Wallet</fullName>
    </customValue>
    <customValue>
        <fullName>Tarjeta Digital Wallet MSI</fullName>
    </customValue>
    <customValue>
        <fullName>TDC / TDD / BBVA Rechazada</fullName>
    </customValue>
    <customValue>
        <fullName>TDC / TDD / CDC BBVA Rechazada</fullName>
    </customValue>
    <customValue>
        <fullName>No cuenta con datos para contratación</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente lo va a pensar</fullName>
    </customValue>
    <customValue>
        <fullName>Cuenta con producto similar otro banco</fullName>
    </customValue>
    <customValue>
        <fullName>TDC / TDD robada o extraviada</fullName>
    </customValue>
    <customValue>
        <fullName>Comparando precios</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente prefiere ir a sucursal</fullName>
    </customValue>
    <customValue>
        <fullName>Economía personal</fullName>
    </customValue>
    <customValue>
        <fullName>Precio alto del producto</fullName>
    </customValue>
    <customValue>
        <fullName>Prefiere otros productos</fullName>
    </customValue>
    <customValue>
        <fullName>Producto no cubre expectativas</fullName>
    </customValue>
    <customValue>
        <fullName>Requiere mayor suma asegurada</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente necesita otro servicio (Llamada entrante)</fullName>
    </customValue>
    <customValue>
        <fullName>Cuenta con producto similar BBVA</fullName>
    </customValue>
    <customValue>
        <fullName>No permite explicación de producto</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono equivocado</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente molesto (no llamar)</fullName>
    </customValue>
    <customValue>
        <fullName>No se escucha cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Desconfianza del medio de comunicación</fullName>
    </customValue>
    <customValue>
        <fullName>Mala experiencia BBVA</fullName>
    </customValue>
    <customValue>
        <fullName>Se dejó mensaje</fullName>
    </customValue>
    <customValue>
        <fullName>No le gustan los seguros</fullName>
    </customValue>
    <customValue>
        <fullName>Finado</fullName>
    </customValue>
    <customValue>
        <fullName>Desconfianza del producto ofertado</fullName>
    </customValue>
    <description>Resultado final del árbol de tipificación para el flujo de venta Telemarketing</description>
    <masterLabel>Tipificación CTI</masterLabel>
</GlobalValueSet>

src/classes/MX_SB_VTS_LeadAutoAssigner.cls
/*
*
* @author Jaime Terrats
* @description API to auto assign leads from Smart Center to call center agents
*
*           No  |     Date     |     Author      |    Description
* @version  1.0    06/24/2019     Jaime Terrats     Create API for Smart Center
* @version  1.1    06/25/2019     Jaime Terrats     Change logic to work with Opportunities or Leads
* @version  1.2    06/26/2019     Jaime Terrats     Add method to create tasks when api is invoked
* @version  1.2.1  06/28/2019     Jaime Terrats     Remove code smells
* @version  1.3    06/28/2019     julio Medellin    Change Stage On  Opporunity
* @version  1.4    09/23/2019     Jaime Terrats     Add json parse to read values from json object
* @version  1.5    10/03/2019     Jaime Terrats     Clear values on fields
*
*/
@RestResource(urlMapping='/leadAutoAssigner/*')
global without sharing class MX_SB_VTS_LeadAutoAssigner { // NOSONAR

    /*
* Method that performs lead auto assignment from
* Smart center by getting the LeadId and owner RFC
*/
    @HttpPost
    global static String assignLead() {
        final String baseUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/'; // NOSONAR
        final Map<String, Object> listener = (Map<String, Object>)JSON.deserializeUntyped(RestContext.request.requestBody.toString());

        final String recordId = String.valueOf(listener.get('recordId'));
        final String rfc =String.valueOf(listener.get('rfc'));
        final String callId = String.valueOf(listener.get('callId'));  // NOSONAR
        final String tipificacion = String.valueOf(listener.get('tipificacion'));  // NOSONAR

        String recordUrl = '';
        String type = ''; // NOSONAR
        Boolean isLead;
        if(String.isNotBlank(recordId)) {
            if(recordId.startsWith('00Q')) {
                type = 'Lead'; // NOSONAR
                isLead = true; // NOSONAR
            } else if(recordId.startsWith('006')) {
                type = 'Opportunity'; // NOSONAR
                isLead = false; // NOSONAR
            }
            final sObject record = getRecord(recordId, type);
            if(String.isNotBlank(recordId) && String.isNotBlank(rfc)) {

                final User usr = getUserInfo(rfc);
                if(String.isNotBlank(usr.Id)) {
                    try {
                        record.put('OwnerId', usr.Id);
                        recordUrl = baseUrl + record.Id;
                        final List<String> params = new List<String>();
                        params.add(callId);
                        params.add(record.Id);
                        params.add(String.valueOf(isLead));
                        params.add(usr.Id);
                        params.add(tipificacion);
                        final Task finalTask = createTask(params);
                        insert finalTask;
                        updateLead(record, isLead, finalTask.Id);
                        updateRecord(record, isLead, 1, 1, 1, 1);
                    } catch(DmlException dmlEx) {
                        recordUrl = System.Label.MX_WB_LG_ErrorBack; // NOSONAR
                        throw new DmlException(dmlEx);
                    }
                }
            } else {
                updateRecord(record, isLead, 1, 0, 1, 0);
                recordUrl = System.Label.MX_WB_LG_ErrorBack;
            }
        } else {
            recordUrl = System.Label.MX_WB_LG_ErrorBack;
        }
        return recordUrl;
    }

    /*
*
* Returns Agent Id
* @param: rfc string to find agent Id
*
*/
    private static User getUserInfo(String rfc) {
        return [Select Id from User where rfc__c =: rfc];
    }

    /*
*
* Increments fields from leads and opportunities based on a criteria
* @param:
*
*/
    public static void updateRecord(sObject record, Boolean isLead, Integer contadorLlamadas, Integer contadorToques, Integer contadorCe, Integer contadorCne) {
        if(isLead) {
            Lead leadUpdate = (Lead)record;

            final Integer llamadas = checkNullVals(leadUpdate.MX_SB_VTS_ContadorLlamadasTotales__c);
            final Integer toques = checkNullVals(leadUpdate.MX_SB_VTS_ContadorRemarcado__c);
            leadUpdate.MX_SB_VTS_ContadorLlamadasTotales__c = llamadas+contadorLlamadas;
            leadUpdate.MX_SB_VTS_ContadorRemarcado__c = toques+contadorToques;
            leadUpdate.Status =      Label.MX_SB_VTS_CONTACTO_LBL;
            leadUpdate.MX_SB_VTS_Tipificacion__c = '';
            leadUpdate.MX_SB_VTS_Tipificacion_LV2__c = '';
            leadUpdate.MX_SB_VTS_Tipificacion_LV3__c = '';
            leadUpdate.MX_SB_VTS_Tipificacion_LV4__c = '';
            leadUpdate.MX_SB_VTS_Tipificacion_LV5__c = '';
            leadUpdate.MX_SB_VTS_Tipificacion_LV6__c = '';
            update leadUpdate;
        } else {
            Opportunity oppUpdate = (Opportunity)record;

            final Integer llamadas = checkNullVals(oppUpdate.MX_SB_VTS_ContadorLlamadasTotales__c);
            final Integer toques = checkNullVals(oppUpdate.MX_SB_VTS_ContadorRemarcado__c);
            oppUpdate.MX_SB_VTS_ContadorLlamadasTotales__c = llamadas+contadorLlamadas;
            oppUpdate.MX_SB_VTS_ContadorRemarcado__c = toques+contadorToques;
            oppUpdate.StageName = Label.MX_SB_VTS_CONTACTO_LBL;
            oppUpdate.MX_SB_VTS_Tipificacion_LV1__c = '';
            oppUpdate.MX_SB_VTS_Tipificacion_LV2__c = '';
            oppUpdate.MX_SB_VTS_Tipificacion_LV3__c = '';
            oppUpdate.MX_SB_VTS_Tipificacion_LV4__c = '';
            oppUpdate.MX_SB_VTS_Tipificacion_LV5__c = '';
            oppUpdate.MX_SB_VTS_Tipificacion_LV6__c = '';
            update oppUpdate;
        }
    }
    /** */
    public static Integer checkNullVals (Decimal value) {
        Integer finalVal = 0;
        if(String.isNotBlank(String.valueOf(value))) {
            finalVal = Integer.valueOf(value);
        }
        return finalVal;
    }

    /*
*
* Update record
* @param: registro SObject, bandera es Lead, Id tarea
*
*/
    public static void updateLead(sObject record, Boolean isLead, Id taskId) {
        if(isLead) {
            final Lead leadRecord = (Lead)record;
            leadRecord.MX_SB_VTS_LookActivity__c = taskId;
            leadRecord.MX_SB_VTS_Tipificacion_LV6__c = '';
            update leadRecord;
        }
    }

    /*
*
* returns a lead or opportunity
* @params recorId return query data by record Id
* @params type used to define if the object is lead or opportunity
*
*/
    private static SObject getRecord(String recordId, String type) { // NOSONAR
        final String query = 'Select Id,MX_SB_VTS_ContadorRemarcado__c,MX_SB_VTS_Llamadas_Efectivas__c,MX_SB_VTS_Llamadas_No_Efectivas__c,MX_SB_VTS_ContadorLlamadasTotales__c, MX_SB_VTS_LookActivity__c, MX_SB_VTS_Tipificacion_LV6__c, OwnerId from ' + type +  ' where Id =: recordId';
        return Database.query(String.escapeSingleQuotes(query));
    }

    /*
*
* @param: params array with ids
* method: creates new task for reassigned lead / opportunity
*
*/
    private static Task createTask(List<String> params) {
        final Task newTask = new Task();
        newTask.Subject = 'Call';
        if(Boolean.valueOf(params[2])) {
            newTask.whoId = params[1];
        } else {
            newTask.whatId = params[1];
        }
        newTask.OwnerId = params[3];
        return newTask;
    }
}