src/objects/Lead.object
<CustomObject>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>ASD</fullName>
    <active>true</active>
    <businessProcess>ASD</businessProcess>
    <label>ASD</label>
</recordTypes>
</CustomObject>

src/objects/Scripts_Stage_Product__c.object
<CustomObject>
	<fields>
        <fullName>MX_SB_VTS_OrigenOpp__c</fullName>
        <description>Origen de la Oportunidad, para diferenciar scripts de Inbound</description>
        <label>Origen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call me back</fullName>
                </value>
                <value>
                    <fullName>Tracking Web</fullName>
                </value>
                <value>
                    <fullName>SAC</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound TLMK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>MX_WB_Etapa__c</fullName>
        <label>Etapa</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Políticas</fullName>
                </value>
                <value>
                    <fullName>Cotización</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
                <value>
                    <fullName>Venta Autorizada</fullName>
                </value>
                <value>
                    <fullName>Apertura</fullName>
                </value>
                <value>
                    <fullName>Cierre llamada no contacto</fullName>
                </value>
                <value>
                    <fullName>Información y condiciones</fullName>
                </value>
                <value>
                    <fullName>Venta cerrada</fullName>
                </value>
                <value>
                    <fullName>Cierre de llamada sin venta</fullName>
                </value>
                <value>
                    <fullName>Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WB_Script__c</fullName>
        <description>Script que será mostrado al asesor. Este script se visualiza dependiendo la etapa y el producto en el que se encuentre.</description>
        <label>Script</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Scripts Stage Product</label>
    <nameField>
        <label>Nombre de Scripts Stage Campaign</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts Stages Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_ScripLead_tst.cls
/**-------------------------------------------------------------------------
* Nombre: MX_SB_VTS_ScripLead_cls
* @author Arsenio Perez Lopez (xemo)
* Proyecto: MW SB VTS - BBVA 
* Descripción : Clase control para componente MX_SB_VTS_ScripLead

* --------------------------------------------------------------------------
*                         Fecha           Autor                   Desripción
* -------------------------------------------------------------------
* @version 1.0           25/04/2019      Arsenio  Perez            Creación
* @version 1.0           25/04/2019      Eduardo Hernandoez        Creación
* --------------------------------------------------------------------------*/
@isTest()
public with sharing class MX_SB_VTS_ScripLead_tst {
    
    @TestSetup
    static void makeData() {
        final Lead LeadTemp = MX_WB_TestData_cls.createLead('Juan');
        LeadTemp.Status= 'Apertura';
        LeadTemp.LeadSource='Inbound';
        LeadTemp.RecordTypeId = Schema.SobjectType.Lead.getRecordTypeInfosByDeveloperName().get('ASD').getRecordTypeId();
        Insert LeadTemp;
        Scripts_Stage_Product__c Script = new Scripts_Stage_Product__c(
            Name='Apertura', 
            MX_WB_Etapa__c= 'Apertura', 
            MX_SB_VTS_OrigenOpp__c ='Inbound',
            MX_WB_Script__c='juanito');
        insert Script;

    }

    @istest static void test2 () {
        final Lead tempLead = [select id, Status from lead where LastName = 'Juan'];
            test.startTest();
                final string temo =   MX_SB_VTS_ScripLead_cls.getScript(tempLead.Id);
                system.assertEquals('juanito', temo);
            test.stopTest();
    }

   @istest static void test3 () {       
            test.startTest();
            final string temo;
            try {
                temo =   MX_SB_VTS_ScripLead_cls.getScript('');
            } catch (AuraHandledException e) {
                system.assert(String.isEmpty(temo),'Valida que al ingresar un vacio no se regrese un script'+e.getMessage());
            }   
            test.stopTest();
    }

}