src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>Folio_Cotizacion__c</fullName>
    <label>Folio Cotización</label>
    <length>10</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>EnviarCTI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EnviarCTI</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_ContadorRemarcado__c</fullName>
    <label>Contador remarcado</label>
    <length>50</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>MX_WB_lst_EstatusBloqueado__c</fullName>
    <description>Nuevo campo Estatus Bloqueado de Tele marketing</description>
    <label>Estatus Bloqueado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estatusdecotizacion__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bloqueo 1 año</fullName>
            </value>
            <value>
                <fullName>Bloqueo definitivo</fullName>
            </value>
            <value>
                <fullName>Bloqueo posibilidad de regreso</fullName>
            </value>
            <value>
                <fullName>No Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono1__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 1</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono2__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 2</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono3__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 3</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_TM_Congelado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo sirve para no enviar el prospecto a CTI cuando tenga el valor activo</description>
    <label>Congelado</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_ContadorRemarcado__c</fullName>
    <label>Contador remarcado</label>
    <length>50</length>
    <type>Text</type>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>MX_WB_rt_Telemarketing</fullName>
    <active>true</active>
    <businessProcess>MX_WB_PC_Telemarketing</businessProcess>
    <label>Outbound</label>
</recordTypes>
</CustomObject>

src/classes/MX_WB_Envio4HrsCTI_sch.cls
/**
 * @File Name          : MX_WB_Envio4HrsCTI_sch.cls
 * @Description        :
 * @Author             : Eduardo Hernández Cuamatzi
 * @Group              :
 * @Last Modified By   : Eduardo Hernández Cuamatzi
 * @Last Modified On   : 20/2/2019 3:29:13
 * @Modification Log   :
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    20/2/2019 3:29:13   Eduardo Hernández Cuamatzi     Initial Version
**/
global with sharing class MX_WB_Envio4HrsCTI_sch implements Schedulable {
/**
*
* @
*/
    global void execute(SchedulableContext scheCont) {
        final String sTypeRecord = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('MX_WB_rt_Telemarketing').getRecordTypeId();
        final String leadSource = 'Outbound TLMK';
        final Integer contadorRemarcado = 5;
        final String noBloqueado = 'No bloqueado';
        String sQuery = '';

        String campaingMembers = '(';
        for(CampaignMember miembro: [Select LeadId From CampaignMember Where Campaign.isActive=true]) {
            campaingMembers += '\''+miembro.LeadId+'\',';
        }
        campaingMembers = campaingMembers.removeEnd(',');
        campaingMembers += ')';

        sQuery = 'SELECT l.Id, l.Folio_Cotizacion__c, l.OwnerId,l.FirstName, l.MX_WB_ph_Telefono1__c, l.MX_WB_ph_Telefono2__c, l.MX_WB_ph_Telefono3__c, l.MX_WB_ContadorRemarcado__c, l.EnviarCTI__c, CreatedDate, '
            	+ '(SELECT Id, Motivos_CONTACTO__c, Telefono__c from Tasks), l.MX_WB_TM_Congelado__c, '
        		+ 'l.LeadSource, l.RecordTypeId From Lead l WHERE RecordTypeId =\'' + sTypeRecord + '\''+' AND LeadSource =\''+leadSource + '\''+' AND MX_WB_ContadorRemarcado__c <= \''+ contadorRemarcado + '\' '
        		+ 'AND MX_WB_lst_EstatusBloqueado__c !=  \''+ noBloqueado + '\' AND MX_WB_TM_Congelado__c = false AND Id in '+campaingMembers;

        System.debug('sQuery'+ sQuery);
		final MX_WB_EnvioLeads4HrsCTI_bch leadEnvio = new MX_WB_EnvioLeads4HrsCTI_bch(sQuery);
		final Id batchInstanceId = Database.executeBatch(leadEnvio, 200);
        System.debug('batchInstanceId ' + batchInstanceId);
	}
}