src/objects/Lead.object
<CustomObject>
<fields>
    <fullName>Folio_Cotizacion__c</fullName>
    <label>Folio Cotización</label>
    <length>10</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>EnviarCTI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EnviarCTI</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_ContadorRemarcado__c</fullName>
    <label>Contador remarcado</label>
    <length>50</length>
    <type>Text</type>
</fields>
<fields>
    <fullName>MX_WB_lst_EstatusBloqueado__c</fullName>
    <description>Nuevo campo Estatus Bloqueado de Tele marketing</description>
    <label>Estatus Bloqueado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estatusdecotizacion__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bloqueo 1 año</fullName>
            </value>
            <value>
                <fullName>Bloqueo definitivo</fullName>
            </value>
            <value>
                <fullName>Bloqueo posibilidad de regreso</fullName>
            </value>
            <value>
                <fullName>No Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono1__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 1</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono2__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 2</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_ph_Telefono3__c</fullName>
    <description>Nuevo campo de teléfono para contactabilidad de telemarketing</description>
    <label>Teléfono 3</label>
    <type>Phone</type>
</fields>
<fields>
    <fullName>MX_WB_TM_Congelado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo sirve para no enviar el prospecto a CTI cuando tenga el valor activo</description>
    <label>Congelado</label>
    <type>Checkbox</type>
</fields>
<fields>
    <fullName>MX_WB_ContadorRemarcado__c</fullName>
    <label>Contador remarcado</label>
    <length>50</length>
    <type>Text</type>
</fields>
<sharingModel>ReadWriteTransfer</sharingModel>
<recordTypes>
    <fullName>MX_WB_rt_Telemarketing</fullName>
    <active>true</active>
    <businessProcess>MX_WB_PC_Telemarketing</businessProcess>
    <label>Outbound</label>
</recordTypes>
</CustomObject>

src/classes/MX_WB_EnvioLeadsCTI_shc_tst.cls
/**-------------------------------------------------------------------------
* Nombre: WB_ProcNotif_cls
* @author Karen Sanchez (KB)
* Proyecto: MW WB Tlmkt - BBVA Bancomer
* Descripción : Clase test que sirve para la cobertura del schedulable MX_WB_EnvioLeadsCTI_shc

* --------------------------------------------------------------------------
*                         Fecha           Autor                   Desripción
* -------------------------------------------------------------------
* @version 1.0           13/02/2019      Karen Sanchez            Creación
* --------------------------------------------------------------------------*/
@isTest
private class MX_WB_EnvioLeadsCTI_shc_tst {
	/**
	* 
	* 
	*/
	public static final String CRON_EXP = '0 0 0 1 1 ? 2022';

	@isTest static void ejecutaSchedulable() {
		final MX_WB_EnvioLeadsCTI_shc objEnvioLeadsSCH = new MX_WB_EnvioLeadsCTI_shc();
		final Id idRecordType = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('MX_WB_rt_Telemarketing').getRecordTypeId();
		final Campaign objCampaign = MX_WB_TestData_cls.createCampania('Campania Preuba500');
		insert objCampaign;
		final Lead objLeads = MX_WB_TestData_cls.createLead('Sanchez');
		objLeads.RecordTypeId = idRecordType;
		objLeads.LeadSource = 'Outbound TLMK';
		objLeads.MX_WB_ContadorRemarcado__c = '2';
		insert objLeads;
		final CampaignMember objCampaignMember = MX_WB_TestData_cls.createCampaignMember(objLeads.Id, objCampaign.Id);
		database.insert (objCampaignMember, false);


		Test.startTest();
		final String noBloqueado = 'No bloqueado';
        final Integer sCantidadEnvio = Integer.valueOf(label.MX_WB_CantidadEnvioCTI);
		String sQuery = 'SELECT l.Id,l.Folio_Cotizacion__c,l.OwnerId,l.FirstName,l.MX_WB_ph_Telefono1__c,l.MX_WB_ph_Telefono2__c,l.MX_WB_ph_Telefono3__c,l.MX_WB_ContadorRemarcado__c, l.EnviarCTI__c,CreatedDate';
        sQuery += ', l.LeadSource, l.RecordTypeId, l.MX_WB_TM_Congelado__c From Lead l WHERE MX_WB_TM_Congelado__c = false AND RecordTypeId =\'' + objLeads.RecordTypeId + '\''+' AND LeadSource =\''+objLeads.LeadSource + '\''+' AND MX_WB_ContadorRemarcado__c <= \''+ objLeads.MX_WB_ContadorRemarcado__c + '\''+'AND MX_WB_lst_EstatusBloqueado__c !=  \''+ noBloqueado+ '\''+'AND Id in (\''+ objCampaignMember.Id+ '\''+') limit '+sCantidadEnvio;
        objEnvioLeadsSCH.sQuery = sQuery;
        final String jobId = System.schedule('Test EnvioLeadsCTI_shc',CRON_EXP,objEnvioLeadsSCH);
        final CronTrigger cronTrig = [SELECT Id, CronExpression, TimesTriggered,NextFireTime FROM CronTrigger WHERE id =: jobId];

        System.assertEquals(0, cronTrig.TimesTriggered,'No hay ninguno en cola');

        objEnvioLeadsSCH.execute(null);

		Test.stopTest();

	}
}