src/objects/Master_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nombre del producto.</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Master Checklist</relationshipLabel>
        <relationshipName>Master_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Master Checklist</label>
    <nameField>
        <label>Nombre de Master</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Checklist</pluralLabel>
    <recordTypes>
        <fullName>MX_WB_objecionesReales</fullName>
        <active>true</active>
        <description>Tipo de registro que contiene las objeciones por etapa &quot;Objeciones Reales&quot; en el proceso de Telemarketing</description>
        <label>Objeciones Reales Telemarketing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MX_WB_preguntasEtapa__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contiene la relación de tipos de registro por etapas que se pueden tener para mostrar las objeciones relacionadas con la misma.</description>
	    <fields>
        <fullName>MX_SB_VTS_Producto__c</fullName>
        <description>Nombre del producto de interes</description>
        <inlineHelpText>Nombre del producto de interes</inlineHelpText>
        <label>Producto Asociado</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>preguntas Etapa</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_WB_Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo de relación hacia producto para asociar la oportunidad a un producto específico.</description>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cotizaciones</relationshipLabel>
        <relationshipName>Cotizaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_CheckList__c.object
<CustomObject>
    <label>Opportunity CheckList</label>
    <nameField>
        <label>Nombre de Master</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity CheckList</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <label>ASD</label>
    </recordTypes>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Cuenta personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Products (Familia de productos)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_WB_controllerMasterChecklist_tst.cls
/*
  @Class Name			: MX_WB_controllerMasterChecklist_tst
  @Description        	: Clase test Happy Path
  @Author             	: Eduardo Hernández Cuamatzi
  @Proyecto				: MW WB TLMKT - BBVA Bancomer
  @Last Modified By   	: Eduardo Hernández Cuamatzi
  ==============================================================================
  Ver         Date                     Author      		      	Modification
  ==============================================================================
  1.0    	02/08/2019 			Eduardo Hernández Cuamatzi		Versión inicial
  1.0.1    	02/12/2019 			Eduardo Hernández Cuamatzi		cobertura 100%
  1.0.2    	20/06/2019 			Eduardo Hernández Cuamatzi		Fix clase test para validar nombre correcto de Productos
*/
@isTest
private class MX_WB_controllerMasterChecklist_tst {

    @testSetup static void setup() {
        final String sysAdminString = System.Label.MX_SB_VTS_ProfileAdmin;
        final User uTelemarketing = MX_WB_TestData_cls.crearUsuario('Telemarketing1', sysAdminString);
        insert uTelemarketing;
        final Id idAgente = UserInfo.getUserId();
        final Account accountRecord = MX_WB_TestData_cls.crearCuenta('LastName', 'PersonAccount');
        accountRecord.OwnerId = uTelemarketing.Id;
        insert accountRecord;
        final MX_WB_FamiliaProducto__c objFamilyPro = MX_WB_TestData_cls.createProductsFamily ( 'ASD' );
        insert objFamilyPro;
        Product2 proTst = MX_WB_TestData_cls.productNew ( 'Auto Seguro Dinamico' );
        proTst.IsActive = true;
        proTst.MX_WB_FamiliaProductos__c = objFamilyPro.Id;
        insert proTst;
        final Opportunity opp = MX_WB_TestData_cls.crearOportunidad('LastName', accountRecord.Id, idAgente, 'ASD');
        opp.Producto__c = 'Auto Seguro Dinamico';
        insert opp;
        final MX_WB_preguntasEtapa__c createPreguntasEtapa = MX_WB_TestData_cls.createPreguntasEtapa('ObjecionesTest', 'Telemarketing', 'MX_WB_objecionesReales');
        insert createPreguntasEtapa;
        final Id recordTypeId = [Select Id,Name, DeveloperName from RecordType where DeveloperName = 'MX_WB_objecionesReales'].Id;
        final Master_Checklist__c createMasterCheck = MX_WB_TestData_cls.createMasterCheck('ObjecionesTest', recordTypeId, uTelemarketing.Id);
        insert createMasterCheck;
        final Opportunity_CheckList__c createOppChkLst = MX_WB_TestData_cls.createOppChkLst(createMasterCheck.Id, uTelemarketing.Id, opp.Id, false);
        insert createOppChkLst;
    }

    @isTest
    static void inicializaObjeciones() {
        final User uTelemarketing = [Select Id, LastName from User where LastName = 'Telemarketing1'];
        System.runAs(uTelemarketing) {
            final MX_WB_preguntasEtapa__c createPreguntasEtapa = MX_WB_TestData_cls.createPreguntasEtapa('ObjecionesTest', 'Telemarketing', 'MX_WB_objecionesReales');
            insert createPreguntasEtapa;
            final Id recordTypeId = [Select Id,Name, DeveloperName from RecordType where DeveloperName = 'MX_WB_objecionesReales'].Id;
            final Master_Checklist__c createMasterCheck = MX_WB_TestData_cls.createMasterCheck('ObjecionesTest', recordTypeId, uTelemarketing.Id);
            insert createMasterCheck;
            Test.startTest();
            	final List<sObject> inicializaObjeciones = MX_WB_controllerMasterChecklist_cls.inicializaObjeciones('ObjecionesTest');
            	System.assert(String.isNotEmpty(((Master_Checklist__c)inicializaObjeciones[0]).Name), 'Name vacío');
            Test.stopTest();
        }
    }
    
    @isTest
    static void inicializaObjecionesSobrecarga() {
        final MX_WB_FamiliaProducto__c objFamilyPro = MX_WB_TestData_cls.createProductsFamily ( 'ASD' );
        insert objFamilyPro;
        final Product2 proTst = MX_WB_TestData_cls.productNew ( 'Auto Seguro Dinámico' );
        proTst.IsActive = true;
        proTst.MX_WB_FamiliaProductos__c = objFamilyPro.Id;
        insert proTst;
        final User uTelemarketing = [Select Id, LastName from User where LastName = 'Telemarketing1'];
        final MX_WB_preguntasEtapa__c createPreguntasEtapa = MX_WB_TestData_cls.createPreguntasEtapa('ObjecionesTest', 'Telemarketing', 'MX_WB_objecionesReales');
        createPreguntasEtapa.MX_SB_VTS_Producto__c =  'Auto Seguro Dinámico';
        insert createPreguntasEtapa;
        final Id recordTypeId = [Select Id,Name, DeveloperName from RecordType where DeveloperName = 'MX_WB_objecionesReales'].Id;
        final Master_Checklist__c createMasterCheck = MX_WB_TestData_cls.createMasterCheck('ObjecionesTest', recordTypeId, uTelemarketing.Id);
        createMasterCheck.MX_WB_Producto__c = proTst.Id;
        insert createMasterCheck;
        System.runAs(uTelemarketing) {        
            Test.startTest();
            	final List<sObject> inicializaObjeciones = MX_WB_controllerMasterChecklist_cls.inicializaObjeciones('ObjecionesTest', 'Auto Seguro Dinámico');
            	System.assert(String.isNotEmpty(((Master_Checklist__c)inicializaObjeciones[0]).Name), 'Name vacío');
            Test.stopTest();
        }
    }

    @isTest
    static void guardaRespuestas() {
        final User uTelemarketing = [Select Id, LastName from User where LastName = 'Telemarketing1'];
        System.runAs(uTelemarketing) {
            Test.startTest();
             	final Opportunity opp = [Select Id from Opportunity];
                final Master_Checklist__c createMasterCheck = [Select Id,Name,RecordTypeId from Master_Checklist__c where Name = 'ObjecionesTest'];
                final MX_WB_controllerMasterChecklist_cls.RespuestasPar respuestasPar = new MX_WB_controllerMasterChecklist_cls.RespuestasPar();
                respuestasPar.Id = String.valueOf(createMasterCheck.Id);
                respuestasPar.Name = createMasterCheck.Name;
                respuestasPar.RecordTypeId = createMasterCheck.RecordTypeId;
                respuestasPar.check = false;
                final List<MX_WB_controllerMasterChecklist_cls.RespuestasPar> lstRespuestasPar = new List<MX_WB_controllerMasterChecklist_cls.RespuestasPar>();
                lstRespuestasPar.add(respuestasPar);
                final String jsonRespuestas = JSON.serialize(lstRespuestasPar);
                final Boolean guardaRespuestas = MX_WB_controllerMasterChecklist_cls.guardaRespuestas(jsonRespuestas, opp.Id);
                System.assert(guardaRespuestas, 'Error en guardaRespuestas');
            Test.stopTest();
        }
    }

    @isTest
    static void guardaRespuestasNoOwner() {
        final String sysAdminString = System.Label.MX_SB_VTS_ProfileAdmin;
        final User uTelemarketing = [Select Id, LastName from User where LastName = 'Telemarketing1'];
        final User uTelemarketing2 = MX_WB_TestData_cls.crearUsuario('Telemarketing 1', sysAdminString);
        insert uTelemarketing2;
        final Account accountRecord = MX_WB_TestData_cls.crearCuenta('LastName', 'PersonAccount');
        accountRecord.OwnerId = uTelemarketing.Id;
        insert accountRecord;
        final MX_WB_FamiliaProducto__c objFamilyPro = MX_WB_TestData_cls.createProductsFamily ( 'ASD' );
        insert objFamilyPro;
        Product2 proTst = MX_WB_TestData_cls.productNew ( 'Auto Seguro Dinamico' );
        proTst.IsActive = true;
        proTst.MX_WB_FamiliaProductos__c = objFamilyPro.Id;
        insert proTst;
        final Opportunity opp = MX_WB_TestData_cls.crearOportunidad('Test', accountRecord.Id, uTelemarketing2.Id, '');
        opp.Producto__c = 'Auto Seguro Dinamico';
        insert opp;
        final Id recordTypeId = [Select Id,Name, DeveloperName from RecordType where DeveloperName = 'MX_WB_objecionesReales'].Id;
        final Master_Checklist__c createMasterCheck = MX_WB_TestData_cls.createMasterCheck('ObjecionesTest', recordTypeId, uTelemarketing2.Id);
        insert createMasterCheck;
        final Opportunity_CheckList__c createOppChkLst = MX_WB_TestData_cls.createOppChkLst(createMasterCheck.Id, uTelemarketing2.Id, opp.Id, false);
        insert createOppChkLst;
        final MX_WB_controllerMasterChecklist_cls.RespuestasPar respuestasPar = new MX_WB_controllerMasterChecklist_cls.RespuestasPar();
        System.runAs(uTelemarketing) {
            	Test.startTest();
            	respuestasPar.Id = String.valueOf(createMasterCheck.Id);
                respuestasPar.Name = createMasterCheck.Name;
                respuestasPar.RecordTypeId = createMasterCheck.RecordTypeId;
                respuestasPar.check = false;
            	final List<MX_WB_controllerMasterChecklist_cls.RespuestasPar> lstRespuestasPar = new List<MX_WB_controllerMasterChecklist_cls.RespuestasPar>();
            	lstRespuestasPar.add(respuestasPar);
            	final String jsonRespuestas = JSON.serialize(lstRespuestasPar);
            	final Boolean guardaRespuestas = MX_WB_controllerMasterChecklist_cls.guardaRespuestas(jsonRespuestas, opp.Id);
            	System.assert(guardaRespuestas, 'Error en guardaRespuestas');
            Test.stopTest();
        }
    }

     @isTest
    static void guardaRespuestasNoResId() {
        final String sysAdminString = System.Label.MX_SB_VTS_ProfileAdmin;
       	final User uTelemarketing = MX_WB_TestData_cls.crearUsuario('Telemarketing 1', sysAdminString);
        insert uTelemarketing;
        final User uTelemarketing2 = MX_WB_TestData_cls.crearUsuario('Telemarketing 1', sysAdminString);
        insert uTelemarketing2;
        final Account accountRecord = MX_WB_TestData_cls.crearCuenta('LastName', 'PersonAccount');
        accountRecord.OwnerId = uTelemarketing.Id;
        insert accountRecord;
        final MX_WB_FamiliaProducto__c objFamilyPro = MX_WB_TestData_cls.createProductsFamily ( 'ASD' );
        insert objFamilyPro;
        Product2 proTst = MX_WB_TestData_cls.productNew ( 'Auto Seguro Dinamico' );
        proTst.IsActive = true;
        proTst.MX_WB_FamiliaProductos__c = objFamilyPro.Id;
        insert proTst;
        final Opportunity opp = MX_WB_TestData_cls.crearOportunidad('Test', accountRecord.Id, uTelemarketing2.Id, '');
        opp.Producto__c = 'Auto Seguro Dinamico';
        insert opp;
        final MX_WB_preguntasEtapa__c createPreguntasEtapa = MX_WB_TestData_cls.createPreguntasEtapa('ObjecionesTest', 'Telemarketing', 'MX_WB_objecionesReales');
        insert createPreguntasEtapa;
        final Id recordTypeId = [Select Id,Name, DeveloperName from RecordType where DeveloperName = 'MX_WB_objecionesReales'].Id;
        final Master_Checklist__c createMasterCheck = MX_WB_TestData_cls.createMasterCheck('ObjecionesTest', recordTypeId, uTelemarketing2.Id);
        insert createMasterCheck;
        final MX_WB_controllerMasterChecklist_cls.RespuestasPar respuestasPar = new MX_WB_controllerMasterChecklist_cls.RespuestasPar();
        System.runAs(uTelemarketing) {
            	Test.startTest();
            	respuestasPar.Id = String.valueOf(createMasterCheck.Id);
                respuestasPar.Name = createMasterCheck.Name;
                respuestasPar.RecordTypeId = createMasterCheck.RecordTypeId;
                respuestasPar.check = false;
            	final List<MX_WB_controllerMasterChecklist_cls.RespuestasPar> lstRespuestasPar = new List<MX_WB_controllerMasterChecklist_cls.RespuestasPar>();
            	lstRespuestasPar.add(respuestasPar);
            	final String jsonRespuestas = JSON.serialize(lstRespuestasPar);
            	final Boolean guardaRespuestas = MX_WB_controllerMasterChecklist_cls.guardaRespuestas(jsonRespuestas, opp.Id);
            	System.assert(guardaRespuestas, 'Error en guardaRespuestas');
            Test.stopTest();
        }
    }
}