src/objects/MX_SB_VTS_Generica__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista Genérica para múltiples valores del flujo de venta.</description>
    <fields>
        <fullName>MX_SB_VTS_Oli_Item__c</fullName>
        <description>Field to Opportunity Line Item</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MX_SB_VTS_Oli_Item</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Quoli_Item__c</fullName>
        <description>Field to Quote line Item</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MX_SB_VTS_Quoli_Item</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Type__c</fullName>
        <description>RecordType for the object
CP1-- Object Quoly to Oli
CP2-- Filtro Campaing
CP3-- Servicios Bandejas
CP4
CP5--Id Salesforce Banquero base al que se asignan las cuentas al no existir un banquero asignado.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>RecordType for the object 
CP1 -- Object Quoly to Oli 
CP2 -- Filtro Campaing 
CP3 -- Servicios Bandejas
CP4 --
CP5--Id Salesforce Banquero base al que se asignan las cuentas al no existir un banquero asignado.</inlineHelpText>
        <label>MX_SB_VTS_Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MX_SB_VTS_Generica</label>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_Numero_de_Poliza__c</fullName>
        <description>Numero de póliza clipert.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Numero de Poliza</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_QuoteAsingOli_cls.cls
/*
* Quote Asing class
* @Autor: XXXXX
* @Create Date:27/03/2019
* @Proyect: BBVA_SEGUROS
* @Description: XXX
* -----Version-----
* 1.0 Creation ... 27/03/2019
*           No  |     Date     |     Author      |    Description
* @version  1.0    04/10/2019     Arsenio Perez      Creacion
*
*/
public without sharing class MX_SB_VTS_QuoteAsingOli_cls {
    /**Lista ListaMeta */
    static List<MX_SB_VTS_Generica__c> ListaMeta;
    /** */
    public static void reasingQuote(Map<id, Quote> trigerEntry,Map<Id,Quote> trigerOutEntry) {
        final set<Id> idOpps = new set<Id>();
        for(Quote temp:trigerEntry.values()) {
            if(temp.Status.equalsIgnoreCase(System.Label.MX_SB_VTS_STATUSEMITIDA_LBL)) {
                idOpps.add(temp.OpportunityId);
            }
        }
        if(idOpps.isEmpty() == false) {
            ftrreasingQuote(idOpps);
        }
    }

    /**
    * @@author Arsenio Perez Lopez
    * @Methodo de llamado a futuro para la asignacion correcta de los campos de QUote a OLI.
    */
    @future
    public static void ftrreasingQuote(set<id> trigerEntry) {
        try {
            List<SObject> LitUpdate = new LIST<SObject>();
            List<QuoteLineItem> Quoli= new List<QuoteLineItem>();
            final set<Id> idOpps = new set<Id>();
            String QueryFielsQuoLi = llenarArreglo();
            idOpps.addAll(trigerEntry);
            final String EMITIDA=system.Label.MX_SB_VTS_STATUSEMITIDA_LBL;
            Quoli = Database.Query('SELECT id, OpportunityLineItemID'+ String.escapeSingleQuotes(QueryFielsQuoLi) +' FROM QuoteLineItem WHERE Quote.IsSyncing =true and Quote.OpportunityId=:idOpps and Quote.status=:EMITIDA and Quote.MX_SB_VTS_Numero_de_Poliza__c !=null ');
            if(Quoli.isEmpty()==false) {
                for(QuoteLineItem Quolitemp: Quoli) {
                    SObject Olitemp = new OpportunityLineItem();
                    Olitemp.id=Quolitemp.OpportunityLineItemID;
                    for(MX_SB_VTS_Generica__c meta: ListaMeta) {
                        if(meta.MX_SB_VTS_Type__c=='CP1') {
                            if(meta.MX_SB_VTS_Quoli_Item__c.contains('Quote.')) {
                                final Quote quotesx = (Quote)Quolitemp.getSObject('Quote');
                                final String temp = meta.MX_SB_VTS_Quoli_Item__c.substringAfter('.');
                                Olitemp.put(meta.MX_SB_VTS_Oli_Item__c,quotesx.get(temp));
                            }else {
                                Olitemp.put(meta.MX_SB_VTS_Oli_Item__c,Quolitemp.get(meta.MX_SB_VTS_Quoli_Item__c));
                            }
                        }
                    }
                    LitUpdate.add(Olitemp);
                }
                update LitUpdate;
            }
        }
        catch(System.ListException ex) {
            throw new ListException(ex);
        }
    }
    /**Metodo llenarArreglo */
    public static String llenarArreglo() {
        string tempQueryFielsQuoLi='';
        ListaMeta = MX_SB_VTS_Generica__c.getall().values();
        for(MX_SB_VTS_Generica__c meta: ListaMeta) {
            if(meta.MX_SB_VTS_Type__c=='CP1') {
                tempQueryFielsQuoLi+=', '+meta.MX_SB_VTS_Quoli_Item__c;
            }
        }
        return tempQueryFielsQuoLi;
    }
}