src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caso_Relacionado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso Relacionado</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnviarCTI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Se hace validación, si fue verdadera envia a closed de CTI para dar atención.</description>
        <label>Enviar a CTI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_OppCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Oportunidades (Caso)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProcNotiOppNoAten__c.object
<CustomObject>
    <description>Objeto que se usa para habilitar un trigger que levante los procesos cada 15 minutos.</description>
    <fields>
        <fullName>Horario__c</fullName>
        <label>Horario</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Matutino</fullName>
                </value>
                <value>
                    <fullName>Vespertino</fullName>
                </value>
                <value>
                    <fullName>A los</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minutos__c</fullName>
        <label>Minutos</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>55</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proceso__c</fullName>
        <label>Proceso</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ProcNotiOppNoAten</label>
    <nameField>
        <displayFormat>PNOA-{00000}</displayFormat>
        <label>Nombre de ProcNotiOppNoAten</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProcNotiOppNoAten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_Familia_Productos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación a familia de producto.</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Presupuestos</relationshipLabel>
        <relationshipName>Presupuestos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Folio_Cotizacion__c</fullName>
        <description>Folio de la póliza.</description>
        <label>Folio Cotizacion</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Movil_txt__c</fullName>
        <description>Número de teléfono en texto para búsqueda</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Movil</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_ScheduldOppsTele_cls.cls
/**
 * @File Name          : MX_SB_VTS_ScheduldOppsTele_cls.cls
 * @Description        :
 * @Author             : Eduardo Hernández Cuamatzi
 * @Group              :
 * @Last Modified By   : Eduardo Hernández Cuamatzi
 * @Last Modified On   : 8/10/2019 0:02:10
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    7/10/2019   Eduardo Hernández Cuamatzi     Initial Version
**/
public without sharing class MX_SB_VTS_ScheduldOppsTele_cls {//NOSONAR
    /**
     * sendOppsHogar envia Oportunidades a SmartCenter
     */
    public static void sendOppsHogar(List<ProcNotiOppNoAten__c> lsNotif, Map<Id,ProcNotiOppNoAten__c> mapOldNotif) {
        for (ProcNotiOppNoAten__c procNoti : lsNotif) {
            if(String.isNotBlank(procNoti.Proceso__c) && procNoti.Proceso__c.equals(System.Label.MX_SB_VTS_SchdProces)) {
                createScheduldOpps(procNoti);
            }
        }
    }

    /**
     * createScheduldOpps crear query base de scheduld
     * @param  registro de trabajos programados
     */
    public static void createScheduldOpps(ProcNotiOppNoAten__c lsNotif) {
        final MX_SB_VTS_SendTrackingTelemarketing_sch scheduldOppTlmk = new MX_SB_VTS_SendTrackingTelemarketing_sch();
        String sQuery = 'Select Opportunity.Id, Opportunity.AccountId, Status, Opportunity.EnviarCTI__c, Opportunity.LastModifiedDate, MX_SB_VTS_Familia_Productos__c,';
        sQuery += ' MX_SB_VTS_Folio_Cotizacion__c, Opportunity.OwnerId,Opportunity.Producto__c, Opportunity.Account.PersonEmail, MX_SB_VTS_Movil_txt__c From Quote ';
        sQuery += ' Where Opportunity.LeadSource = \'Tracking Web\'';
        sQuery += ' And Opportunity.AccountId != null';
        sQuery += ' And MX_SB_VTS_Folio_Cotizacion__c != null';
        sQuery += ' And CreatedDate >= ' + System.label.MX_SB_VTS_SCHEDULE_DATE_LBL;
        sQuery += ' And Opportunity.Caso_Relacionado__c = null';
        sQuery += ' And Opportunity.MX_SB_VTS_OppCase__c = null';
        sQuery += ' And MX_SB_VTS_Familia_Productos__r.Name = \'' + System.label.MX_SB_VTS_HogarFam + '\'';
        final String sch = '0 ' + lsNotif.Minutos__c + ' 0-23 1-31 1-12 ?';
        final String sNombreProc = lsNotif.Horario__c + ' : ' + lsNotif.Minutos__c + ' estatus : ' + 'Tracking';
        scheduldOppTlmk.sQuery = sQuery;
        System.schedule(sNombreProc, sch, scheduldOppTlmk);
    }
}