src/objects/MX_WB_FamiliaProducto__c.object
<CustomObject>
    <description>Esto objeto guardará las categorías a las que pertenecen los productos</description>
    <label>Familia de productos</label>
    <nameField>
        <label>Familia de productos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famlias de productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Products (Familia de productos)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scripts_Stage_Product__c.object
<CustomObject>
	<fields>
        <fullName>MX_WB_Etapa__c</fullName>
        <label>Etapa</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Políticas</fullName>
                </value>
                <value>
                    <fullName>Cotización</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
                <value>
                    <fullName>Venta Autorizada</fullName>
                </value>
                <value>
                    <fullName>Apertura</fullName>
                </value>
                <value>
                    <fullName>Cierre llamada no contacto</fullName>
                </value>
                <value>
                    <fullName>Información y condiciones</fullName>
                </value>
                <value>
                    <fullName>Venta cerrada</fullName>
                </value>
                <value>
                    <fullName>Cierre de llamada sin venta</fullName>
                </value>
                <value>
                    <fullName>Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Familia de productos a los que se les asociará el script</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Scripts Stages Products</relationshipLabel>
        <relationshipName>Scripts_Stages_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_Script__c</fullName>
        <description>Script que será mostrado al asesor. Este script se visualiza dependiendo la etapa y el producto en el que se encuentre.</description>
        <label>Script</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Scripts Stage Product</label>
    <nameField>
        <label>Nombre de Scripts Stage Campaign</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts Stages Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_WB_ControlScriptsTgr_tst.cls
/**-------------------------------------------------------------------------
* Nombre: MX_WB_ControlScriptsTgr_tst
* Autor Alexis Pérez
* Proyecto: MW WB TLMKT - BBVA Bancomer
* Descripción : Clase de prueba para MX_WB_ControlScriptCls. 

* --------------------------------------------------------------------------
* Versión       Fecha           Autor                   Desripción<p />
* -------------------------------------------------------------------
* 1.0           06/12/2018      Alexis Pérez   			Creación
* --------------------------------------------------------------------------
*/

@IsTest
public class MX_WB_ControlScriptsTgr_tst {
    
    /*
     * Test method for the trigger created on the object Scripts_Stage_Product__c
     */
    @IsTest
    public static void test() {
        boolean error = false;
        try {
            final MX_WB_FamiliaProducto__c objFamProd = new MX_WB_FamiliaProducto__c();
            objFamProd.Name = 'ASD';
            insert objFamProd;
            
            final Product2 objProducto = new Product2();
            objProducto.Name = 'TestProductoMinion001';
            objProducto.IsActive = true;
            objProducto.MX_WB_FamiliaProductos__c = objFamProd.Id;
            insert objProducto;
            
            final Scripts_Stage_Product__c objScriptStageProduct = new Scripts_Stage_Product__c();
            objScriptStageProduct.MX_WB_Etapa__c = 'Contacto Efectivo';
            objScriptStageProduct.MX_WB_FamiliaProductos__c = objFamProd.Id;
            objScriptStageProduct.MX_WB_Script__c = 'TestScriptMinion001';
            insert objScriptStageProduct;
            
            final Scripts_Stage_Product__c objScriptStageProduct2 = new Scripts_Stage_Product__c();
            objScriptStageProduct2.MX_WB_Etapa__c = 'Contacto Efectivo';
            objScriptStageProduct2.MX_WB_FamiliaProductos__c = objFamProd.Id;
            objScriptStageProduct.MX_WB_Script__c = 'TestScriptMinion001Error';
            insert objScriptStageProduct2;
            
        } catch(DMLException ex) {
            error = true;
            System.assertEquals(error, ex.getMessage().contains(Label.MX_WB_lbl_MsgScriptException), 'Se esperaba error que contenga mensaje personalizado');
        }
    }
}