src/objects/MX_WF_Afiliaciones__c.object
<CustomObject>
    <description>Objeto para las afiliaciones que se informan en WALLET</description>
    <fields>
        <fullName>MX_WF_Wallet__c</fullName>
        <description>Campo para la aplicación WF, permite relacionar las afiliaciones con el registro de Wallet</description>
        <label>Wallet</label>
        <referenceTo>MX_WF_Wallet__c</referenceTo>
        <relationshipLabel>Afiliaciones</relationshipLabel>
        <relationshipName>Afiliaciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Afiliaciones</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Número de Afiliación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Afiliaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MX_WF_Wallet__c.object
<CustomObject>
    <description>Objeto para la aplicación workflow, se utiliza solo para las campañas de tipo Alianzas Comerciales</description>
    <fields>
        <fullName>MX_WF_Afiliaciones__c</fullName>
        <description>Campo que acepta múltiples afiliaciones, cada afiliación consta de 7 dígitos y se debe separar con una &quot;coma&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Indicar las afiliaciones participantes a 7 dígitos separados por coma</inlineHelpText>
        <label>Afiliaciones</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MX_WF_Estado__c</fullName>
        <description>Campo de estado para el objeto wallet</description>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Documentación</fullName>
                    <default>true</default>
                    <label>Documentación</label>
                </value>
                <value>
                    <fullName>Vo.Bo. WALLET</fullName>
                </value>
                <value>
                    <fullName>Aprobado</fullName>
                </value>
                <value>
                    <fullName>Cancelada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WF_Fecha_fin__c</fullName>
        <description>Fecha de fin de promoción</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MX_WF_Nombre_de_promocion__c</fullName>
        <description>Nombre de la promoción</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de promoción</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_WF_Promocion_Corta__c</fullName>
        <description>Breve descripción de promoción</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Promoción Corta</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Wallet</label>
    <nameField>
        <displayFormat>WAL{YY}{MM}{0000}</displayFormat>
        <label>Folio del registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_WF_Reporte_Wallet_test.cls
/**
* ------------------------------------------------------------------------------
* @Nombre: MX_WF_Reporte_Wallet_test
* @Autor: Sandra Ventura García
* @Proyecto: Workflow Campañas
* @Descripción : Test para clase MX_WF_Reporte_Wallet.
* ------------------------------------------------------------------------------
* @Versión       Fecha           Autor                         Descripción
* ------------------------------------------------------------------------------
* 1.0           18/09/2019     Sandra Ventura García	         test
* ------------------------------------------------------------------------------
*/
@isTest
private class MX_WF_Reporte_Wallet_test {
    
  /**
  * @description: Datos prueba.
  * @author Sandra Ventura
  */ 
   public static List<MX_WF_Wallet__c> createWllts(Integer num) {
        final List<MX_WF_Wallet__c> wll = new List<MX_WF_Wallet__c>();
          String vAfiliaciones ='278732';
        for(Integer i=0;i<num;i++) {
            final MX_WF_Wallet__c wAfil = new MX_WF_Wallet__c(MX_WF_Estado__c='Aprobado',
                                                    MX_WF_Afiliaciones__c= vAfiliaciones, 
                                                    MX_WF_Fecha_fin__c= date.today(),
                                                    MX_WF_Nombre_de_promocion__c='Testpromo' + i, 
                                                    MX_WF_Promocion_Corta__c = 'Test' + i);
            
            
            wll.add(wAfil);
            vAfiliaciones = vAfiliaciones + i + '200,';
        }
        insert wll;
       
        return wll;
       
    }
    
  /**
  * @description: test reporte promociones.
  * @author Sandra Ventura
  */ 
    @isTest static void testreporteP() {
        
        MX_WF_Reporte_Wallet_test.createWllts(50);
        final Blob resultProm=  MX_WF_Reporte_Wallet.rptPromocion();
        System.assert(resultProm.size()<>0,'El reporte no fue generado');        
        
        }
  /**
  * @description: test reporte afiliaciones.
  * @author Sandra Ventura
  */ 
    @isTest static void testreporteA() {
        
        MX_WF_Reporte_Wallet_test.createWllts(50);
        
        final Blob resultAfil = MX_WF_Reporte_Wallet.rptAfiliacion();
        System.assert(resultAfil.size()<>0,'El reporte no fue generado');       
        }    
  /**
  * @description: test scheduler envio reportes.
  * @author Sandra Ventura
  */ 
    @isTest public static void  testschedule() {
        
        Test.StartTest();
        final MX_WF_Reporte_Wallet sh1 = new MX_WF_Reporte_Wallet();      
               final String jobId = system.schedule('Test', '0 0 9 * * ?', sh1);
               final CronTrigger crtri = [SELECT Id, CronExpression, TimesTriggered,NextFireTime
                                          FROM CronTrigger WHERE id = :jobId];
                System.assertEquals(0, crtri.TimesTriggered, 'Proceso exitoso');
        Test.stopTest();
        }


}