src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estatus__c</fullName>
        <description>Estatus de la cotización.</description>
        <label>Estatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Creada</fullName>
                </value>
                <value>
                    <fullName>Tarificada</fullName>
                </value>
                <value>
                    <fullName>Formalizada</fullName>
                </value>
                <value>
                    <fullName>Emitida</fullName>
                </value>
                <value>
                    <fullName>Cobrada</fullName>
                </value>
                <value>
                    <fullName>Cancelada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FolioCotizacion__c</fullName>
        <description>Folio para dar seguimiento a la cotización.</description>
        <externalId>true</externalId>
        <label>Folio Cotizacion</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Aplica_Cierre__c</fullName>
        <description>Indica si ya se cuenta con contrato para permitir el cierre de la oportunidad</description>
        <defaultValue>false</defaultValue>
        <label>Aplica Cierre</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <description>Tipo de plan para la cotización.</description>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Esencial</fullName>
                </value>
                <value>
                    <fullName>Basico</fullName>
                </value>
                <value>
                    <fullName>Amplio</fullName>
                </value>
                <value>
                    <fullName>Amplio Plus</fullName>
                </value>
                <value>
                    <fullName>Plan Personalizado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <description>Producto para cotización.</description>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro auto  Clasico</fullName>
                </value>
                <value>
                    <fullName>Seguro de moto</fullName>
                </value>
                <value>
                    <fullName>Seguro de bicicleta</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto otros usos</fullName>
                </value>
                <value>
                    <fullName>Otros Ramos ( Vida / Salud )</fullName>
                </value>
                <value>
                    <fullName>Seguro de Auto</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto UDI</fullName>
                </value>
                <value>
                    <fullName>Campaña TP</fullName>
                </value>
                <value>
                    <fullName>Base Uber</fullName>
                </value>
                <value>
                    <fullName>Seguro Fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Legalizado</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto Udi</fullName>
                </value>
                <value>
                    <fullName>Seguro de Moto Bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo bancomer</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto nacionalizado</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinamico</fullName>
                </value>
                <value>
                    <fullName>Auto Seguro Dinámico</fullName>
                </value>
                <value>
                    <fullName>Seguro de auto fronterizo</fullName>
                </value>
                <value>
                    <fullName>Seguro Carretero</fullName>
                </value>
                <value>
                    <fullName>Hogar</fullName>
                </value>
                <value>
                    <fullName>Vida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Información para la cotización.</description>
        <label>Motivo de la Oportunidad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Venta Pre emisión</fullName>
                </value>
                <value>
                    <fullName>No Venta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <recordTypes>
        <fullName>ASD</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>ASD</label>
    </recordTypes>
	<recordTypes>
        <fullName>MX_WB_RT_Telemarketing</fullName>
        <active>true</active>
        <businessProcess>Telemarketing</businessProcess>
        <label>Outbound</label>

    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Producto__c.object
<CustomObject>
    <description>Objeto para administrar los productos que los ejecutivos podrán registrar en las oportunidades.</description>
    <label>Producto</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_WB_EvaluacionOportunidades_test.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     MX_WB_EvaluacionOportunidades_test
* @Author   Salvador Reyna Gonzalez
* @Date     Created: 2019-01-21
* @Group  	Telemarketing
* @Description This class works as a test Class for the APEX class MX_WB_EvaluacionOportunidades_ctrl
* @Coverage 100%
* @Changes
*/
@isTest
private class MX_WB_EvaluacionOportunidades_test {
    /** 
    *Field 
    */
    static Account aacountTest;
    /** 
    *Field
    */
    static Opportunity oppWon;
    /* --------------------------------------------------------------------------------------
    * @Description Inserts and Account and a Opportunity Type "ASD"
    **/
    static void init() {
        final RecordType rtOpp = [Select Id from RecordType Where SObjectType ='Opportunity' AND DeveloperName='MX_WB_RT_Telemarketing'];

        aacountTest = new Account();
        aacountTest.FirstName = 'Test Name';
        aacountTest.LastName = 'Test Last';
        aacountTest.PersonEmail = 'test@testbbva.com';
        aacountTest.PersonMobilePhone = '5551040002';
        aacountTest.PersonHomePhone = '5551040002';
        insert aacountTest;

        oppWon = new Opportunity();
        oppWon.Name = 'Test Opp';
        oppWon.StageName = 'Closed Won';
        oppWon.CloseDate = Date.today().addDays(1);
        oppWon.Producto__c = 'Auto Seguro Dinamico';
        oppWon.Reason__c = 'Venta';
        oppWon.MX_SB_VTS_Aplica_Cierre__c = true;
        oppWon.Estatus__c = 'Emitida';
        oppWon.LeadSource = 'Inbound';
        oppWon.FolioCotizacion__c = 'Test123';
        oppWon.Plan__c = 'Basico';
        oppWon.AccountId = aacountTest.Id;
        oppWon.RecordTypeId = rtOpp.Id;
        insert oppWon;
    }

    /* --------------------------------------------------------------------------------------
    * @Description Tests getOpportunities method from APEX Class MX_WB_EvaluacionOportunidades_ctrl
    **/
    static testMethod void getOpportunities() {
        init();
        final List<Opportunity> opps = MX_WB_EvaluacionOportunidades_ctrl.getOpportunities();
        System.assertEquals(opps[0].Name, oppWon.Name, 'Coinciden los nombres de opportunidad');
    }
}