src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Tipo_de_Registro_Manual2__c</fullName>
        <description>Tipo de registro asociado a la oportunidad</description>
        <inlineHelpText>Tipo de Registro Manual</inlineHelpText>
        <label>Tipo de Registro de la Oportunidad</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adquirente</fullName>
                </value>
                <value>
                    <fullName>Adquirente v2</fullName>
                </value>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aportaciones</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>Banca de Inversión Empresas (BIE)</fullName>
                </value>
                <value>
                    <fullName>Banca electrónica</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bcom</fullName>
                </value>
                <value>
                    <fullName>BPyP</fullName>
                </value>
                <value>
                    <fullName>Cadenas de valor</fullName>
                </value>
                <value>
                    <fullName>CIB</fullName>
                </value>
                <value>
                    <fullName>CIE</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE V2</fullName>
                </value>
                <value>
                    <fullName>Coberturas y derivados</fullName>
                </value>
                <value>
                    <fullName>Comercio internacional</fullName>
                </value>
                <value>
                    <fullName>Consumer Finance</fullName>
                </value>
                <value>
                    <fullName>Cotización Arrendamiento</fullName>
                    <default>true</default>
                    <label>Cotización Arrendamiento</label>
                </value>
                <value>
                    <fullName>DEM</fullName>
                </value>
                <value>
                    <fullName>DEM V2</fullName>
                </value>
                <value>
                    <fullName>DIE</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Disposición</fullName>
                </value>
                <value>
                    <fullName>Domiciliación</fullName>
                </value>
                <value>
                    <fullName>Domiciliación PyME</fullName>
                </value>
                <value>
                    <fullName>Domiciliación V2</fullName>
                </value>
                <value>
                    <fullName>Fiduciario</fullName>
                </value>
                <value>
                    <fullName>Fiduciario V2</fullName>
                </value>
                <value>
                    <fullName>Financiamiento</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_Producto__c</fullName>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tipo_de_Registro_Manual2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Alianzas Comerciales</fullName>
                </value>
                <value>
                    <fullName>Aplinet</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Financiero</fullName>
                </value>
                <value>
                    <fullName>Arrendamiento Puro</fullName>
                </value>
                <value>
                    <fullName>Asset Management Gestión Terceros</fullName>
                </value>
                <value>
                    <fullName>Asset Management Previsión Social</fullName>
                </value>
                <value>
                    <fullName>Auto Flotilla Única</fullName>
                </value>
                <value>
                    <fullName>Banca Electrónica PyME</fullName>
                </value>
                <value>
                    <fullName>Bancomer.com</fullName>
                </value>
                <value>
                    <fullName>Bancomer Net Cash</fullName>
                </value>
                <value>
                    <fullName>Cadenas NAFIN</fullName>
                </value>
                <value>
                    <fullName>Cambios</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito</fullName>
                </value>
                <value>
                    <fullName>Cartas de Crédito PyME</fullName>
                </value>
                <value>
                    <fullName>Ciclos de Vida/ Previsión Social</fullName>
                </value>
                <value>
                    <fullName>CIE Electrónico</fullName>
                </value>
                <value>
                    <fullName>CIE PyME</fullName>
                </value>
                <value>
                    <fullName>CIE Ventanilla</fullName>
                </value>
                <value>
                    <fullName>Cobertura/Renta Variable</fullName>
                </value>
                <value>
                    <fullName>Cobertura de Tasa</fullName>
                </value>
                <value>
                    <fullName>Cobertura de Tipo de Cambio</fullName>
                </value>
                <value>
                    <fullName>Cobertura Empresarial</fullName>
                </value>
                <value>
                    <fullName>Cobranza</fullName>
                </value>
                <value>
                    <fullName>Cobro inmediato</fullName>
                </value>
                <value>
                    <fullName>Compra de reserva territorial</fullName>
                </value>
                <value>
                    <fullName>Crediproveedores</fullName>
                </value>
                <value>
                    <fullName>Crédito de habilitación o Avío</fullName>
                </value>
                <value>
                    <fullName>Crédito en cuenta corriente</fullName>
                </value>
                <value>
                    <fullName>Crédito Líquido</fullName>
                </value>
                <value>
                    <fullName>Crédito Líquido PyME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_BPP_CamposDependientes_Test.cls
/**
*Desarrollado por:       Accenture SC
*Autor:                  Mario Calderón
*Proyecto:               BPyP
*Descripción:            Clase Test para la clase MX_BPP_CamposDependientes_cls
*
*Cambios (Versiones) prueba
*-------------------------------------------------------------------------------
*No.         Fecha            Autor                         Descripción
*------   ----------------   --------------------   ----------------------------
*1.0      28-01-2019         Mario Calderón                 Creación
*1.0      17-06-2019         Cindy Hernández		Se modifica el método getDependentMap_Test2 para incluir el try catch.
													Se agrega el método camposDepConstructor.
**/

@isTest
public class MX_BPP_CamposDependientes_Test {

    @isTest
    static void getDependentMap_Test() {
        Test.startTest();
        final String tipo = 'Opportunity';
        final Schema.SObjectType targetType = Schema.getGlobalDescribe().get(tipo);
        final Map<String,List<String>> actual = MX_BPP_CamposDependientes_Ctrl.getDependentMap(targetType.newSObject(),'Tipo_de_Registro_Manual2__c', 'Tipo_Producto__c');
        System.assertNotEquals(null, actual,'Correcto!');
        Test.stopTest();
    }

    @isTest
    static void getDependentMap_Test2() {
        final String tipo = 'Account';
        String errorMessage = '';
        final Schema.SObjectType targetType = Schema.getGlobalDescribe().get(tipo);
        Map<String,List<String>> actual = new Map<String,List<String>>();
        Test.startTest();
        try {
        	actual = MX_BPP_CamposDependientes_Ctrl.getDependentMap(targetType.newSObject(),'Tipo_de_Registro_Manual2__c', '');
        } catch (Exception e) {
        	errorMessage = e.getMessage();
        }
        Test.stopTest();
        System.assertEquals('Script-thrown exception', errorMessage);
        System.assertEquals(true, actual.isEmpty(),'No se encontraron campos dependientes en el objeto');
    }

    @isTest
    static void camposDepConstructor() {
        String errorMessage = '';
        test.startTest();
        try {
	        final MX_BPP_CamposDependientes_Ctrl camposDep = new MX_BPP_CamposDependientes_Ctrl();
	        System.assert(camposDep != null);
        } catch (Exception e) {
            errorMessage = e.getMessage();
        }
        test.stopTest();
        System.assertEquals('', errorMessage);
    }
}