src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Tipificacion_LV2__c</fullName>
        <label>¿Contacto Efectivo?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MX_SB_VTS_Tipificacion_LV1__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Contacto No Efectivo</fullName>
                </value>
                <value>
                    <fullName>No Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_ContadorRemarcado__c</fullName>
        <description>Contador total llamadas por el proveedor de call center</description>
        <label>Contador Llamadas Toques</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_Efectivas__c</fullName>
        <description>Contador de llamadas efectivas al cliente</description>
        <label>Contador llamadas efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MX_SB_VTS_Llamadas_No_Efectivas__c</fullName>
        <description>contador de llamadas no efectivas</description>
        <label>Contador Llamadas No Efectivas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_SB_VTS_OpportunityTrigger.cls
/*
* BBVA - Mexico
* @Author: Diego Olvera
* MX_SB_VTS_OpportunityTrigger
* @Version 1.0
* @LastModifiedBy: Diego Olvera
* @ChangeLog
* 1.0 Created class - Diego Olvera
*/

public without sharing class MX_SB_VTS_OpportunityTrigger {//NOSONAR
    /**
    * @method: susbtractContactTouchOpp
    * @description: substract counter
    * @params: oppItem <Trigger.new>, oldMap <Trigger.oldMap>
    */
    public static void substractContactTouchOpp(List<Opportunity> oppItem, Map<Id, Opportunity> oldMap) {
        final Id recordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(System.Label.MX_SB_VTS_Telemarketing_LBL).getRecordTypeId();
        for(Opportunity lst : oppItem) {
            final Opportunity oldOpp = oldMap.get(lst.Id);
            final Integer contador = MX_SB_VTS_LeadAutoAssigner.checkNullVals(lst.MX_SB_VTS_ContadorRemarcado__c);
            if (lst.RecordTypeId.equals(recordType) && contador>0 && System.Label.MX_SB_VTS_Nocontacto.equals(lst.MX_SB_VTS_Tipificacion_LV2__c) && String.isBlank(oldOpp.MX_SB_VTS_Tipificacion_LV2__c)) {
                lst.MX_SB_VTS_ContadorRemarcado__c = contador-1;

            }
        }
    }
	/**
	* @method: substracteffectiveContactOpp
    * @description: adds +1 to counter
    * @params: oppItem <Trigger.new>, oldMap <Trigger.oldMap>
	*/
    public static void substractEffectiveContactOpp (List<Opportunity> oppItem, Map<Id, Opportunity> oldMap) {
        final Id recordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(System.Label.MX_SB_VTS_Telemarketing_LBL).getRecordTypeId();
        for(Opportunity lst: oppItem) {
            final Opportunity oldOpp = oldMap.get(lst.Id);
            final Integer contador2 = MX_SB_VTS_LeadAutoAssigner.checkNullVals(lst.MX_SB_VTS_Llamadas_Efectivas__c);
            if(lst.RecordTypeId.equals(recordType) && System.Label.MX_SB_VTS_ContactoEfectivo.equals(lst.MX_SB_VTS_Tipificacion_LV2__c)   && String.isBlank(oldOpp.MX_SB_VTS_Tipificacion_LV2__c)) {
                lst.MX_SB_VTS_Llamadas_Efectivas__c = contador2+1;
            }
        }
    }
	/**
	* @method: substractNoEffectiveContactOpp
    * @description: adds +1 to counter to MX_SB_VTS_Llamadas_No_Efectivas
    * @params: oppItem <Trigger.new>, oldMap <Trigger.oldMap>
	*/
    public static void substractNoEffectiveContactOpp(List<Opportunity> oppItem, Map<Id, Opportunity> oldMap) {
        final Id recordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(System.Label.MX_SB_VTS_Telemarketing_LBL).getRecordTypeId();
        for(Opportunity lst: oppItem) {
            final Opportunity oldOpp = oldMap.get(lst.Id);
            final Integer contador3 = MX_SB_VTS_LeadAutoAssigner.checkNullVals(lst.MX_SB_VTS_Llamadas_No_Efectivas__c);
            if(lst.RecordTypeId.equals(recordType) && System.Label.MX_SB_VTS_Nocontacto.equals(lst.MX_SB_VTS_Tipificacion_LV2__c)  && String.isBlank(oldOpp.MX_SB_VTS_Tipificacion_LV2__c)) {
                lst.MX_SB_VTS_Llamadas_No_Efectivas__c = contador3 + 1;

             }

        }

    }
}