src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CR</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>División</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oficina__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Oficina</label>
        <length>100</length>
        <type>Text</type>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CR</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oficina__c</fullName>
        <label>Oficina</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Divisi_n__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>EMPRESAS QUERETARO CONSTITUYENTES</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO D.F.</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO ESTADO DE MEXICO</fullName>
                </value>
                <value>
                    <fullName>SECTOR DESARROLLO SOCIAL</fullName>
                </value>
                <value>
                    <fullName>SECTOR EDUCACION</fullName>
                </value>
                <value>
                    <fullName>SECTOR INSTITUCIONES</fullName>
                </value>
                <value>
                    <fullName>SECTOR SALUD</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS AVILA CAMACHO</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS BOSQUES DE LAS LOMAS</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. CENTRO BANCOMER</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. GLORIETA COLON</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. LOMAS</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. PALMAS</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. POLANCO</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. REFORMA FLORENCIA</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. SAN ANGEL</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. SANTA FE</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS D.F. VALLEJO</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS TLALNEPANTLA</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS TOLUCA</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS MONTERREY REVOLUCION</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS MONTERREY SANTA CATARINA</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS MONTERREY UNIVERSIDAD NORTE</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS MONTERREY VALLE</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS Y GOBIERNO TAMPICO</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO NUEVO LEON</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS CD. JUAREZ ZARAGOZA</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS HERMOSILLO</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS MEXICALI</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS Y GOBIERNO CD. JUAREZ RENACIMIENTO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Divisi_n__c</fullName>
        <label>División</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>VP_ls_Banca__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BAJIO</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO CENTRO</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA</fullName>
                </value>
                <value>
                    <fullName>NORESTE</fullName>
                </value>
                <value>
                    <fullName>NOROESTE</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE</fullName>
                </value>
                <value>
                    <fullName>SUR</fullName>
                </value>
                <value>
                    <fullName>SURESTE</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVA</fullName>
                </value>
                <value>
                    <fullName>BAJIO PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA NORTE PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA SUR PYME</fullName>
                </value>
                <value>
                    <fullName>NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>NOROESTE PYME</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>SUR PYME</fullName>
                </value>
                <value>
                    <fullName>SURESTE PYME</fullName>
                </value>
                <value>
                    <fullName>METRO NORTE</fullName>
                </value>
                <value>
                    <fullName>METRO SUR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContarOppsGrupo_cls.cls
/**
******************************************************************************
*	@Desarrollado por:		Indra												*
*	@Autor:					Arsenio Perez Lopez								*
*	@Proyecto:				Bancomer											*
*	@Descripción:			Trigger de usuarios									*
*																				*
*	Cambios (Versiones)															*
*	--------------------------------------------------------------------------	*
*	No.		Fecha				Autor					Descripción				*
*	------  ----------  ----------------------		---------------------------	*
*	1.0		21/11/2017	Arsenio perez lopez         Creación Trigger	        *
*   1.1     20/04/2018  Sergio Ortiz                Se Elimina Querys en for en *
*                                                   OppClienteGrupoBeforeInsert *
*	1.2		11/07/2019	Jair Ignacio Gonzalez G.	Se depuro clase con los		*
*													metodos confirmados en la	*
*													migracion de bpyp y pymes	*
********************************************************************************
*/
public without sharing class ContarOppsGrupo_cls {
	/** Varianbles Integer */
    static Integer oppsAbiertas, oppsCerradas, oppsDescartadas, oppsTotales;
	/** Set de Ids de Oportunidades */
    static Set<Id> oportunidadIds = new Set<Id>();// EGL
	/** Lista de Oportunidades */
	static List<Opportunity> lOpp = new list<Opportunity>();
	/** Set de Ids Usuarios */
	static set<Id> sUsr = new set<Id>();
	/** Set con las etapas */
	static set<String> etapasAbiertas = new set<String>{'Diagnóstico de necesidades','Diagnóstico de necesidades','Propuesta','Manejo de objeciones','Integración de información',
    												'Formalización','Firmas','Áreas centrales','Producto activado','Promoción','Análisis','Admisión','Formalización crédito',
    												'Desembolso','Autorizada','Negociación de tarea/Comisión','En contratación','Firmada'};
	/** Set con Ids de Clientes */
	static  Set<Id> clienteIds = new Set<Id>();

	private ContarOppsGrupo_cls() {
  	}

    /*****************
    +
    +
    +Base del trigger OppUsrTrigger.Trigger Se parte la logica acorde a su tiempo de ejecucion
    +Before Insert y Before Update
    +
    ******************/
	public static void oppUsrTiggerTrig(List<Opportunity>triggerNew, map<Id,Opportunity> triggerOldMap) {
		for(Opportunity opp : triggerNew) {
			if(Trigger.isUpdate) {
				final Opportunity oldOpp = triggerOldMap.get(opp.Id);
				if(opp.OwnerId!=oldOpp.OwnerId) {
					lOpp.add(opp);
					sUsr.add(opp.OwnerId);
				}
			} else {
				lOpp.add(opp);
				sUsr.add(opp.OwnerId);
			}
		}
		if (!sUsr.isEmpty()) {
			final map<Id,User> mpUsr = new map<Id,User>([SELECT Id,CR__c,Oficina__c,Divisi_n__c FROM User WHERE Id IN:sUsr]);
			for(Opportunity op : lOpp) {
				op.CR__c=mpUsr.get(op.OwnerId).CR__c;
				op.Oficina__c=mpUsr.get(op.OwnerId).Oficina__c;
				op.Division__c=mpUsr.get(op.OwnerId).Divisi_n__c;
			}
		}
	}

}