src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FolioCotizacion__c</fullName>
        <description>Folio para dar seguimiento a la cotización.</description>
        <externalId>true</externalId>
        <label>Folio Cotizacion</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MX_WB_EvaluacionCalidad__c</fullName>
        <defaultValue>&quot;Pendiente&quot;</defaultValue>
        <description>Determina si una cotización ha sido evaluada por el área de calidad</description>
        <label>Evaluación calidad</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                    <default>true</default>
                    <label>Pendiente</label>
                </value>
                <value>
                    <fullName>Realizada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MX_WB_EvaluacionOportunidades_ctrl.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     MX_WB_EvaluacionOportunidades_ctrl
* @Author   Salvador Reyna Gonzalez
* @Date     Created: 2019-01-09
* @Group  	Telemarketing
* @Description This class works as a controller for the component MX_WB_EvaluacionOportunidades
* @Changes
*/
public with sharing class MX_WB_EvaluacionOportunidades_ctrl {
    /**
    * --------------------------------------------------------------------------------------
    * @Description Searches and returns a list of Won/Lost Opportunities
    * @return List<Opportunity>
    **/

    @auraEnabled
    public static List<Opportunity> getOpportunities() {
        return [SELECT Id, Name, CloseDate, FolioCotizacion__c, StageName, Owner.Name, MX_WB_EvaluacionCalidad__c FROM Opportunity WHERE RecordType.Name = 'Outbound' AND (StageName = 'Closed Won' OR StageName = 'Closed Lost')  AND CloseDate >= LAST_N_MONTHS:4];
    }
}