src/objects/Scripts_Stage_Product__c.object
<CustomObject>
	<fields>
        <fullName>MX_WB_Etapa__c</fullName>
        <label>Etapa</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto Efectivo</fullName>
                </value>
                <value>
                    <fullName>Objeciones</fullName>
                </value>
                <value>
                    <fullName>Políticas</fullName>
                </value>
                <value>
                    <fullName>Cotización</fullName>
                </value>
                <value>
                    <fullName>Objeciones Reales</fullName>
                </value>
                <value>
                    <fullName>Venta Autorizada</fullName>
                </value>
                <value>
                    <fullName>Apertura</fullName>
                </value>
                <value>
                    <fullName>Cierre llamada no contacto</fullName>
                </value>
                <value>
                    <fullName>Información y condiciones</fullName>
                </value>
                <value>
                    <fullName>Venta cerrada</fullName>
                </value>
                <value>
                    <fullName>Cierre de llamada sin venta</fullName>
                </value>
                <value>
                    <fullName>Contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MX_WB_FamiliaProductos__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Familia de productos a los que se les asociará el script</description>
        <label>Familia de productos</label>
        <referenceTo>MX_WB_FamiliaProducto__c</referenceTo>
        <relationshipLabel>Scripts Stages Products</relationshipLabel>
        <relationshipName>Scripts_Stages_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MX_WB_Script__c</fullName>
        <description>Script que será mostrado al asesor. Este script se visualiza dependiendo la etapa y el producto en el que se encuentre.</description>
        <label>Script</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Scripts Stage Product</label>
    <nameField>
        <label>Nombre de Scripts Stage Campaign</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts Stages Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MX_WB_ControlScriptCls.cls
/**-------------------------------------------------------------------------
* Nombre: MX_WB_ControlScriptsTgr_tst
* Autor Alexis Pérez
* Proyecto: MW WB TLMKT - BBVA Bancomer
* Descripción : Clase con lógica de trigger para evitar la inserción de más de un script
*				en la misma etapa y asociado a un mismo producto.
* --------------------------------------------------------------------------
* Versión       Fecha           Autor                   Desripción<p />
* -------------------------------------------------------------------
* 1.0           06/12/2018      Alexis Pérez   			Creación
* 2.0           05/02/2019      Alexis Pérez   			Cambio de producto a Familia de producto.
* --------------------------------------------------------------------------
*/
public without sharing class MX_WB_ControlScriptCls {

    private MX_WB_ControlScriptCls() {}
    /*
     * Avoid inserting a record if it has the same stage and is associated with the same product as an existing record.
     * @param List<Scripts_Stage_Product__c> lstTgrNewScript	 incoming records.
     */
    public static void verificaExistenciaScript(List<Scripts_Stage_Product__c> lstTgrNewScript) {
        final List<Scripts_Stage_Product__c> lstTgrOldScript = [SELECT Id, MX_WB_Etapa__c, MX_WB_FamiliaProductos__c, MX_WB_Script__c
                                                          FROM Scripts_Stage_Product__c
                                                          WHERE NOT(MX_WB_Etapa__c = null)];
        System.debug('lstTgrOldScript::: ' + lstTgrOldScript);
        for(Scripts_Stage_Product__c iteratorOld : lstTgrOldScript) {
            for(Scripts_Stage_Product__c iteratorNew : lstTgrNewScript) {
                if(iteratorNew.MX_WB_Etapa__c == iteratorOld.MX_WB_Etapa__c && iteratorNew.MX_WB_FamiliaProductos__c == iteratorOld.MX_WB_FamiliaProductos__c) {
                    iteratorNew.addError(Label.MX_WB_lbl_MsgScriptException);
                }
            }
        }
    }
}