src/objects/User.object
<CustomObject>
    <fields>
        <fullName>VP_ls_Banca__c</fullName>
        <label>Banca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red BEyG</fullName>
                </value>
                <value>
                    <fullName>Red PyME</fullName>
                </value>
                <value>
                    <fullName>Red CF</fullName>
                </value>
                <value>
                    <fullName>Red HP</fullName>
                </value>
                <value>
                    <fullName>Red HI</fullName>
                </value>
                <value>
                    <fullName>Red Hipotecaria</fullName>
                </value>
                <value>
                    <fullName>Red HI Venta Remota</fullName>
                </value>
                <value>
                    <fullName>Red BPyP</fullName>
                </value>
                <value>
                    <fullName>Red Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BPyP_ls_NombreSucursal__c</fullName>
        <description>Campo creado para la Banca Patrimonial y Privada que es dependiente de la Division</description>
        <label>Nombre Sucursal BPyP</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Divisi_n__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0680 LOMAS</fullName>
                </value>
                <value>
                    <fullName>4214 LOMAS VERDES</fullName>
                </value>
                <value>
                    <fullName>4221 MAZARIK</fullName>
                </value>
                <value>
                    <fullName>6336 UHN MÉXICO</fullName>
                </value>
                <value>
                    <fullName>6340 TORRE BANCOMER</fullName>
                </value>
                <value>
                    <fullName>6341 SATELITE</fullName>
                </value>
                <value>
                    <fullName>6342 CENTRO BANCOMER</fullName>
                </value>
                <value>
                    <fullName>6343 PEDREGAL</fullName>
                </value>
                <value>
                    <fullName>6356 PASEOS DE CHURUBUSCO</fullName>
                </value>
                <value>
                    <fullName>6357 VITO ALESSIO</fullName>
                </value>
                <value>
                    <fullName>6358 INTERLOMAS</fullName>
                </value>
                <value>
                    <fullName>6379 LILAS</fullName>
                </value>
                <value>
                    <fullName>6385 BANCA PERISUR</fullName>
                </value>
                <value>
                    <fullName>6393 BANCA PLAZA FORUM</fullName>
                </value>
                <value>
                    <fullName>6398 BANCA ACOXPA</fullName>
                </value>
                <value>
                    <fullName>6400 BANCA DEL VALLE</fullName>
                </value>
                <value>
                    <fullName>6402 TOLUCA</fullName>
                </value>
                <value>
                    <fullName>6345 ZACATECAS</fullName>
                </value>
                <value>
                    <fullName>6365 IRAPUATO</fullName>
                </value>
                <value>
                    <fullName>6366 CELAYA</fullName>
                </value>
                <value>
                    <fullName>6372 MOROLEON</fullName>
                </value>
                <value>
                    <fullName>6384 AGUASCALIENTES</fullName>
                </value>
                <value>
                    <fullName>6388 PACHUCA</fullName>
                </value>
                <value>
                    <fullName>6390 QUERETARO</fullName>
                </value>
                <value>
                    <fullName>6391 SAN LUIS POTOSI</fullName>
                </value>
                <value>
                    <fullName>6405 LEON</fullName>
                </value>
                <value>
                    <fullName>0708 MONTERREY VALLE SENA</fullName>
                </value>
                <value>
                    <fullName>6348 DURANGO</fullName>
                </value>
                <value>
                    <fullName>6354 REYNOSA</fullName>
                </value>
                <value>
                    <fullName>6371 MONTERREY COUNTRY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Divisi_n__c</fullName>
        <label>División</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>VP_ls_Banca__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BAJIO</fullName>
                </value>
                <value>
                    <fullName>GOBIERNO CENTRO</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA</fullName>
                </value>
                <value>
                    <fullName>NORESTE</fullName>
                </value>
                <value>
                    <fullName>NOROESTE</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE</fullName>
                </value>
                <value>
                    <fullName>SUR</fullName>
                </value>
                <value>
                    <fullName>SURESTE</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVA</fullName>
                </value>
                <value>
                    <fullName>BAJIO PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA NORTE PYME</fullName>
                </value>
                <value>
                    <fullName>METROPOLITANA SUR PYME</fullName>
                </value>
                <value>
                    <fullName>NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>NOROESTE PYME</fullName>
                </value>
                <value>
                    <fullName>OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL NORESTE PYME</fullName>
                </value>
                <value>
                    <fullName>REGIONAL OCCIDENTE PYME</fullName>
                </value>
                <value>
                    <fullName>SUR PYME</fullName>
                </value>
                <value>
                    <fullName>SURESTE PYME</fullName>
                </value>
                <value>
                    <fullName>METRO NORTE</fullName>
                </value>
                <value>
                    <fullName>METRO SUR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MX_BPP_CompUtils_cls.cls
/*
    Proyecto :	ENGMX
    Versión     Fecha           Autor                   Descripción
    ___________________________________________________________________________________________________
    1.0         08-Nov-2018     Cristian Espinosa       Creación de la clase.
														Clase de utilidades para los componentes BPyP_AccountFiltr,
														BPyP_Contact_Acc,BPyP_OppRep,BPyP_Contact_Chan.
														Generalmente usada para retornar información de los usuarios.
														*Clases de pruebas : BPyP_AccFiltrTest,BPyP_OppRepTest,BPyP_Contact_AccTest.
	1.1			21-Nov-2018		Cristian Espinosa		Se agrega campo title al método getUsrData.
*/
public with sharing class MX_BPP_CompUtils_cls {

    //Constructor with no arguments
    private MX_BPP_CompUtils_cls() {
    }

    /** Lista divBpyp*/
    private static List<AggregateResult> divBpyP = new List<AggregateResult>();
    /** Mapa offBpyp*/
    private static Map<String,List<AggregateResult>> offBpyP = new Map<String,List<AggregateResult>>();
    /** Mapa usrBpyp*/
    private static Map<String,List<AggregateResult>> usrBpyP = new Map<String,List<AggregateResult>>();
    /** Lista red*/
    private static List<Integer> red = new List<Integer>();
    /** Lista blue*/
    private static List<Integer> blue = new List<Integer>();
    /** Lista green*/
    private static List<Integer> green = new List<Integer>();

    /*
    	@description: 	Método que obtiene todas las divisiones de los usuarios BPyP activos.
						Se hace uso de variables estáticas para evitar hacer consultas innecesarias.
	*/
    public static List<AggregateResult> getBPyPDivisions() {
        //Obtention of Divisions
        if(divBpyP.isEmpty()) {
            for(AggregateResult agr : [Select Owner.Divisi_n__c from Account where Owner.VP_ls_Banca__c = 'Red BPyP' and (NOT (Owner.BPyP_ls_NombreSucursal__c = '')) and (NOT (Owner.Divisi_n__c = '')) and Owner.IsActive=True group by  Owner.Divisi_n__c]) {
                divBpyP.add(agr);
            }
        }
        return divBpyP;
    }

    /*
    	@description: 	Método que obtiene las oficinas de los usuarios BPyP activos de alguna división.
						Se hace uso de variables estáticas para evitar hacer consultas innecesarias.
	*/
    public static List<AggregateResult> getBPyPOffices(String div) {
        List <AggregateResult> lsReturn = new List <AggregateResult>();
        //if no divisions will send null to clear errors
        if(String.isNotBlank(div)) {
            lsReturn = new List <AggregateResult>();
            if(offBpyP.containsKey(div)) {
                lsReturn = offBpyP.get(div);
            } else {
                for(AggregateResult agr : [Select Owner.BPyP_ls_NombreSucursal__c from Account where Owner.VP_ls_Banca__c = 'Red BPyP' and (NOT (Owner.BPyP_ls_NombreSucursal__c = '')) and (NOT(Owner.Divisi_n__c = '')) and Owner.Divisi_n__c=:div and Owner.IsActive=True group by  Owner.BPyP_ls_NombreSucursal__c]) {
                    lsReturn.add(agr);
                }
                offBpyP.put(div,lsReturn);
            }
        }
        return lsReturn;
    }

    /*
    	@description: 	Método que obtiene las oficinas de los usuarios BPyP activos de alguna división.
						Se hace uso de variables estáticas para evitar hacer consultas innecesarias.
	*/
    public static List<AggregateResult> getBPyPUsrs(String div,String office) {
        List <AggregateResult> lsReturn = new List <AggregateResult>();
        if(String.isNotBlank(div) && String.isNotBlank(office)) {
            lsReturn = new List <AggregateResult>();
            if(usrBpyP.containsKey(office)) {
                lsReturn = usrBpyP.get(office);
            } else {
                for(AggregateResult agr : [SELECT OwnerId,Owner.Name from Account where Owner.VP_ls_Banca__c = 'Red BPyP' and (NOT(Owner.BPyP_ls_NombreSucursal__c = '')) and (NOT (Owner.Divisi_n__c = '')) and Owner.BPyP_ls_NombreSucursal__c=:office and Owner.Divisi_n__c=:div and Owner.IsActive=True group by  OwnerId,Owner.Name]) {
                    lsReturn.add(agr);
                }
                usrBpyP.put(office,lsReturn);
            }
        }
        return lsReturn;
    }
    /**Metodo getUsrData */
    public static List<String> getUsrData() {
        final List<String> res = new List<String>();
        final User actusr = [select Id,Name,Divisi_n__c,BPyP_ls_NombreSucursal__c,profile.Name,Title from User where Id = :UserInfo.getUserId()];
        if(actusr.profile.Name == null) {
            res.add(' ');
        } else {
            res.add(actusr.profile.Name);
        }
        if(actusr.Divisi_n__c == null) {
            res.add(' ');
        } else {
            res.add(actusr.Divisi_n__c);
        }
        if(actusr.BPyP_ls_NombreSucursal__c == null) {
            res.add(' ');
        } else {
            res.add(actusr.BPyP_ls_NombreSucursal__c);
        }
        if(actusr.Name == null) {
            res.add(' ');
        } else {
            res.add(actusr.Name);
        }
        if(actusr.Title == null) {
            res.add(' ');
        } else {
            res.add(actusr.Title);
        }
        return res;
    }
    /**Metodo getbaseUrl */
	public static String getBaseUrl( ) {
        String dir=URL.getSalesforceBaseUrl().toExternalForm() + '/';
        dir=dir.mid(0,dir.indexOf('.'))+'.lightning.force.com/one/one.app#/sObject/';
        return dir;
    }

    /*
    	Métodos que crean arreglos de enteros para generar colores, los usan todos los componentes.
    */
    public static List<Integer> genRedBBVA() {
        if(red.isEmpty()) {
            red.add(0); red.add(10); red.add(45); red.add(42); red.add(216); red.add(90); red.add(247); red.add(243); red.add(70); red.add(247);
            red.add(247); red.add(100); red.add(190); red.add(215); red.add(212); red.add(156); red.add(183); red.add(40); red.add(2); red.add(197);
            red.add(185); red.add(143); red.add(247); red.add(103); red.add(39);
        }
        return red;
    }
    /** Metodo genGreenBBVA */
    public static List<Integer> genGreenBBVA() {
        if(green.isEmpty()) {
            green.add(69); green.add(95); green.add(204); green.add(134); green.add(190); green.add(190); green.add(137); green.add(94); green.add(175); green.add(205);
            green.add(140); green.add(100); green.add(190); green.add(55); green.add(237); green.add(108); green.add(158); green.add(133); green.add(132); green.add(105);
            green.add(42); green.add(122); green.add(137); green.add(84); green.add(122);
        }
        return green;
    }
    /**Método genBlueBBVA */
    public static List<Integer> genBlueBBVA() {
        if(blue.isEmpty()) {
            blue.add(130); blue.add(180); blue.add(205); blue.add(202); blue.add(117); blue.add(255); blue.add(59); blue.add(97); blue.add(100); blue.add(82);
            blue.add(232); blue.add(100); blue.add(190); blue.add(80); blue.add(252); blue.add(1); blue.add(94); blue.add(202); blue.add(132); blue.add(185);
            blue.add(69); blue.add(229); blue.add(60); blue.add(184); blue.add(62);
        }
        return blue;
    }

}