src/objects/WB_Log__c.object
<CustomObject>
    <description>Log para los servicios web.</description>
    <fields>
        <fullName>WB_Mensaje__c</fullName>
        <description>Mensaje de Error o Éxito.</description>
        <label>Mensaje</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WB_Rta__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Respuesta Boolean.</description>
        <label>Rta</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WB_Servicio_Web__c</fullName>
        <label>Servicio Web</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WB_CrearLog_cls.cls
/**
*
*
* @Descripción: Crea un log
*/
public with sharing class WB_CrearLog_cls {
    private WB_CrearLog_cls() {

    }
    /** Method fnCrearLog*/
    public static void fnCrearLog(String sMsn, String sServicio , Boolean blRta) {
        if( Label.WB_BorrarLog == 'OK' ) {
            final WB_Log__c oLog = new WB_Log__c();
            oLog.WB_Mensaje__c = sMsn;
            oLog.WB_Rta__c = blRta;
            oLog.WB_Servicio_Web__c = sServicio;
            insert oLog;
        }
    }
}