src/objects/WB_Log__c.object
<CustomObject>
    <description>Log para los servicios web.</description>
    <fields>
        <fullName>WB_Rta__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Respuesta Boolean.</description>
        <label>Rta</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WB_Servicio_Web__c</fullName>
        <label>Servicio Web</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WB_CrearLog_tst.cls
@isTest
/** Clase WB_CrearLog_tst */
private class WB_CrearLog_tst {

	@isTest static void testMethodOne() {
		WB_CrearLog_cls.fnCrearLog('Test', 'Prueba', false);

        final List<WB_Log__c> listaLogs = [SELECT ID FROM WB_Log__c WHERE WB_Rta__c = false AND WB_Servicio_Web__c = 'Prueba' LIMIT 1];
        System.assertEquals(listaLogs.size(), 1, 'Log de prueba no fue encontrado/insertado');
	}
}